### ISSUE TITLE
Cannot remove columns from WormMine tables

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#1945]
The "X" buttons at the top of each column of results in WormMine that normally allows the user to remove a column from the table is no longer working, making it impossible to prune columns off of a larger table.

The sort, hide, and summary buttons seem to work fine.

**Comment by sibyl229** [comment]
Hi @chris-grove The close column button should work now. Though the change doesn't persist after page refresh, which seems to be a intermine thing (happens on FlyMine too). Maybe we can remove some columns from default?

**Comment by chris-grove** [comment]
@sibyl229  OK great! This seems fine. Actually, the fact that the columns reappear after refreshing is kind of a nice feature ;)  In case you accidentally remove a column you can restore it by refreshing the page.

As far as removing some columns from the default, I think it would be best NOT to include long text fields, like description fields. For example, the Gene class default columns include "Brief Description" which I think should be removed from the default. I can let you know specifically about others as I find them.

**Comment by sibyl229** [comment]
Hi @chris-grove I removed the gene brief description from the list view (say you saved a list of genes). 
![screen shot 2015-09-08 at 1 47 46 pm](https://cloud.githubusercontent.com/assets/1753893/9742755/388e5ada-5630-11e5-9958-9390e5214ab9.png)

But I kept the description for list search, because if I remove that it also removes the description from keyword search display, which seems less ideal.
![screen shot 2015-09-08 at 1 41 56 pm](https://cloud.githubusercontent.com/assets/1753893/9742715/f4c089fe-562f-11e5-8c8b-c28f20371a22.png)

**Comment by chris-grove** [comment]
Sounds good @sibyl229  thanks!
