### ISSUE TITLE
Selecting FPKM datasets and graphs

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#2900]
Hi,  <br /><br />Is there a way to select which datasets are displayed in the bar graph under "FPKM expression data" in the Expression widget?  You used to show all of the datasets, but now you're only displaying one of them by default (which is not the one I want to look at).  <br /><br />Thanks!

Reported by: Dan ********* (ddic*****************)  (obscured for privacy)
Submitted From: F33G12.2%20(gene) (/species/c_elegans/gene/WBGene00018014#0e-94b1a6cd-10-a)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.153 Safari/537.36

**Comment by sibyl229** [comment]
Hi @gw3 the fpkm expression data is showing individual plots per project now http://staging.wormbase.org/species/c_elegans/gene/WBGene00006763#01--3. I still need to make the display better. One problem is it makes the expression widget really long. Two options:

- One, I can show the summary table with **links to each plot**, and the user has to click on icons that correspond to the plots, to view the plot in a popup
- Another option is to have the summary table **display the plot images**, the whole table will be **hidden ** until the user click on "show fpkm expression plots"

What do you think? Thanks!

**Comment by gw3** [comment]
Hi Sibyl,

I like the idea of hiding the plots until they are requested.
The number of plots is growing larger - there are about 34 of them in 
WS247 in elegans.
I think the first option is best as it doesn't use up display space 
unless requested.

The RNASeq data will become richer in WS247.

Each study (each study corresponds to a plot) will have an analysis 
object named like 'RNASeq_Study.STUDY ID', for example: 
'RNASeq_Study.SRP000244'
These study analysis objects will have a short Title, for example: 
'Variant discovery in elegans (Hillier 2008)' that can be used to label 
the plot.
They will have a longer Description, usually paraphrasing part of the 
description in the paper.
They will have a list of Analysis objects under the Subproject tag that 
describe the individual experiments that make up the study.
They will have a list of one or more of the conditions that are varied 
across the experiments in the tag 'Independent_variable', for example: 
Life_stage, Sex, so that the plots can be constructed to group the 
results the varying conditions. These independent variables do not 
necessarily include Life_stage.

There will also be "control" mean and median FPKM values derived from 
the data which does not have a specific experimental condition applied, 
as discussed in the Conference call on 18 Dec 2014
(http://wiki.wormbase.org/index.php/WBConfCall_2014.12.18-Agenda_and_Minutes)
For each Gene object there will be a overall control mean and median 
FPKM value with an analysis of 'RNASeq.elegans.all_stages.control_mean' 
and 'RNASeq.elegans.all_stages.control_median'.
These overall control mean and median values should probably be 
separately displayed as text in the Expression widget.

Gene : "WBGene00009082"
RNASeq_FPKM  "WBls:0000002"  "119.125760406092"  From_analysis 
"RNASeq.elegans.all_stages.control_mean"
RNASeq_FPKM  "WBls:0000002"  "115.062"  From_analysis 
"RNASeq.elegans.all_stages.control_median"



There will also be mean and median FPKM values for each gene for the 
Life Stages: Embryo, L1, L2, L3, L4, Dauer, Adult and Mixed. When the 
original experimental data was done on a life_stage that was more 
specific than these life stages, the life stage reported has been 
promoted in the life stage ontology to these main developmental stages.


Gene : "WBGene00009082"
RNASeq_FPKM  "WBls:0000003"  "78.789065882353"  From_analysis 
"RNASeq.elegans.WBls:0000003.control_mean"
RNASeq_FPKM  "WBls:0000024"  "140.800247058824"  From_analysis 
"RNASeq.elegans.WBls:0000024.control_mean"
RNASeq_FPKM  "WBls:0000027"  "204.898777777778"  From_analysis 
"RNASeq.elegans.WBls:0000027.control_mean"
RNASeq_FPKM  "WBls:0000041"  "161.010865714286"  From_analysis 
"RNASeq.elegans.WBls:0000041.control_mean"
RNASeq_FPKM  "WBls:0000038"  "141.893273333333"  From_analysis 
"RNASeq.elegans.WBls:0000038.control_mean"
RNASeq_FPKM  "WBls:0000002"  "92.1579818181864"  From_analysis 
"RNASeq.elegans.WBls:0000002.control_mean"
RNASeq_FPKM  "WBls:0000035"  "195.839714285714"  From_analysis 
"RNASeq.elegans.WBls:0000035.control_mean"


Maybe a box-plot using these mean or median control values could be 
displayed by default?

**Comment by gw3** [comment]
Hi Sibyl,

Since I didn't see a reply from you about my message (above in #2900), this is just a reminder that the WS247 RNASeq descriptions will be richer and more informative, allowing better description of the experiments and easier display of the plots of both the normal RNASeq experiments and the mean and median values of the control data.

Please get back to me if you have any questions or suggestions on how to improve this to make it easier for you to use it.

Gary

**Comment by sibyl229** [comment]
Hi @gw3,

Here is how the fpkm plot looks now: http://staging.wormbase.org/species/c_elegans/gene/WBGene00015146#01--3 

So far I added the descriptive titles for plots, and pulled out the control data and displayed them in a table. I will continue working it, to make better use of the richer data available now. Plotting by appropriate independent variable is one of them.

Some confusion I have are:
- some studies have multiple independent variables, (RNASeq_Study.SRP000401 has 4). I'm not sure what factor(s) I should plot it by.
- is boxplot appropriate, when a study has very few analyses?
- does the project links to NCBI page should go to the appropriate Study page now?

Thank you.

**Comment by gw3** [comment]
HI Sibyl,

This is starting to look very good. Thanks!

Answers to your confusions:

1) Some studies have multiple independent variables. I would like to see 
the ability for the user to select one of the set of independent 
variables and have the appropriate box plot displayed. There are some 
instances where the independent variable is not the life stage (e.g. 
RNASeq_Study.SRP028611 which has Strain and Temperature as independent 
variables) in which case displaying a single value life stage in a box 
plot looks uninformative, so this will have to be addressed at some 
stage. The default independent variable chosen for the initial display 
does not matter much if the user can change the selection.

2) When a study has very few analyses, a box plot is not the best way to 
display the data. However, as the user will probably be comparing box 
plots from different studies, having all the data displayed as box plots 
makes them easier to compare.

3) Yes, the links look good.

Some comments:

The "Control Statistics" list of mean and median values should possibly 
also be displayed as a couple of box plots.

The "Control Statistics" list of mean and median values probably needs 
some explanation. Maybe change the title of this section to "FPKM 
mean/median results from the controls of all published studies"?

Should the section with the box plots in (with column headings of 
"Project", "Description" and "Image") have a heading for the section. 
Maybe something like "FPKM results from published RNA-seq studies"?

The last section listing the Analysis objects (with column headings of 
"Name", "Project", "Life stage" and "FPKM value") should probably have a 
heading. Maybe something like "List of all RNA-seq experiments"

Thoughts for the future:

I consider the values for the "control" experiments to be the most 
informative. I wonder if it was a mistake to pre-calculate the mean and 
median values of these control experiments.
Perhaps it would have been better to indicate which experiments are 
controls in some way (set a tag in the Condition object perhaps?) and 
then only those Experiments that are controls could then be plotted in a 
box plot. Would that be better? Paul Davis has suggested that I should 
keep the mean and median values for the controls but also have a 
'Control' tag in the Condition object. Then the display for this section 
could be altered so that the columns contain: "Life stage" (as now), 
"Statistics type" (as now), "FPKM value" (as now but with the addition 
of a '?' that is a link to the Analysis object) then the last column 
(taking up the space of both the mean and median rows for this life 
stage) could be a box plot of the raw values for the control values of 
this life stage. Thsi would have the advantage of hiding the 
non-informative names of the Analysis objects (e.g. 
"RNASeq.elegans.WBls:0000003.control_median") from the users. I suspect 
that there would be problems in getting the individual box plots to all 
use the same x-axis scale, so this may be more trouble that it is worth.

Thanks again,
Gary

**Comment by xdwang** [comment]
@gw3 @Paul-Davis I would argue to list all controls in their own projects plots. Shouldn't all experiments/projects have their own controls? If this is the case, controls should be plotted within the same projects. Or if controls are used crossed different projects, it makes sense to list them in a separate common table as they are now.

**Comment by gw3** [comment]
Hi Xiaodong,

Yes, the projects have their own control data and this is already 
displayed as part of the data for each project.
The control expression values are useful as they give the expression for 
the gene with no special condition, but it is sometimes not easy to see 
which data are the controls without reading the paper.

For each gene, I have extracted all of the control data from all of the 
experiments.
I then worked out which of the basic life-stages the data referred to 
(embryo, L1, L2, L3, L4, adult, all stages) as often the life stage is a 
rarely-used subdivision of these basic life stages.
Within each basic life stage I then calculated the mean and median FPKM 
values.

Maybe if this is not a clear set of data, it might be too confusing to 
present to the users?

Gary

**Comment by gw3** [comment]
Hi Sibyl,

Looking at http://staging.wormbase.org/species/c_elegans/gene/WBGene00015146#01--3 some more, Kevin has suggested that the table of control mean and median values could be improved by making the FPKM value column into two columns, the first for the mean value and the second for the median value (I will probably add a standard deviation value soon). The link to the Analysis object should be removed and the text from the Description of this Analysis object should be seen as a popup text balloon when mousing over the appropriate value.

Gary

**Comment by sibyl229** [comment]
Hi @gw3 I added the plot you created to the Expression widget (on Gene and Transcript pages for now). http://staging.wormbase.org/species/c_elegans/gene/WBGene00015099#01--10 Could you take a look to see if it's correct? Thank you!

I modified the columns for the Control statistics table, according to Kevin's suggestion.

**Comment by gw3** [comment]
Hi @sibyl229,

This looks good.

Could you add some sort of description of what it is.
At a minimum the title should be changed to say:

"FPKM expression data from selected modENCODE libraries"

Maybe you could have a pop-up longer description like:

"This shows the FPKM expression values of PolyA+ and Ribozero modENCODE
libraries across life-stages. The grey bars show the median value of the
libraries plotted. Other modENCODE libraries which were made using other
protocols or which are from a particular tissue or attack by a pathogen
have been excluded."

**Comment by epaule** [comment]
resolved
