### ISSUE TITLE
genome browser balloon popup bug

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/website#2991]
I was on the genome browser and started to get multiple tabs being created even though I hadn't clicked on any of the tracks.

It appears that instead of a balloon pop-up for the WormBase nematode mRNAs/ESTs (best) you get a new tab launched with a Sequence report for the EST.......a bit agressive IMO ;)

screenshot:
![no balloon](https://cloud.githubusercontent.com/assets/717707/3842840/baa1a876-1e3a-11e4-805c-2aeeca8c4170.png)

**Comment by scottcain** [comment]
I think I have a fix for this (a hack, really, since I don't know what was happening in the first place).  @epaule and @Paul-Davis please take a look and let me know if it's good for you:

http://staging.wormbase.org/tools/genome/gbrowse/c_elegans_PRJNA13758/?start=14753000;stop=14756999;ref=X;width=800;version=100;flip=0;grid=1;id=698eee172288b915c82300a21df1e787;l=SEQUENCE_SIMILARITY_WORMBASE_CORE_ESTS_AND_MRNAS_BEST%1EHits_3acbcb_My_Track_1%1EGENES%1EVARIATIONS_POLYMORPHISMS%1ELOCI%3Aoverview

**Comment by scottcain** [comment]
Fixed on staging and will go live with 253 in a few days.
