### ISSUE TITLE
  Under human diseases for the gene nfi...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3552]
<p>&nbsp;&nbsp;Under human diseases for the gene nfi-1 it would be good to list #613735 CHROMOSOME 1p32-p31 DELETION SYNDROME which includes deletion of the human homolog of nfi-1, NFIA.  Thanks.  Rich</p>

Reported by: Rich***************** (rgro*************)  (obscured for privacy))
Submitted From: Frequently asked questions <a href="http://www.wormbase.org//about/Frequently_asked_questions#c372ea0895641bd--10">/about/Frequently_asked_questions#c372ea0895641bd--10</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/600.2.5 (KHTML, like Gecko) Version/8.0.2 Safari/600.2.5

**Comment by draciti** [comment]
From Ranjana
Dear Richard,
Thanks for writing to WormBase and alerting us to this.  We pull in diseases based on orthology of elegans genes to OMIM genes and their associated MIM phenotypes, by automated scripts.  It could be that this got missed because the 1p32-p31 DELETION SYNDROME is not listed as a MIM phenotype of the OMIM gene NFIA, though this information is buried in the ‘Molecular Genetics’ section.  But I could easily incorporate this in our manual curation, which I will do for the next release of WormBase, WS248, releasing in a couple of months.

Best
Ranjana Kishore
WormBAse
