### ISSUE TITLE
  The sequence on this page doesn't loa...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3558]
<p>&nbsp;&nbsp;The sequence on this page doesn't load. http://www.wormbase.org/species/c_angaria/cds/860376:Cang_2012_03_13_00234.g7562.t1#05--10</p>

Reported by: diet*****************  (obscured for privacy)
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.99 Safari/537.36

**Comment by sibyl229** [comment]
This is probably due to an ACe object being saved to cache. But after I re-cached this widget from my dev instance, without modifying any code, I didn't see the Ace object in cache, and the error disappeared. I still don't understand how the Ace object got there during pre-caching. 

For debugging purpose, the cache file looks like:

> ÞÝ¼Tÿÿÿÿÿÿÿÿ12345678data
,predicted exon structure within the sequencedescriptionpredicted_exon_structuredata
homologous sequencesdescriptionprint_homologies**Ace::Object::Wormbase.dirtysource_exons	structure
sace://localhost:2005db
Methodname
sace://localhost:2005db
curatedname.right
Methodclass.right
tagclassmethod
transcript
sace://localhost:2005db
Propertiesname
sace://localhost:2005db
Codingname.col
sace://localhost:2005db.end_row
+?CDS?860376:Cang_2012_03_13_00234.g7562.t1?
?tag?Properties?
?tag?Coding?
?tag?CDS?.raw
CDSname
.start_row
tagclass.right
tagclass.right
tagclass
properties
sace://localhost:2005db
Codingname
sace://localhost:2005db
CDSname.right
tagclass.right
tagclasscoding.PATHS
sace://localhost:2005db**
%860376:Cang_2012_03_13_00234.g7562.t1name.root
CDSclassdata
JThe name and WormBase internal ID of 860376:Cang_2012_03_13_00234.g7562.t1descriptionname
%860376:Cang_2012_03_13_00234.g7562.t1source
Elegans genome
Elegans proteintargetdata
links to BLAST analysesdescriptionprint_blastdata
&features contained within the sequencedescriptionpredicted_unitsdata
*Transcripts in this region of the sequencedescriptiontranscriptsvlengtho<span style="Background-color: #FFFF00">ATGGGACTTTGCAAGTGCCCGAAACGAAAGGTTACCAATTTATTTTGCTATGAACATCGAGTAAATGTATGCGAATTTTG
CTTAGTTGATAACCATCCTAAT</span>gtgagtttttttctcgttgaaaattgaaattaggaaaaaggtaatttttag<span style="Background-color: #FFA500">TGCGTTG
TTCAAAGTTACCTTGCATGGTTAACCGATTCCGATTACGATCCAAATTGTGCACTTTGTCAAACACCATTGAATTCTGGC
GAAACTATACGTCTGAACTGTCTTC</span>gtaagttcgataatttttcaagttaaaaatatcctaaattttcccag<span style="Background-color: #FFFF00">ATCTTCTT
CACTGGAAATGTTTCGATGATTGGGCTGCAGCATTTCCAAATACAACAGCTCCAGCAGGTTATCGTTGTCCATGTTGTAG
TAAAGAAGTATTTCCACCACTCAATGAAGTTTCTCCACTCGTTGAAAAACTTCGAGAGCAGTTGAAATTATCAAATTGGG
CTCGAGCAGCTTTAGGTCTTCCAGTTTTACCGGAATTGAATCGTCCAATCACAAAAACTTTTGATAAACCGATTCCTCCA
CCAATTGTGAATAAACCAGTGGAAAATGTTGGAGCTGTTGCTCATCAAACTCAACGATCAATAACTCCCGCAACACATTT
AGATATGGAAGATTCTGCATCTTTTTCTGTTTCTTCAAGTGATGTTACTTTTT</span>gtaagtttacttgtaaacattcattct
gatgtttatttataaattttag<span style="Background-color: #FFA500">CACGTAAAAAGAATTTGGGAGATACTCGTCCATTGTTACAAAATGATAATCGCGATGC
AGACAATGAAGCAAATAAATATAAACGTAGACCAGCTGGAGAATGGATTCGTGGATTGTGGAGAGCAAAATATGGTCCTG
GAGTACCAGAAGATGGTTTGAGTGGAAGAAAGAAATTGGTTTTTGTAGTTTTCATTGCATTTGTTTCATTGGTTACT</span>gtg
agtttattctagaattctttaattaatttcttcggtaaattgaaaaaaaaacaaatataaaaccttctaaatttttgtag<span style="Background-color: #FFFF00">
ATTTATCTTGTTCTCAAACGACTTGGTGTAAATAATGACAACGATCCAATGTTTGACCCATTATCAAATCCAAACATCAG
AGTTGCTTCGAACAATGAATAA</span>sequencestyle
unspliced + UTRheaderlength<span style="Background-color: #FFFF00">ATGGGACTTTGCAAGTGCCCGAAACGAAAGGTTACCAATTTATTTTGCTATGAACATCGAGTAAATGTATGCGAATTTTG
CTTAGTTGATAACCATCCTAAT</span><span style="Background-color: #FFA500">TGCGTTGTTCAAAGTTACCTTGCATGGTTAACCGATTCCGATTACGATCCAAATTGTG
CACTTTGTCAAACACCATTGAATTCTGGCGAAACTATACGTCTGAACTGTCTTC</span><span style="Background-color: #FFFF00">ATCTTCTTCACTGGAAATGTTTCGAT
GATTGGGCTGCAGCATTTCCAAATACAACAGCTCCAGCAGGTTATCGTTGTCCATGTTGTAGTAAAGAAGTATTTCCACC
ACTCAATGAAGTTTCTCCACTCGTTGAAAAACTTCGAGAGCAGTTGAAATTATCAAATTGGGCTCGAGCAGCTTTAGGTC
TTCCAGTTTTACCGGAATTGAATCGTCCAATCACAAAAACTTTTGATAAACCGATTCCTCCACCAATTGTGAATAAACCA
GTGGAAAATGTTGGAGCTGTTGCTCATCAAACTCAACGATCAATAACTCCCGCAACACATTTAGATATGGAAGATTCTGC
ATCTTTTTCTGTTTCTTCAAGTGATGTTACTTTTT</span><span style="Background-color: #FFA500">CACGTAAAAAGAATTTGGGAGATACTCGTCCATTGTTACAAAATG
ATAATCGCGATGCAGACAATGAAGCAAATAAATATAAACGTAGACCAGCTGGAGAATGGATTCGTGGATTGTGGAGAGCA
AAATATGGTCCTGGAGTACCAGAAGATGGTTTGAGTGGAAGAAAGAAATTGGTTTTTGTAGTTTTCATTGCATTTGTTTC
ATTGGTTACT</span><span style="Background-color: #FFFF00">ATTTATCTTGTTCTCAAACGACTTGGTGTAAATAATGACAACGATCCAATGTTTGACCCATTATCAAATC
CAAACATCAGAGTTGCTTCGAACAATGAATAA</span>sequencestyle

spliced + UTRheader/length0MGLCKCPKRKVTNLFCYEHRVNVCEFCLVDNHPNCVVQSYLAWLTDSDYDPNCALCQTPLNSGETIRLNCLHLLHWKCFDDWAAAFPNTTAPAGYRCPCCSKEVFPPLNEVSPLVEKLREQLKLSNWARAALGLPVLPELNRPITKTFDKPIPPPIVNKPVENVGAVAHQTQRSITPATHLDMEDSASFSVSSSDVTFSRKKNLGDTRPLLQNDNRDADNEANKYKRRPAGEWIRGLWRAKYGPGVPEDGLSGRKKLVFVVFIAFVSLVTIYLVLKRLGVNNDNDPMFDPLSNPNIRVASNNE*sequence
aatype
conceptual translationheaderdata
the sequence of the sequencedescriptionprint_sequence

**Comment by sibyl229** [comment]
Hi, 

Thanks for reporting the issue! The CDS sequence is loading fine now. http://www.wormbase.org/species/c_angaria/cds/860376:Cang_2012_03_13_00234.g7562.t1#05--10 <http://www.wormbase.org/species/c_angaria/cds/860376:Cang_2012_03_13_00234.g7562.t1#05--10>
Sorry about the difficulty.

Sibyl
