### ISSUE TITLE
Searching for a peptide ID returns irrelevant results

### ISSUE THREAD

**Issue by brucebolt** [WormBase/website#3587]
E.g. searching for BM38054 (Bm2, isoform b) yields a selection of other results but not the protein we are interested in: http://www.wormbase.org/search/protein/BM38054

In some cases, e.g. CN06574, results are displayed for a completely different species.

These identifiers are found elsewhere on the web, e.g. Ensembl, so it could be possible users will be using these to identify proteins and will want to search for them on WormBase.

**Comment by epaule** [comment]
Actually it does appear ... just not necessary on the first page.
I believe the search drags up each and any protein that has the ID
somewhere in its homologies or any other field.

**Comment by epaule** [comment]
Actually it does appear ... just not necessary on the first page.
I believe the search drags up each and every protein that has the ID somewhere in its homologies or any other field.

**Comment by khowe** [comment]
Need better prioritisation of search results. See #2971

**Comment by sibyl229** [comment]
Thanks @brucebolt @epaule @khowe. Searching for CN06574 http://staging.wormbase.org/search/protein/CN06574 and BM38054 http://staging.wormbase.org/search/protein/BM38054 are returning the right result is on the top of search results now. 

The issue is intriguing and has to do with search heuristics. Basically to optimize for speed, _not all_ potential matches are searched. Some potential match, that would generated a good score in ranking, may not be searched. A simple solution would be to force it to look at more match, this is what's done. Better indexing may help too, but that will require more consideration.

**Comment by brucebolt** [comment]
That looks good, thanks for the explanation @sibyl229.

**Comment by epaule** [comment]
I think it is also a bit special for the proteins, as the objects
themselves contain a prefix, so the best you can get with "just" the
protein id is a substring match.

**Comment by tharris** [comment]
@epaule is definitely on to something with this. If these are commonly used identifiers that we are expecting users to use across websites, do we / should we actually be prefixing them? Who is the canonical owner of these IDs? We should follow their lead.

**Comment by khowe** [comment]
In the case of the ids above (CN06574, BM38054), *we* are the canonical owner. These are WormBase (wormpep) IDs!

Since the protein class contains entries for proteins from various database, a prefix is added to guarantee uniqueness (two different dbs might use the same accession for different objects). 

Historically, we treated the protein set for each WormBase species as a "database" in itself ("wormpep", "remapep", "brugpep" etc).  So for consistency (I guess), these protein objects are created in  Acedb with a prefix code for the database from which they came ("WP:" for wormpep, "RP:" for remapep, "BM:" for brugpep etc).  But the informative part of the id (the CN\d+ and BM\d+ above) is already guaranteed to be unique, by construction. Note they already have a prefix! No additional prefix is necessary. 

I'd like to see the "WP:", "RP:" etc prefixes removed for WormBase-internal entities. This is a Hinxton task. However, we'll need to do this carefully because I daresay we have code in the build that assumes them...

**Comment by tharris** [comment]
@khowe I know. It's almost like we should have propagated our prefixed names to other services to begin with. Slightly hilarious that we have our own distinct representation of IDs.

I'm happy stripping the prefixes from the internal IDs. It will definitely affect the display code as well. I think there are places where we do bizarre things like ascertain species according to the prefix.

**Comment by brucebolt** [comment]
This appears to have been resolved.  The correct protein comes up as the first result now.
