### ISSUE TITLE
OpenID 2.0 being retired; notice to migrate to OpenID Connect by April 2015

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#3595]
I'm sure the web team is already aware of this, but thought I'd just point out that when I logged into my WormBase account today, I got the following message:

![screen shot 2015-02-06 at 10 08 47 am](https://cloud.githubusercontent.com/assets/611382/6086795/6c993cf8-adf9-11e4-9ce7-3c2b2ff1df5d.png)

**Comment by sibyl229** [comment]
Hi @chris-grove, thanks for the reminder. It now has been changed to use OAuth2 instead of OpenID for signing in with Google. You should be able to use Google to sign in on staging site now. You might need to refresh the page to see your status as logged in though, I'm still working on fixing that. Could you please let me know if you see something isn't working? 

The staging database for user information isn't complete, so you won't be able to see your _previous_ browsing history. But you should be able to see new ones, as they are generated.

**Comment by chris-grove** [comment]
Thanks @sibyl229  looks good!
