### ISSUE TITLE
Jbrowse track labels

### ISSUE THREAD

**Issue by epaule** [WormBase/website#3622]
I think it would be great, if it would show the isform/CDS name somewhere (as example in the "undefined" field), else you end up with multiple lines with the same name (see below)

![screenshot from 2015-02-19 15 26 46](https://cloud.githubusercontent.com/assets/20523/6269586/2b469fb8-b84c-11e4-935b-3dc82d12e3c0.png)

**Comment by scottcain** [comment]
In this instance, it looks like it would make more sense just to suppress the isoform name altogether, unless in this track there are different isoform names that would get displayed for other genes.  Assuming this is one of the curated genes tracks, my visual inspection leads me to believe they are always going to look like this.  The question is this: is there missing data that should go where "undefined" is, or is should it go away.

Comparing to the Curated Genes track in GBrowse, I think it should just be suppressed, since it doesn't look to me like it adds anything in GBrowse either.

**Comment by epaule** [comment]
Normally I would expect the transcript or CDS id to be where the "undefined" is

**Comment by scottcain** [comment]
Is this better?

![screen shot 2015-02-19 at 12 46 15 pm](https://cloud.githubusercontent.com/assets/274751/6272453/bcc20458-b835-11e4-842a-10ded2d513f7.png)

I'd say this is better than what currently happens in GBrowse:

![screen shot 2015-02-19 at 12 51 11 pm](https://cloud.githubusercontent.com/assets/274751/6272499/06806b34-b836-11e4-9235-13df569f48e6.png)

(as an aside, it looks like I have the colors backwards--I'll fix that now).

**Comment by epaule** [comment]
yes, that falls into the "excellent" category :-)

**Comment by scottcain** [comment]
The new, better labeling has been commited :-)
