### ISSUE TITLE
Broken image thumbnail in Expression widget

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#3636]
On the F49H12.4 gene page:

http://www.wormbase.org/species/c_elegans/gene/WBGene00018655#01--10

in the expression widget, the thumbnail pop-up for Expr10647 is showing a broken image link:

![screen shot 2015-02-24 at 2 15 31 pm](https://cloud.githubusercontent.com/assets/611382/6360574/01865e06-bc30-11e4-8e77-dc222ca875f0.png)

and clicking on the broken image link icon returns no results:

![screen shot 2015-02-24 at 2 18 49 pm](https://cloud.githubusercontent.com/assets/611382/6360590/289858d2-bc30-11e4-8907-a78b802bab3f.png)

Also, the second Expr7963 image shows a working thumbnail:

![screen shot 2015-02-24 at 2 19 54 pm](https://cloud.githubusercontent.com/assets/611382/6360621/5a696fea-bc30-11e4-9cce-03469be0a457.png)

but again, no results when clicking on the image:

![screen shot 2015-02-24 at 2 20 08 pm](https://cloud.githubusercontent.com/assets/611382/6360630/641a7304-bc30-11e4-97ee-7a5cd9115ec0.png)

**Comment by draciti** [comment]
Sibyl, let me know if you need any input on this one. thanks

**Comment by sibyl229** [comment]
Hi @draciti the broken original image link is fixed now: http://staging.wormbase.org/species/c_elegans/gene/WBGene00018655#01--10

I also made a small change to the "view images" link in Expression pattern table (Gene page), so that the popup will be the picture/lightbox widget (which has a description), instead of the curated images field on Expr_pattern page (without description). It also works for Expr_pattern with multiple pictures Expr3857 in http://staging.wormbase.org/species/c_elegans/gene/WBGene00001170#1--10 Please let me know what you think about this. Thank you.

**Comment by draciti** [comment]
thanks Sibyl! It looks good
just one question. For the examples that have more than one picture (e.g. Expr3857 on this page http://staging.wormbase.org/species/c_elegans/gene/WBGene00001170#1--10), would it be possible to click on one image and in the pop up box you can click on a 'next picture' button to see any additional one?

**Comment by sibyl229** [comment]
@draciti Yup. It can be done. Please leave the issue open, and I can work on it.

**Comment by draciti** [comment]
thanks sibyl!

**Comment by sibyl229** [comment]
Hi @draciti it's possible to move between expression images without exiting the popup now. http://staging.wormbase.org/species/c_elegans/gene/WBGene00015146#10-9f-3

**Comment by draciti** [comment]
That is wonderful Sibyl, thank you! It looks really nice. I am closing
