### ISSUE TITLE
  Hello, I am looking for C. elegans ge...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3670]
<p>&nbsp;&nbsp;Hello,<br/>I am looking for C. elegans genes names for klp-2 and klp-5. I used these genes for a RNAi screen 2 years ago but since then, they are no longer in the list of Wormbase genes. Could you help me please?<br/>Thanks<br/>Sophie (quintin@igbmc.fr)</p>

Reported by: Soph********** (quin************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/600.3.18 (KHTML, like Gecko) Version/7.1.3 Safari/537.85.12

**Comment by tuli** [comment]
Dear Sophie,

Thank you for writing to WormBase.

klp-2 is an other name of osm-3
klp-5 is an other name of vab-8

My records show that this has been the status since 2002.

A search in WormBase does not give a very intuitive list of results
and this is something we are working on, however, if you enter e.g.
klp-2 in the search box it should auto fill to osm-3 which you can
then select and it will take you to the right page.

You say the genes are no longer in the list of Wormbase genes. Is this
a specific list you are referring to or do you mean the WormBase
website?

Thank you,

Mary Ann

~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by tuli** [comment]
Follow up. Have been communicated with Sophie and have pointed her to staging version of search function which is much better.
