### ISSUE TITLE
  Hello, we are trying to design genoty...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3708]
<p>&nbsp;&nbsp;Hello, we are trying to design genotyping primers for str-182, but cannot find its mutation information from WormBase.  Can you please let us know how to find such information?  I remember we can locate this information when using the old version of WormBase.  But it seems there is no access to the old version anymore. <br/>Thank you very much for your help.<br/>Sunny</p>

Reported by: Sunn* (jing**************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 6.1; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; InfoPath.3; BRI/2; rv:11.0) like Gecko

**Comment by vanaukenk** [comment]
Dear Sunny,

Thanks for writing to WormBase.

Information about the molecular nature of mutations can be found by
clicking on the Genetics widget on the left side of the gene page.

Within the Genetics section, you can click on individual mutations to get
details about the sequence change, if available.

If you need more assistance, please let us know.

Best,
--Kimberly Van Auken



> How
> Do
> I
> ...?
>   Hello, we are trying to design genotyping primers for str-182, but
> cannot find its mutation information from WormBase.  Can you please let
> us know how to find such information?  I remember we can locate this
> information when using the old version of WormBase.  But it seems there
> is no access to the old version anymore.
> Thank you very much for your help.
> Sunny
> Submitted From:
>   support /tools/support
>  This issue has been assigned ticket number: #3708. Follow progress on our
> issue tracker.
>
>   Reported by: Sunny (jingru.sun@wsu.edu)
>  25 Mar 15 22:03
>
>  Mozilla/5.0 (Windows NT 6.1; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET
> CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C;
> .NET4.0E; InfoPath.3; BRI/2; rv:11.0) like Gecko     This question was
> reported via the web interface at wormbase.org. You can also email us
> directly.
>   --
>  --
>  You received this message because you are subscribed to the "WormBase:
> help" group.
>  To post to this group, send email to help@wormbase.org
>  To unsubscribe from this group, send email to
>  help+unsubscribe@wormbase.org
>  For more options, visit this group at
>  http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>
>   To unsubscribe from this group and stop receiving emails from it, send
> an email to help+unsubscribe@wormbase.org.
>

**Comment by vanaukenk** [comment]
Hi Sunny, the gray indicates an untranslated region (UTR).

Best,

Chris Grove



> HI Kimberly,
>
> Thank you for your help!
>
> I have a new question about frpr-10 gene.  From Wormbase, we can see that
> it consists several exons under "Location" tab.  I notice the color of the
> first exon is gray, and half of the second exon is also gray.  Could you
> please let me know why they are gray? And what is the difference between
> gray and pink used for exons?
>
> Thank you.
>
> Sunny
>
>
> -----Original Message-----
> From: vanauken@caltech.edu [mailto:vanauken@caltech.edu]
> Sent: Thursday, March 26, 2015 6:40 AM
> To: Sun, Jingru
> Cc: vanauken@caltech.edu; help@wormbase.org
> Subject: RE: [wormbase-help] How Do I ...?: Hello, we are trying to design
> genoty... (Sunny)
>
> Dear Sunny,
>
> The only additional information I can find on the ok1419 deletion is at
> the CGC's web site:
>
> https://urldefense.proofpoint.com/v1/url?u=http://www.cgc.cbs.umn.edu/strain.php?id%3D12072&k=EWEYHnIvm0nsSxnW5y9VIw%3D%3D%0A&r=lwg3iOwkWOag0ubVdh4Nkp26Gwg42NGm58%2FHasAE5mU%3D%0A&m=GL5BcKch%2B4YlIGQtVmotxh7Qe2W4Lyv8bGsBKXAdMkw%3D%0A&s=992d89fdef0513f957e04d34bbe7515d0e22bf1b5163bd2b3370416e235e4ffe
>
> This entry says that the estimated deletion size is about 800bp.
>
> You may want to sequence the resulting PCR product to confirm the deletion
> breakpoints, though.
>
> Best,
> --Kimberly
>
>
>
>
>> Hi Kimberly,
>>
>> Thank ou very much for your quick response.  I found str-182 genetic
>> information but it looks like str-182(ok1419) has not been placed on
>> the physical map.  From its molecular details, I found the oligos for
>> sequece-only assays: OK1419_external and OK1419_internal.  Could you
>> please let me know if we can use these oligos to genotype this gene
>> str-182(ok1419)?
>>
>> Thank you very much for your time and help.
>>
>> Sunny

**Comment by vanaukenk** [comment]
An additional response from Mark Edgley and a question about primers in WB:

Hi Mark,

 

Thank you very much for your detailed information and advice!

 

I still have a couple of questions about this RB1306(OK1419).

 

1.      From CGC, I found its nested PCR sequences are: Outer Left Sequence: aacatggctttttctggcac. Outer Right Sequence: aaagggaaaattgggcaaag. Inner Left Sequence: acggtgcaaacattggtaca. Inner Right Sequence: ttcgaccttgcttcgaaagt. Inner Primer PCR Length: 2264. Estimated Deletion Size: about 800 bp.

 

However, from WormBase, here is the oligo information:

 

Sequence-only assay

Verified PCR product:
	

OK1419_external

Left Oligo:
	

aaagggaaaattgggcaaag

Right Oligo:
	

aacatggctttttctggcac

 

Sequence-only assay

Verified PCR product:
	

OK1419_internal

Left Oligo:
	

ttcgaccttgcttcgaaagt

Right Oligo:
	

acggtgcaaacattggtaca

 

My question is that why the outer LEFT sequence from CGC becomes RIGHT oligo for OK1419_external in wormbase, and why the outer RIGHT sequence becomes LEFT oligo?  These also apply to inner sequences?  I also found this happens to other genes.  I guess there must be reason for that.  Could you please let me know it? 

 

2.      I failed to find the oligo sequences from its unspliced or spliced gene sequence.  For example, I can’t find the outer right sequence: aaagggaaaattgggcaaag from the gene sequence.  Any suggestions?

 

Thank you very much for your time and help!

 

Sunny

 

 

From: Mark Edgley [/webmail/src/compose.php?send_to=edgley@mail.ubc.ca]
Sent: Thursday, March 26, 2015 2:00 PM
To: Sun, Jingru
Cc: Mary Ann Tuli; vanauken@caltech.edu
Subject: Re: Fwd: [wormbase-help] How Do I ...?: Hello, we are trying to design genoty... (Sunny)

 

Dear Sunny,

I'm sorry that I'm not able to help very much, but I can give you some advice.  The ok1419 deletion was never
sent to us in Vancouver to sequence, so I don't have any data on its breakpoints.  Since WormBase does not
have any better molecular detail, it's probably safe to say that no one else has sequenced the deletion either!

Nested PCR was used to detect the deletion in all stages of processing in the originating lab, from initial screens
through subsequent establishment of the homozygous line that became RB1306.  The primers for that PCR are
the ones given in the CGC strain description, so that the "outer left" and "outer right" pair are for the first-round PCR,
and the "inner left" and "inner right" are for the second-round PCR.  We used nested PCR routinely to provide both
sensitivity and specificity for detecting deletions in complex genomic DNA pools, but we did not test individual
primer pairs to see if they worked very well.

My best advice is to use nested PCR with the primers given in the CGC strain description for genotyping, as we
know that PCR was robust and reliable.  Once you've shown that those primers reliably distinguish between deletion
and wild-type templates, you could play around with individual primer pairs to see if you can see the deletion in
single-round PCR.  In any case, you should sequence the deletion PCR product with appropriate primers to determine
the breakpoints and then send that result to WormBase.

Bear in mind that a low percentage of deletion alleles identified by any of the Knockout Consortium labs are not truly
mutant because they appear to carry a deleted copy of the gene in addition to a functional wild-type copy.  The easiest
diagnostic for this is to do PCR on wild-type and deletion templates using one primer outside the deletion breakpoint
and one inside - you should get a product from the wild-type but not from the mutant.

I hope this helps!  Good luck.

best wishes,

Mark
