### ISSUE TITLE
  I am interested in aligning some RNA ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3709]
<p>&nbsp;&nbsp;I am interested in aligning some RNA sequences to the WS247 build. I am looking for an annotation file I can use to do a differential gene analysis.  Usually I use a GTF file, but I dont have one for this build. Is there a way to creat such a file in wormmine or does this file already exist somewhere?</p>

Reported by: Patr*** (gonz*****************)  (obscured for privacy))
Submitted From: Tools <a href="http://www.wormbase.org//header">/header</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:36.0) Gecko/20100101 Firefox/36.0

**Comment by epaule** [comment]
we don't include GTF files on our FTP server (they are quite easy to create from the GFF files), 
but you can get a GTF file for WS245 from the ensembl FTP site instead of convertnig it yourself ftp://ftp.ensembl.org/pub/release-79/gtf/caenorhabditis_elegans

Also WS247 hasn't been officially released yet, and we are still in the process to remove bugs from the files, so you would be anyway better off with the WS246 release, unless there is some specific feature of WS247 (curation topics / papers published since WS246 / etc.) that you need.
