### ISSUE TITLE
  Hi Folks, When I search for a gene an...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3775]
<p>&nbsp;&nbsp;Hi Folks,<br/>When I search for a gene and enter unc-13 in the box, it only comes up with this page for the drosophila homolog, rather than the C. elegans gene.<br/>http://www.wormbase.org/species/drosophila_melanogaster/gene/FBgn0025726#016-9abdc3e7f4-10<br/>Thanks for all you do!<br/>Bob O'Hagan</p>

Reported by: Robe********** (1kbb*************)  (obscured for privacy))
Submitted From: unc-13 (gene) <a href="http://www.wormbase.org//species/drosophila_melanogaster/gene/FBgn0025726#016-9abdc3e7f4-10">/species/drosophila_melanogaster/gene/FBgn0025726#016-9abdc3e7f4-10</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36

**Comment by khowe** [comment]
@tharris : In the database, "unc-13" is the public name for both the C. elegans gene and its D.mel ortholog. I would therefore expect a gene search for "unc-13" to result in (at least) two hits. However, the web-site takes you directly to the gene page for the D.mel gene.

**Comment by khowe** [comment]
Seems multiple people are hitting this issue.

**Comment by epaule** [comment]
same as #3796

**Comment by tharris** [comment]
I don't think a disambiguation is the right solution for this. Our core user community consists of C. elegans researchers. Locus names are used as unique identifiers by our community. When someone searches for unc-104 they expect to be taken to the C. elegans unc-104 page. 

We need to either a) change the search results so that it prioritizes C. elegans results and directs users directly to that page; or b) stop the practice of duplicating what should be unique IDs for our community, especially since it serves no purpose.

**Comment by khowe** [comment]
To be fair, these names do serve a purpose. We are now storing the orthology relationships correctly, as ?Gene->?Gene, and the yeast/fly/zebrafish/human orthologs for worm genes are now being shown in the homology widget with their correct community names. 

It's unfortunate that for a handful of genes (46 to be precise; see list below), the fly/zebrafish communities have used the same symbol as a worm gene. I also concede that when even a fly researcher types "unc-13" into WormBase, they are almost certainly looking for (a) C. elegans unc-13, or (b) the C.elegans ortholog of unc-13. Either way, they are looking for a worm gene. So agreed, direct fall-through to the C. elegans gene page is the desired behaviour. 

The ideal solution to this would be to prioritise search results, such that when a collection of genes is hit but only one of them is C. elegans, then the user should be taken directly to the C. elegans gene page. Alternatively, could non-nematode genes be excluded from the gene search index? The database itself does not provide an easy way of determining whether a species is nematode, but a quick-and-dirty approach would be to use treat genes having "WBGene" ids as ours (and to be indexed), with other gene objects being excluded from search index. 

Also, I would argue that even when a symbol is unique to D. mel (e.g. "14-3-3zeta"), it's better for search results to show worm genes referring to that D. mel gene (in this case, ftt-2 and par-5), rather than being taken to a stub gene page for the D. mel gene itself. 

alg-2
aph-1
ari-1
atf-2
ced-12
ced-6
che-13
dcr-1
dec-1
fem-1
fmo-1
fmo-2
glct-1
hmt-1
lin-28
lin-52
lis-1
lsd-1
lsm-4
mab-21
mep-1
mes-4
nrx-1
par-1
par-6
patr-1
pen-2
ric-3
rme-8
sas-4
sas-6
sodh-1
sodh-2
spd-2
sra-1
trx-2
trxr-1
trxr-2
unc-104
unc-119
unc-13
unc-4
unc-45
unc-5
unc-76
unc-89

**Comment by khowe** [comment]
Also, I should add: if the quickest way to address this bug for WS247 (the current live release) is to patch the database to get rid of the conflicts, we can supply a patch, no problem. But I don't think that's the correct long-term fix.

**Comment by timschedl** [comment]
Yes, the top hit for such a search needs to be the C. elegans gene.
Tim

**Comment by tharris** [comment]
@khowe can I please have patch files for BOTH WS247 and WS248? On its surface, it seems like this might be an easy issue to resolve but it actually involves several components, including search indexing and behavior. For now, I really want the app to behave the way users expect: searching with a canonical C. elegans locus name results in automatic direction to a C. elegans gene page.  We will deal with the nuance of the ID overloading at a  later date.

**Comment by khowe** [comment]
Patches available:

ftp://ftp.sanger.ac.uk/pub/consortia/wormbase/releases/WS247/acedb/PATCHES/gnames_patch.WS247.ace

ftp://ftp.sanger.ac.uk/pub/consortia/wormbase/releases/WS248/acedb/PATCHES/gnames_patch.WS248.ace

Note: when this is fixed "properly" at the search level, auto-complete also needs to be addressed. When you start typing "unc" into the search box, the first raft of genes coming back on the auto-complete are not worm genes; only when you add the "-" do the results enrich for worm genes. Autocomplete should restrict to worm gene names.

**Comment by tharris** [comment]
Thanks, patching starting with WS248 for now.

**Comment by tharris** [comment]
Fixed for WS247 and WS248; marking this as under testing so we can close all of these reports. See the new parent issue at #3820.

**Comment by tharris** [comment]
Response to user: 

This issue is resolved.

Thank you for reporting the problem, and my apologies for the difficulties.
