### ISSUE TITLE
  The sequences for CJA35107 & CJA35108...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3806]
<p>&nbsp;&nbsp;The sequences for CJA35107 & CJA35108 look incorrect:<br/>>CJA35107 gene=WBGene00210954<br/>ataccccacaacaatttccatctcctgccgtatcttttccgacagtccgg<br/>ccgtctgagaaaatagttaaaaaatcagaaaaggtgggtaaagttcggaa<br/>ggcatcaaaaatgcatcagaacacctgctgtaccaattgtggaattggca<br/>agacaactttgtggcggagaagtgaatcaggacttccagagtgcaacgct<br/>tgcaacacttatgaacgtgtgaagggacacaaacggcctgcagagctttg<br/>gaacaaaccgacaatgcagagaagacgtcgcccacttgccaaaatcaatg<br/>agaagacgtcaggtggagaagataaatga<br/>>CJA35108 gene=WBGene00210955<br/>gtttgttcatatcacccttatcaacgtgttcccacgtgattacgttgcag<br/>gtggacgattcaagaaagaggtggttatcgaagggcagagccatttgctg<br/>ctcattcgtgacgagggccaacaacacttggacgtgcagttttgccagtg<br/>ggtcgacgccattgtgtttgtgttcaacgtgtgctcgatccaaagctacg<br/>acagtattcagtcgttggcgcacgagatgagcaagtatcggaatattggc<br/>gatttgccactgattttggttggcaccaag<br/>These are supposed to be CDS, but they don't start with ATG.  There is also an early stop codon in CJA35107.</p>

Reported by: Scot******** (sari*************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:37.0) Gecko/20100101 Firefox/37.0

**Comment by epaule** [comment]
CJA35107 is just a C-terminal fragment of a gene, due to the contig ending upstream of the splice site.
If you go it the website of its CDS: http://www.wormbase.org/species/c_japonica/cds/CJA35107 it shows a Partial CDS: start not found

CJA35108 is even worse, as the contig only contains one exon from the middle of a gene. You have to translate it in GFF phase 2 / the 3rd frame to get the translation in the database.

These gene fragments on short contigs are a feature of whole genome shotgun sequencing and the situation did get worse with the advent of short-read assemblies.
We could have excluded contigs below a certain cut off from the gene set for aesthetic reasons, but as these fragments might be the only bits we have of some genes, I left them in.

There are actually 5767 fragmentary genes in the current gene set of 29931 protein coding genes.

But as we depend on community requests to identify genes for curation in C.japonica, please continue to tell us about any gene models that you would like us to have a look on.
