### ISSUE TITLE
S.ratti coming up as genusAllspecies

### ISSUE THREAD

**Issue by epaule** [WormBase/website#3834]
I had a quick stab around in the orthology and species data, but couldn't see anything obvious.

http://staging.wormbase.org/species/b_malayi/gene/WBGene00222185

![screenshot 2015-04-30 at 16 39 55](https://cloud.githubusercontent.com/assets/20523/7416488/98e7c942-ef57-11e4-88e0-392c0dfa7063.png)

**Comment by dasmoth** [comment]
I think this is because S. ratti gene stubs don't (as of WS248) seem to have a Species tag.

Looking at the code [here](https://github.com/WormBase/website/blob/staging/lib/WormBase/API/Object/Gene.pm#L1010-L1019), it seems that the species column on that table comes from Gene->Species of the ortholog gene, not from the species field that's attached to the the orthology record itself.

**Comment by epaule** [comment]
thanks.

I put a patch for WS248 here:
ftp://ftp.ebi.ac.uk/pub/databases/wormbase/releases/WS248/acedb/PATCHES/WS248_sratti_patch.ace.gz

... and at Sanger.
It will blow away the dodgy genes.

**Comment by dasmoth** [comment]
Will deleting the gene objects actually help?

Is it possible to add a Species tag to the existing gene stubs?

**Comment by epaule** [comment]
the S.ratti genes that link from the ortholog tag of the genes have been replaced with a new geneset, just the compara still contained the old ids. Have a look at the respective S.ratti GBrowse, and you will see.

**Comment by tharris** [comment]
Patched.

**Comment by epaule** [comment]
looks fine :-)
