### ISSUE TITLE
modENCODE track update in G(J)Browse

### ISSUE THREAD

**Issue by gw3** [WormBase/website#3836]
@scottcain could you replace the existing modENCODE tracks currently in GBrowse with the ones in 

http://gbrowse.modencode.org/fgb2/gbrowse/worm/

It would probably be best if they were all in one section clearly labelled as "modENCODE data (2014)"

I think it would not be necessary to copy the WormBase data in the modENCODE sections: "Annotations for Curated and Predicted Genes from WormBase", " Gene Structure" and "RNA Expression Profiling", "non-modENCODE Reference Data" as this largely duplicates our own tracks.

This leaves the sections: "Chromatin Structure", " General", and "Transcription Factors" to be copied.

We think that it is not necessary to remap the data from the WS220 release coordinates that they are currently aligned to as the differences between WS220 and the current assembly are small when compared to the size and resolution of the features being displayed in these tracks.

**Comment by scottcain** [comment]
@tharris can you give me a little guidance on how to start with this?  I believe you mentioned something about an existing pipeline?

**Comment by tharris** [comment]
@scottcain I wrote a pipeline to automatically process incoming quantitative data a few years ago. We have only received a few files I processed as one-offs.

You should be able to get all the files you need (including gbrowse config) from modencode.org. There may still be a copy kicking around at OICR, or we could just copy the data directory and config wholesale. I think the browser data structure has a slightly, um, confusing structure. But if you aren't remapping, you don't need to reprocess. You'll just need the data (place it in /quantitative_data), config files, and then update paths as appropriate.

**Comment by scottcain** [comment]
Having just finished the porting of data currently in GBrowse to JBrowse, I'm finally returning to this problem.  If I'm understanding correctly, the outline below shows the categories, subcategories and labels for each of the tracks that need to be moved over from modENCODE.  This is approximately 180 tracks, not including subtracks, which will add (as a guess) a few hundred more tracks to the total.  I will port these to JBrowse first unless somebody would prefer that I do otherwise.

General
  EFL-1 Combined (GFP ChIP)
  L1LIN35-1cap1

Chromatin Structure
  Chromatin modifying enzymes
    Centromere Specificaton ChIP-chip arrays
    Chromatin Silencing ChIP-chip arrays
    Chromosome-Nuclear Envelope Interaction
  Histone Modifications and Variants
    ChIP-Seq
      Core Histones ChIP-Seq
      Histone Modifications in H3K18 (ChIP-Seq)
      Histone Modifications in H3K79 (ChIP-Seq)
      Histone Modifications (H3K4) ChIP-Seq
      Histone Modifications in H3K23 (ChIP-Seq)
      Histone Modifications in H3K9 (ChIP-Seq)
      Histone Modifications (H4) ChIP-Seq
      Histone Modifications in H3K27 (ChIP-Seq)
      Histone Modifications in H3Ser10
      Histone Modifications in H2AK5 (ChIP-Seq)
      Histone Modifications in H3K36 (ChIP-Seq)
      Histone Modifications in H4K20 (ChIP-Seq)
      Histone Modifications in H3K14 (ChIP-Seq)
      Histone Modifications in H3K4 (ChIP-Seq)
      Histone Modifications in H4K8 (ChIP-Seq)
    ChIP-chip
      Core Histones ChIP-chip arrays
      Histone Modifications (H3K4) ChIP-chip arrays
      Histone Modifications (H4) ChIP-chip arrays
      Histone Modifications (H3K27) ChIP-chip arrays
      Histone Modifications (H3K79) ChIP-chip arrays
      Histone Variants ChIP-chip arrays
      Histone Modifications (H3K36) ChIP-chip arrays
      Histone Modifications (H3K9) ChIP-chip arrays
  Nucleosome Structure
    Chromatin fractions extracted with NaCl
    Mononucleosomes
    H3.3 Chromatin fractions extracted with NaCl
    Mononucleosomes 80mM NaCl

Transcription factors
  Control N2 ChIP
    Pol II Combined (N2 ChIP)
General
  EFL-1 Combined (GFP ChIP)
  L1LIN35-1cap1

Chromatin Structure
  Chromatin modifying enzymes
    Centromere Specificaton ChIP-chip arrays
    Chromatin Silencing ChIP-chip arrays
    Chromosome-Nuclear Envelope Interaction
  Histone Modifications and Variants
    ChIP-Seq
      Core Histones ChIP-Seq
      Histone Modifications in H3K18 (ChIP-Seq)
      Histone Modifications in H3K79 (ChIP-Seq)
      Histone Modifications (H3K4) ChIP-Seq
      Histone Modifications in H3K23 (ChIP-Seq)
      Histone Modifications in H3K9 (ChIP-Seq)
      Histone Modifications (H4) ChIP-Seq
      Histone Modifications in H3K27 (ChIP-Seq)
      Histone Modifications in H3Ser10
      Histone Modifications in H2AK5 (ChIP-Seq)
      Histone Modifications in H3K36 (ChIP-Seq)
      Histone Modifications in H4K20 (ChIP-Seq)
      Histone Modifications in H3K14 (ChIP-Seq)
      Histone Modifications in H3K4 (ChIP-Seq)
      Histone Modifications in H4K8 (ChIP-Seq)
    ChIP-chip
      Core Histones ChIP-chip arrays
      Histone Modifications (H3K4) ChIP-chip arrays
      Histone Modifications (H4) ChIP-chip arrays
      Histone Modifications (H3K27) ChIP-chip arrays
      Histone Modifications (H3K79) ChIP-chip arrays
      Histone Variants ChIP-chip arrays
      Histone Modifications (H3K36) ChIP-chip arrays
      Histone Modifications (H3K9) ChIP-chip arrays
  Nucleosome Structure
    Chromatin fractions extracted with NaCl
    Mononucleosomes
    H3.3 Chromatin fractions extracted with NaCl
    Mononucleosomes 80mM NaCl

Transcription factors
  Control N2 ChIP
    Pol II Combined (N2 ChIP)
General
  EFL-1 Combined (GFP ChIP)
  L1LIN35-1cap1

Chromatin Structure
  Chromatin modifying enzymes
    Centromere Specificaton ChIP-chip arrays
    Chromatin Silencing ChIP-chip arrays
    Chromosome-Nuclear Envelope Interaction
  Histone Modifications and Variants
    ChIP-Seq
      Core Histones ChIP-Seq
      Histone Modifications in H3K18 (ChIP-Seq)
      Histone Modifications in H3K79 (ChIP-Seq)
      Histone Modifications (H3K4) ChIP-Seq
      Histone Modifications in H3K23 (ChIP-Seq)
      Histone Modifications in H3K9 (ChIP-Seq)
      Histone Modifications (H4) ChIP-Seq
      Histone Modifications in H3K27 (ChIP-Seq)
      Histone Modifications in H3Ser10
      Histone Modifications in H2AK5 (ChIP-Seq)
      Histone Modifications in H3K36 (ChIP-Seq)
      Histone Modifications in H4K20 (ChIP-Seq)
      Histone Modifications in H3K14 (ChIP-Seq)
      Histone Modifications in H3K4 (ChIP-Seq)
      Histone Modifications in H4K8 (ChIP-Seq)
    ChIP-chip
      Core Histones ChIP-chip arrays
      Histone Modifications (H3K4) ChIP-chip arrays
      Histone Modifications (H4) ChIP-chip arrays
      Histone Modifications (H3K27) ChIP-chip arrays
      Histone Modifications (H3K79) ChIP-chip arrays
      Histone Variants ChIP-chip arrays
      Histone Modifications (H3K36) ChIP-chip arrays
      Histone Modifications (H3K9) ChIP-chip arrays
  Nucleosome Structure
    Chromatin fractions extracted with NaCl
    Mononucleosomes
    H3.3 Chromatin fractions extracted with NaCl
    Mononucleosomes 80mM NaCl

Transcription factors
  Control N2 ChIP
    Pol II Combined (N2 ChIP)
  GFP ChIP
    AHA-1 Combined (GFP ChIP)
    FOS-1 Combined (GFP ChIP)
    NHR-28 Combined (GFP ChIP)
    ALR-1 Combined (GFP ChIP)
    GEI-11 Combined (GFP ChIP)
    NHR-6 Combined (GFP ChIP)
    ALY-2 Combined (GFP ChIP)
    HAM-1 Combined (GFP ChIP)
    NHR-6.v2 Combined (GFP ChIP)
    AMA-1 Combined (GFP ChIP)
    HLH-1 Combined (GFP ChIP)
    NHR-67 Combined (GFP ChIP)
    BLMP-1 Combined (GFP ChIP)
    HLH-30 Combined (GFP ChIP)
    NHR-76 Combined (GFP ChIP)
    C01B12.2 Combined (GFP ChIP)
    HPL-2 Combined (GFP ChIP)
    NHR-77 Combined (GFP ChIP)
    C16A3.4 Combined (GFP ChIP)
    JUN-1 Combined (GFP ChIP)
    PAX-1 Combined (GFP ChIP)
    C34F6.9 Combined (GFP ChIP)
    LIN-11 Combined (GFP ChIP)
    PEB-1 Combined (GFP ChIP)
    CEH-14 Combined (GFP ChIP)
    LIN-13 Combined (GFP ChIP)
    PES-1 Combined (GFP ChIP)
    CEH-16 Combined (GFP ChIP)
    LIN-15B Combined (GFP ChIP)
    PHA-4 Combined (GFP ChIP)
    CEH-26 Combined (GFP ChIP)
    LIN-35 Combined (GFP ChIP)
    PQM-1 Combined (GFP ChIP)
    CEH-28 Combined (GFP ChIP)
    LIN-39 Combined (GFP ChIP)
    R02D3.7 Combined (GFP ChIP)
    CEH-30 Combined (GFP ChIP)
    LSY-2 Combined (GFP ChIP)
    SEA-2 Combined (GFP ChIP)
    CEH-39 Combined (GFP ChIP)
    MAB-5 Combined (GFP ChIP)
    SEM-4 Combined (GFP ChIP)
    CES-1 Combined (GFP ChIP)
    MDL-1 Combined (GFP ChIP)
    SKN-1 Combined (GFP ChIP)
    DAF-12 Combined (GFP ChIP)
    MED-1 Combined (GFP ChIP)
    SMA-9 Combined (GFP ChIP)
    DAF-16 Combined (GFP ChIP)
    MEF-2 Combined (GFP ChIP)
    SPTF-1 Combined (GFP ChIP)
    DPL-1 Combined (GFP ChIP)
    MEP-1 Combined (GFP ChIP)
    TLP-1 Combined (GFP ChIP)
    DPY-27 Combined (GFP ChIP)
    MML-1 Combined (GFP ChIP)
    UNC-130 Combined (GFP ChIP)
    DVE-1 Combined (GFP ChIP)
    N2_POLIII_YA Combined (GFP ChIP)
    UNC-39 Combined (GFP ChIP)
    EGL-27 Combined (GFP ChIP)
    NFYA-1 Combined (GFP ChIP)
    UNC-55 Combined (GFP ChIP)
    EGL-5 Combined (GFP ChIP)
    NHR-10 Combined (GFP ChIP)
    UNC-62 Combined (GFP ChIP)
    ELT-1 Combined (GFP ChIP)
    NHR-11 Combined (GFP ChIP)
    W03F9.2 Combined (GFP ChIP)
    ELT-3 Combined (GFP ChIP)
    NHR-116 Combined (GFP ChIP)
    ZAG-1 Combined (GFP ChIP)
    EOR-1 Combined (GFP ChIP)
    NHR-12 Combined (GFP ChIP)
    ZIP-2 Combined (GFP ChIP)
    F16B12.6 Combined (GFP ChIP)
    NHR-129 Combined (GFP ChIP)
    ZK377.2 Combined (GFP ChIP)
    F23B12.7 Combined (GFP ChIP)
    NHR-2 Combined (GFP ChIP)
    ZTF-11 Combined (GFP ChIP)
    F23F12.9 Combined (GFP ChIP)
    NHR-21 Combined (GFP ChIP)
    ZTF-4 Combined (GFP ChIP)
    F45C12.2 Combined (GFP ChIP)
    NHR-23 Combined (GFP ChIP)
    ZTF-7 Combined (GFP ChIP)
    FKH-10 Combined (GFP ChIP)
    NHR-237 Combined (GFP ChIP)
    FKH-2 Combined (GFP ChIP)
    NHR-25 Combined (GFP ChIP)
  GFP ChIP (Peak Recall)
    ALR-1 Combined (GFP ChIP) recalled peaks
    GEI-11 Combined (GFP ChIP) recalled peaks
    MEP-1 Combined (GFP ChIP) recalled peaks
    BLMP-1 Combined (GFP ChIP) recalled peaks
    HLH-1 Combined (GFP ChIP) recalled peaks
    PES-1 Combined (GFP ChIP) recalled peaks
    CEH-14 Combined (GFP ChIP) recalled peaks
    LIN-11 Combined (GFP ChIP) recalled peaks
    PHA-4 Combined (GFP ChIP) recalled peaks
    CEH-30 Combined (GFP ChIP) recalled peaks
    LIN-13 Combined (GFP ChIP) recalled peaks
    PQM-1 Combined (GFP ChIP) recalled peaks
    DPY-27 Combined (GFP ChIP) recalled peaks
    LIN-15B Combined (GFP ChIP) recalled peaks
    SKN-1 Combined (GFP ChIP) recalled peaks
    EGL-27 Combined (GFP ChIP) recalled peaks
    LIN-39 Combined (GFP ChIP) recalled peaks
    UNC-130 Combined (GFP ChIP) recalled peaks
    EGL-5 Combined (GFP ChIP) recalled peaks
    MAB-5 Combined (GFP ChIP) recalled peaks
    EOR-1 Combined (GFP ChIP) recalled peaks
    MDL-1 Combined (GFP ChIP) recalled peaks
  HOT
    High Occupancy Target regions
  PolII ChIP
    AMA-1 Combined (Pol II ChIP)
    EOR-1 Combined (Pol II ChIP)
    PHA-4 Combined (Pol II ChIP)
    DAF-16 Combined (Pol II ChIP)
    HLH-8 Combined (Pol II ChIP)
    EGL-5 Combined (Pol II ChIP)
    MAB-5 Combined (Pol II ChIP)
  PolII Isoforms ChIP
    Polymerase II Isoforms ChIP-chip arrays
  Transcription and Chromatin
    CBP-1 ChIP-chip arrays
    MRG-1 ChIP-chip arrays
    Transcription Factors ChIP-Seq L3
    Dosage Compensation ChIP-chip arrays
    No Antibody (IGG) ChIP-chip arrays
    Transcription Factors ChIP-Seq Late Embryo
    Dosage Compensation ChIP-Seq
    Polycomb Proteins ChIP-Seq
    Transcription Factors ChIP-Seq Mixed embryo
    Lin-15B ChIP-chip arrays
    Transcription Factors ChIP-Seq DH245
    ZFP-1 ChIP-chip arrays
    MES-4 ChIP-chip arrays
    Transcription Factors ChIP-Seq Early Embryo

**Comment by scottcain** [comment]
Nearly all (or possibly all) of the new tracks from modencode make use of the vista plot glyph in GBrowse, which is a hybrid of a wiggle xyplot and a generic glyph to mark peak calls.  While this looks very nice in GBrowse, JBrowse doesn't currently have an equivelent.  I'm working on a possible option, but in the mean time I'm porting these tracks to GBrowse first.  The first set of tracks are "modENCODE data (2014):Transcription Factors: GFP ChIP" of which there a quite a few tracks.  Here are a few examples:

http://staging.wormbase.org/tools/genome/gbrowse/c_elegans_PRJNA13758/?start=7809500;stop=7829499;ref=III;width=800;version=100;flip=0;grid=on;id=0e64448f783c71df9bcc5f6c7c26f4c6;l=SNYDER_ANTIGFP_CHIPCHIP_C01B12%1ESnyder_ANTIGFP_WIG_COMB_BLMP1_GFP_L1%1ESnyder_ANTIGFP_WIG_AMA1_COMB%1ELOCI%3Aoverview

Note that the mouse-over balloon is broken, but it is also broken for other GBrowse tracks that make use of the "gbrowse_key_img" functionality, which just appears to be generally broken.  Other than that, I think this is in good shape and will continue down this path unless somebody suggests otherwise.

**Comment by scottcain** [comment]
I believe all of the requested tracks from modENCODE 2014 have been added to GBrowse on staging.  Here are a few comments on the added tracks:
* The tracks in General were there due to bugs in the modENCODE configuration files.  One of them is really a transcription factor (which I added in the right place) and one was in one of the "non-requested" categories, so I ignored it.
* I haven't added the HOT track; it's not clear to me if this is part of modENCODE or data from somewhere else.  @gw3  , can you take a look and let me know what do do with this data?  If you'd like it included, I'm sure I can find a place for it.

**Comment by scottcain** [comment]
All the data has been ported to both GBrowse and JBrowse.  Closing...
