### ISSUE TITLE
  Problems using FASTA dumper functiona...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3878]
<p>&nbsp;&nbsp;Problems using FASTA dumper functionality in the P. redivivus genome browser:<br/>Landmark: KB455535:581500..582199<br/>From coordinates 580.3k to end of transcript (~581-6k) FASTA dump doesn't work (FASTA dumper opens a new window but prints out blank). Flanking regions work perfectly though (dumper opens a new window and prints out sequence)<br/>Any idea why?</p>

Reported by: Davi********* (davi*******************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.152 Safari/537.36

**Comment by scottcain** [comment]
I have no idea--when I try to do roughly the same thing, I get a new window with this URL:

http://www.wormbase.org/tools/genome/gbrowse/p_redivivus_PRJNA186477/?plugin=FastaDumper;plugin_action=Go;name=KB455535:580300..581699

that prints out some sequence, which I'm assuming is the correct sequence.  In the newly opened window, what does the URL look like.

@tharris : as a side note, I don't appear to have been added to the helpdesk mailing list yet since I didn't get the original email and so I don't have Davi*'s email address)

**Comment by chris-grove** [comment]
@scottcain  e-mailed user directly
Does not appear to be an issue any more. Closing
