### ISSUE TITLE
  Hi i am looking at crm-1 at transcrip...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3879]
<p>&nbsp;&nbsp;Hi i am looking at crm-1 at transcript c.1 and c.2. The curator comments say is it based on 'EST  confirmed intron', just wanting to clarify what this is? Thanks</p>

Reported by: Kayl****** (u501***************)  (obscured for privacy))
Submitted From: crm-1 (gene) <a href="http://www.wormbase.org//species/c_elegans/gene/WBGene00007103#0-91bef6jd234578ac-10">/species/c_elegans/gene/WBGene00007103#0-91bef6jd234578ac-10</a>

Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.152 Safari/537.36

**Comment by Paul-Davis** [comment]
Dear Kayla,

Thank you for your annotation question.

Intron 4 in the CDS B0024.14c was confirmed by EST BJ107591. This is a 
non-modular 3 splice variation that is also seen in the RNASeq data for 
this gene.....But the problem here is that this is a very highly 
expressed gene and of the ~15500 reads that cover these 2 intron 
variants only ~1.5% confirm this unusual splicing event. Unfortunately 
we are seeing that EST libraries contain an unusually high level of rare 
splice events that we would exclude from our annotations if we were 
looking at the gene now and annotate them solely as Transcript Isoforms 
or exclude completely if EST data doesn't exist.

I have re-annotate this loci and convert both the c and e isoforms into 
a full length transcript with no coding product and added a note to the 
d isoform as this is also a very rare variant, but modular 3 this time 
so can go full length while maintaining coding frame.

For the purposes of any analysis on this gene I would only include 
Isoforms of a,b and f.

These changes will appear in the WS250 release of WormBase.

Thanks again.

Paul



On 20/05/2015 01:50, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   Hi i am looking at crm-1 at transcript c.1 and c.2. The curator 
> comments say is it based on 'EST confirmed intron', just wanting to 
> clarify what this is? Thanks
>
> Submitted From:
>   crm-1 (gene) 
> /species/c_elegans/gene/WBGene00007103#0-91bef6jd234578ac-10 
> <http://www.wormbase.org//species/c_elegans/gene/WBGene00007103#0-91bef6jd234578ac-10> 
>
>
> This issue has been assigned ticket number: #3879. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/3879>.
>
> Reported by: Kayla Venn (u5011162@anu.edu.au)
> 20 May 15 00:51
>
> Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like 
> Gecko) Chrome/42.0.2311.152 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>


-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
