### ISSUE TITLE
FPKM expression fields broken on live site

### ISSUE THREAD

**Issue by dasmoth** [WormBase/website#3886]
See, e.g. [pha-4](http://www.wormbase.org/species/c_elegans/gene/WBGene00004013#-1-10).

The spinner runs for a long time, then eventually fails with a "Bad Gateway".  Appears to be a problem fetching http://www.wormbase.org/rest/field/gene/WBGene00004013/fpkm_expression_summary_ls

**Comment by sibyl229** [comment]
Thanks @dasmoth 
The FPKM field doesn't seem to use the cached data (in CouchDB), looking at the page loading time. It takes around 10 seconds on dev to load, which would be long enough for production to timeout. So I checked if the cached data is broken. I took code from origin/master, and modified it to loading data from the cached WS247 data in Couch. I could successfully load that page in 2 seconds. So I'm puzzled why it's not working on production. 

Hi @tharris do you have any thought on how to debug this?

**Comment by tharris** [comment]
Does the fpkm images exist on staging/production?

I can't check right now. But I wonder if the images are missing it will try to generate them again and likely timeout. And pha-4 has lots of data...

**Comment by sibyl229** [comment]
Hmm on staging: the image for pha-4 is here 
> /usr/local/wormbase/website-shared-files/html/img-static/rplots/WS247/1849/fpkm_WBGene00004013/
They are generated with calls to the fpkm_expression_summary_ls. I would expect the images to in the same location on production.

But I don't think the missing image will cause the cache fetching to fail. Because when the cache exists (which it does) and is fetched (even if it includes non-existent links), the code will bypass the fpkm_expression_summary_ls, hence not calling any plot function. And the result would be a bunch of broken images, not a timeout page. This is really puzzling.

**Comment by dasmoth** [comment]
I'm pretty certain that this was working a few days ago.

If @sibyl229 is right about this not using cached data, I'm wondering if this could have the same root cause as #3880 et al., which I *think* started at a similar time.

**Comment by dasmoth** [comment]
Fixed now (along with Genetic Map and Tree View).

Thanks.

**Comment by tharris** [comment]
I'm going to reopen as quick reminder for myself. I know what's happening but have not yet fixed.

**Comment by Paul-Davis** [comment]
#3896 also refers to this issue I believe

**Comment by tharris** [comment]
Fixed for WS248 and should be going forward.
