### ISSUE TITLE
  The first coding exon of col-166 (iso...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3891]
<p>&nbsp;&nbsp;The first coding exon of col-166 (isoform A-specific) does not seem very well supported by RNAseq or other data. The B isoform is more similar to other collagens.</p>

Reported by: Andr*********** (chis*************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.152 Safari/537.36

**Comment by gw3** [comment]
Andrew,
You are correct.
This gene's structure has not been looked at since 2003 and the RNASeq data
clearly shows that transcription starts in the last 30-odd bases of the
current structure's first exon, after any START codons.
The 'a' isoform will be retired and the 'b' isoform will be renamed to be
'T07H6.3'.

Gary Williams

**Comment by Paul-Davis** [comment]
I can confirm the change has made.
