### ISSUE TITLE
  HI, I'm wondering what the best way i...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3906]
<p>&nbsp;&nbsp;HI,<br/>I'm wondering what the best way is to convert a VCF file from WS230 coordinates to WS245 coordinates. Specifically, I want to convert the SNP and indel coordinates from the CB4856 strain in this recently published paper (http://www.ncbi.nlm.nih.gov/pubmed/25995208 file S2 & S3) to WS245 coordinates.  <br/>Thank you,<br/>Greg<br/>(hobertlab.org)</p>

Reported by: Greg************ (gm21********************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36

**Comment by khowe** [comment]
Hi Greg, 

We don't provide a tool for the direct conversion of VCF files. However, we do provide a generic coordinate conversion tool for GFF-like file formats:

ftp://ftp.ebi.ac.uk/pub/databases/wormbase/software/Remap-between-versions/

With a little bit of scripting, you can make a GFF-like file with the coords you wish to convert, convert them, and then use the converted GFF to produce a remapped version of the the VCF. 

There is a pitfall with converting variation coords in this way though: you will run into cases where a variant position overlaps with a region that has changed in the assembly. These are annoyingly common, because variants will have been called against errors in the reference sequence that have subsequently been fixed. 

We will be integrating the data from this paper in the coming months, converting the coords taking the above into account. If you are willing to wait for that (hopefully available in our WS250 release), you'll be able to get the data from our GFF files. 

Best,

Kevin
