### ISSUE TITLE
Allele-Phenotype Form feedback

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#3929]
I'm creating this ticket to collect issues and feedback regarding the Allele-Phenotype form:

(on Sandbox):
http://mangolassi.caltech.edu/~azurebrd/cgi-bin/forms/allele_phenotype.cgi

**Comment by chris-grove** [comment]
Originally posted in #3867 by @dasmoth 

Playing with the Allele-Phenotype form... The "Can't find your phenotype?" labels have what look like checkbox controls next to them. However, if I click one of these it causes an irreversible change to the page -- adding some new fields and removing the checkbox. This seems unnecessarily alarming -- can you leave the checkbox so it's possible to reverse the change. Better still, show the "Suggest Observed Phenotype" fields by default (maybe inactive/greyed out until you select a "Can't find my phenotype?" checkbox), so users can see immediately what they're getting into.

**Comment by chris-grove** [comment]
Originally posted in #3867 by @dasmoth

It's not entirely obvious when you start that the form is going to allow you to enter more than on phenotype. Worth adding a note somewhere that this is possible?

Also, a minor bug I think. Enter one phenotype, get an extra phenotype field. But then hit "Preview" to see how things are going, and you're back down to a single phenotype field. Had to delete and re-enter the last character of my existing phenotype before I could enter another one.

**Comment by chris-grove** [comment]
@dasmoth  Thanks!
RE "Can't find your phenotype" check-box behavior:
We can consider making the appearance of the "Suggest Observed Phenotype" fields reversible, but we were intentionally trying to keep the form simple and small by default, so I would prefer not to make them visible by default. Since they are optional (and conditional) fields, I'd like them to stay hidden unless they are called upon.

**Comment by kyook** [comment]
Perhaps instead of "Suggest Observed Phenotype", use "Suggest New Term" - saves on space a bit.

**Comment by kyook** [comment]
The addition of space for general comments is a nice touch!

**Comment by chris-grove** [comment]
@kyook  RE: "Suggest New Term", yeah, Juancarlos and I discussed that, but we decided it would be too ambiguous and/or confusing.
Glad you like the comments section!

**Comment by chris-grove** [comment]
@dasmoth RE: "more than one phenotype": I see your point, but I'm not convinced it's worth the page real-estate to make that explicit.
RE: "extra phenotype field disappearing on 'Preview'", OK thanks for pointing that out. @azurebrd  has now fixed that.

**Comment by kyook** [comment]
The instructions that pop up for the green question marks are a bit long. Perhaps we could make them more succinct and to the point? 

Some suggestions:
-leave out the "Please(s)" 
-specify the list by objects rather than "suggested options"
-save "A WormBase Curator will be in touch if there are any questions" for the acknowledgement e-mail or after the submit button has been pressed
-either add to all the instructions that 'more information about the entered object will appear in the floating pop up box for verification', leave it out of all of the instructions, or add it to the main text of the form (I vote the last option). 

For Your Name
Instead of:
"Please start typing and select a name from the suggested options. This form requires that your name is registered with WormBase. If you do not have a WBPerson ID, please fill out our Person Update Form."
Perhaps these instructions will do:
"Start typing and select your name from the list of registered WormBase persons and IDs. If you do not have a WBPerson ID, fill out our Person Update Form."

Your E-mail Address (unfortunately not much shorter):
Enter your preferred e-mail address. A confirmation e-mail will be sent to this address upon data submission. If you selected your name from the registered WormBase Persons list in the previous field, your e-mail on file would have been used to populate this field. Feel free to correct this to a different, preferred e-mail address. You will need to update your contact information in the Person Update Form if you want us to store this new e-mail address for you.

For PubMed ID 
Enter the PubMed ID for the paper in which this phenotype data was published. If your paper does not have a PubMed ID, please enter any unique identifier, like a D.O.I. e.g., doi10.1038/ni.2957

Allele Name
Enter the name of a single allele for which you are providing phenotype data. Once you have started typing, select an allele from the list of known alleles. If you are entering an allele not recognized by WormBase, continue with your submission and a WormBase curator will contact you to confirm the new allele.

Observed Phenotype
For phenotypes observed with this allele, start typing and select a phenotype term from the WormBase Phenotype Ontology. If you are having trouble finding a phenotype, you may browse the phenotype ontology with the link provided. If you still cannot find a suitable phenotype term,  click on the checkbox next to "Can’t find your Phenotype?" and enter your suggested term and a definition in the fields provided.

Suggest Observed Phenotype (Change to "Suggest a New Term")
Provide the name of a new phenotype term and a brief definition. This phenotype will be annotated to the allele you have selected.

Suggested Definition
Provide a brief definition for the new term you entered.

Phenotype Remark (the placement of this field is a bit off, or there should be one attached each to the Observed Phenotype and Not Observed Phenotype fields.)
If you would like, provide more information about the phenotype effects of this allele.

Not Observed Phenotype
Enter a phenotype term assayed for and determined to be not exhibited with this allele, start typing and select a phenotype term from the WormBase Phenotype Ontology. If you are having trouble finding your phenotype, you may browse the phenotype ontology with the link provided. If you still cannot find a suitable phenotype,  click on the checkbox next to "Can’t find your Phenotype?" and enter your suggested term and a definition in the fields provided. 

Allele Nature
If applicable, choose the inheritance pattern of the allele with respect to the phenotype(s) entered.

Allele Function
If applicable, choose the functional consequence of the allele with respect to the phenotype(s) entered.

Penetrance
If applicable, choose a level of penetrance of the phenotype with respect to the allele entered.

Temperature Sensitive
If applicable, choose a temperature sensitivity of the allele with respect to the phenotype(s) entered.

**Comment by kyook** [comment]
For the suggested  phenotype term will we actually be accepting any new term suggested through this form or will it need to be approved as the instructions say?

**Comment by tuli** [comment]
- when I type an unknown name in and tab to next field, unless it is recognised in WormBase, then name is simply removed. Not until I click on the ? do I understand that it is because the name I entered has no WBPersonID. 

- what is the turn around time for getting a WBPersonID? The link to the Person form is great for updates, but I feel it's not so clear for new users.

**Comment by chris-grove** [comment]
@kyook  I'm in the process of adopting essentially all the help text changes you suggested. Thanks.

RE: accepting suggested terms: new terms will need to be reviewed by Gary and possibly modified to fit in the WPO

**Comment by chris-grove** [comment]
@tuli  RE: name field, yeah I'd like to not add any more explanatory text to the form by default, so I think people will just need to realize this
RE: turn-around time, I really have no idea.  @ceciliaWBPerson1 would know

**Comment by tuli** [comment]
I'm looking at allele.cgi (email on its way to you soon @azurebrd!) and one of the changes is to give it the look and feel of the new forms. One thing I noticed is that the form heading/title varies between forms. 

Ignoring micropublication for the moment as it has its own groovy symbol I prefer the simple bold text of community_gene_description.cgi and allele.cgi to the less bold and underlines allele_phenotype.cgi

Also, should we call it Community Allele-Phenotype Submission Form to be more consistent, or change community_gene_description.cgi to "Contribute Gene Description Connections"?

**Comment by chris-grove** [comment]
@tuli 
Yeah, I think we can remove the underline for the Allele-Phenotype form title. As for the title "Community Allele-Phenotype Submission Form", I think @paulwsternberg specifically wanted to avoid using the word "Form" and asked for the existing title by name, so I will defer to him.

**Comment by tuli** [comment]
Thanks @chris-grove 
I support not using the word "form"

**Comment by tuli** [comment]
This is related to https://github.com/WormBase/website/issues/3956 
Can we have a link from the allele_phenotype notification page the submitter sees? e.g. If you would like to submit molecular details for an allele, please do so here (as in what's already on the form itself - the 'here' is linked to /allele.cgi

**Comment by chris-grove** [comment]
@tuli  I'm not sure I understand which page you mean by the "allele_phenotype notification page" or what link you want to create. Could you clarify?

**Comment by tuli** [comment]
@chris, I mean the page submitters see after they press the submit button -
the acknowledgment page. Sorry for not being more clear.

On Friday, 12 June 2015, Chris Grove <notifications@github.com> wrote:

> @tuli <https://github.com/tuli> I'm not sure I understand which page you
> mean by the "allele_phenotype notification page" or what link you want to
> create. Could you clarify?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WormBase/website/issues/3929#issuecomment-111565091>.
>


-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by chris-grove** [comment]
@tuli  I see, OK sure

**Comment by tuli** [comment]
I don't know if it's just me, but when I go to open the Optional fields, I feel like I should be able to click on the actual word "optional" not just the arrow.

**Comment by dasmoth** [comment]
@tuli I agree -- the "folding" arrow is quite a small target to click (and will just become worse as touchscreen devices become more common).

Is it really essential to hide away the optional fields in the first place?  I get that the aim here is to make the form look simple at first glance, but people understand optional fields (could possibly put them in a coloured box or something to better separate them), and having those fields visible by default makes them much easier to discover.

**Comment by chris-grove** [comment]
@tuli @dasmoth  OK, thanks for the input. @azurebrd has updated the "Optional" to be clickable now. As for showing the optional fields by default, I'd really rather not.

**Comment by tuli** [comment]
@azurebrd 
Thanks for making 'optional' clickable. Please can you make it more obvious that's it's clickable - as it stands the user wouldn't know.

**Comment by tuli** [comment]
@chris-grove @azurebrd 

The requested URL /~azurebrd/cgi-bin/forms/allele_sequence.cgi was not found on this server.
