### ISSUE TITLE
  Hi, just a question. Is it possible t...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3942]
<p>&nbsp;&nbsp;Hi,<br/>just a question. Is it possible to browse into version WS245 of C. elegans genome?<br/>Thanks!<br/>Paola</p>

Reported by: p j (paol*******************)  (obscured for privacy))
Submitted From: home <a href="http://www.wormbase.org//#01-23-6">/#01-23-6</a>

Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0

**Comment by epaule** [comment]
the genome assembly hasn't changed since WS235, but if you are interested in the gene models, you can see the WS245 genes on
metazoa.ensembl.org
ensembl.org

... or you can try my pet project: the WormBase assembly hub:
just got to the UCSC genome browser and under "My Data" -> "Track Hubs" add http://ftp.ebi.ac.uk/pub/databases/wormbase/releases/current-production-release/COMPARATIVE_ANALYSIS/hub/hub.txt
that will add an C.elegans assembly WBcel235 with gene tracks from WS245 as well as WS248.
