### ISSUE TITLE
  I would like to have a description of...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3943]
<p>&nbsp;&nbsp;I would like to have a description of the pseudogene Y55F3C.17 found in chromosome IV<br/>inC.elegans.<br/>Thank you for your help</p>

Reported by: Juan (juan*******************)  (obscured for privacy))
Submitted From: Tools <a href="http://www.wormbase.org//header">/header</a>

Mozilla/5.0 (X11; Linux i686 on x86_64; rv:28.0) Gecko/20100101 Firefox/28.0

**Comment by Paul-Davis** [comment]
Dear Juan,

Please could you be a bit more specific about what you are requesting.

Y55F3C.17 was curated as a pseudogene with the following Comment:

^
[130904 gw3 <http://www.wormbase.org/search/variation/gw3>] Created this 
pseudogene based on the protein homology and the SL1 site. It is 
possible that this is not a processed pseudogene, but just a repetitive 
region that happens to have an SL1 site at the 5' end.
*Protein id evidence*: WP:CE32684 
<http://www.wormbase.org/search/all/WP:CE32684>
*Feature evidence*: WBsf128454 
<http://www.wormbase.org/species/c_elegans/feature/WBsf128454>

Based on this comment, this loci appears to be rather dubious and could 
be a false positive because of the repetitive nature of the genome or it 
could be a very degraded gene where the promoter is still active but 
produces a non-productive transcript that is targeted by the cells 
housekeeping machinery.

If you are working on this gene, WormBase would be interested in 
anything that you discover about it.

Paul Davis
[Sequence Curation]

On 10/06/2015 17:37, no-reply@wormbase.org wrote:
> Feature Request
>
>   I would like to have a description of the pseudogene Y55F3C.17 found 
> in chromosome IV
> inC.elegans.
> Thank you for your help
>
> Submitted From:
>   Tools /header <http://www.wormbase.org//header>
>
> This issue has been assigned ticket number: #3943. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/3943>.
>
> Reported by: Juan (juan.a.subirana@upc.edu)
> 10 Jun 15 16:38
>
> Mozilla/5.0 (X11; Linux i686 on x86_64; rv:28.0) Gecko/20100101 
> Firefox/28.0
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>


-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
Waiting for user response....if none if forthcoming I think we should close this ticket at the ned of this helpdesk stint.
