### ISSUE TITLE
  How do I cite a gene class listed on ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3944]
<p>&nbsp;&nbsp;How do I cite a gene class listed on worm base?<br/>How do I find out when the class was established?<br/>Specifically I am looking to reference the "cey" class identified by Andy Fire's lab.</p>

Reported by: Amel** (aale*************)  (obscured for privacy))
Submitted From: cey (gene_class) <a href="http://www.wormbase.org//resources/gene_class/cey#01--10">/resources/gene_class/cey#01--10</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5) AppleWebKit/537.78.2 (KHTML, like Gecko) Version/6.1.6 Safari/537.78.2

**Comment by tuli** [comment]
Dear Amelia,

Thank you for writing to WormBase.

Instructions on how to cite WormBase and specific pages (in your case,
the cey gene class), can be found here:
http://www.wormbase.org/about/citing_wormbase

We do not display when a gene class was added to WormBase, and since
cey was added quite a while ago I referred to Jonathan Hodkgin, who
was gene name curator at this time. He told me that the cey- class
goes back to 1993, with cey-1, cey-2 and cey-3 populating it. cey-1
and cey-2 are included in a paper by Seydoux and Fire (1994).

I hope this answers your questions.

Best wishes,

Mary Ann

On 10 June 2015 at 18:52,  <no-reply@wormbase.org> wrote:
> How Do I ...?
>
>   How do I cite a gene class listed on worm base?
> How do I find out when the class was established?
> Specifically I am looking to reference the "cey" class identified by Andy
> Fire's lab.
>
> Submitted From:
>   cey (gene_class) /resources/gene_class/cey#01--10
>
> This issue has been assigned ticket number: #3944. Follow progress on our
> issue tracker.
>
> Reported by: Amelia (aalessi@umich.edu)
> 10 Jun 15 17:52
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5) AppleWebKit/537.78.2 (KHTML,
> like Gecko) Version/6.1.6 Safari/537.78.2
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
