### ISSUE TITLE
WS249 files missing from ftp://ftp.wormbase.org/pub/wormbase/species/

### ISSUE THREAD

**Issue by khowe** [WormBase/website#3971]
Hi Todd, 

Although the WS249 release directory is present and correct on ftp.wormbase.org/pub/wormbase/releases, the symlinks pointing to those files are missing. At what stage do those files get created? When we announce a release to dev, that becomes the development release, so it would be useful if the "current_development" symlinks were put in place as soon as the data is mirrored to ftp.wormbase.org (collaborators at UniProt require those links to be there quickly). 

If this is not possible, we will need to create the corresponding symlinks on the EBI FTP site, and point UniProt there - in which case, it would be handy to get your script for doing this!

Thanks,

Kevin

**Comment by tharris** [comment]
Currently this happens at the END of the staging process which is due on the first of July. The timing of this is due to requests of other users who were unhappy with discordance of symlinks on the canonical FTP site and the version displayed on the website.

I will adjust the timing of this step and gauge how attentive other users are.

**Comment by khowe** [comment]
Let me see if I've understood things correctly: the timings at the moment are such that the "current" symlinks are consistent with www.wormbase.org, and the "current_development" links are consistent with staging.wormbase.org. I can see the appeal of that, and it makes sense on the face of it. 

Agree with the users that "current" should always point to the version of the data being shown on www.wormbase.org. But IMO, "current_development" should always point to the most recent version of the data, regardless of the state of staging.wormbase.org (which is only for internal use). 

We really need the current_development links in place as soon as possible at the end of the build. This is important for flow of data from WormBase to ENA and UniProt (which, I recently found out, is critical for our GO annotation workflow). Could they be created as soon as the new release has finished synching from hinxton to ftp.wormbase.org? Is that possible?

**Comment by raymond91125** [comment]
i concur that a symlink to the most recent release is useful.

**Comment by tharris** [comment]
@raymond91125 excellent, since we've been doing it for a very, very long time already :)

What we have never defined has been when the development cycle begins with relation to people wishing to consume bleeding edge data.  

As I said earlier, I will adjust the timing of the creation of these symlinks. 

Still, there are very, very good reasons for waiting until the data is available on a website. Here's one I cannot count how many times GFF or fasta files have been broken or missing or acedb requires patching. These problems are often detected during our staging process. Since we have no mechanism of contacting downstream users of provisional data, they will be using broken or incomplete data.

Bumping up the creation time of symlinks removes that qaqc.

**Comment by raymond91125** [comment]
bleeding_development for pre-qaqc?

**Comment by tharris** [comment]
Me not understand @raymond91125. What are you asking here in relation to this discussion about symlinks on the FTP site?

**Comment by tharris** [comment]
Symlinks updated for WS249 and will be so immediately following sync with the EBI FTP site henceforth and in perpetuity.

**Comment by khowe** [comment]
Sorry, me not understand @tharris. "excellent, since we've been doing it for a very, very long time already". Until you updated them moments ago, there were not symlinks pointing to the latest development release (WS249)!  Which is why I created this ticket!

Anyway, your points about a development release not being stable/reliable are noted. But that's why it's a "development" release. Caveat emptor. We're announcing the release to dev@wormbase.org long before the data is made available on any web-site.  

Anyway, thanks for updating the symlinks. That will help with the data flow. One technical thing: it's unfortunate that when you download a file via one of these symlinks, there is no easy way of knowing which release that file actually comes from. Other than inserting a release number somewhere in the file itself (which is possible on a # line in GFF, but for for some of the other file types), I can't think of a good solution for this.
