### ISSUE TITLE
  Is there an easy way for me to downlo...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3977]
<p>&nbsp;&nbsp;Is there an easy way for me to download a fasta file including all meNOG C. elegans protein sequences?  Thanks!</p>

Reported by: Wend********** (wend***********************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 6.1; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0

**Comment by epaule** [comment]
it is quite easy to dump it from our ACeDB database (so i did that for you and attached the file). There is caveat, that out protein set diverged from the one eggNOG used for their analysis, as a few years passed since then.

To get exactly the protein set they used, you can get it from their FTP site (http://eggnog.embl.de/version_3.0/downloads.html) and filter out any that don't appear in the meNOG cluster file (also on the same site).
