### ISSUE TITLE
  I've been trying since last week to r...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#3987]
<p>&nbsp;&nbsp;I've been trying since last week to retrieve a table with gene, some associated gene data and phenotypes (simplified query below), but unluckily, none of my attempts produced more than a crash with 'Oops, service failed. Please contact support'.<br/>Is there any way i can retrieve this information?<br/>---<br/><query model="genomic" view="Gene.primaryIdentifier Gene.briefDescription Gene.secondaryIdentifier Gene.symbol Gene.dataSets.bioEntities.phenotypesObserved.identifier Gene.dataSets.bioEntities.phenotypesObserved.name Gene.dataSets.bioEntities.phenotypesObserved.description" ><br/></query></p>

Reported by: Mart* (mart*************************)  (obscured for privacy))
Submitted From: Tools <a href="http://www.wormbase.org//header">/header</a>

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.124 Safari/537.36

**Comment by dasmoth** [comment]
Dear Marta,

Thank you for writing to WormBase.

I'm afraid I don't see your query attached to the e-mail -- is there any
chance you could re-send it?

Am I right in thinking that you're using the WormMine tool to retrieve this
information?

        Thomas.

**Comment by dasmoth** [comment]
(For records, e-mailed response from Marta)

Hi there,

See below the XML output of the query i tried of WormMine. My original query has a bit more information, but the important one is the phenotypes, that's why i started playing with only those paramenters to see if I found where it crashes.

My original idea is to retrieve using WormMine all coding genes with gene names, description, location in the genome and gene expression patterns, together with phenotypes when available. That crashed and I tried simplifying the query asking only for all genes with phenotypes, but still it breaks down.

Thanks for your quick answer and help!

Marta 

---

<query model="genomic" view="Gene.primaryIdentifier Gene.briefDescription Gene.secondaryIdentifier Gene.symbol Gene.dataSets.bioEntities.phenotypesObserved.identifier Gene.dataSets.bioEntities.phenotypesObserved.name Gene.dataSets.bioEntities.phenotypesObserved.description" >
</query>

**Comment by dasmoth** [comment]
Can reproduce this, even with a constraint in place to restrict the query to a single gene -- so almost certainly not a scaling issue.

![image](https://cloud.githubusercontent.com/assets/209047/8285755/5ae07bba-18fd-11e5-8a4a-ab4918972eb1.png)

My query, for reference:

         <query model="genomic" view="Gene.symbol Gene.briefDescription Gene.primaryIdentifier Gene.secondaryIdentifier Gene.organism.name Gene.dataSets.bioEntities.phenotypesObserved.observedIn.primaryIdentifier" sortOrder="Gene.symbol ASC" >
          <constraint path="Gene.symbol" op="=" value="pha-4" code="A" />
         </query>

**Comment by chris-grove** [comment]
Hi Marta, thanks for resending the query. The issue is that the query you
sent is looking for phenotypes under the "Data Sets > Bio Entities"
portion of the data model, but what you need to do is query for phenotypes
from under the "Alleles" section of the model browser (we currently only
have phenotypes for alleles in WormMine). Here's XML for a working query:

<query name="" model="genomic" view="Gene.primaryIdentifier
Gene.briefDescription Gene.secondaryIdentifier Gene.symbol
Gene.alleles.phenotypesObserved.description
Gene.alleles.phenotypesObserved.identifier
Gene.alleles.phenotypesObserved.name" longDescription=""
sortOrder="Gene.primaryIdentifier asc">
</query>

Note that you may want to remove/rearrange the descriptions as they tend
to make the table hard to read.

Hope that helps!

Best,

Chris Grove
