### ISSUE TITLE
C. elegans genomic region

### ISSUE THREAD

**Issue by dasmoth** [WormBase/website#4008]
(Forwarded by Matt B., copying here for tracking purposes)

>Dear Dr. Berriman,
>I am hoping you can help me, but I apologize in advance if you are the
>wrong person to ask this question. I have been trying to find sequence
>information for a specific locus in C. elegans and the information
>doesn¹t seem to exist. I was hoping you could help. I am looking for the
>sequence of the rrs-1 locus (which encodes SL1). Wormbase has not
>annotated this to the physical map and there is no sequence data
>associated with this entry in wormbase. At least part of the locus should
>be in cosmid T25B12, but there is no sequence data available for this
>cosmid. A portion of this locus should also be in cosmid K07H12, for
>which there is also no sequence data. I can¹t even find the rrs-1 region
>using the UCSC genome browser. I am guessing that this has something to
>do with the fact that this locus is composed of tandom repeats. I am
>looking for the sequence of one complete repeat for this region, any
>ideas?

**Comment by Paul-Davis** [comment]
Dear Lesley,

This is an interesting piece of old data coming from the C. elegans I/II.

rrs-1 is a multi gene locus and as such is problematic to annotate in 
our current infrastructure. There are a number of historical gene style 
names that were generated from genetic mapping experiments that on the 
whole get resolved to a single gene as they are identified and mapped to 
the genome.

For rrs-1 this will never happen as it is well established that it is a 
locus or gene cluster rather than a gene. We need to review how we are 
storing this data, but in the mean time I have attached the sequence of 
one copy of the repeat.

This file contains the sequence containing sls-1.3 (Y102A5D.15) rrn-4.13 
(Y102A5D.11) and the intergenic sequence up to but not including the 
next gene sls-1.2 (Y102A5D.14).

Thanks

Paul


On 23/06/2015 17:09, Matthew Berriman wrote:
> Dear Lesley
>
> I don¹t know the answer to your query but I¹ve forwarded your email to
> colleagues at WormBase that may be able to help.
>
> Best wishes
> Matt
>
>
>
> On 23/06/2015 4:30 pm, "lesleymacneil" <macneil@mcmaster.ca> wrote:
>
>> Dear Dr. Berriman,
>> I am hoping you can help me, but I apologize in advance if you are the
>> wrong person to ask this question. I have been trying to find sequence
>> information for a specific locus in C. elegans and the information
>> doesn¹t seem to exist. I was hoping you could help. I am looking for the
>> sequence of the rrs-1 locus (which encodes SL1). Wormbase has not
>> annotated this to the physical map and there is no sequence data
>> associated with this entry in wormbase. At least part of the locus should
>> be in cosmid T25B12, but there is no sequence data available for this
>> cosmid. A portion of this locus should also be in cosmid K07H12, for
>> which there is also no sequence data. I can¹t even find the rrs-1 region
>> using the UCSC genome browser. I am guessing that this has something to
>> do with the fact that this locus is composed of tandom repeats. I am
>> looking for the sequence of one complete repeat for this region, any
>> ideas?
>> Thank you in advance,
>> Lesley
>>
>>
>>
>> Lesley MacNeil, PhD
>> Assistant Professor
>> Department of Biochemistry and Biomedical Sciences
>> Farncombe Family Digestive Health Research Institute
>> Faculty of Health Sciences
>> McMaster University
>> 1280 Main St. W
>> Hamilton, Ontario, Canada
>> L8S 4K1
>>
>> Office: HSC-4H30E
>> Lab: HSC-3N11B
>> Phone:905-525-9140 x 26523
>>
>
>


-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================


>Y102A5D
tttgtctccccgagaggagacgttccaaaatttatagctaacgccaaatt
tctttgggtcagtttcaatgtttacctcaaacttgggtaattaaaccgac
ttgaacggcgcgtctctgcgcctaacaccaacctacagcagacagcgagc
gaggtctacgatcggcaacccccctctccacacaacacacagccagccag
tagcactgacgaaggggtagaggcctagtcgggtggtggggggtttgtaa
ctgacatggcacttgtccatagacgcttacgaccatatcacgttgaatgc
acgccatcccgtccgatctggcaagttaagcaacgttgagtccagttagt
acttggatcggagacggcctgggaatcctggatgttgtaagctttttgca
tttttttagaatgactaaaaaaatttgtttttgttgcaacatcatatgaa
ttagaaacgattttaaaataattttcaaaaaatttttccccagccaaaat
gacacttctggagagtcgtattttcgagtgtaattaagagactgctattt
tttttaggtgtgtgatgtgttggactttattgcgtgtacctaatgagtga
atattgattatactggatgtgtcgggtcgatttttggaacatgaaaaatt
taggttcttttgaaaatttttgagaacaattgcatttttcagttgaggag
cgcacggcacccatacatgagaatctataatttttttgcatcacatagac
tatttccatatatgtatgtaccagtagcaagaatgaaaagcacttttgaa
gagtgtagatgagctggagggcaacatcatatttagatcggggatcccgt
cccccaatcaatatcatcaccttcccacatctccacatacggacagccat
gctccctcatctccacatattttcgaatggaccgttctccaacatggatg
aaccgattttcgaatttcttagtattt

**Comment by chris-grove** [comment]
@Paul-Davis  Can we close this ticket, or are we still trying to resolve the rrs-1 display issue?
