### ISSUE TITLE
  Hi, The AQL query example: Which gene...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4026]
<p>&nbsp;&nbsp;Hi,<br/>The AQL query example:<br/>Which genes are expressed in named cells<br/>select l from l in class Locus, <br/>ex in l->Expr_pattern <br/>where exists ex->cell order<br/>Is no longer functioning; likely because the structure has been changed.<br/>Can I please get a bit of query code that finds the genes expressed in all the named neuronal cells, with a list output for all the 302 cells? Or a tutorial on how to do this? <br/>As an example, like the list here: http://www.wormbase.org/tools/ontology_browser/show_genes?focusTermName=AVAL&focusTermId=WBbt:0003870<br/>Except for all the cells.<br/>Best Regards,<br/>Taqi</p>

Reported by: Taqi**** (tali********************)  (obscured for privacy))
Submitted From:  >?Chrom* - search <a href="http://www.wormbase.org//tools/queries/run">/tools/queries/run</a>

Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.125 Safari/537.36 OPR/30.0.1835.88

**Comment by dasmoth** [comment]
Dear Taqi, thank you for writing to WormBase.

The immediate issue with that AQL query is that Locus objects are only used
to support the curation of genetic mapping data.  You could try changing
"locus" to "gene" in that example -- Gene objects do have expression
patterns.  If you want to write AQL queries, you'll probably want to
consult our model browser
<http://www.wormbase.org/tools/schema/run?class=Expr_pattern>.

Alternatively, you might like to try our newer WormMine
<http://www.wormbase.org/tools/wormmine/begin.do> data-mining platform,
based on the Intermine software.  Here's a sample query for with expression
patterns linked to the "neuron" anatomy term, which might be a useful
starting point.

      <query model="genomic" view="ExpressionPattern.gene.primaryIdentifier
ExpressionPattern.gene.symbol ExpressionPattern.gene.secondaryIdentifier
ExpressionPattern.gene.briefDescription ExpressionPattern.gene.organism.name"
>
             <constraint path="ExpressionPattern.anatomyTerms" op="IN"
value="Neuron anatomy term and all descendants - 18 Jun 2013" code="A" />
       </query>

(If you want to try this, select "QueryBuilder" in the WormMine interface
then "Import query from XML").

Please let us know if you need further assistance.

Best wishes,

        Thomas

**Comment by raymond91125** [comment]
Hi,

Another way you can get at genes expressed in any neuron is to do 
exactly what you did but look at the term WBbt:0003679 (neuron). Thus 
the gene list page URL is 
<http://www.wormbase.org/tools/ontology_browser/show_genes?focusTermName=neuron&focusTermId=WBbt:0003679>. 
The second list is of 2802 genes.

The data in WormMine is a bit out of date but we will bring it up shortly.

Raymond

**Comment by taqiali** [comment]
Hi Thomas and Raymond,

Thanks for the quick replies and example code!

First to address Thomas' suggestions. I did in fact try the WormMine query with the same constraint on Anatomy_term earlier, for example:

<query name="" model="genomic" view="ExpressionPattern.anatomyTerms.name ExpressionPattern.gene.primaryIdentifier ExpressionPattern.gene.symbol" longDescription="" sortOrder="ExpressionPattern.anatomyTerms.name asc">
  <constraint path="ExpressionPattern.anatomyTerms" op="LOOKUP" value="AVAL" extraValue=""/>
</query>

This produces a list of 90 genes, more than the 52 on the list from the URL I posted earlier, and more than the 60 genes on the actual page on Wormbase (however overlap exists). These discrepancies (how is each list sorted?), led me to try AQL queries to directly probe the source. I tried substituting the "Gene" class instead of locus, but a timeout error occured. I'll have another crack at it with a better understanding of the underlying structure, and will come back here if I have trouble.

And thank you Raymond, however I was not very clear in my original post. I would like each list of genes to be under the name of a particular anatomy term, for all neuronal anatomy terms, as opposed to the entire gene list in one column. So a table, with anatomy terms as headers and genes as rows. Changing the URL focusTermId to different Anatomy term IDs might be used if I can't get the AQL query to work.

Hopefully I'll have a solution soon to post up here for future readers.

Best Regards,
Taqi

**Comment by taqiali** [comment]
Hi all,

Currently, what we are trying to do is use this RESTapi script:

curl -H content-type:application/json http://api.wormbase.org/rest/field/anatomy_term/[ID]/expression_patterns/

Where the ID is replaced by the WormBase anatomy terms for all the nervous system, and using an iterative process to go through the entire list and build a table. This is done by extracting the "gene" lists using "certainty" as a qualifier for confirmed expression, listed by anatomy term id.

I was wondering if this is the most efficient solution to the problem? I think a query example which filters by anatomy term and produces the gene expression list would be much quicker, and an example code would be very appreciated.

My study will be about linking genetic expression to the neuronal network, to find correlation and perhaps new information about hub neurons and their genetic expression. 

Regards,
Taqi

**Comment by draciti** [comment]
Hi Tali,

you can parse the Gene Association file that is on the FTP site:
ftp://ftp.wormbase.org/pub/wormbase/releases/WS249/ONTOLOGY/anatomy_association.WS249.wb

I also attach a list of the 302 neurons -with WBbt ids

I recommend to include in your output also rows that do not have a qualifier 

Daniela

**Comment by taqiali** [comment]
Hi Daniela,

Thank you so much! That is exactly the data I was looking for. I looked at the FTP files but didn't think there would be a single file with all the data, so thanks again for the link, and the ID list. I will take into account your suggestion also.

Best Regards,
Taqi

**Comment by draciti** [comment]
Glad it worked!
Daniela
