### ISSUE TITLE
  I am trying to search for a sequence ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4028]
<p>&nbsp;&nbsp;I am trying to search for a sequence in the landmark or region box, but I get this error when I try:  <br/>Internal Server Error<br/>The server encountered an internal error or misconfiguration and was unable to complete your request.<br/>Please contact the server administrator, [no address given] and inform them of the time the error occurred, and anything you might have done that may have caused the error.<br/>More information about this error may be available in the server error log.</p>

Reported by: http**************************************************************************** (ja21***********)  (obscured for privacy))
Submitted From: Tools <a href="http://www.wormbase.org//header">/header</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 Safari/537.36

**Comment by tharris** [comment]
I wrote:

Sorry for the difficulties. Unfortunately, we lost the ability to search for sequences a few years ago due to some internal changes with the Genome Browser, a third party tool developed outside of WormBase. 

This is one of the reasons (among several) why we are testing a new genome browser. Perhaps you would like to try it?

http://jbrowse.wormbase.org/

**Comment by tharris** [comment]
@scottcain, Julie is reporting that searching with a sequence isn't working. Isn't this a JBrowse feature?  Can you check?

**Comment by scottcain** [comment]
Won't get fixed for GBrowse (without a significant investment of time anyway), and to the extent it is available on JBrowse, it's already implemented.
