### ISSUE TITLE
  I have noticed that the Brugia malayi...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4033]
<p>&nbsp;&nbsp;I have noticed that the Brugia malayi entry for DHFR in Wormbase (BMA-DHFR-1,  BM34009) is identical to the Pubmed (protein search) entry CDQ02220.1 ; however, when doing a search in Pubmed/protein for B malayi DHFR, a second shorter entry also shows up (XP_001902443.1). This second entry  is missing a 13 amino acid stretch "VYELGLNSPFLHQ". The previous Wormbase Bm DHFR entry corresponded to this shorter entry but as of August 2014 (or thereabouts) was updated or modified to the longer entry including the 13AA stretch.  The 13AA stretch seems to be clearly important, as it is well conserved in other species.  Looking at the Brugia genomic locus, including this 13 aa stretch in the DHFR protein requires prediction and splicing of an intron that starts with a "nonclassical" GC and ends the classical AG.  Is this indeed the underlying argumentation, together with looking at protein sequence alignments ?  <br/>Any comments would be greatly appreciated.<br/>Many thanks.<br/>Ueli Gubler / Montclair State University, Montclair NJ</p>

Reported by: Ueli******* (uagu**************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 Safari/537.36

**Comment by epaule** [comment]
he RefSeq entry XP_001902443.1 (aka Bm1_54930A) is from the original submission of a previous assembly to GenBank.
There are actually 5 RNASeq libraries supporting the intron in Bm2626 (CDQ02220.1) and none for the previous Bm1_54930A model.
From the protein homologies it also looks like they support the Bm2626 more than the old one.
So I am quite sure of the GC-AG splice site at the moment. especially since among our clade III genomes in WB only D.immitis has a C>T (converting it back to a canonical one).
