### ISSUE TITLE
  I think WM191 (MAGO12) should also sh...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4048]
<p>&nbsp;&nbsp;I think WM191 (MAGO12) should also show up in wago-4 strains</p>

Reported by: alex************ (alex********************)  (obscured for privacy))
Submitted From: wago-4 (gene) <a href="http://www.wormbase.org//species/c_elegans/gene/WBGene00010263#04-9ec5db8-10">/species/c_elegans/gene/WBGene00010263#04-9ec5db8-10</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.71 (KHTML, like Gecko) Version/6.1 Safari/537.71

**Comment by tuli** [comment]
Dear Alexandra,

Thank you for writing to WormBase.

I believe you are correct. I am checking with the CGC before I update
the WormBase record and will write back to you again once I have heard
back from them.

Best wishes,

Mary Ann

**Comment by tuli** [comment]
Reply from CGC Aric.

Hi Mary Ann,

Yes.  The complete genotype is far too long to fit into our genotype field.  The genotype is limited to 125 characters, the full genotype is currently 204.  This is the only strain which has been annotated as such.  Unlike Excel, we cannot shrink the cells to view only part of the content in our current software, so expanding the field to accommodate the entire genotype means that this field takes up our entire display:  we are unable to view other fields on the display without arrowing over in the most commonly used view of this database.  

The new system has the capability to wrap text in fields and should handle unusually long genotypes (see attached screenshot).  It looks as though the field is still a few characters short, but that should be an easy fix.  We can make the change to the genotype after the transition, if that works on your end.  

It looks like there is a typo in the ppw-2 allele.  I think it should be tm1120.  I have also updated the gene names, but it is still ~200 characters:  

sago-2(tm894) ppw-1(tm914) ppw-2(tm1120) wago-2(tm2686) wago-1(tm1414) I; wago-11(tm1127) wago-5(tm1113) wago-4(tm1019) II; hrde-1(tm1200) sago-1(tm1195) III; wago-10(tm1186) V; nrde-3(tm1116) X.

**Comment by tuli** [comment]
Reply to author. Not sure why these are being added to this ticket. 

Dear Alexandra,

Further to my message yesterday, I have heard back from Aric at the
CGC and can explain what you are seeing in WormBase.

There are two issues, the first is that the genotype had not been
updated to reflect the approved gene names e.g.
F58G1.1 = wago-4. This has now been done and will be visible in release WS250.

The second issue is that the Contains widget is not populated. This is
because the full genotype appears as Curatorial Remark rather than in
the Genotype field. The reason for this is that WB191 has the longest
genotype at the CGC and it exceeds the limit of what can be entered in
the Genotype field.  This issue is being addressed and so the full and
correct genotype will appear in the genotype field which will allow
the Contains widget to be populated with the Genes and Alleles carried
by this strain.

Thank you,

Mary Ann
