### ISSUE TITLE
Problem with Transgene WBTransgene00014445

### ISSUE THREAD

**Issue by gw3** [WormBase/website#4051]
Hello,

I think that there is a problem with this page
http://www.wormbase.org/species/all/transgene/WBTransgene00014445#021--10
as the gene name and the sequence name correspond to 2 different objects mdh-1 and T05G5.1.

Moreover, referring to table S1 from the associated paper WBPaper00038444, these 2 genes have failed to go into the cloning pipeline, so no GFP strains were never produced.
Thereby the association with mitochondrial expression inferred should be wrong on this page
http://www.wormbase.org/species/c_elegans/gene/WBGene00018491#0-e1cfd6b759-10

Thanks,
Nathalie

Nathalie Pujol
Innate immunity in C. elegans
CIML
campus Luminy case 906
13288 Marseille Cedex 9
Tel (33).491.26.9124
Fax (33).491.26.9430
www.ciml.univ-mrs.fr

**Comment by draciti** [comment]
thanks Karen. at that time I replied to the user but did not update github.

Hi Nathalie,

Karen is right. In supplemental table 2-attached, the authors were referring to mdh-1 (columnB, line 180) but they meant mdh-2 (F20H11.3). 

mdh-1 is listed as synonym of mdh-2 (http://www.wormbase.org/species/c_elegans/gene/WBGene00003162#-108eg3-10), this could have been the reason of the confusion.

I fixed the corresponding Expression pattern object, now linking to mdh-2.

Thanks,

Daniela





On Jul 16, 2015, at 12:59 PM, Karen Yook wrote:

Hi Daniela, 

I don't see any construct containing MDH-1 or its CDs name F46E10.10 in the paper or tables.

In supplement table 2 though I see this line: 
F20H11.3 | mdh-1 | NAD-dependent malate dehydrogenase | mdh-1 encodes a homolog of malate dehydrogenase that is predicted to be mitochondrial.

F20H11.3 corresponds to mdh-2 in WB, for which mdh-1 is an other name.  Unfortunately, mdh-1 also exists as its own gene, F46E10.10- due to some nomenclature anomalies?

So it looks like the construct should be [pT05G5.1::PDESTbarb2::F20H11.3]?
Would you please take a look? 

Thanks, 
Karen

**Comment by draciti** [comment]
As for mitochondrial expression it comes from tables 1 and 2:
The authors place F20H11.3 (mdh-2) into category 11 (table2). category 11 corresponds to  expression in Mitochondria (Table 1).
F20H11.3 in supplementary table S1 is in column 1 
Column 1: Gateway clones resulting in good GFP::tagged protein sub-cellular localization after injections.

I will write again to Nathalie to make sure she has all the answers.
