### ISSUE TITLE
  I am a high school teacher working wi...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4053]
<p>&nbsp;&nbsp;I am a high school teacher working with the su1006 mutant of rol-6. They will be sequencing DNA from rol-6 mutants without knowing the specific allele, and I want them to be able to search for the allele based on their sequencing data. Do you already have a way to do this within WormBase? Thank you, Amy</p>

Reported by: Amy ******* (alin************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.132 Safari/537.36

**Comment by raymond91125** [comment]
Hi Amy,

I don't think there's a simple, direct way to search for matching 
variations based on sequence. However here's what you can do:

1. Take a sizable stretch of sequence, say 25bp+mutation+25bp and do a 
BLAT search (Tools->Blast/Blat) against Ce genome.
2. Go to the genome view through the result page
3. On the Genome Browser page, "Select Tracks", turn on "Classical 
alleles" and "DNA/GC Content"
4. Back on GBrowser, zoom to show ~100 bp in the window so that DNA 
bases are visible.
5. See what alleles align perfectly with the center of your 'Hits' and 
review their respective sequence changes.

The added benefit of this approach is that your students can study in 
the context of other tracks on Genome browser (e.g. translation, 
cross-species conservation) to appreciate how this mutation may affect 
gene function.

Cheers,

Raymond
