### ISSUE TITLE
  Hi, How can I get access to the corre...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4056]
<p>&nbsp;&nbsp;Hi,<br/>How can I get access to the corresponding DNA sequence of a given protein (isoform)? <br/>e.g. Bma-let-603 , aka Bm1727 (I cannot even download the scaffold...) Thanks!</p>

Reported by: Fred************* (fred**************************)  (obscured for privacy))
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:39.0) Gecko/20100101 Firefox/39.0

**Comment by chris-grove** [comment]
Hi Frederic,

 You should be able to click on the DNA/Sequence icons associated with the isoform of interest in the "Sequences" widget on the gene page and click on "view unspliced + UTR" or "view spliced + UTR" in the resulting pop-up window:

http://www.wormbase.org/species/b_malayi/gene/WBGene00221988#0-9f-3

Otherwise you can click on the name of the transcript or CDS which will direct you to the WormBase page for that isoform, e.g.:

http://www.wormbase.org/species/b_malayi/transcript/Bm1727a#042--10

Let us know if you have any other questions.

Best,

Chris Grove

**Comment by chris-grove** [comment]
Fantastic, thanks!

Other (last) question.

How about proteins available through NCBI, but not(?) annotated on the wormbase?
How can I find this protein for instance, in order to get access to the DNA sequence?


http://www.ncbi.nlm.nih.gov/protein/170591264



Thanks Chris!

**Comment by chris-grove** [comment]
The most straight-forward thing to do is perform a BLASTP in WormBase with
the protein sequence from the NCBI entry, selecting Brugia malayi as the
species. This results in an exact match to Bma-rsks-1:

http://www.wormbase.org/species/b_malayi/transcript/Bm6597#06--10

Cheers,

Chris
