### ISSUE TITLE
Problematic protein motif lines in several GFF files

### ISSUE THREAD

**Issue by scottcain** [WormBase/website#4062]
While the polypeptide_motif:translated_feature lines in the C. elegans GFF3 file for WS249 seems fine, similar features in the c_briggsae and p_pacificus files have problems.  See this example from C. briggsae:

```
I       translated_feature      polypeptide_motif       17993   18060   .       +       .       ID=motif:CBG11839-hmmpanther.1
I       translated_feature      polypeptide_motif       17993   18060   .       +       .       ID=motif:CBG11839-hmmpanther.1;cds=CBG11839;type=hmmpanther;range=3-109;exons=1-2;protein=BP:CBP17299;description=HMMPANTHER:PTHR15087
```

This seems to happen to the hmmpanther lines and is causing JBrowse to trip up.  I'm guessing this is a case of there really being multiple discontiguous regions of the feature but the coordinates are getting overwritten somewhere so that each line of the feature has the same coordinate.

**Comment by scottcain** [comment]
Sorry for the "several"; when I started writing this I thought there were more than two affected :-/

**Comment by khowe** [comment]
This is same problem as #3135. The code was fixed some time ago, but the sequence curation data for these two species has not been updated for over a year, so the new code has not been run on them. 

In WS250, we will be updating all species, so this will get fixed then. @scottcain , can you workaround for these two species for WS249, e.g. by ignoring the protein_motif lines for them (resulting in empty tracks)? This would be acceptable, given that the data has been broken for over a year. 

If it's not easy workaround, we will need to unpack the relevant data in order to run the new/fixed code on the old data, and provide new GFF3 for these two species.

**Comment by scottcain** [comment]
@khowe No problem: since some had been fixed, I just wanted to make sure it was pointed out that it wasn't 100%.  I can just delete those tracks and they will just get added back in when 250 gets processed.
