### ISSUE TITLE
 Server Error: 500 at  tools/ontology_browser/show...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4097]
<p>Server Error: 500 at <a href="http://www.wormbase.org/tools/ontology_browser/show_genes?focusTermName=chromatin%20organization&amp;focusTermId=GO:0006325">tools/ontology_browser/show_genes</a></p><p>
</p><p>Error Message:<br> Caught exception in WormBase::Web::Controller::Tools-&gt;tools "malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before "(end of string)") at /var/lib/jenkins/jobs/staging_build/workspace/lib/WormBase/API/Service/ontology_browser.pm line 274." </p><p>What were you doing? <br />&nbsp;&nbsp;Retrieve genes of certain GO term.</p>

Reported by: Tao *** (vlad******************)  (obscured for privacy))
Submitted From: ontology_browser <a href="http://www.wormbase.org//tools/ontology_browser/show_genes">/tools/ontology_browser/show_genes</a>

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/600.7.12 (KHTML, like Gecko) Version/8.0.7 Safari/600.7.12

**Comment by azurebrd** [comment]
The direct non-celegans query is not working.  For example, see : 
http://wobr.caltech.edu:8082/solr/go/select?qt=standard&indent=on&wt=json&version=2.2&fl=bioentity,bioentity_label&start=0&rows=10000000&q=document_category:annotation&sort=taxon%20asc&sort=bioentity%20asc&group=true&group.field=bioentity&group.ngroups=true&group.format=simple&fq=-qualifier:%22not%22&fq=source:%22WB%22&fq=-taxon:NCBITaxon\:6239&fq=annotation_class:%22GO:0007155%22
redirecting to : 
http://131.215.12.204:8080/solr/go/select?qt=standard&indent=on&wt=json&version=2.2&fl=bioentity,bioentity_label&start=0&rows=10000000&q=document_category:annotation&sort=taxon%20asc&sort=bioentity%20asc&group=true&group.field=bioentity&group.ngroups=true&group.format=simple&fq=-qualifier:%22not%22&fq=source:%22WB%22&fq=-taxon:NCBITaxon\:6239&fq=annotation_class:%22GO:0007155%22
Gives a solr 404 because "can not sort on multivalued field: taxon"
Did the data change requiring a change in the queries we should use ?

**Comment by raymond91125** [comment]
yes, the was an upstream change. do we need to sort by taxon (or bioentity)? if not, just remove the sort flags should fix the problem.

**Comment by azurebrd** [comment]
I don't remember what the output looked like before, and I can't see it now.  If you let me know what query to use to replace, then I can just change it.  I don't know what sorting we're doing, but we're looking at : 
"grouped" -> "bioentity" -> "doclist" -> "docs" -> "bioentity"
"grouped" -> "bioentity" -> "doclist" -> "docs" -> "bioentity_label"

**Comment by raymond91125** [comment]
just remove "&sort .... %20asc" from the query.

**Comment by azurebrd** [comment]
I've changed it on juancarlos.wormbase.org and it's not breaking.  Let me know if the data looks good to make a pull request.  You should probably test the solr queries after rebuilding solr so we can sync the git code with the WS release.  I think this will now be broken until the next WS release, unless you revert the solr build.

**Comment by raymond91125** [comment]
I'm still getting error for this page
http://juancarlos.wormbase.org/tools/ontology_browser/show_genes

**Comment by azurebrd** [comment]
No one should ever go to that page, links should be to specific object pages.  I've changed it to stop breaking when going to that page through editing the URL though.

**Comment by raymond91125** [comment]
specific term pages are broken, e.g. tools/ontology_browser/show_genes?focusTermName=translation regulator activity&focusTermId=GO:0045182

**Comment by raymond91125** [comment]
rolled back schema.xml of solr server and the error has gone away. however, going forward, we should still fix the query to remove sort=taxon as the upstream schema has changed to make taxon multi-value and thus incompatible with the sort flag.

**Comment by raymond91125** [comment]
Hi Tao,

Thanks for reporting the problem. It should now be fixed.

Cheers,

Raymond

**Comment by azurebrd** [comment]
Fixed and made pull request to fix broken solr queries due to change in schema.
