### ISSUE TITLE
  When I put wormbase into google and c...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4100]
<p>&nbsp;&nbsp;When I put wormbase into google and click the result parts of the homepage does not load.<br/>When I use a bookmark the homepage does load.<br/>Is the link from Google broken?</p><p>What were you doing? <br />&nbsp;&nbsp;going to wormbase from google</p>

Reported by: wech************  (obscured for privacy)
Submitted From: support <a href="http://www.wormbase.org//tools/support">/tools/support</a>

Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.130 Safari/537.36

**Comment by sibyl229** [comment]
Hi,

Sorry about the problem with the link from Google. The reason is that Google prioritize search results adopting HTTPS protocol, while WormBase site isn't fully up to speed with HTTPS. We have HTTPS enabled for only parts of the site, such as login. We are working on solving the problem. For now, please change the URL in the address bar to http://wormbase.org <http://wormbase.org/> (remove the “s" in https). Sorry about this.

Thank you for letting us know.

Sibyl
