### ISSUE TITLE
  I want to ask you about the animal C....

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4112]
<p>&nbsp;&nbsp;I want to ask you about the animal C.elegans. I was a student who wanted to do research on quantum dot nanoparticles using animals c.elegans as an animal model. I want to know how to order and bring the animals c.elegas to my country. because at my college no such animal. I also want to know anything are the requirements that I could examine the use of these animals. Please information to me as soon as possible, because I really need the animal.<br/>Thank you</p>

Reported by: Juma**** (mr.i********************)  (obscured for privacy))
Submitted From: PCR Product/Oligo <a href="http://www.wormbase.org//species/c_elegans/pcr_oligo#1-0-3">/species/c_elegans/pcr_oligo#1-0-3</a>

Mozilla/5.0 (Windows NT 6.3; rv:39.0) Gecko/20100101 Firefox/39.0

**Comment by Gschindelman** [comment]
Jumardin
WormBase does not distribute nematodes.  Please contact the Caenorhabditis Genetics Center (CGC) for help with obtaining C.elegans strains.

http://cbs.umn.edu/cgc/home

In order to lean about how to work with C. elegans, please see:
http://www.wormbook.org/
in particular..
http://www.wormbook.org/toc_wormmethods.html

Thanks
Gary S 
WormBase Help Desk
