### ISSUE TITLE
etr-1 had an isoform C which was removed from it b...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4159]
*Help Desk query collected when no chat operators were online. Follow up required.*

etr-1 had an isoform C which was removed from it but the sequence features still has isoform C. It is a typo with the system? Is there isoform C or not? Thank you.
    
**Reported by:** Ruby******** (ruby*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00001340#0-9f-3">http://www.wormbase.org/species/c_elegans/gene/WBGene00001340#0-9f-3</a>
**Browser:** Chrome 44.0.2403.157

**Comment by gw3** [comment]
Ruby,

etr-1, isoform C is modelled using the aligned EST AU216445 and some RNASeq
data, both of which show that there is some evidence for a retained intron
in the eleventh intron.

This used to be modelled as a CDS, but it was recently reviewed and we
found that it did not fit our criteria for a CDS: there is no evidence for
polyA sites in the eleventh intron and so this transcript would have
premature termination codons and would probably be removed by the NMD
pathway.

It has therefore been changed to be a non-coding transcript isoform. This
still has the same ID for the 'C' isoform: 'T01D1.2c'.
It is not a CDS though, it is a ncRNA transcript, which is why you might
have missed it in the display of isoforms in the 'Sequence Features' widget
on the web site: it is displayed as a structure which is grey (indicating
it is non-coding) all along its length.

Gary WIlliams
