### ISSUE TITLE
Molecule display page: papers in phenotype affected widget missing in references widget

### ISSUE THREAD

**Issue by kyook** [WormBase/website#4179]
Is this a data problem or can this be fixed on the website?

**Comment by tharris** [comment]
The References widget is generated from our search database. We may need to update the search database so that these references appear.

**Comment by kyook** [comment]
This was a problem with the allele phenotype evidence - perhaps since it is contained in the phenotype_info hash. We fixed this by submitting a .ace specific with just allele paper connections, which were used for reference widgets.  Do I need to do the same for these cases? Or can the other issue be solved with you updated search database (and I no longer have to generate that second .ace)?

**Comment by sibyl229** [comment]
Hi @kyook I think an ace file for the Paper-Molecule connection is needed. The reason is that the content of the Reference widget comes from searching the papers that were indexed, and looking for those papers matching the molecule. And since the paper ace file doesn't have the molecule reference (those hidden in affected_phenotype_of tag of Molecule object), the information isn't included when indexing the papers, and can't be searched. I'm curious if these Molecules can be added to the Paper model.

Sorry Karen, this probably means more work for you. I can't think of a better way to do this though x.x

**Comment by kyook** [comment]
Ok,  I'll work on getting a paper-molecule .ace dump for WS253. Thanks!
