### ISSUE TITLE
  Dear wormbase staffs, I am asking how...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4187]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Dear wormbase staffs,<br/>I am asking how to retrive the ontology annotations of all C.elegans genes from the current wormbase release. <br/>I want to make Anatomy/Phenotype/GO... enrichment for my gene list. So the minimal result could be two-column table like "GENE:Phenotype". <br/>I tried the REST api for genes to retrieve the results one by one, but even the example codes returned "Server Error: 500". The wormmart seems to give a reasonable output based on ws220. Meanwhile I was completely lost in wormmine.  For example, in the QueryBuilder, the "GO annotation" is in the root level, while there is another "GO terms" inside "Expression pattern". Is there an "easier" way to get the information?<br/>Many thanks and best regards,<br/>Runsheng</p>
    
**Reported by:** Runs**** (runs******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.125 Safari/537.36

**Comment by tharris** [comment]
Hi Runsheng - 

If you look at the FTP site, you’ll find a wealth of information that we prepare for every release. The files in this directory might be of some use to you:

ftp://ftp.wormbase.org/pub/wormbase/releases/WS249/ONTOLOGY

I highly, highly recommend taking a look through our FTP site. It is very well structured compared to other resources like WormBase: file names and paths are predictable and consistent, names reflect contents, etc. You probably won’t need to resort to things like BioMart or Intermine if you look through the files we prepare and are familiar with programmatic tools such as BioPerl for manipulating sequence (should your project require such).

As to the REST API, the documentation isn’t 100% up-to-date, something we intend to fix. That said, you can simply use the developer console of your browser to see how the website leverages the API. It’s most convenient to fetch entire widgets as data structures that you can then parse, instead of the field-by-field approach.

Hope this helps.

Todd
