### ISSUE TITLE
  Hi, I am a post-doc working in Univ o...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4223]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi,<br/>I am a post-doc working in Univ of Michigan. My PI and I recently receive a Email from wormbase asking us to flag some developmental cell lineage data collected in one of our published papers. I assume the purpose of that is to help community/curator include that paper/dataset to some database of WormBase.  So recently I want to conduct some additional studies regarding the developmental cell lineage (or part of the lineage) upon genetic changes such as gene knock-out.  Given my experience flagging my own paper, I presumed that there is a section somewhere on WormBase that will listed all published papers with cell lineage data (by a tag/an ontology/a folder, or anything like that), but I cannot find such a section.  So is such information really available on WormBase, or I should look somewhere else? Thanks in advance !</p>
    
**Reported by:** Phil******* (yang************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0

**Comment by kyook** [comment]
Hi Philip,

Would you give me a bit more information about the e-mail you received?
What is the title of your paper? And what type of data did you submit;
mutant phenotype data or anatomy/cell specific data via ablation studies
(for example)?  I'm asking since there are many curators involved in the
curation of data that is flagged by the public and if I know the specific
data that you submitted, I can direct you to the person who can help you
best.

Thank you for getting in touch with us.
Karen





On Tue, Sep 29, 2015 at 6:18 PM, <no-reply@wormbase.org> wrote:

> How Do I ...?
>
>   Hi,
> I am a post-doc working in Univ of Michigan. My PI and I recently receive
> a Email from wormbase asking us to flag some developmental cell lineage
> data collected in one of our published papers. I assume the purpose of that
> is to help community/curator include that paper/dataset to some database of
> WormBase. So recently I want to conduct some additional studies regarding
> the developmental cell lineage (or part of the lineage) upon genetic
> changes such as gene knock-out. Given my experience flagging my own paper,
> I presumed that there is a section somewhere on WormBase that will listed
> all published papers with cell lineage data (by a tag/an ontology/a folder,
> or anything like that), but I cannot find such a section. So is such
> information really available on WormBase, or I should look somewhere else?
> Thanks in advance !
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #4223. Follow progress on our issue
> tracker <https://github.com/WormBase/website/issues/4223>.
>
> Reported by: Philip Yang (yangjr@umich.edu)
> 30 Sep 15 01:21
>
> Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0
>
> This question was reported via the web interface at wormbase.org. You can
> also email us <help@wormbase.org> directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>


-- 
Please take the WormBase survey!  http://qrs.ly/9m4rpsc

~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 626.395.5878
e-mail: kyook@caltech.edu
e-mail: kyook@wormbase.org
skype name: wbkaren

**Comment by raymond91125** [comment]
Hi Philip,

WormBase does not yet have much curated cell-lineage information other 
than what's in the anatomy ontology. But we are planning to do so since 
as you know, this data type has become increasingly important with the 
maturation of 4D microscopy technique and software. If you would, please 
let us know which paper you (or others) have published so that we can 
make sure that they are being considered for devising suitable data 
models and in the cue for curation.

Best regards,

Raymond


On 09/29/2015 06:18 PM, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   Hi,
> I am a post-doc working in Univ of Michigan. My PI and I recently 
> receive a Email from wormbase asking us to flag some developmental 
> cell lineage data collected in one of our published papers. I assume 
> the purpose of that is to help community/curator include that 
> paper/dataset to some database of WormBase. So recently I want to 
> conduct some additional studies regarding the developmental cell 
> lineage (or part of the lineage) upon genetic changes such as gene 
> knock-out. Given my experience flagging my own paper, I presumed that 
> there is a section somewhere on WormBase that will listed all 
> published papers with cell lineage data (by a tag/an ontology/a 
> folder, or anything like that), but I cannot find such a section. So 
> is such information really available on WormBase, or I should look 
> somewhere else? Thanks in advance !
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #4223. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/4223>.
>
> Reported by: Philip Yang (yangjr@umich.edu)
> 30 Sep 15 01:21
>
> Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
