### ISSUE TITLE
Hi, 
I want to know the sequence of mys-1 deletion...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4242]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi, 
I want to know the sequence of mys-1 deletion (strain MT13172) is correct or not. Because we found the sequence of VC5.4 and mys-1 deletion sequence didn't match. 
Thank you.
    
**Reported by:** Susa* (susa*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00007029#5a3-08964fe-3">http://www.wormbase.org/species/c_elegans/gene/WBGene00007029#5a3-08964fe-3</a>
**Browser:** Chrome 45.0.2454.101

**Comment by tuli** [comment]
Dear Susan,

Thank you for contacting WormBase.

The n4075 deletion (carried by MT13172) was curated based on
publication PMID 15068795 Ceol CJ et al. (2004) Dev Cell "A new class
of C. elegans synMuv genes implicates a Tip60/NuA4-like HAT complex as
....".

I have just checked the paper and can confirm that our curation does
match the paper's description. We do assume published data is correct
and add appropriate evidence so that users know the source of our
information.

We are always interested in knowing about new findings so please do
send us any data you have. We may need to contact the authors of the
original paper to resolve any discrepancies.

I hope this answers your question.

Best wishes,

Mary Ann

~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by tuli** [comment]
User is checking. Closing.
