### ISSUE TITLE
Hello,
I was just wondering whether there is some ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4248]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello,
I was just wondering whether there is some easy way to get list of secreted proteins in C. elegans? I used Biomart using "GO:0005576", extracellular region,GO term.It returned only 357 genes annotated for this GO term, proportion is clearly lot less than found in other organisms.
Thanks
Nishant
    
**Reported by:** Nish*** (thak*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00003553#0-9f3-3">http://www.wormbase.org/species/c_elegans/gene/WBGene00003553#0-9f3-3</a>
**Browser:** Chrome 45.0.2454.101

**Comment by epaule** [comment]
did you use the WormBase ParaSite BioMart or the old WormMart?
Because if I query for you go term and C.elegans on the ParaSiteMart, I get a few thousand genes back. It is probably best to avoid WormMart and rather use the ParaSiteMart for the time being.

We plan to release soon an updated version of the WormMine, which should be even more up to date than the ParaSite one (as C.elegans is in parasite mostly as comparator species)
