### ISSUE TITLE
Hi, just a quick question: On the page for the mut...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4299]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi, just a quick question: On the page for the mutant alelle by134 (http://www.wormbase.org/species/c_elegans/variation/WBVar00000635#02-45-2-), it is writen that the nucleotide change is a t/r (wild type / variant). I understand that the change is to a purine that is not defined.  I just found it strange and wanted to ask if the interpretation is correct and if there is usually a reason for not specifying the exact change to G or A.

Thanks!
    
**Reported by:** Paol* (pjur***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/variation/WBVar00000635#02-45-2-">http://www.wormbase.org/species/c_elegans/variation/WBVar00000635#02-45-2-</a>
**Browser:** Firefox 41.0

**Comment by tuli** [comment]
Dear Paola.

Thank you for contacting WormBase.

Excluding the large sequencing projects which generate tens of
thousands of variants, most alleles are curated from the literature,
with a smaller proportion submitted to us using our submission forms
usually by the group who identified the allele.

The reason we have not specified the change in by134 is because (as
you say yourself) it is not defined in the literature. This is not
uncommon for nonsense codons, so we curate to the highest level of
accuracy we can. Should we be informed or come across literature which
allows us to define the nature of the nonsense codon precisely then
the record will be updated.

I hope this answers your question.

Best wishes,

Mary Ann

~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
