### ISSUE TITLE
a mistake in wormbase

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#4324]
Dear Sir/Madam:

 

I am a graduate student in ShanghaiTech University. I found a problem when using WormBase. I searched the gene cdd-1 on the page below:

http://www.wormbase.org/species/c_elegans/transcript/C47D2.2#0653--10

 

But I found that the information of “view spliced + UTR (900 bp)” and “view unspliced + UTR + 2000 upstream + 2000 downstream (6399 bp)” are different. As we know, the initiation codon are ATG as we see in “view spliced + UTR (900 bp)”,but they are not in “view unspliced + UTR + 2000 upstream + 2000 downstream (6399 bp)”. After aligning the two sequences, it is clearly that the exons and introns are wrongly marked in “view unspliced + UTR + 2000 upstream + 2000 downstream (6399 bp)”. The two screenshots are in the attachment. Maybe there was a bug in your website and I wish you could check it and fix it if there was a problem indeed. Thank you!

**Comment by chris-grove** [comment]
Screenshot attachments:
![1](https://cloud.githubusercontent.com/assets/611382/10827290/407eba3c-7e2b-11e5-9e26-ea5baa66a040.png)

![2](https://cloud.githubusercontent.com/assets/611382/10827292/427abc5a-7e2b-11e5-9844-4f986afe2e0c.png)

**Comment by chris-grove** [comment]
Hello Tao,

 You are correct, there is a problem with the sequence display. Thank you for the report.

It appears that the sequence including the upstream and downstream sequences is being displayed in the wrong direction and the exon highlighting is therefore incorrect.

I've created a GitHub ticket for this issue which you can follow here:

https://github.com/WormBase/website/issues/4324


Thanks again for the notice. We will get this fixed as soon as possible.

Best,

Chris Grove
WormBase Help Desk

**Comment by chris-grove** [comment]
@sibyl229  It looks like the sequence including upstream and downstream sequences is in reverse order, and the exon highlighting appears to be off, maybe calculated for the forward sequence and overlayed on the reverse?

**Comment by chris-grove** [comment]
@sibyl229 
 Also, I just looked at a handful of other genes and it doesn't seem to be a systematic problem. It also isn't specific to genes on one strand or another.

**Comment by sibyl229** [comment]
Hi @chris-grove this bug of wrong flanking region sequence should be fixed now: http://staging.wormbase.org/species/c_elegans/transcript/C47D2.2#0653--10 The problem was that the code identified the wrong segment that has the same name, so it was totally fetching the wrong sequence. I compared it with the result from http://rsat.sb-roscoff.fr/ attached below. The difference is due to an extra base found in our downstream sequence that's not in theirs. So I think the fixed sequence fetching code is working correctly. Could you double check please? Thanks a lot!

`>cdd-1	C47D2.2; upstream from -2000 to 4398; size: 6399; feature type:mrna; location: Caenorhabditis_elegans:NC_003284.7:8206692:8213090:R; upstream neighbour: NM_076984.1 (distance: 3928)
GCATATGAGGGTCCGAAAATCTAGGTGACGCATTCAAAACAGAAAAAAAAACAACATCTG
ACTGCAAAAGCTGTTGAAAATGCGAAAACATCCGAATCCGAAGACATTCTATAATTATTG
CCGCTCTTTGCATTATGTAACGTTAAAAAAATGGTTGTTATGTAGTAGCCGTATATTATA
TCAATTAAAACAAATGATGAGCCGTTTCGTTCAGTTTCCTGTAGAGGGCTGGCTGTTTTC
TTAGCAATAAGCCAAAAAAAAACGTTCGTAAACGTAAAAACGTAAGTTCGCGTTTCGATT
GAGTAACCATTATTCGATTATCATAAATTTTAAAAAGTTGTTTTTAAATCCTGCGAAGAA
CTTCTTCTATTTTTTTACAAACCACAAGAATTCAATCTAAAATTTAATGTACTAAAATAA
TATTTTAAAAGCTCATTTTGTCTTCAGAATTTGATATACTTAAGAATATGATAAGAGTTG
TCAGCAAAAAAAACTTCGGTATTTGGAATTCATTGTCATTTTTATCCTAGATCTTTACCC
ACAGAGAGTTCTTGTATTGCAGATGTATTCTATAGCTGATCAGACAAAGTAGCAATACAT
AATATAGTTGCTTGATGTTTCCACCCACCATTACTTTTGGAATTGACAAAAGCTGACAAC
TTTTCTTGTATATAATGAGGCAAATGATCAAAAAAGTTTGGTCTCTTGAAATGTAGGCAT
TGTCTGTTACATGATTTAAAAGATCACACACTTGTGTGATGATAGCAAAGTTCAAAAAAA
GAGAGTCTCGTGAGTGGATTTCAAGCTATTTTCGGTTACCCGCACATTTTTGCTGCAAAC
AATTCACAAGACATTTGAGTTCAAAATCATTCTGAGAATACTCTGAGAATCGCTATTGGA
CTTTTAAAATATGTTTTAAAAACAAAAAAAAAGTTGATAGGCATACTTTGAATTAGGCAA
TTGTTCAAAATAAGATGCTGAGCTATTCCACCGCAGTAGTCGTCAAATATAAACGAGATA
TAGGGATTTTTTAAAAATATTTTTGAGGAAGTTCAGTAGTTATATTTTGAGGAAGTTCAG
TTAGTGAAGCAGTATAAAGTAAACATAAATAAAGTCAGTTTTTCGCTCAGTGTACAGTGT
ATGAATCACATTAATTGTGAAGAAAAACAATTTCAGTCAACAAAAAATGCCAGAACCGCC
ACATCAATGAGTTGTTTTGTCACTTTTGTCTTTCAAGAAATACTCCCTTATATACACATA
TTCTTTGTTCTTATAAAGATGCTTGAGATACATTTCTTAAAAGGTTTTATTTATTTCGGC
TGGTTTTAAGAAGAGCATTTGTGGTTCAAAATATGAATTTTTCTAAAAGTAGTGAAATCA
TATTTGAAATACTTTGAAGTTTTTATTAACATTTGAAACAGCTATTAGCATTTCTAGAGA
CACAAATGAGGAATTTTTGTAAATGTGATGGAAGAAACTGTTGAAATGATTCATAGTTCA
AAATTTAGTTTCAACTGTAAAAATTAAAAACTATTTTTAAACGGCCGTTTAAAAAAAATT
GCTAATTTTTATTCAAATAGAATATCGAAGAGCAATTCGTTTGTCGCATTTTGTTATCTA
TTCTCTTGCAAATGAATCTTTGCAAATAGATTTCTCATCACTCTTATAATCCCATATATT
GTTTAAAATTGAAGCACTATTGGCACCAATCGTTATCAAAACTTTCATAGTAATCGTTAA
GGCTGAAGTTTGTAGGCAATGCATAGTTTCTACAAAGCCCATGAACATCACTTTCAATTT
AATGGACCAGTTGAAAATGAAATGATAAATTCGACCGAATTTTCTAGAATCGTCTGAATG
TGGCGTACGTCAGTGAACCAAGTCGTAAAACGACGCGGGTTTGCCATCCTATTCCTTATT
TCTTATCATTATCACTCCTCGTGGCCCACTGTTATCAATCATCGGGAAATGTATAAAAAA
CCCCCACATACTCACTCTTTCCCCATTCACAGTACATTTAGAAAGGCAAAGTTCTTACAG
GAATGGTGAATGGGGAAATGTAATTAAAAATTTTAATTTTTACGTCTGTTCTTGATACTT
ATTTTGATTTGTCCTTGGATGGAATATTTTATAACATAAGTTGAAGTTTGTACAAATTTC
GAAGACGGTTAGAAAGCAAAGTTCTCCATGCAACGAAAAATTGGAGCAAATATTGACTAT
CCGATTCATTTGCTTTATTTAGTTTTCACATCCTAACTAACCACGTGCGAATTGAATCTA
CTGTTTGCAAGCTTCTTTTTCTTAGTTTAGCCAAAATTTTCAACAATAGTTTTAAGTTTT
AAAAAATTTACAGAATGACTACAACAAAGGCAAACCTTACCGAGTTTGAGCAGCAACTTG
TTGATAAAGCAATTGGAGCAATGGAGAATGCTTACTGGTATTTCAAAAAAGCACGGTAAA
TGTTTTACAAAAAACATTTTTAGCAAGTATAGCAACTTCAAAGTTGGAGCTGCGCTGGTG
TGTGACGACGGAGAAATTATCATAGGAGGTGGGTGGAGACTATGATTTTCGTCCTTGTCT
GATTCATTAGTAAATGTGAGAACTTGAAAGTGCAACATTTACATCCGATTACTAACTATT
CACAATCATTCGAGTATTTTCAGCTAACCATGAGAATGCGTCATACGGAGCAACGATTTG
TGCAGAGAGAAGCGCAATAGTTACCGCCTTGACCAAGGGACACAGAAAATTTAAGTACAT
TGTTGTTGGTGAGTTGAAAAAAAGGTTCTAACGTTTTTAAAGTATTCATACTACATTATA
TAAGATACGCAGTTGAAAATTGAAACTCAGAATTTACAAATTCTGTTAAAAATGAAACTT
GATAGTACACCTACTCATCTTCATGTCATAAATGATCTTACGAACTTTGAAGAGTAATGA
ACAATTTTAAACGGGTTTTAAAAAGCTCCTGTTTTGAGAATATCTGTCTGACACTAATAA
TAAAAATATCTTATTTCTTTTTTCATTTTGAAAATGACATCCCAAAACAGTATATCATAT
TTTGAGTAAACCTCAAATATCAAAATTATGTTATATTATTGCGAAAATAATAGATTTTAA
AATAGTTTAAATGTTCAATTACAATTTGAAGTTGACATTCTTAAATGTAGTGTGGGTGGA
ATTCCATATTTTGAAGACAGACAGACTCATATTTCCGAAATCCCGATAGTTGCATAAATT
GAGACAAATAATACATCATGATGAAAATTTGAAACGCACTTCAAATCGAAATGAAGGTTG
TTTGTAAATGTTCTGACTTCATTTTTATATAAAAAAAAAATCAAAGACATAATGAAAACT
AAAATTGATGGTTTGCTGGGTTTGTAAAAAATTAAATTCATATGAATGTACTAACTCAAA
AATTAAAAACTAAAATTAATAGCAAAATATAATTTTTGAAGGGTTTCACGTGAAAATTTT
TTAGTTCAAGAACAAGAAACTTCTCCGAATACAGTGTCAATCATGAAACGATCAATTTTT
TTAAACTTAGTCATTTCAAAGTTCCAGTCTCGACAATAGAATGCGATTTAAAAAAAATAG
AGAGAGAGTTTTGTATACCAGGCTGATCAAAAATACATTTAGTGAAAAATTGTAATTGTT
TCACAGTAGGAAGATACATTCACAATATGAGGCAGAACTCTTTAAATATCACACAATTGA
ACTTTAAAACAGCTAAACGTCGTAACTAAATTTGAACTAAATTTTTAATGTTTTTAGCAA
CCGAACTAGAGGCTCCCTGCTCGCCATGTGGAGTATGCCGACAGGTCCTTATCGAATTTG
GAGACTACAAGGTTGGTTAGAAATATTTCAAAATTTAATATGCATAACAAAATTTAATAT
GCATAACTAAACTATGCTGATTCTTTTTTTCATAGTTTTCAAATTTATGCTCGCTATTAT
AAAATTATGTGAGCAATTATATTTGAAGAAAGCCTTGCATATTCTCTGAAAACAAAGTAA
AAAATGGAGGAAAAATACGAATGAAAAAGTCATAATGAGTGTTTTCCCTTCAACCTGCAA
GAGTCTACTCCATTTCCACTATTCGTTTCGTTTATTTCCAGATGAATTGTTTTCTGGACC
ACCCACGTCTTCGGTTTCAAATGTCATTTTTCTTGTTCAGGTCATTCTCGGGTCTTCGAC
TAGTGATCAAATTATCGAGACTACAACATACGAGCTTCTGCCATATGCATTCACTCCAAA
ATCACTCGATGATCATGAAAAGGAGACTGAAGAGCGCAAACATCACAATGATCACAACAA
TAAGGAATAGGGAAAATTTTCAGAAATTCATAAATGTTATGAACACAGTAATTTCTATTA
ATAAAACATGGTTGTTGAATATATTTCTGGTTTGACTTTTTCCAAAAAATACTGGATACA
CTTAATAACAAACTTCAAAACTTTACCGAGTTCAGAAAGTTTGGCAAATGTAAATTTTCT
ATTATAATTCAATGTTAAAAGACTTGCATTTGAAGGCAGTTTTAGCTATATATTATATAA
TTTTTGTAACTGTTTTTCGAAGCCGGGCACTATTTTGGTTTCACACTGTGTACCAATGGG
TTCCCTTTAAATATTTCCATGACGTTCAGAAGAAACAGCAAGCCTTATGTCATTTTAATG
AAGTTCCAAAAAAAATTGTCATGATCCATTATTTTGCGTCAAATTTGAAAATGAACTTGC
TCATGCCCTTACTTTGGAAATATGCAGTTCTCGGAAACTTTAATCATTTGCAGCTTACTA
CCCATAAATTATTTTCTACAAAATGATTGAGATGACATTTATACTTTTTTTAGTTGCGAA
ATATACAAAACCGTCTAAAAGTGTTTAGTCACAGAATCATCTTCATACGATGTTCACCTA
TATTTATAATTTTTTTTTAATGTGATATATAATTTTAAAAGTTGTTTTGTTTTACAGAAC
AAACTACGATTAGATACGGCCAAAAATTATAATTTTACCTTTTCCCAGATTTTTTTTATT
GTTAGTACTTTTTCAAGGACTGTGTTAACCGTTTTGCAGGCTTTCATTGCGTTTTTTTTT
TTTGGAAATTTTGAAAGTTAATTCAATAGATGGATGAAATTTTGTAACTATGATTTCTGA
ACATTGGCCCCAATTCGAACACAATTTTCAAAATTTGCACTAAATTGAACATGTTCCATT
ACTCAATTCATCCCCAATTCTTTCAACGCCCCAGTCAATGTGAACACGAAATTTTATCGT
TTACACTAATCAATGCAGTATAAATGACAAAAATATTGCGAAGAGACATGTCGGTCCATG
TGACATTCGGTGATGATGATGGAACATTTCACTTGTCTTATTCAACAAGCAATTGTATTT
ATAATGAGAATTGATCTGATTTAATCTAAGAATCATATTTGGGTTTTTATGTAGTTCGCA
TTTGGAAGACTTTCCAAATATTTATACGTCTGTTGAACGGCCGCGCTTCATAAATTAGAA
ATTTCTCAAACTTTTTAACACCGCTAAACCAGGTTCCTGCACATGGTACAAACCCCAGAA
AGACCTTGGAGAGATCTGTGAAGAAGTGGAAAAACGAACCGGACGTATTGAACATGTTTA
CAAAGTTTTAAACTTTACTAAGTAATCTTTACAGGCGTTCTGCCTCCAAAAGATATGCAC
TTTGCCCCCCCCCCCCCCCCCCCCCCCGACTATTACTATTTCAGATATCATATTCACCTG
TATATAAGCACCCGACATGTTCTTTACCTTTCATCATTATTTTCGCATAGTTTGCTGAAA
AAACATTCAAATAATATAATTTGAAAATAAATTCGCCCCCCCCCCCCCTTCACTAATCAT
TTGGAAATTTTCTTAAAGTTGTTTTTTTGAGCTCCTTCTCATTTTTTTTTCTTATCCGTC
TAATAAAAATATCATATTTCACGTGTGTTTGCCACCAAGAGTGTGTGTCAACGTCTGTTT
TTTTTCTCTTTCTCTGCCGCCAGAAATAAGAATAACTTTTTTTCTTGAGAAATGCATTGT
TATTAAAGAATTACGAGGAATTTGTTTTTTTTTTTCGTAAAACTTGACGAACAAAAAATT
TCGAAGGACCTCTGCGTGAACTTTTTTTCGAAACGAAATAATGCTTCAATTTTTGTAGAA
TAGCCTGAAATAGTGAACAAACATTATCGTATCATTGAATCTCTCAATTTCACTGTGTAT
CAAAGCTTCAGTAAGTTTTTGAACTGCTTAATGAAAACAATATTGAGCAGTTTTTGCGAT
AACCAATTTTTAGCACTGACCAATTTAGCATTAATCAAGTTCTCATTGATCAACTTTTGG
CACTGACCATCTTGCCAGTAATCAACTATATGTACTGAC`

**Comment by chris-grove** [comment]
@sibyl229  Yes, looks good! Thanks!
