### ISSUE TITLE
  . . . report our newly published RNAi...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4342]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;. . . report our newly published RNAi data? We were recently asked by WormBase to self-curate allele data from our 2015 G&D paper. We will do this, but we'd also like to add the RNAi data. Is there a mechanism for us to do this?<br/>Thanks!</p>
    
**Reported by:** asew****************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_5) AppleWebKit/537.78.2 (KHTML, like Gecko) Version/6.1.6 Safari/537.78.2

**Comment by chris-grove** [comment]
Hello,

 We don't yet have a simple web form for RNAi phenotypes like we do for
allele-phenotypes, but hope to soon. In the meantime, I'd be happy to
take in whatever RNAi data you have. If you have RNAi phenotype data in a
spreadsheet format, that would be great. Otherwise I can curate it from
the paper myself.

Thanks!

Chris Grove
WormBase

**Comment by chris-grove** [comment]
Communicated with Aileen and have imported her data
