### ISSUE TITLE
where can i look up supporting evidence for gene p...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4346]
*Help Desk query collected when no chat operators were online. Follow up required.*

where can i look up supporting evidence for gene predictions made in ParaSite for the genomes of m hapla and m incognita. i.e. ESTs and mRNA data.

**Reported by:** Sash******** (loew*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#01-23-6">http://www.wormbase.org/#01-23-6</a>
**Browser:** Safari 6.1.6

**Comment by brucebolt** [comment]
Dear Sasha

The gene predictions for these two genomes has been imported using data supplied by the groups who performed the sequencing.  I would therefore recommend contacting the corresponding authors of the relevant genome papers in order to obtain any supporting evidence.

For H. hapla, this is Charles Opperman (warthog@ncsu.edu <mailto:warthog@ncsu.edu>) [Paper: http://www.pnas.org/content/105/39/14802b <http://www.pnas.org/content/105/39/14802b>]
For H. incognita, this is Pierre Abad (pierre.abad@sophia.inra.fr <mailto:pierre.abad@sophia.inra.fr>) [Paper: http://www.nature.com/nbt/journal/v26/n8/full/nbt.1482.html <http://www.nature.com/nbt/journal/v26/n8/full/nbt.1482.html>]

Best regards

Bruce


-----
Bruce Bolt
Software Engineer, Non-vertebrate Genomics

European Bioinformatics Institute (EMBL-EBI)
Wellcome Trust Genome Campus
Hinxton
Cambridge
CB10 1SD
