### ISSUE TITLE
  Hello, I want to generate a list of g...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4353]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello,<br/>I want to generate a list of genes that are expressed in somatic tissues only (no germline).  In other words, how do I exclude "germline" in WormMine queries?<br/>Thank you</p>

**Reported by:** N2Br***************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:42.0) Gecko/20100101 Firefox/42.0

**Comment by raymond91125** [comment]
I don't think you can easily do this query in WormMine because it 
doesn't have inference built in. To get at genes that are 'NOT' 
expressed in germline tissues, you can subtract those that have 
annotated germline expression from all genes that have expression data.

You can download the respective gene list from the Ontology Browser widget

All 
<http://www.wormbase.org/species/all/anatomy_term/WBbt:0000100#03--10>, 
5022 genes
germ line 
<http://www.wormbase.org/species/all/anatomy_term/WBbt:0005784#03--10>, 
525 genes

Afterwards, you can paste the list into WormMine to retrieve other, 
direct annotations of those genes.

Thanks.

Raymond


On 11/10/2015 04:36 AM, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   Hello,
> I want to generate a list of genes that are expressed in somatic 
> tissues only (no germline). In other words, how do I exclude 
> "germline" in WormMine queries?
> Thank you
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #4353. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/4353>.
>
> Reported by: N2Bristol@gmail.com
> 10 Nov 15 12:37
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:42.0) Gecko/20100101 
> Firefox/42.0
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by raymond91125** [comment]
not heard back. probably settled.
