### ISSUE TITLE
How do I change my username. It is currently an ol...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4384]
*Help Desk query collected when no chat operators were online. Follow up required.*

How do I change my username. It is currently an old email address. I would also like to update my primary email address - same problem.

Thanks!

**Reported by:** Mich********* (m-st*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/me#12-0-10">http://www.wormbase.org/me#12-0-10</a>
**Browser:** Chrome 46.0.2490.86

**Comment by chris-grove** [comment]
Hi Michael,

As for changing your username, our web team will need to get back to you.

You can change your e-mail address (or other personal information) using this form:

http://tazendra.caltech.edu/~azurebrd/cgi-bin/forms/person.cgi

Just query for your name at the top of the form and confirm on the following page to reach your personal info:

http://tazendra.caltech.edu/~azurebrd/cgi-bin/forms/person.cgi?action=Query&number=two624

Then you can make whatever edits are needed. Note that the phone numbers are not visible on your WBPerson page:

http://www.wormbase.org/resources/person/WBPerson624#01432--10


Best,

Chris

**Comment by chris-grove** [comment]
@tharris  can you let Michael know how to change his username?

**Comment by chris-grove** [comment]
Thanks, Chris.

Under My Wormbase, My Profile 
http://www.wormbase.org/me#12-0-10

... it lists my old ucf email address as "primary." That is what I was trying to correct, because I thought that that designation was being used for something important (i.e. how to contact me by email).

But I don't think that means anything, since on my Person page
http://www.wormbase.org/resources/person/WBPerson624#01243--10

... it lists my correct, current email address.

The form link you sent does not change that. Maybe I will just ignore the "primary" designation, since it doesn't seem to have any ramifications.

Thanks,

Michael

**Comment by chris-grove** [comment]
Hi Michael,

 OK, I see. I think Todd Harris (CC'ed) would have to comment on what
determines the "primary" e-mail address in the My Profile widget when
you're logged into WormBase.

Chris

**Comment by draciti** [comment]
Todd, Chris, has this been resolved?

**Comment by chris-grove** [comment]
@draciti  Hi Daniela, yes I think this is resolved. I've just sent Michael an e-mail to double check. If there are any remaining issues, I'll reopen. Closing now.

**Comment by draciti** [comment]
great, thanks Chris
