### ISSUE TITLE
  F42G9.6 should be named as  dagl-1 ac...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4393]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;F42G9.6 should be named as  dagl-1 according to our publication in Aging Cell (http://www.ncbi.nlm.nih.gov/pubmed/24889782 ), not dagl-2 on wormbase (http://www.wormbase.org/species/c_elegans/gene/WBGene00018364#0-c9e7b5f8416-10 ).  Please correct it.  Thank you very much!<br/>Sincerely, visitor_name</p>

**Reported by:** Horn********** (hdwa*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; InfoPath.3; rv:11.0) like Gecko

**Comment by tuli** [comment]
Dear Horng-Dar,

Thank you for writing to WormBase.

F42G9.6 was assigned as dagl-2 following communication between you and
Tim Schedl in Feb 2014.

This is what he wrote:
"The new gene class designation:
“dagl” for “DiAcylGlycerol Lipase homolog”   -------- is approved

The new gene association:

F42G9.6 = dagl-2  [using -2 as F42G9.6 is more similar to dagl(beta)
than dagl(alpha)]

-------- is approved "

WormBase aims to reflect the literature so we will assign dagl-1 to
this gene. I have included Tim in this message as he will need to
decide whether dagl-1 or dagl-2 will be the main name with the other
one being assigned as an other name.

Tim will contact you soon.

Best wishes,

Mary Ann

~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by tuli** [comment]
Hi Horng-Dar, 

As indicated in the earlier email, F42G9.6 is more similar to dagl beta than to alpha, which was the reasoning for naming it dagl-2. 

Tim 

----- Original Message -----

**Comment by tuli** [comment]
Dear Tim:

 

Though F42G9.6 was later to be found more like dagl beta, after we published our paper in Aging Cell 2014 and the reviewer suggested us to name it dagl-1 in the paper for F42G9.6.  That is also why we registered F42G9.6 in the wormbase as dagl-1.  Even you later find F42G9.6 is more like beta form, to be consistent with our paper and respect whom gave it the name first into the wrombase, we strongly suggest that F42G9.6 should be reverted back as dagl-1.  If you DO find another worm dagl alpha gene, you can just name it dagl only ( or dagl-0).

 

Best wishes,

 

Horng-Dar Wang, Ph.D.

Porfessor and Director

Institute of Biotechnology

Institute of Systems Neuroscience

Department of Life Science

National Tsing Hua University

101, Section 2, Kuang-Fu Road

HsinChu, Taiwan 30013

Phone: +886-3-5742470

Fax: +886-3-5715934

**Comment by draciti** [comment]
Mary Ann, can we close this one?

**Comment by tuli** [comment]
Hi Tim,

This user query is still pending. If you are able to address it soon
it would be good.

Thank you,

Mary Ann

On 29 November 2015 at 23:28, Tim Schedl <ts@genetics.wustl.edu> wrote:
> Hi Horng-Dar,
>
> As indicated in the earlier email, F42G9.6 is more similar to dagl beta than
> to alpha, which was the reasoning for naming it dagl-2.
>
> Tim
>
> ________________________________
> From: "Mary Ann Tuli" <maryann.tuli@wormbase.org>
> To: hdwang@life.nthu.edu.tw
> Cc: help@wormbase.org, "WormBase/website"
> <reply@reply.github.com>,
> "Tim Schedl" <ts@genetics.wustl.edu>
> Sent: Wednesday, November 25, 2015 3:47:35 AM
> Subject: Re: [wormbase-help] Content Correction: F42G9.6 should be named as
> dagl-1 ac... (Horng-Dar Wang)
>
>
> Dear Horng-Dar,
>
> Thank you for writing to WormBase.
>
> F42G9.6 was assigned as dagl-2 following communication between you and
> Tim Schedl in Feb 2014.
>
> This is what he wrote:
> "The new gene class designation:
> “dagl” for “DiAcylGlycerol Lipase homolog”   -------- is approved
>
> The new gene association:
>
> F42G9.6 = dagl-2  [using -2 as F42G9.6 is more similar to dagl(beta)
> than dagl(alpha)]
>
> -------- is approved "
>
> WormBase aims to reflect the literature so we will assign dagl-1 to
> this gene. I have included Tim in this message as he will need to
> decide whether dagl-1 or dagl-2 will be the main name with the other
> one being assigned as an other name.
>
> Tim will contact you soon.
>
> Best wishes,
>
> Mary Ann
>
> ~ Mary Ann Tuli
>
> ~ email: maryann.tuli@wormbase.org
> ~ Database Curator, WormBase
>
> ~ Biology Division
> ~ California Institute of Technology
> ~ 1200 E. California Blvd
> ~ Pasadena, CA 91125
>
>
>
> On 25 November 2015 at 01:13,  <no-reply@wormbase.org> wrote:
>> Content Correction
>>
>>   F42G9.6 should be named as dagl-1 according to our publication in Aging
>> Cell (http://www.ncbi.nlm.nih.gov/pubmed/24889782 ), not dagl-2 on
>> wormbase
>>
>> (http://www.wormbase.org/species/c_elegans/gene/WBGene00018364#0-c9e7b5f8416-10
>> ). Please correct it. Thank you very much!
>> Sincerely, Horng-Dar Wang
>>
>> Submitted From:
>>   support /tools/support
>>
>> This issue has been assigned ticket number: #4393. Follow progress on our
>> issue tracker.
>>
>> Reported by: Horng-Dar Wang (hdwang@life.nthu.edu.tw)
>> 25 Nov 15 01:14
>>
>> Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR
>> 2.0.50727;
>> .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C;
>> .NET4.0E; InfoPath.3; rv:11.0) like Gecko
>>
>> This question was reported via the web interface at wormbase.org. You can
>> also email us directly.
>>
>> --
>> --
>> You received this message because you are subscribed to the "WormBase:
>> help"
>> group.
>> To post to this group, send email to help@wormbase.org
>> To unsubscribe from this group, send email to
>> help+unsubscribe@wormbase.org
>> For more options, visit this group at
>> http://groups.google.com/a/wormbase.org/group/help?hl=en
>>
>
>
>
> --
> Tim Schedl
> WormBase Gene Name/Nomenclature Curator
> Department of Genetics
> Campus Box 8232
> Washington University School of Medicine
> St. Louis MO, 63110
> Caenorhabditis Nomenclature Guidelines:
> http://www.wormbase.org/about/userguide/nomenclature
> WormBase: http://www.wormbase.org/
> Email genenames@wormbase.org



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by tuli** [comment]
Not yet.

On 17 December 2015 at 16:08, draciti <notifications@github.com> wrote:

> Mary Ann, can we close this one?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WormBase/website/issues/4393#issuecomment-165495912>.
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by draciti** [comment]
ok, thanks

**Comment by tuli** [comment]
Hi Horng-Dar, 

WormBase employs the gene name that provides the most useful information on the function of the gene. 
Given that F42G9.6 is being named based on sequence similarity and that it is most similar to dagl beta, it was given the primary name dagl-2, as indicated in the email to you on Friday, February 14 , 2014 2:20:37 PM. 

As indicated in the Nomenclature section on WormBase, gene names approval should be sought prior to submission of manuscripts for publication so that a name is chosen that will be acceptable. It was your choice to give F42G9.6 a name that had not been approved by WormBase. 

Since dagl-1 has been used in the literature, dagl-1 will be listed as Other name so that searches of WormBase for dagl-1 will retrieve the F42G9.6 gene page. 
However, I notice that your paper 
Aging Cell, 2014. Aug 13(4):755-64 
WBPaper00045327 
is not listed on the F42G9.6 gene page, which will be corrected. 

Thank you, 

Tim 



----- Original Message -----

From: "Horng-Dar Wang" <hdwang@life.nthu.edu.tw> 
To: "Tim Schedl" <ts@genetics.wustl.edu>, "Mary Ann Tuli" <maryann.tuli@wormbase.org>, pws@caltech.edu 
Cc: help@wormbase.org, "WormBase/website" <reply@reply.github.com> 
Sent: Sunday, November 29, 2015 11:05:03 PM 
Subject: RE: [wormbase-help] Content Correction: F42G9.6 should be named as dagl-1 ac... (Horng-Dar Wang) 



Dear Tim: 

Though F42G9.6 was later to be found more like dagl beta, after we published our paper in Aging Cell 2014 and the reviewer suggested us to name it dagl-1 in the paper for F42G9.6. That is also why we registered F42G9.6 in the wormbase as dagl-1. Even you later find F42G9.6 is more like beta form, to be consistent with our paper and respect whom gave it the name first into the wrombase , we strongly suggest that F42G9.6 should be reverted back as dagl-1. If you DO find another worm dagl alpha gene, you can just name it dagl only ( or dagl-0). 


Best wishes, 

Horng-Dar Wang, Ph.D. 
Porfessor and Director 
Institute of Biotechnology 
Institute of Systems Neuroscience 
Department of Life Science 
National Tsing Hua University 
101, Section 2, Kuang-Fu Road 
HsinChu, Taiwan 30013 
Phone: +886-3-5742470 
Fax: +886-3-5715934

**Comment by tuli** [comment]
Dear Tim:

 

Thank you very much for the help.  Merry Christmas and Happy New Year!

 

Best wishes,

 

Horng-Dar Wang, Ph.D.

Professor and Director

Institute of Biotechnology

Institute of Systems Neuroscience

Department of Life Science

National Tsing Hua University

101, Section 2, Kuang-Fu Road

HsinChu, Taiwan 30013

Phone: +886-3-5742470

Fax: +886-3-5715934

**Comment by kyook** [comment]
This looks closable now.  Correct me if I'm wrong.
