### ISSUE TITLE
visitor_name (visitor_email): Hello, how do you in...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4406]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_email): Hello, how do you interpret BLAST/BLAT results? thx

**Reported by:** Paul*** (pfon*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/tools/blast_blat/run">http://www.wormbase.org/tools/blast_blat/run</a>
**Browser:** Chrome 46.0.2490.86

**Comment by chris-grove** [comment]
Hi Pauline,

 Could you be a bit more specific? Is there a certain BLAST/BLAT output
that you are having difficulty with?

Generally, the higher the score (in bits) and the lower the E-value (often
expressed as "e-50", for example, where "e-100" is a lower and better
score than "e-50" which is a lower and better score than "e-25", etc.),
the better the match to a known gene, genomic sequence or protein
sequence.

Best,

Chris Grove
WormBase

**Comment by chris-grove** [comment]
Hi Chris,

Thanks for your email. 
Well I blasted the coding sequence of  ugt-22 to see if it would map to something
else in the genome as I have been using ugt-22(Rnai) in my expts. There were indeed
some other hits (with lower scores) and so was wondering what to make of this/ how
to interpret those results. Does that mean that when I do ugt-22 Rnai I am also
knocking down those other hits it because their scores are low I can disregard them?

**Comment by chris-grove** [comment]
Resolved offline
