### ISSUE TITLE
  Dear WormBase team, We were hoping yo...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4432]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Dear WormBase team,<br/>We were hoping you can help us with the issue with apparently switched act-2 alleles, or295 and or261. We thought we mixed up the strains after both came up with the same sequence, but after re-ordering or295 we still had the same problem. Here is what we have figured out:<br/>-the or295 and or261 alleles are switched in the WormBase: based on the paper that described them, or621 should be S14A, tcc to gcc, but it is shown as G15R.  <br/>or295 should be G15R, gga to aga, it comes up as S14A<br/>Link to the paper: 10.1091/mbc.E05-09-0886<br/>- the strain EU1296 should contain or621(S14A), but is actually G15R according to our sequencing<br/>- EU1381 and EU1073 both should have or295, and both indeed are G15R<br/>So at the moment, we have three or295 (G15R) strains. We would like to order a strain with or621(S14A). Based on WormBase this should be EU1295, but we are not certain which of the two mutations it has. <br/>We would appreciate your advise,<br/>Best,<br/>Tali</p>

**Reported by:** Tali*********** (tg44************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36

**Comment by tuli** [comment]
Dear Tali,

Thank you for bringing this discrepancy to our attention.

You are absolutely correct, the molecular lesions were attributed to
the wrong allele.

I have made the following corrections.

or295 is now G16R
or621 is now S15A
nb the amino acid numbering in the paper is one out but I am confident
what we have is now correct.

I am cc'ing my colleague Aric at the CGC who I hope can confirm which
strain you need to order.
It may be that since the alleles were muddled in WormBase, the CGC
updated their records. The mistake was made many years ago so rather
than me speculate I would rather Aric check.

I apologise for this confusion. You will see the update of or295 and
or621 in release WS253 of WormBase.

Best wishes,

Mary Ann

~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by tuli** [comment]
Don't close until Aric has responded

**Comment by tuli** [comment]
Has Aric replied to you yet Mary Ann?  I haven't seen anything through the
group e-mail list.

Karen

On Wed, Dec 16, 2015 at 3:03 AM, Mary Ann Tuli <maryann.tuli@wormbase.org>
wrote:

> Dear Tali,
>
> Thank you for bringing this discrepancy to our attention.
>
> You are absolutely correct, the molecular lesions were attributed to
> the wrong allele.
>
> I have made the following corrections.
>
> or295 is now G16R
> or621 is now S15A
> nb the amino acid numbering in the paper is one out but I am confident
> what we have is now correct.
>
> I am cc'ing my colleague Aric at the CGC who I hope can confirm which
> strain you need to order.
> It may be that since the alleles were muddled in WormBase, the CGC
> updated their records. The mistake was made many years ago so rather
> than me speculate I would rather Aric check.
>
> I apologise for this confusion. You will see the update of or295 and
> or621 in release WS253 of WormBase.
>
> Best wishes,
>
> Mary Ann
>
> ~ Mary Ann Tuli
>
> ~ email: maryann.tuli@wormbase.org
> ~ Database Curator, WormBase
>
> ~ Biology Division
> ~ California Institute of Technology
> ~ 1200 E. California Blvd
> ~ Pasadena, CA 91125
>
> On 15 December 2015 at 18:27,  <no-reply@wormbase.org> wrote:
> > Content Correction
> >
> >   Dear WormBase team,
> > We were hoping you can help us with the issue with apparently switched
> act-2
> > alleles, or295 and or261. We thought we mixed up the strains after both
> came
> > up with the same sequence, but after re-ordering or295 we still had the
> same
> > problem. Here is what we have figured out:
> > -the or295 and or261 alleles are switched in the WormBase: based on the
> > paper that described them, or621 should be S14A, tcc to gcc, but it is
> shown
> > as G15R.
> > or295 should be G15R, gga to aga, it comes up as S14A
> > Link to the paper: 10.1091/mbc.E05-09-0886
> > - the strain EU1296 should contain or621(S14A), but is actually G15R
> > according to our sequencing
> > - EU1381 and EU1073 both should have or295, and both indeed are G15R
> > So at the moment, we have three or295 (G15R) strains. We would like to
> order
> > a strain with or621(S14A). Based on WormBase this should be EU1295, but
> we
> > are not certain which of the two mutations it has.
> > We would appreciate your advise,
> > Best,
> > Tali
> >
> > Submitted From:
> >   support /tools/support
> >
> > This issue has been assigned ticket number: #4432. Follow progress on our
> > issue tracker.
> >
> > Reported by: Tali Gidalevitz (tg443@drexel.edu)
> > 15 Dec 15 18:29
> >
> > Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like
> Gecko)
> > Chrome/46.0.2490.86 Safari/537.36
> >
> > This question was reported via the web interface at wormbase.org. You
> can
> > also email us directly.
> >
> > --
> > --
> > You received this message because you are subscribed to the "WormBase:
> help"
> > group.
> > To post to this group, send email to help@wormbase.org
> > To unsubscribe from this group, send email to
> > help+unsubscribe@wormbase.org
> > For more options, visit this group at
> > http://groups.google.com/a/wormbase.org/group/help?hl=en
> >
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>
>


-- 
~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 626.395.5878
e-mail: kyook@caltech.edu
e-mail: kyook@wormbase.org
skype name: wbkaren

**Comment by tuli** [comment]
Hi Karen,

I do not have anything about the molecular nature of the lesions, and all
the info I have about these strains is in the descriptions on our website.
Sorry, I intended to contact Bruce about this last week but got
sidetracked.  I will check to see if he or his lab can shed some light on
the matter, or if necessary, send stocks of each to them for validation.
I'll let you know what I find out.

Aric

On Tue, Jan 5, 2016 at 6:44 PM, Karen Yook <kyook@wormbase.org> wrote:

> Has Aric replied to you yet Mary Ann?  I haven't seen anything through the
> group e-mail list.
>
> Karen
>
> On Wed, Dec 16, 2015 at 3:03 AM, Mary Ann Tuli <maryann.tuli@wormbase.org>
> wrote:
>
>> Dear Tali,
>>
>> Thank you for bringing this discrepancy to our attention.
>>
>> You are absolutely correct, the molecular lesions were attributed to
>> the wrong allele.
>>
>> I have made the following corrections.
>>
>> or295 is now G16R
>> or621 is now S15A
>> nb the amino acid numbering in the paper is one out but I am confident
>> what we have is now correct.
>>
>> I am cc'ing my colleague Aric at the CGC who I hope can confirm which
>> strain you need to order.
>> It may be that since the alleles were muddled in WormBase, the CGC
>> updated their records. The mistake was made many years ago so rather
>> than me speculate I would rather Aric check.
>>
>> I apologise for this confusion. You will see the update of or295 and
>> or621 in release WS253 of WormBase.
>>
>> Best wishes,
>>
>> Mary Ann
>>
>> ~ Mary Ann Tuli
>>
>> ~ email: maryann.tuli@wormbase.org
>> ~ Database Curator, WormBase
>>
>> ~ Biology Division
>> ~ California Institute of Technology
>> ~ 1200 E. California Blvd
>> ~ Pasadena, CA 91125
>>
>> On 15 December 2015 at 18:27,  <no-reply@wormbase.org> wrote:
>> > Content Correction
>> >
>> >   Dear WormBase team,
>> > We were hoping you can help us with the issue with apparently switched
>> act-2
>> > alleles, or295 and or261. We thought we mixed up the strains after both
>> came
>> > up with the same sequence, but after re-ordering or295 we still had the
>> same
>> > problem. Here is what we have figured out:
>> > -the or295 and or261 alleles are switched in the WormBase: based on the
>> > paper that described them, or621 should be S14A, tcc to gcc, but it is
>> shown
>> > as G15R.
>> > or295 should be G15R, gga to aga, it comes up as S14A
>> > Link to the paper: 10.1091/mbc.E05-09-0886
>> > - the strain EU1296 should contain or621(S14A), but is actually G15R
>> > according to our sequencing
>> > - EU1381 and EU1073 both should have or295, and both indeed are G15R
>> > So at the moment, we have three or295 (G15R) strains. We would like to
>> order
>> > a strain with or621(S14A). Based on WormBase this should be EU1295, but
>> we
>> > are not certain which of the two mutations it has.
>> > We would appreciate your advise,
>> > Best,
>> > Tali
>> >
>> > Submitted From:
>> >   support /tools/support
>> >
>> > This issue has been assigned ticket number: #4432. Follow progress on
>> our
>> > issue tracker.
>> >
>> > Reported by: Tali Gidalevitz (tg443@drexel.edu)
>> > 15 Dec 15 18:29
>> >
>> > Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like
>> Gecko)
>> > Chrome/46.0.2490.86 Safari/537.36
>> >
>> > This question was reported via the web interface at wormbase.org. You
>> can
>> > also email us directly.
>> >
>> > --
>> > --
>> > You received this message because you are subscribed to the "WormBase:
>> help"
>> > group.
>> > To post to this group, send email to help@wormbase.org
>> > To unsubscribe from this group, send email to
>> > help+unsubscribe@wormbase.org
>> > For more options, visit this group at
>> > http://groups.google.com/a/wormbase.org/group/help?hl=en
>> >
>>
>> --
>> --
>> You received this message because you are subscribed to the "WormBase:
>> help" group.
>> To post to this group, send email to help@wormbase.org
>> To unsubscribe from this group, send email to
>> help+unsubscribe@wormbase.org
>> For more options, visit this group at
>> http://groups.google.com/a/wormbase.org/group/help?hl=en
>>
>>
>>
>
>
> --
> ~~~~
> Karen Yook
>
> Curator
> WormBase Caltech
> Tel: 626.395.5878
> e-mail: kyook@caltech.edu
> e-mail: kyook@wormbase.org
> skype name: wbkaren
>



-- 

Aric L. Daul, PhD
Curator, Caenorhabditis Genetics Center
University of Minnesota
Genetics, Cell Biology & Development
6-160 Jackson Hall
321 Church Street SE
Minneapolis MN  55455

phone: 612-625-2265
fax:      612-625-4648
email: daul0006@umn.edu
          cgc@umn.edu

**Comment by tuli** [comment]
Thanks Aric.  Happy New Year!

Karen

On Tue, Jan 5, 2016 at 5:28 PM, Aric Daul <daul0006@umn.edu> wrote:

> Hi Karen,
>
> I do not have anything about the molecular nature of the lesions, and all
> the info I have about these strains is in the descriptions on our website.
> Sorry, I intended to contact Bruce about this last week but got
> sidetracked.  I will check to see if he or his lab can shed some light on
> the matter, or if necessary, send stocks of each to them for validation.
> I'll let you know what I find out.
>
> Aric
>
> On Tue, Jan 5, 2016 at 6:44 PM, Karen Yook <kyook@wormbase.org> wrote:
>
>> Has Aric replied to you yet Mary Ann?  I haven't seen anything through
>> the group e-mail list.
>>
>> Karen
>>
>> On Wed, Dec 16, 2015 at 3:03 AM, Mary Ann Tuli <maryann.tuli@wormbase.org
>> > wrote:
>>
>>> Dear Tali,
>>>
>>> Thank you for bringing this discrepancy to our attention.
>>>
>>> You are absolutely correct, the molecular lesions were attributed to
>>> the wrong allele.
>>>
>>> I have made the following corrections.
>>>
>>> or295 is now G16R
>>> or621 is now S15A
>>> nb the amino acid numbering in the paper is one out but I am confident
>>> what we have is now correct.
>>>
>>> I am cc'ing my colleague Aric at the CGC who I hope can confirm which
>>> strain you need to order.
>>> It may be that since the alleles were muddled in WormBase, the CGC
>>> updated their records. The mistake was made many years ago so rather
>>> than me speculate I would rather Aric check.
>>>
>>> I apologise for this confusion. You will see the update of or295 and
>>> or621 in release WS253 of WormBase.
>>>
>>> Best wishes,
>>>
>>> Mary Ann
>>>
>>> ~ Mary Ann Tuli
>>>
>>> ~ email: maryann.tuli@wormbase.org
>>> ~ Database Curator, WormBase
>>>
>>> ~ Biology Division
>>> ~ California Institute of Technology
>>> ~ 1200 E. California Blvd
>>> ~ Pasadena, CA 91125
>>>
>>> On 15 December 2015 at 18:27,  <no-reply@wormbase.org> wrote:
>>> > Content Correction
>>> >
>>> >   Dear WormBase team,
>>> > We were hoping you can help us with the issue with apparently switched
>>> act-2
>>> > alleles, or295 and or261. We thought we mixed up the strains after
>>> both came
>>> > up with the same sequence, but after re-ordering or295 we still had
>>> the same
>>> > problem. Here is what we have figured out:
>>> > -the or295 and or261 alleles are switched in the WormBase: based on the
>>> > paper that described them, or621 should be S14A, tcc to gcc, but it is
>>> shown
>>> > as G15R.
>>> > or295 should be G15R, gga to aga, it comes up as S14A
>>> > Link to the paper: 10.1091/mbc.E05-09-0886
>>> > - the strain EU1296 should contain or621(S14A), but is actually G15R
>>> > according to our sequencing
>>> > - EU1381 and EU1073 both should have or295, and both indeed are G15R
>>> > So at the moment, we have three or295 (G15R) strains. We would like to
>>> order
>>> > a strain with or621(S14A). Based on WormBase this should be EU1295,
>>> but we
>>> > are not certain which of the two mutations it has.
>>> > We would appreciate your advise,
>>> > Best,
>>> > Tali
>>> >
>>> > Submitted From:
>>> >   support /tools/support
>>> >
>>> > This issue has been assigned ticket number: #4432. Follow progress on
>>> our
>>> > issue tracker.
>>> >
>>> > Reported by: Tali Gidalevitz (tg443@drexel.edu)
>>> > 15 Dec 15 18:29
>>> >
>>> > Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like
>>> Gecko)
>>> > Chrome/46.0.2490.86 Safari/537.36
>>> >
>>> > This question was reported via the web interface at wormbase.org. You
>>> can
>>> > also email us directly.
>>> >
>>> > --
>>> > --
>>> > You received this message because you are subscribed to the "WormBase:
>>> help"
>>> > group.
>>> > To post to this group, send email to help@wormbase.org
>>> > To unsubscribe from this group, send email to
>>> > help+unsubscribe@wormbase.org
>>> > For more options, visit this group at
>>> > http://groups.google.com/a/wormbase.org/group/help?hl=en
>>> >
>>>
>>> --
>>> --
>>> You received this message because you are subscribed to the "WormBase:
>>> help" group.
>>> To post to this group, send email to help@wormbase.org
>>> To unsubscribe from this group, send email to
>>> help+unsubscribe@wormbase.org
>>> For more options, visit this group at
>>> http://groups.google.com/a/wormbase.org/group/help?hl=en
>>>
>>>
>>>
>>
>>
>> --
>> ~~~~
>> Karen Yook
>>
>> Curator
>> WormBase Caltech
>> Tel: 626.395.5878
>> e-mail: kyook@caltech.edu
>> e-mail: kyook@wormbase.org
>> skype name: wbkaren
>>
>
>
>
> --
>
> Aric L. Daul, PhD
> Curator, Caenorhabditis Genetics Center
> University of Minnesota
> Genetics, Cell Biology & Development
> 6-160 Jackson Hall
> 321 Church Street SE
> Minneapolis MN  55455
>
> phone: 612-625-2265
> fax:      612-625-4648
> email: daul0006@umn.edu
>           cgc@umn.edu
>



-- 
~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 626.395.5878
e-mail: kyook@caltech.edu
e-mail: kyook@wormbase.org
skype name: wbkaren

**Comment by tuli** [comment]
Thanks for the reminder @tharris 
I've poked Aric.

**Comment by tuli** [comment]
Hi Karen and Mary Ann,

I received a reply from Bruce regarding the act-2 alleles.  I sent
freshly-thawed stocks of each strain to his lab for analysis, and their
sequencing indicates that the strains are correct.  However, the amino acid
affect by each allele was incorrectly noted in their paper.  I've pasted
his message below.  Since this was initiated throguh WormBase Help, would
you like to pass along this information to Tali, or would you prefer that I
write to her?  Also, I did keep the inquiry anonymous when I wrote to
Bruce, but it sounds as though he would be open to Tali contacting him
directly if she has additional questions.

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

hi Aric.

Sorry it has taken so long to get back to you on this, but the former PhD
student who agreed to clear this up for us had to leave the US for a
conference where he gave a talk and that slowed us down quite a bit (John
Willis, now a senior research associate in another lab here, and who was
first author on that act-2 paper and did the original allele sequencing).

Bottom line is that he has figured out that the nucleotide changes we
reported in that paper (and on WormBase) were correct, but the amino acid
numbers were incorrectly reported! Our bad.

In short, we reported or621 as being S14A, when it is in fact S15A (we
reported the correct NT change, tcc to gcc at NT#43); and we reported or295
as being G15R when it is in fact G16R (reported correct NT change as gga to
aga at NT #46).

So I think this is the source of the confusion. In fact all four of the
strains you sent us do have the correct NT changes as listed above, and
those correspond to the corrected AA changes listed above.

I’m attaching a powerpoint file that summarizes this (we also thawed out
other or621 strains we have and sequenced them, and that data also is
shown).

I am not surprised the other group was confused, even though the strains
were correct (the information on amino acid changes were incorrect). Maybe
you can share this information with the group that was confused and ask
them if this now makes sense?

We need to change the annotation at WormBase to correct the amino acid
changes; perhaps you can advise me on whom to contact to do that?

I also will contact the journal (MBoC) and see if we can get the online
version corrected.

I am very sorry for this confusion. It is entirely our fault.

If you can let me know (i) if this makes sense to you; (ii) if you’ll get
in touch with the other group to see if it clears things up for them, and
(iii) advise me on whom to contact at WormBase, I’d appreciate it.

And of course let me know if you have any questions. Thanks for helping us
fix this very unfortunate mistake on our part.

Bruce


>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>



On Wed, Jan 6, 2016 at 12:20 AM, Karen Yook <kyook@wormbase.org> wrote:

> Thanks Aric.  Happy New Year!
>
> Karen
>
> On Tue, Jan 5, 2016 at 5:28 PM, Aric Daul <daul0006@umn.edu> wrote:
>
>> Hi Karen,
>>
>> I do not have anything about the molecular nature of the lesions, and all
>> the info I have about these strains is in the descriptions on our website.
>> Sorry, I intended to contact Bruce about this last week but got
>> sidetracked.  I will check to see if he or his lab can shed some light on
>> the matter, or if necessary, send stocks of each to them for validation.
>> I'll let you know what I find out.
>>
>> Aric
>>
>> On Tue, Jan 5, 2016 at 6:44 PM, Karen Yook <kyook@wormbase.org> wrote:
>>
>>> Has Aric replied to you yet Mary Ann?  I haven't seen anything through
>>> the group e-mail list.
>>>
>>> Karen
>>>
>>> On Wed, Dec 16, 2015 at 3:03 AM, Mary Ann Tuli <
>>> maryann.tuli@wormbase.org> wrote:
>>>
>>>> Dear Tali,
>>>>
>>>> Thank you for bringing this discrepancy to our attention.
>>>>
>>>> You are absolutely correct, the molecular lesions were attributed to
>>>> the wrong allele.
>>>>
>>>> I have made the following corrections.
>>>>
>>>> or295 is now G16R
>>>> or621 is now S15A
>>>> nb the amino acid numbering in the paper is one out but I am confident
>>>> what we have is now correct.
>>>>
>>>> I am cc'ing my colleague Aric at the CGC who I hope can confirm which
>>>> strain you need to order.
>>>> It may be that since the alleles were muddled in WormBase, the CGC
>>>> updated their records. The mistake was made many years ago so rather
>>>> than me speculate I would rather Aric check.
>>>>
>>>> I apologise for this confusion. You will see the update of or295 and
>>>> or621 in release WS253 of WormBase.
>>>>
>>>> Best wishes,
>>>>
>>>> Mary Ann
>>>>
>>>> ~ Mary Ann Tuli
>>>>
>>>> ~ email: maryann.tuli@wormbase.org
>>>> ~ Database Curator, WormBase
>>>>
>>>> ~ Biology Division
>>>> ~ California Institute of Technology
>>>> ~ 1200 E. California Blvd
>>>> ~ Pasadena, CA 91125
>>>>
>>>> On 15 December 2015 at 18:27,  <no-reply@wormbase.org> wrote:
>>>> > Content Correction
>>>> >
>>>> >   Dear WormBase team,
>>>> > We were hoping you can help us with the issue with apparently
>>>> switched act-2
>>>> > alleles, or295 and or261. We thought we mixed up the strains after
>>>> both came
>>>> > up with the same sequence, but after re-ordering or295 we still had
>>>> the same
>>>> > problem. Here is what we have figured out:
>>>> > -the or295 and or261 alleles are switched in the WormBase: based on
>>>> the
>>>> > paper that described them, or621 should be S14A, tcc to gcc, but it
>>>> is shown
>>>> > as G15R.
>>>> > or295 should be G15R, gga to aga, it comes up as S14A
>>>> > Link to the paper: 10.1091/mbc.E05-09-0886
>>>> > - the strain EU1296 should contain or621(S14A), but is actually G15R
>>>> > according to our sequencing
>>>> > - EU1381 and EU1073 both should have or295, and both indeed are G15R
>>>> > So at the moment, we have three or295 (G15R) strains. We would like
>>>> to order
>>>> > a strain with or621(S14A). Based on WormBase this should be EU1295,
>>>> but we
>>>> > are not certain which of the two mutations it has.
>>>> > We would appreciate your advise,
>>>> > Best,
>>>> > Tali
>>>> >
>>>> > Submitted From:
>>>> >   support /tools/support
>>>> >
>>>> > This issue has been assigned ticket number: #4432. Follow progress on
>>>> our
>>>> > issue tracker.
>>>> >
>>>> > Reported by: Tali Gidalevitz (tg443@drexel.edu)
>>>> > 15 Dec 15 18:29
>>>> >
>>>> > Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like
>>>> Gecko)
>>>> > Chrome/46.0.2490.86 Safari/537.36
>>>> >
>>>> > This question was reported via the web interface at wormbase.org.
>>>> You can
>>>> > also email us directly.
>>>> >
>>>> > --
>>>> > --
>>>> > You received this message because you are subscribed to the
>>>> "WormBase: help"
>>>> > group.
>>>> > To post to this group, send email to help@wormbase.org
>>>> > To unsubscribe from this group, send email to
>>>> > help+unsubscribe@wormbase.org
>>>> > For more options, visit this group at
>>>> > http://groups.google.com/a/wormbase.org/group/help?hl=en
>>>> >
>>>>
>>>> --
>>>> --
>>>> You received this message because you are subscribed to the "WormBase:
>>>> help" group.
>>>> To post to this group, send email to help@wormbase.org
>>>> To unsubscribe from this group, send email to
>>>> help+unsubscribe@wormbase.org
>>>> For more options, visit this group at
>>>> http://groups.google.com/a/wormbase.org/group/help?hl=en
>>>>
>>>>
>>>>
>>>
>>>
>>> --
>>> ~~~~
>>> Karen Yook
>>>
>>> Curator
>>> WormBase Caltech
>>> Tel: 626.395.5878
>>> e-mail: kyook@caltech.edu
>>> e-mail: kyook@wormbase.org
>>> skype name: wbkaren
>>>
>>
>>
>>
>> --
>>
>> Aric L. Daul, PhD
>> Curator, Caenorhabditis Genetics Center
>> University of Minnesota
>> Genetics, Cell Biology & Development
>> 6-160 Jackson Hall
>> 321 Church Street SE
>> Minneapolis MN  55455
>>
>> phone: 612-625-2265
>> fax:      612-625-4648
>> email: daul0006@umn.edu
>>           cgc@umn.edu
>>
>
>
>
> --
> ~~~~
> Karen Yook
>
> Curator
> WormBase Caltech
> Tel: 626.395.5878
> e-mail: kyook@caltech.edu
> e-mail: kyook@wormbase.org
> skype name: wbkaren
>



-- 

Aric L. Daul, PhD
Curator, Caenorhabditis Genetics Center
University of Minnesota
Genetics, Cell Biology & Development
6-160 Jackson Hall
321 Church Street SE
Minneapolis MN  55455

phone: 612-625-2265
fax:      612-625-4648
email: daul0006@umn.edu
          cgc@umn.edu

**Comment by tuli** [comment]
Dear Tali,

It has been a while since these alleles were updated, but I have just
heard from Aric at the CGC who
has been talking to Bruce Bowerman.

As I said in December, the molecular details of the alleles were
updated. These are now available on our development site
http://staging.wormbase.org/species/c_elegans/variation/WBVar00094749
& http://staging.wormbase.org/species/c_elegans/variation/WBVar00094711
nb please note that the development site may be unstable.

Bruce has confirmed that strains EU1295 & EU1296 carry or621 (S15A)
and EU1381 & EU1073 carry or295 (G16R).

I hope if there was still some uncertainty that this now clarifies
things for you.

Best wishes,

Mary Ann


~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
