### ISSUE TITLE
Hello, I'm looking at sfxn-1.1 in C. elegans, and ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4438]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello, I'm looking at sfxn-1.1 in C. elegans, and the WormBase page says it is predicted to have 'ion transmembrane transporter' activity, but I think this should say 'iron', not 'ion'?
Regards, Avril

**Reported by:** Avri********* (alc@************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00007080#0f-9e63bg1-10">http://www.wormbase.org/species/c_elegans/gene/WBGene00007080#0f-9e63bg1-10</a>
**Browser:** Firefox 38.0

**Comment by kyook** [comment]
Hi Avril,

It looks like no one has gotten back to you, please let correct me if I am
wrong.
Since the concise description you pointed out was built using an automated
script, I'm forwarding your message to Ranjana, the curator in charge of
that script.

Thank you for contacting WormBase, and again, apologies for the delay in
getting back to you.

Best wishes,
Karen

On Fri, Dec 18, 2015 at 1:56 AM, <no-reply@wormbase.org> wrote:

> offline chat Hello, I'm looking at sfxn-1.1 in C. elegans, and the
> WormBase page says it is predicted to have 'ion transmembrane transporter'
> activity, but I think this should say 'iron', not 'ion'? Regards, Avril
>
> Submitted From:
>
> http://www.wormbase.org/species/c_elegans/gene/WBGene00007080#0f-9e63bg1-10
> http://www.wormbase.org/species/c_elegans/gene/WBGene00007080#0f-9e63bg1-10
> <http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00007080#0f-9e63bg1-10>
>
> This issue has been assigned ticket number: #4438. Follow progress on our issue
> tracker <https://github.com/WormBase/website/issues/4438>.
>
> Reported by: Avril Coghlan (alc@sanger.ac.uk)
> 18 Dec 15 09:59
>
> This question was reported via the web interface at wormbase.org. You can
> also email us <help@wormbase.org> directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>


-- 
~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 626.395.5878
e-mail: kyook@caltech.edu
e-mail: kyook@wormbase.org
skype name: wbkaren

**Comment by kyook** [comment]
Ranjana has contacted user.
