### ISSUE TITLE
  Hi, I am trying to find the gene (or ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4463]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi,<br/>I am trying to find the gene (or genes) that encodes the Proline tRNA that recognizes the "CCC" codon.  I know previous versions of Wormbase annotation (for example, WS230) used tRNAscan-SE as the source for defining tRNA genes.  However, the currently published versions of the tRNAscans for WS220 show no tRNAs that recognize the CCC codon.  C. elegans clearly uses this codon for Proline, so there must be a tRNA for it.  Can you tell me whether there is now a known Proline tRNA (CCC), and if not, how I might go about identifying it?  (I will soon try to run tRNAscan on the latest genome release, but I'm guessing that's already been done). <br/>Thank you for your help!</p>

**Reported by:** Kris*** (kste*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36

**Comment by Paul-Davis** [comment]
Dear Kristan,

Thank you for contacting us, you are right it does seem very odd that 
there are no tRNAs annotated with the GGG anticodon.
I have run tRNAScan (v1.3.1 and older versions) and can confirm that all 
the GGG anticodon Proline matches must score below the inbuilt filtering 
applied by tRNAScan and are removed. I am going to pursue this further 
as it might be that the prediction model doesn't fit nematodes as well 
as it does for other species.

Some of our core species do have the GGG Proline type but again they are 
quite low scoring and when you compare the GGG type to the other Proline 
tRNAs the score is ~20% lower.

I'll be in touch when I have additional information.

Paul



On 06/01/2016 00:42, no-reply@wormbase.org wrote:
> Feature Request
>
>   Hi,
> I am trying to find the gene (or genes) that encodes the Proline tRNA 
> that recognizes the "CCC" codon. I know previous versions of Wormbase 
> annotation (for example, WS230) used tRNAscan-SE as the source for 
> defining tRNA genes. However, the currently published versions of the 
> tRNAscans for WS220 show no tRNAs that recognize the CCC codon. C. 
> elegans clearly uses this codon for Proline, so there must be a tRNA 
> for it. Can you tell me whether there is now a known Proline tRNA 
> (CCC), and if not, how I might go about identifying it? (I will soon 
> try to run tRNAscan on the latest genome release, but I'm guessing 
> that's already been done).
> Thank you for your help!
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #4463. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/4463>.
>
> Reported by: Kristan (ksteffen@berkeley.edu)
> 06 Jan 16 00:43
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 
> (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>


-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
Dear Kristan,

Looking at Y51A2B.t1 it should definitely be defined as a isoleucine 
tRNA. The annotation was taken directly from the tRNAScan prediction, it 
might be that the match you are seeing is a secondary prediction because 
of similarity and there is a higher scoring isoleucine match in your data.

To check you can take the sequence of the gene:
 >Y51A2B.t1
gtcgcagtggctcaggtgggtagagtaatgactatggggaaataggtccg
gggttcgagcccccgctgatggca

and blast it at the Genomic tRNA database resource

http://lowelab.ucsc.edu/cgi-bin/GtRNAdb-BLAST.cgi

The top matches are for

Caenorhabditis_elegans_chrV.trna113-IleTAT (18373831-18373758) ... 147 2e-36
Caenorhabditis_elegans_chrV.trna113-IleTAT (18374001-18373928) ... 147 2e-36

I really couldn't find a GGG proline in the genome. There are however 9 
very low scoring GGG proline pseudo types that you can see on the 
gtRNAdb website.

http://lowelab.ucsc.edu/GtRNAdb/search.html

I think this all comes down to the "wobble" effect of the 3rd base.

Web definition: According to the genetic code, the cell would need tRNAs 
with 61 different anticodons to complement the available 61 codons. 
However, due to the degeneracy of the genetic code, the third base is 
less discriminatory for the amino acid than the other two bases. This 
third position in the codon is referred to as the wobble position. At 
this position Us and Cs may be read by a G in the anticodon. Similarly, 
As and Gs may be read by a U or y (pseudouridine) in the anticodon.

I have asked for clarification from the Lowe lab about including or 
excluding the Pseudo GGG proline gene from the gene set, but I can say 
with confidence that there isn't a functional Pro GGG missing.

I hope this helps

Paul


On 08/01/2016 21:45, Kristan Steffen wrote:
> Hi Paul,
>
> Thanks for your response.  I went ahead and uploaded the WS250 ncRNAs 
> (c_elegans.PRJNA13758.WS250.ncRNA_transcripts.fa) and ran tRNAScan 
> with the default parameters.  One Proline tRNA for the CCC codon was 
> identified (but with a fairly low score of 20.61) - the transcript was 
> Y51A2B.t1.  Surprisingly, when I searched for this transcript in 
> Wormbase, the description states that it is tRNA-Ile.  Do you know why 
> this was annotated as being an isoleucine tRNA?
>
> Thanks again for your help with this.
>
> Kristan
>
>
>> On Jan 8, 2016, at 7:07 AM, Paul Davis <paul.davis@wormbase.org 
>> <mailto:paul.davis@wormbase.org>> wrote:
>>
>>
>> Dear Kristan,
>>
>> Thank you for contacting us, you are right it does seem very odd that 
>> there are no tRNAs annotated with the GGG anticodon.
>> I have run tRNAScan (v1.3.1 and older versions) and can confirm that 
>> all the GGG anticodon Proline matches must score below the inbuilt 
>> filtering applied by tRNAScan and are removed. I am going to pursue 
>> this further as it might be that the prediction model doesn't fit 
>> nematodes as well as it does for other species.
>>
>> Some of our core species do have the GGG Proline type but again they 
>> are quite low scoring and when you compare the GGG type to the other 
>> Proline tRNAs the score is ~20% lower.
>>
>> I'll be in touch when I have additional information.
>>
>> Paul
>>
>>
>>
>> On 06/01/2016 00:42,no-reply@wormbase.orgwrote:
>>> Feature Request
>>>
>>>   Hi,
>>> I am trying to find the gene (or genes) that encodes the Proline 
>>> tRNA that recognizes the "CCC" codon. I know previous versions of 
>>> Wormbase annotation (for example, WS230) used tRNAscan-SE as the 
>>> source for defining tRNA genes. However, the currently published 
>>> versions of the tRNAscans for WS220 show no tRNAs that recognize the 
>>> CCC codon. C. elegans clearly uses this codon for Proline, so there 
>>> must be a tRNA for it. Can you tell me whether there is now a known 
>>> Proline tRNA (CCC), and if not, how I might go about identifying it? 
>>> (I will soon try to run tRNAscan on the latest genome release, but 
>>> I'm guessing that's already been done).
>>> Thank you for your help!
>>>
>>> Submitted From:
>>>   support/tools/support <http://www.wormbase.org//tools/support>
>>>
>>> This issue has been assigned ticket number: #4463. Follow progress 
>>> on ourissue tracker <https://github.com/WormBase/website/issues/4463>.
>>>
>>>
>>> Reported by: Kristan (ksteffen@berkeley.edu)
>>> 06 Jan 16 00:43
>>>
>>> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 
>>> (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36
>>>
>>> This question was reported via the web interface atwormbase.org 
>>> <http://wormbase.org/>. You can alsoemail us 
>>> <mailto:help@wormbase.org>directly.
>>>
>>> --
>>> --
>>> You received this message because you are subscribed to the 
>>> "WormBase: help" group.
>>> To post to this group, send email tohelp@wormbase.org
>>> To unsubscribe from this group, send email to
>>> help+unsubscribe@wormbase.org
>>> For more options, visit this group at
>>> http://groups.google.com/a/wormbase.org/group/help?hl=en
>>>
>>
>>
>> -- 
>> ===========================================
>> WormBase
>> European Bioinformatics Institute (EMBL-EBI)
>> European Molecular Biology Laboratory
>> Wellcome Trust Genome Campus
>> Hinxton
>> Cambridge CB10 1SD
>> United Kingdom
>> ===========================================
>


-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
