### ISSUE TITLE
  I would like to generate a list of al...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4474]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I would like to generate a list of all the ribosome protein subunits (large and small) and their associated RNAi phenotypes. No clue how to use the new database mining tool, so step-by-step directions would be great. :)</p>

**Reported by:** Step*************** (svon***********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9

**Comment by kyook** [comment]
Hi Stephen,

One of the best ways to get this list of genes is actually through the main
WB site.
In the search box, choose GO term, then search for ribosomal subunit.  This
search will take you to the ribosomal subunit GO term page where you can
browse the ontology annotations for child terms of ribosome, large
ribosomal subunits and small ribosomal subunits. (
http://www.wormbase.org/species/all/go_term/GO:0044391#012--10-1)
The genes annotated to these terms are in the brackets following the term,
click on the bracketed information to get a list of genes.

My colleagues will have to get back to you about the correct WormMine
search.

In the meantime I hope the WB search gives you what you need.

Best wishes,
Karen



On Fri, Jan 8, 2016 at 1:48 PM, <no-reply@wormbase.org> wrote:

> How Do I ...?
>
>   I would like to generate a list of all the ribosome protein subunits
> (large and small) and their associated RNAi phenotypes. No clue how to use
> the new database mining tool, so step-by-step directions would be great. :)
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #4474. Follow progress on our issue
> tracker <https://github.com/WormBase/website/issues/4474>.
>
> Reported by: Stephen Von Stetina (svonstetina@mcb.harvard.edu)
> 08 Jan 16 21:49
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9
> (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9
>
> This question was reported via the web interface at wormbase.org. You can
> also email us <help@wormbase.org> directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>


-- 
~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 626.395.5878
e-mail: kyook@caltech.edu
e-mail: kyook@wormbase.org
skype name: wbkaren

**Comment by chris-grove** [comment]
Hi Stephen,

 WormBase has two gene classes, rpl and rps, for genes encoding ribosomal
proteins of the large and small subunits, respectively. You can review
these gene classes on their respective pages:

http://www.wormbase.org/resources/gene_class/rpl#01--10
http://www.wormbase.org/resources/gene_class/rps#01--10

In C. elegans there are 47 members of the rpl class, and 31 members of the
rps class. The WormMine data mining tool currently does not have RNAi
phenotypes (but will soon), only allele phenotypes. To get these data you
will need to create a WormMine list by uploading the list of 78 genes (I
would recommend uploading the Sequence names, e.g. B0393.1) to WormMine on
the Lists tab. Follow steps to confirm the list of genes and create the
list. Once the list is created you can import the following XML for the
query via the "Import query from XML" link on the QueryBuilder tab:

<query name="" model="genomic" view="Gene.primaryIdentifier Gene.symbol
Gene.secondaryIdentifier Gene.organism.name
Gene.alleles.phenotypesObserved.name
Gene.alleles.phenotypesObserved.identifier Gene.alleles.symbol"
longDescription="" sortOrder="Gene.primaryIdentifier asc">
  <constraint path="Gene" op="IN" value="Gene list for all organisms 8 Jan
2016 14.25"/>
</query>

where you can substitute the "Gene list for all organisms 8 Jan 2016
14.25" list name for the name of your list of ribosomal proteins. Click
"Show results" to get the all allele phenotypes for these genes.

Since WormMine does not have RNAi phenotypes yet, I've performed an AQL
query of the database to retrieve the data you need (attached).

Let us know if you need anything else.

Best,

Chris Grove
WormBase

PS. The reason for the discrepancy in ribsome subunit protein coding genes
listed in the ontology browser, as suggested by my colleague Karen, and
the rpl/rps gene class list is mostly (or entirely) due to the inclusion
of mitochondrial ribosome protein-coding genes (which have their own gene
class).
