### ISSUE TITLE
  I want to know the gene of C.elegent ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4493]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I want to know the gene of C.elegent associated with the reproduction, but I don’t know how to get it .I need your help. thanks for your attention</p>

**Reported by:** Rong****** (8732************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36

**Comment by kyook** [comment]
Hi RongrongLv,

Perhaps the place to start is to look at C. elegans genes annotated with
the Gene Ontology term of Reproduction. You can do that by searching for
"Reproduction" in the search box on the main page after choosing Gene
Ontology from the dropdown list within the search box. You will be taken to
the GO term page Reproduction. You can find the genes annotated with
Reproduction by looking in the Ontology Browser widget.

Otherwise you can retrieve the gene association file that will have all the
genes and their GO term associations from our ftp site
ftp://ftp.wormbase.org/pub/wormbase/releases/current-production-release/ONTOLOGY/gene_association.WS251.wb.c_elegans
  and parse the file yourself for the GO term you are interested in.
Reproduction is GO:0000003.

Hope that helps.
Karen

On Tue, Jan 12, 2016 at 11:16 PM, <no-reply@wormbase.org> wrote:

> How Do I ...?
>
>   I want to know the gene of C.elegent associated with the reproduction,
> but I don’t know how to get it .I need your help. thanks for your attention
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #4493. Follow progress on our issue
> tracker <https://github.com/WormBase/website/issues/4493>.
>
> Reported by: RongrongLv (873263869@qq.com)
> 13 Jan 16 07:17
>
> Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko)
> Chrome/31.0.1650.63 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You can
> also email us <help@wormbase.org> directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>


-- 
~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 626.395.5878
e-mail: kyook@caltech.edu
e-mail: kyook@wormbase.org
skype name: wbkaren
