### ISSUE TITLE
hawaiian strain jbrowse on live

### ISSUE THREAD

**Issue by epaule** [WormBase/website#4494]
the hawaiian JBrowse seems not to work on live:

![screenshot 2016-01-13 at 14 37 53](https://cloud.githubusercontent.com/assets/20523/12297078/4c42eb5e-ba03-11e5-84bd-69612bbeb2c0.png)

**Comment by scottcain** [comment]
That message doesn't affect the operation of JBrowse for Hawiian (ie, you can just click OK and continue to use JBrowse).  The problem is that there were no feature types that get their names indexed for autocompletion in the 251 release; this problem goes away with the 252 release since there are more features.

**Comment by scottcain** [comment]
...But I fixed it for the 251 release anyway; I removed the section of the config where it looks for the name index.
