### ISSUE TITLE
question about a gene sequence...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4501]
*Help Desk query collected when no chat operators were online. Follow up required.*

question about a gene sequence

**Reported by:** hout** (hout********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00021075#043ebg-9fc1-3">http://www.wormbase.org/species/c_elegans/gene/WBGene00021075#043ebg-9fc1-3</a>
**Browser:** Chrome 47.0.2526.106

**Comment by Paul-Davis** [comment]
Dear Houtan,

Please could you provide additional information so that we might help you.

Paul


On 14/01/2016 16:37, no-reply@wormbase.org wrote:
> offline chat question about a gene sequence
>
> Submitted From:
>   http://www.wormbase.org/species/c_elegans/gene/WBGene00021075#043ebg-9fc1-3 
> http://www.wormbase.org/species/c_elegans/gene/WBGene00021075#043ebg-9fc1-3 
> <http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00021075#043ebg-9fc1-3> 
>
>
> This issue has been assigned ticket number: #4501. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/4501>.
>
> Reported by: houtan (houtan.moshiri@gmail.com)
> 14 Jan 16 16:38
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>


-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
