### ISSUE TITLE
Patch for 'Inferred_automatically' evidence problem in Automated_descriptions

### ISSUE THREAD

**Issue by rankishore** [WormBase/website#4520]
The text in the 'Inferred_automatically' evidence tag for all WS252 Automated_descriptions is garbled because of a bug in a Caltech dumping script.
See amx-1 for an example:
http://staging.wormbase.org/species/c_elegans/gene/WBGene00000137#0-9g-3

@sibyl229 is looking into it to see if she can fix at the display level.
But I have the patch file ready if @gw3 or @khowe can patch WS252. Please let me know.
Thanks-Ranjana

**Comment by khowe** [comment]
@rankishore the appropriate thing to do at this stage is to put the patch file here:

ftp://ftp.ebi.ac.uk/pub/databases/wormbase/releases/WS252/acedb/PATCHES/

People installing the database locally (and there may be one or two out there. Somewhere) can then apply it (and other patches in that folder) after unpacking the db. If you send me the patch, I will put it in that folder. 

For what it's worth, I think by far the simplest fix for this problem is for the patch to be applied to the web-site copy of the database. For @tharris, or someone else who knows where the web-site db lives, this is really is just a few seconds work. Investigating/making code changes to accommodate the problem when (a) it's still possible to patch the db and (b) the problem will go away in WS253, just seems like more work than is needed.

**Comment by tharris** [comment]
@khowe I completely agree. I'm not in favor of hacking the display to fix broken data. 

Far better to patch the data at this stage.

**Comment by rankishore** [comment]
Whatever is the best way to fix this at this time is fine with me. @khowe, the patch file was in the e-mail I sent earlier to you, Todd and Sibyl. Will send again.  Thanks all for your help.

**Comment by rankishore** [comment]
From @tharris: Sibyl, I just patched ace on dev.wormbase.org.  Do you want to check that it fixes the problem?

From @khowe : To close the circle, the patch is also now available to users as part of the WS252 distribution:
ftp://ftp.ebi.ac.uk/pub/databases/wormbase/releases/WS252/acedb/PATCHES/concise_dump_WS252corrected.ace.gz

**Comment by tharris** [comment]
(issue is pending updated .ace file from Ranjana. First file didn't resolve the issue)

**Comment by rankishore** [comment]
@tharris @sibyl229, I sent a (second) corrected patch file for this issue, on Feb 8th via e-mail, did it fix the problem? I still see the garbled text in 'Inferred_automatically' tag on staging.  See alh-4 as example:
http://staging.wormbase.org/species/c_elegans/gene/WBGene00000110#0-9g-3
 
Here is the file again.
[automated_descrips_patch_for_WS252.gz](https://github.com/WormBase/website/files/134906/automated_descrips_patch_for_WS252.gz)

**Comment by epaule** [comment]
I put it also onto the EBI-FTP server under PATCHES, just in case someone needs it later.

**Comment by sibyl229** [comment]
Hi @rankishore, @tharris did the patches for the Inferred_automatically tag. I think it looks fine now: http://staging.wormbase.org/species/c_elegans/gene/WBGene00000110#0h-9g-3

**Comment by rankishore** [comment]
@sibyl229 @tharris: Yes, I checked several genes with the 'Inferred_automatically' tag and this issue is fixed now.  Thanks!
@epaule: Thanks for putting it in the PATCHES on the EBI-FTP. 
Closing issue.
