### ISSUE TITLE
hi,
i am working on brugia malayi.i am looking for...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4528]
*Help Desk query collected when no chat operators were online. Follow up required.*

hi,
i am working on brugia malayi.i am looking for its go terms.can you please tell me how to look for it.

**Reported by:** Nami** (numi*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/resources/disease/DOID:0050117#0--10">http://www.wormbase.org/resources/disease/DOID:0050117#0--10</a>
**Browser:** Firefox 41.0

**Comment by janelomax** [comment]
Hi Namita

You can see links to the Gene Ontology terms for Brugia malayi on individual gene pages e.g.:

http://www.wormbase.org/species/b_malayi/gene/WBGene00223921?redirect=1#03e98-b61-3

by clicking on the ‘Gene Ontology’ link in the left menu.

Alternatively, you can download the full GO annotation set for Brugia from this page:

ftp://ftp.wormbase.org/pub/wormbase/releases/WS251/ONTOLOGY/

Hope that helps,

Jane Lomax
WormBase helpdesk


On Jan 26, 2016, at 11:12 AM, <no-reply@wormbase.org> <no-reply@wormbase.org> wrote:

i am working on brugia malayi.i am looking for... (Namita)
Content-type: text/html; charset="utf-8"
Date: Tue, 26 Jan 2016 11:14:03 +0000
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit



                                                                                    <style type="text/css">.fade{font-size:.9em;color:#999}</style>  offline chat hi,
i am working on brugia malayi.i am looking for its go terms.can you please tell me how to look for it.  <p>Submitted From:
<br>&nbsp;&nbsp;http://www.wormbase.org/resources/disease/DOID:0050117#0--10 <a href="http://www.wormbase.org/http://www.wormbase.org/resources/disease/DOID:0050117#0--10">http://www.wormbase.org/resources/disease/DOID:0050117#0--10</a>
</p>

<p>
This issue has been assigned ticket number: #4528. Follow progress on our <a href="https://github.com/WormBase/website/issues/4528">issue tracker</a>.
<p>

<p>
Reported by: Namita (numita.dube@gmail.com) <br />
<span class="fade">26 Jan 16 11:14 </span><br /><br />
<span class="fade"> </span>
</p>

<p class="fade">
This question was reported via the web interface at wormbase.org. You can also <a href="mailto:help@wormbase.org">email us</a> directly.
</p>

-- 
-- 
You received this message because you are subscribed to the "WormBase: help" group.
To post to this group, send email to help@wormbase.org
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en




-- The Wellcome Trust Sanger Institute is operated by Genome Research Limited, a charity registered in England with number 1021457 and a company registered in England with number 2742969, whose registered office is 215 Euston Road, London, NW1 2BE. 
-- 
-- 
You received this message because you are subscribed to the "WormBase: help" group.
To post to this group, send email to help@wormbase.org
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en
