### ISSUE TITLE
JBrowse links not working

### ISSUE THREAD

**Issue by janelomax** [WormBase/website#4529]
Hi

The links to JBrowse don't seem to be working in the current release, getting this error:

Not Found

The requested URL /tools/genome/jbrowse/full.html was not found on this server.

Apache/2.2.22 (Debian) Server at www.wormbase.org Port 8000

Example genes I looked at were:

https://www.wormbase.org/species/c_elegans/gene/WBGene00001803#03e982-b61-3
https://www.wormbase.org/species/c_elegans/gene/WBGene00001133#03e98-b61-3

cheers

Jane

**Comment by scottcain** [comment]
Hi @janelomax thanks for pointing that out. @sibyl229 can you take a look at the code to see if it's using port 8000?  It shouldn't be; it should just be using port 80. Thanks.

**Comment by scottcain** [comment]
@janelomax @sibyl229 Actually I fixed it--I think it's probably due to a misconfiguration of apache on the GBrowse server, but I just added a file structure that mimicked the url structure (ie, /tools/genome/jbrowse) and it works now.  It's not clear to me why jbrowse works from the nav menu but didn't in the object page, but that is a problem for another day.
