### ISSUE TITLE
i need help finding the number of nucleotides in a...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4530]
*Help Desk query collected when no chat operators were online. Follow up required.*

i need help finding the number of nucleotides in a gene on your site

**Reported by:** samm* (samm*********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00004194#06-93-3-63">http://www.wormbase.org/species/c_elegans/gene/WBGene00004194#06-93-3-63</a>
**Browser:** Chrome 47.0.2526.111

**Comment by tuli** [comment]
Dear Sammy,

In addition to Chris's suggestion, in order to find the length of the
actual gene you can look at the Genomic Position within the Location
widget and with a little bit of maths you can see that the gene is
1944bp.

Best wishes,

Mary Ann


~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
