### ISSUE TITLE
  how to find a region upstream of a ge...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4534]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;how to find a region upstream of a gene coding sequence?</p>

**Reported by:** anur********** (anur************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36

**Comment by janelomax** [comment]
Dear Anuradha Singh

Thank you for contacting WormBase.

Is it the UTR sequence you need? If so go to the transcript or CDS page for the gene you are interested in and you can download the gene sequence + UTR from the Sequences widget.

Otherwise you can export sequences from the GBrowse view. Go to the gene page, then select ‘Location’ from the menu on the left and click on the browser view e.g.

http://www.wormbase.org/tools/genome/gbrowse/c_elegans_PRJNA13758/?name=III%3A9135934..9142116

Select the region of sequence along the scale of the bottom panel. A menu will pop-up, choose ‘Dump this selection as FASTA’

Let us know if you have any other questions.


Dr Jane Lomax
Senior Bioinformatician, WormBase
Parasite Genomics Group
Wellcome Trust Sanger Institute
Genome Campus, Hinxton,
Cambridge, CB10 1SA, UK


On Jan 28, 2016, at 7:39 AM, WormBase Helpdesk <notifications@github.com> wrote:

> Submitted from the feedback form on the WormBase website.
> 
>   how to find a region upstream of a gene coding sequence?
> 
> Reported by: anur********** (anur*********************)
> *Submitted from: /tools/support
> Browser: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36
> 
> —
> Reply to this email directly or view it on GitHub.
> 




-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.
