### ISSUE TITLE
Phenotype Graph should be suppressed if there are ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4536]
*Help Desk query collected when no chat operators were online. Follow up required.*

Phenotype Graph should be suppressed if there are  no phenotype annotations

**Reported by:** Raym*** (raym****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00020580#0-bc-10">http://www.wormbase.org/species/c_elegans/gene/WBGene00020580#0-bc-10</a>
**Browser:** Firefox 43.0

**Comment by azurebrd** [comment]
@raymond91125  I'm not sure what you mean, I see the widget open with no graph in there.  Are you saying that you don't want the widget to show up at all ?  I think that has to do with the #0-bc-10 stuff, which probably has to do with your settings for opening the gene page.

**Comment by raymond91125** [comment]
i mean suppressing the graph border and legend so that not a large space is taken for no graph. even better if a sensible text is in place, like "No phenotype data.".

**Comment by azurebrd** [comment]
Ok, it's changed on juancarlos.wormbase   If the annotSummaryJsonp query doesn't have any elements.nodes it replaces the widget data with 'No phenotype data', otherwise it generates the graph.  We don't know if it's empty until the query comes back, so everything else still shows.  We could hide it by default and only show it after the query comes back.  I would expect that most have data, so it would be more jarring to suddenly show it.

**Comment by chris-grove** [comment]
@raymond91125 @azurebrd 
Small point: maybe have it say "no observed phenotypes" instead of "no phenotype data", since there may be not observed phenotypes

**Comment by azurebrd** [comment]
@chris-grove @raymond91125 Done.

**Comment by chris-grove** [comment]
@azurebrd  Cool, looks good. @raymond91125  I think we can close this?

**Comment by raymond91125** [comment]
yes, looks good. @azurebrd, do you need to make a pull request?

**Comment by azurebrd** [comment]
@raymond91125 @chris-grove Sure thing, pull request in.
