### ISSUE TITLE
FPKM expression control statistics Table

### ISSUE THREAD

**Issue by gw3** [WormBase/website#4540]
In the Expression widget for Genes there is a table titled "FPKM expression control statistics".

It has an error in the names displayed for the "Life stages" column.
It has "all stages Ce" repeated twice. One of these should be "Total".
For example, in 
http://staging.wormbase.org/species/c_elegans/gene/WBGene00020283#1--10
The row with median and mean values of 1.598 and 10.2036 should be displayed as "Total" not "all stages Ce" - these values are from the entries in the ACeDB database with Analysis objects "RNASeq.elegans.total_over_all_stages.control_median" and "RNASeq.elegans.total_over_all_stages.control_mean".

Thanks.

**Comment by janelomax** [comment]
"all stages Ce" is also showing up for Onchocerca which is clearly not right, one of our collaborators is complaining. Can we fix asap please? Thanks.

**Comment by sibyl229** [comment]
Hi @gw3 @janelomax the life stage is showing "total over all stages". The issue happens because the data is structured like this: 
`RNASeq_FPKM -> WBls:0000002 -> 10.1294 -> RNASeq.elegans.total_over_all_stages.control_mean`

```
RNASeq_FPKM	?Life_stage	Float	#Evidence
``` 

For now, I extract the life stage from the Analysis string as oppose to use the `RNASeq_FPKM	?Life_stage` tag. Though I think it would probably makes more sense to move the RNASeq.elegans.total_over_all_stages.control_mean to its own life stage instead of attaching it to WBls:0000002. What do you think?

**Comment by janelomax** [comment]
I don't think that 'all stages' is a meaningful life-stage for the ontology. It's more an analysis than a life-stage.

I notice that on staging it currently just says "total over all stages" without a link to an ontology term. I think this solution is good.

**Comment by sibyl229** [comment]
@janelomax I understand now. Thanks! Closing
