### ISSUE TITLE
  Hello http://www.wormbase.org/species...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4554]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello<br/>http://www.wormbase.org/species/c_elegans/variation/WBVar00091846#02-45-3<br/>There is a discrepancy for the gene linked to ok560. It is given in RB778 as F32E10.7(ok560) IV., but F32E10.7 is dead.</p>

**Reported by:** Jona************* (ewba*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:44.0) Gecko/20100101 Firefox/44.0

**Comment by tuli** [comment]
Dear Jonathan,

Thank you for bringing this error to our attention.

It appears that the genotype of RB778 was not updated when F32E10.7
was merged into tag-80 (F45E4.3). I have made the update now which
will be available in release WS253 of WormBase.

I have also cc'ed Aric at the CGC so that their records can be updated as well.

Best wishes,

Mary Ann

~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
