### ISSUE TITLE
  Hello,  I have RNA-seq datasets from ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4597]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello, <br/>I have RNA-seq datasets from C. elegans and I would like to align them to the WS245 version of the reference genome using STAR. STAR requires as input the genomic fasta sequence, which I have successfully downloaded from the ftp site.  STAR also requires an annotation file, preferably in GTF format.  However, I have only been able to locate annotations on the ftp site in the GFF2 and GFF3 file format. Is the GTF file format available, and if so, where can I download it? Thank you so much for your help! <br/>Sincerely,<br/>Stephanie</p>

**Reported by:** Step************** (smpy****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36

**Comment by gw3** [comment]
Stephanie,

STAR does NOT require a GTF file.
If one is provided, it will use it in an initial alignment step that 
only aligns against the indicated transcript sequences and then any 
unmapped reads are aligned against the genome.
This provides faster and more accurate alignments if the GTF annotation 
is 100% accuarate.

We do not use a GTF file for STAR alignment in WormBase because we use 
the RNASeq alignments to help in manual annotation to improve the gene 
models and using alignments based on (possibly inaccurate) gene models 
would lead us into Aristotle's circular reasoning logical fallacy.
By all means use a GTF of WormBase gene models as the vast majority of 
C. elegans gene models are correct. :-)

Its pretty easy to make a GTF file from the GFF2 files.
It is the same format as GFF2 and you just pull out the transcript span 
and exon lines for coding genes, all the types of non-coding genes and 
pseudogenes.

Here is one I prepared earlier using release WS252 (this has not been 
tested with STAR, but should work):
ftp://ftp.sanger.ac.uk/pub/wormbase/STAFF/gw3/transcripts.gtf
NB. I am using the abbreviated names of the chromosomes in this file 
('I', instead of 'CHROMOSOME_I'). The chromosome names in the GTF file 
must match those in the fasta genomic sequence file.

Gary Williams

**Comment by gw3** [comment]
Hi Gary,

Thank you so much for your reply and the detailed explanation on using STAR
for alignments. I really appreciate it!

As you pointed out, given that the vast majority of C. elegans gene models
are indeed correct, I would like to load the recommended GTF file for
alignments with STAR as you suggest.

I've spent some time searching online trying to figure out the best way to
pull out the transcript span and exon lines for coding genes, and all the
types for non-coding genes and pseudogenes from the gff file as you suggest
to make a gtf formatted file, but it seems better to get your expert
opinion. One of the options I've tracked down seems to be gffutils which is
a python package. Do you have any other, perhaps more biologist/amateur
bioinformaticist-friendly options? Obviously the large size of the file
means I can't readily manipulate it in text edit or excel. Another option
was to try and build a wormmine query, but I'm certainly open to other
ideas! Do you have a favorite way to manipulate these types of files and
pull out the fields you need?

Thank you also for sending me your link to the WS252 annotation gtf file.
Am I correct in thinking that the WS252 is just an updated annotation that
is still based on the WBcel235 genome build? I will also be working with
ChIP-seq files, so I just want to ensure that everything is aligned to the
same genome sequence build.

And while we're at it, is there anything else that you think I'm missing
that I should be aware of? Questions I should have asked you instead? Thank
you so much for your help, Gary! I truly appreciate the help!

All the best,
Stephanie

**Comment by khowe** [comment]
@gw3: we will start producing a GTF file (containing the canonical gene set in GTF format) from WS253.
