### ISSUE TITLE
images not displaying

### ISSUE THREAD

**Issue by draciti** [WormBase/website#4671]
Images are not displayed

http://www.wormbase.org/species/all/expr_pattern/Expr1149515#0213--10
http://www.wormbase.org/species/all/expr_pattern/Expr1143118#0213--10

they all relate to the same study, WBPaper00046121
thanks

**Comment by sibyl229** [comment]
Hi @draciti I confirmed the problem on staging site, and I couldn't find any images for WBPaper00046121 on the file system of the dev server, where they are supposed to be. Do you know if these images are submitted? If so, I will ask Todd if he saw them somewhere. Thanks

**Comment by draciti** [comment]
Thanks Sibyl, the images should be in WBPerson4037 folder but I just double checked on Canopus and for some reason the script did not transfer them to the OICR folder. I'll look into it with Juancarlos and keep you posted

**Comment by sibyl229** [comment]
@draciti I see. The code is expecting the pictures to be in the `WBPaper00046121` directory. Could you explain when should it look for pictures in directories by person?

**Comment by draciti** [comment]
if the pictures are contributed by persons (large scale), they are stored in WBPerson folders. This is because the acknowledgment differs if paper vs person
Examples:
http://www.wormbase.org/species/all/expr_pattern/Expr9817#012--10
http://www.wormbase.org/img-static/pictures/WBPerson266/2dmdTranAemb.jpg

http://www.wormbase.org/species/all/expr_pattern/Expr1016862#01--10
http://www.wormbase.org/img-static/pictures/WBPerson4037/WBGene00001170.jpg

I think the original code written by Adrian -2010/2011- should take that into account, but we could revise that if need be. We have added a lot since then
we can Skype if you prefer

**Comment by sibyl229** [comment]
Hi @draciti I think two problems together caused the problem of the broken image:
- the link was pointing to the wrong directory. I will fix this to determine the directory based on the Acknowledgement ->Template content. Could you confirm the image for http://www.wormbase.org/species/all/expr_pattern/Expr1143128#0123--10 should be found at http://www.wormbase.org/img-static/pictures/WBPerson4037/Hashimshony_WBGene00015146_200.jpg

- the other problem is that the image doesn't exist there yet. If that path is correct, we will work with Juancarlos and/or Todd to get the image.

**Comment by sibyl229** [comment]
And @draciti another question: if the images weren't sync'ed to the staging server, do you know how many of them have this problem?

**Comment by draciti** [comment]
thanks Sibyl. I confirm that the path is correct. The images are now in the directory they are supposed to be on Canopus. 
The number of images affected is >20,000. it was a batch. They were not transferred by a script but we fixed that. thanks

**Comment by draciti** [comment]
for your reference the pictures on Canopus are in this folder:
/home/daniela/OICR/Pictures

**Comment by draciti** [comment]
Hi sibyl, just checking in on this issue
thanks
d

**Comment by sibyl229** [comment]
Hi @draciti looks like the pictures and code changes are in place, could you test this? Thanks!

**Comment by draciti** [comment]
it works great! thanks Sibyl

**Comment by draciti** [comment]
sibyl, I am reopening this ticket, could it be that with the change that Todd did yesterday, other images are now not displaying correctly?

http://www.wormbase.org/species/all/expr_pattern/Expr9817#012--10
http://www.wormbase.org/species/c_elegans/expr_pattern/Expr12292#012--10

**Comment by sibyl229** [comment]
Hi Daniela,

Actually there are two issues causing the image to be missing. One is the image file not getting synced, which will appear as a broken image.
The other issue is caused by web code, which the two examples you show above are caused by (http://www.wormbase.org/species/all/expr_pattern/Expr9817#012--10 <http://www.wormbase.org/species/all/expr_pattern/Expr9817#012--10>http://www.wormbase.org/species/c_elegans/expr_pattern/Expr12292#012--10 <http://www.wormbase.org/species/c_elegans/expr_pattern/Expr12292#012--10>), which appear as "No curated images available.". 

Both issues have been fixed on staging. Todd may have fixed the broken image problem on production, but the web code problem hasn’t been fixed on production yet. We are preparing for a web release very soon, probably by end of next week. By then a copy of the staging site will become the production, and the issues with production site will be fixed. Please take a look at the staging site and let me if there is any issue still.

Thanks,

Sibyl

**Comment by draciti** [comment]
Everything works well on staging
thanks Sibyl!
