### ISSUE TITLE
  WormMine WS250 seems to report a lot ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4692]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;WormMine WS250 seems to report a lot of incorrect data along with correct responses to queries in some instances.<br/>I used WormMine to retrieve the allele gk1 and display its name along with strain names associated with that allele.  The query overview was:<br/>Allele<br/>Public Name<br/>= gk1<br/>Gene Gene<br/>Strains Strain Collection<br/>WormBase ID<br/>According to data in WormBase (which I know to be correct), gk1 is carried by the strains DM5116 and VC2.  Both are in the WormBase data set, although VC2 does not have much information.  The query results page lists gk1 multiple times (15) for different strains.  DM5116 is there, VC2 is not, and all the others do not have anything to do with gk1.  The strains listed incorrectly as carrying gk1 were DM1208, DM3004, DM3006, DM3007, DM3009, DM3010, DM3011, DM3012, DM5113, DM5115, RW3570, RW3609, VC100 and VC54.<br/>Earlier today I had another sort of reverse example where a VC strain carrying a simple deletion allele was incorrectly listed as carrying a whole pile of Hawaiian SNPS.  </p>

**Reported by:** Mark******* (edgl**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; InfoPath.3; .NET4.0C; .NET4.0E; rv:11.0) like Gecko

**Comment by chris-grove** [comment]
Hi Mark,

 Unfortunately, this query isn't going to work in WormMine right now, as the strain-to-variation connections are not imported. What's happening, in the case of gk1, is that it's looking at the gene associated with gk1 (unc-112) and returning all strains that "carry" that gene, or in this case, any allele of that gene. This is because only strain-to-gene connections have been imported.

With the VC strain and Hawaiian SNPs, it was probably the same issue: the query was looking at which gene was associated with the VC strain, and then looking up all alleles associated with that gene (not the strain).

Apologies. I'm working out the AQL examples you asked for and should get back to you on that soon.

Chris

**Comment by chris-grove** [comment]
Here's a use case for loading strain-variation connections into WormMine

**Comment by tuli** [comment]
I hadn't realised that strain-variation data was not imported for any reason other than it just hadn't been done yet.
