### ISSUE TITLE
  blast is not working for several days...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4695]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;blast is not working for several days. Today is Friday 25th March. </p><p>What were you doing? <br />&nbsp;&nbsp;Blast</p>

**Reported by:** Mike (cell***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36

**Comment by raymond91125** [comment]
Hi Mkie,

I just tested blast using the sample sequence successfully. Could you 
give it another go and if you encounter problems still please give us 
details about your query so that we can better troubleshoot?

Thanks.

Raymond

On 03/25/2016 07:13 AM, no-reply@wormbase.org wrote:
> Question:
>
>   blast is not working for several days. Today is Friday 25th March.
>
> What were you doing?
>   Blast
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #4695. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/4695>.
>
> Reported by: Mike (celltimer@gmail.com)
> 25 Mar 16 14:13
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 
> (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google 
> Groups "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by tharris** [comment]
Resolved and user contacted.
