### ISSUE TITLE
  There is a wrong automatic annotation...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4698]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;There is a wrong automatic annotation taht has been added to nipi-4. It is not an orthologue of human PTK2B (protein tyrosine kinase 2 beta) and PTK2 (protein tyrosine kinase 2); but a nematode specific "pseudo" kinase see labed et all 2012 "The Caenorhabditis proteins, from elegans, briggsae,<br/>brenneri, japonica and remanei species, are predicted to be kinase dead,<br/>since they lack the essential aspartic acid active site residue.<br/>In contrast, predicted NIPI-4 orthologs from non-Caenorhabditis<br/>species like Ascaris suum and Pristionchus pacificus are expected to be<br/>functional kinases. Conversely, only the Caenorhabditis proteins<br/>have a tyrosine in the predicted activation loop that could<br/>potentially be the target of phosphorylation"<br/>Thanks</p>

**Reported by:** pujo********** (pujo******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586

**Comment by epaule** [comment]
we added that bit to the description, since Panther version 9 predicted them.
I will update the Panther orthology predictions to version 10, as it will improve at least the nipi-4 data. That will be part of the WS254 release.

And I forgot to advertise our new form for people to improve our gene description (it is in the community curation section):
http://www.wormbase.org/about/userguide/submit_data
