### ISSUE TITLE
  how do I download for sequence promot...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4706]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;how do I download for sequence promote (2K) in one gene?<br/>what is 504 Gateway Time-out?</p>

**Reported by:** caro***** (caro************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36

**Comment by azurebrd** [comment]
Could you tell us what page you are on, and what you're trying to do ?

Thank you,
Juancarlos, taking over Help Desk

> March 30th, 2016
>
> how do I download for sequence promote (2K) in one gene?
> what is 504 Gateway Time-out?

**Comment by Paul-Davis** [comment]
I will answer this, was in the middle of trying to get a solution sorted.. @azurebrd isn't it ridiculously early for you?

**Comment by Paul-Davis** [comment]
Dear Carolaing,

Sorry for the delay in replying to you, but you can download the 2kb of 
upstream sequence of a given gene by following these steps.

  * Go to the gene summary page for your gene
  * Click on Location on the left menu
  * In here you should see a gbrowse link with chromosome and
    co-ordinates, click this
  * This takes you to the genome browser and you should see the
    structure of your gene on the genome
  * Navigate so that you have the 1st exon of your gene just visible
    with the 2kb of sequence you want
  * Now click and drag a box on the scale bar that covers the region you
    want
  * You should get a pop-up menu when you let go with a " Dump selection
    as FASTA" option
  * Select this and the sequence is displayed in a new tab.

Here is a screencast demonstration: 
https://app.box.com/s/2yfnqu0ejyk14ibba94f4grydtm522ad

I hope this helps

Paul




On 31/03/2016 00:06, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   how do I download for sequence promote (2K) in one gene?
> what is 504 Gateway Time-out?
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #4706. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/4706>.
>
> Reported by: carolaing (carolaing.gabaldon@gmail.com)
> 30 Mar 16 23:07
>
> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, 
> like Gecko) Chrome/49.0.2623.87 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>


-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by azurebrd** [comment]
Thanks @Paul-Davis I've been really tired recently, got a long nap, now I'm up in the middle of the night =P I'll hopefully get some reasonable amount of sleep soon =)

**Comment by draciti** [comment]
Quick note: Michael Zhang, sitting 2 floors up from where I sit, used to maintain the C elegans promoter database. Not active at present
https://cb.utdallas.edu/cgi-bin/CEPDB/home.cgi?process=GetProms
Seems the interface to locate promoters is user friendly. Shall I poke him to ask for a resurrection?

**Comment by chris-grove** [comment]
@draciti   Something like that (UT Dallas) tool (pretty much the same, I think) can be done using ParaSite BioMart. You can't specify how many nucleotides into the gene you want, but you can specify any number of nucelotides upstream (or downstream) of a list of genes.

**Comment by draciti** [comment]
thanks Chris, I now recall you redirected users to the BioMart tool in the past

**Comment by chris-grove** [comment]
There's also a tool at this site:
http://www.rsat.eu/
which allows you to exclude upstream open reading frames, so that your promoter sequence doesn't overlap with an upstream gene. It's quite nice.
