### ISSUE TITLE
  searching sequence in genome browser ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4728]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;searching sequence in genome browser gives internal error</p><p>What were you doing? <br />&nbsp;&nbsp;see above</p>

**Reported by:** Juli********** (ja21***********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36

**Comment by scottcain** [comment]
I sent this response:

Hi Julie,

Unfortunately, that functionality has been broken in GBrowse for some time.  JBrowse 

http://www.wormbase.org/tools/genome/jbrowse/full.html?data=data/c_elegans_PRJNA13758

has similar functionality, though it isn't the same.  If you click on the "File" menu in JBrowse (that is, not the web browser's file menu), you can select "Add sequence search track" where you can enter nucleotide or amino acid sequences (where it searches the translated DNA sequence) and it will show where those sequences are in the currently viewed region (as opposed to GBrowse, which would give you a list of places where the sequence occurs).  The JBrowse search is nice in that it allows you to enter regular expressions so that you can search for "fuzy" sequences, like "ATG[AC]" would mean to look for ATG plus an A or a C.

Please let us know if you need any further assistance.
Scott
