### ISSUE TITLE
  Hi, I wonder if I can get the longest...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4731]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, I wonder if I can get the longest isoform for a long list with gene names.</p>

**Reported by:** Joyc* (qzha***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36

**Comment by chris-grove** [comment]
I'm pointing her to WormMine to get a table of transcripts and their lengths for a list of genes, which she will have to manually filter for the longest transcript. If anyone has a better method, please let me/her know.

**Comment by chris-grove** [comment]
Hi Zhaozhao,

I don't have a way to automatically get you the longest isoform, but we can use WormMine to create a table of all transcripts and their lengths for a gene or list of genes. WormMine is back up now, so I'll explain using that:

http://intermine.wormbase.org/tools/wormmine/begin.do

First, create a list of genes by going to the "Lists" tab of WormMine and pasting your list of genes into the blank field provided. The list type and organisms should be "Gene" and "C. elegans" by default, respectively. Then click on "Create List". The next screen will ask you to confirm the list of genes. Because of some duplicate "ghost" gene objects it may ask you to disambiguate some genes. Just click "Add" for each gene entry that has a WBGene ID. Then click on "Save a list of <number> Genes". This should show you a table of your gene list. Next, go to the "QueryBuilder" tab and click on "Import query from XML" and paste in the following XML code into the field provided:
 
`<query name="" model="genomic" view="Gene.primaryIdentifier Gene.symbol Gene.secondaryIdentifier Gene.organism.name Gene.transcripts.length Gene.transcripts.symbol" longDescription="" sortOrder="Gene.transcripts.length desc">
</query>`

then click "Submit". This will take you to a query builder overview page. Click on "CONSTRAIN" to the right of "WormBase Gene ID". The "Constrain" dialog box will open allowing you to specify a gene or a list of genes. Click on the checkbox to the left of "Contained in list:" and then choose your list in the following drop down menu. Then click "Add to query".

Now you can click on "Show results" and you will get the table of your genes including all isoforms and their respective lengths. You can download the results by clicking on the "Download" button at the upper right corner of the table and selecting a file type. At that point you'll need to manually go through the list to find the longest isoforms, unless you can write a script to do that.

I hope that helps.

Chris

**Comment by chris-grove** [comment]
User is happy
