### ISSUE TITLE
GBrowse rubber banding menu options don't all work or have problems.

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/website#4741]
When you select a region in the gbrowse you are given various options

* Zoom in - Works (or appears to?)
* Dump selection as FASTA - Works with an offset of ~10% (think there is a known issue with our version of gbrowse?)
* Browse selection at modENCODE - gateway time out
* Browse selection at UCSC - Works
* BLAT this sequence - Creates a new tab with the current view? circular redirect with no blat?
* BLAST this sequence - Creates a new tab with the current view? circular redirect with no blast?

**Comment by scottcain** [comment]
Hi @Paul-Davis Thanks for this report.  The modencode issue seems to be due to modencode changing their url; that should be easy to fix.  I think the fasta problem is related to a few other reported bugs with GBrowse and will be difficult to fix.  I have no idea what's going on with blat/blast but will look into it.

**Comment by scottcain** [comment]
The modENCODE link has been fixed on staging.  Looking at blat/blast now.

**Comment by scottcain** [comment]
Does anyone know/remember when or if the blat and blast options worked from the GBrowse dropdown? @tharris ?

**Comment by scottcain** [comment]
Fixed and working on staging; code committed and a pull request issued.
