### ISSUE TITLE
Display of entity-quality pairs in phenotype widget, 4-19-2016

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#4756]
Extension of issue #4221

@sibyl229 
After receiving some feedback, I'd like to revisit the display of entities affected in the Phenotype widget display. Currently we have this type of display:

http://www.wormbase.org/species/c_elegans/gene/WBGene00003239#c--10

![screen shot 2016-04-19 at 11 19 27 am](https://cloud.githubusercontent.com/assets/611382/14650433/9e6d9712-0620-11e6-87ac-3e6898fdb06a.png)

It seems clear now that the preferred display would be to have all of the "Entity" data displayed in its own separate column, which could have the header "Entities Affected" and then display the ontology type for each entity-quality pair. So in the example for "mig-2" above, there would be a new column between "Phenotype" and "Supporting Evidence" that displays for the allele mu28 and phenotype "axon guidance variant" the entry "Anatomy: PDE, abnormal" and likewise for RNAi 65139 and phenotype "cell migration variant" it would display "Life Stage: L2 larva Ce, abnormal". For any annotations that refer to a GO term it could display as, for example, "GO Term: development, abnormal".

**Comment by sibyl229** [comment]
Hi @chris-grove the "Entities affected" column is added for Phenotype table and Phenotype_not_observed table on the gene page: http://staging.wormbase.org/species/c_elegans/gene/WBGene00003239#0c--10

The problem with the supposedly hidden column (_Phenotype) showing up should be fixed now. I was baffled by it for a long time. I think it's caused by a typo in Overexpression table, making the javascript table code confused about which table is which. I haven't seen the problem again. Please let me know if you encounter it again. Thanks!

**Comment by chris-grove** [comment]
Looks great! Thanks @sibyl229 !!
