### ISSUE TITLE
  How do I become a member?  I tried on...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4770]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How do I become a member?  I tried on the home page where it says Login or become a member, it doesn't let me become a member - just says login incorrect</p>

**Reported by:** Edwa********** (edwa***********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36

**Comment by ceciliaWBPerson1** [comment]
Hi Edward,

Sorry about the difficulty. We are trying to move away from using password
login, so the account registration form is turn off on the website. We
encourage new users to get an account by ‘Login with Google’. This way your
WormBase account is associated with a more permanent email address (instead of
institution specific ones). And it’s also easier for us to manage user
accounts. 

We only use Google for account authentication: we only get your name and email
address from Google, and we are not sharing your browsing activity with them.
Does this work for you? Please let me if you have any concern, and we can work
out an alternative solution.

Best,

Sibyl
web dev
