### ISSUE TITLE
  Hi. I am trying to download a databas...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4783]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi. I am trying to download a database of all known protein-protein interactions for proteins in worms (C. elegans). Is this available on wormbase?</p>

**Reported by:** Ed H***** (edwa********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64; rv:46.0) Gecko/20100101 Firefox/46.0

**Comment by chris-grove** [comment]
Hi Ed,

 I'm attaching an Excel spreadsheet with all of the protein-protein interactions that we currently have annotated in WormBase. Note that this does not cover all known protein-protein interactions, as we have not been able to annotate all of them from the literature. This set does include a large scale yeast-two-hybrid dataset originally published in 2004 and updated more recently.


Since the spreadsheet refers to genes by their respective WormBase gene IDs, I'm also attaching a file that lists the IDs, sequence names, and public names for all genes in the database, so that you may map whichever name you prefer over to the interactions.


Best,


Chris Grove

WormBase
