### ISSUE TITLE
visitor_name (visitor_email): Hello, my I have a q...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4786]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_email): Hello, my I have a queation about using this website for looking for mirRNA's information?</br>visitor_name (visitor_email): I want to find daf-12 of mir-235's 3' UTR, how to do that?

**Reported by:** feie* (5422************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#01-23-6">http://www.wormbase.org/#01-23-6</a>
**Browser:** MSEdge 12.10240

**Comment by chris-grove** [comment]
Hello Feier,


 I'm not entirely clear what your asking for, but it sounds like you're looking for a mir-235 binding site in the 3'UTR of daf-12? I don't see any evidence of interaction between daf-12 and mir-235, but here's how I look for these interactions:


1) Go to the daf-12 gene page: http://www.wormbase.org/species/c_elegans/gene/WBGene00000908#08-9-3


2) In the "Interactions" widget, type "mir" into the search box. This filters all of the interactions with daf-12 to those with a "mir" microRNA gene. It looks like daf-12 only has reported interactions with mir-241, mir-84, and mir-237. To look at the daf-12 3'UTR for miRNA binding sites we can next look at the GBrowse genome browser


3) In the "Location" widget of the same page, click on the genomic position coordinates "X:10644407..10666869"; this will take you to the genome browser


4) Once in the genome browser, click on "Select Tracks". Find the track group called "Binding Sites & Regions", and click on the check boxes for "Binding regions", "Binding sites (curated)", and "Binding sites (predicted)"; then click on "Back to Browser" at the top of the page


5) You should see a number of features that align with the 3'UTR (shaded in grey) of daf-12 in the "Binding sites (predicted)" track. You can zoom into that region by clicking and dragging across that region at the top of the GBrowse window and clicking on "Zoom in"


6) Once zoomed into the daf-12 3'UTR, click on the configuration icon for the "Binding sites (predicted)" track (looks like a little wrench), and next to "Spacing" select "Expand & Label". Then click on the "Change" button. This will expand the "Binding sites (predicted)" so that you can read the details of each predicted binding site, including which miRNAs are predicted to bind here. It looks like there are only predictions of binding the daf-12 3'UTR for: mir-84, let-7, mir-48, mir-239a, mir-238, mir-239b, mir-241, mir-90, mir-62, mir-50

Here's a screenshot video of this process:


https://dl.dropboxusercontent.com/u/4290782/WormBase/Looking_at_miRNA_binding_in_daf-12_3%27UTR_5-3-2016.mov


I hope that helps.


Best,


Chris Grove

WormBase
