### ISSUE TITLE
  How do I find genome statistics (such...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4808]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How do I find genome statistics (such as the total number of protein-coding genes, plus numbers of genes for different categories of RNA genes, numbers of pseudogenes etc ) for the latest release of Wormbase and when was the most recent release. </p><p>What were you doing? <br />&nbsp;&nbsp;Trying to find genome statistics</p>

**Reported by:** Tom ******** (tom.******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36

**Comment by tuli** [comment]
Dear Tom.

Thank you for writing to WormBase.

Our release schedule can be found here:
http://www.wormbase.org/about/release_schedule
The most recent release (WS252) has been available since the 7th March 2016.

If you click on the release number e.g. WS252 it will take you to the
release notes which will gives various stats and links to files in our
FTP site which should give you the stats you are looking for.

Best wishes,

Mary Ann

~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
