### ISSUE TITLE
  Hi,  How do I search the list of my h...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4814]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, <br/>How do I search the list of my human genes that have been implicated to disease to your list in Wormbase or Gene to function.</p>

**Reported by:** Rica************* (rica*********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36

**Comment by tuli** [comment]
---------- Forwarded message ----------
From: Kishore, Ranjana <ranjana@caltech.edu>
Date: 15 May 2016 at 00:29
Subject: Re: [wormbase-help] How Do I ...?:   Hi,  How do I search the
list of my h... (Ricardo Harripaul)
To: "ricardo.harripaul@camh.ca" <ricardo.harripaul@camh.ca>
Cc: WormBase Help <help@wormbase.org>


Hi Ricardo
Currently our data mining tool WormMine does not include the disease
data type.  But we are working to expand it to other data types like
disease.
For now, you can cross check your gene list with the annotation file
of C. elegans genes to disease terms:

ftp://ftp.wormbase.org/pub/wormbase/releases/WS253/ONTOLOGY/disease_association.WS253.wb

The rows with the evidence code IEA, are automatic annotations,
associating a C. elegans gene with a human disease based on it’s
orthology to the implicated human disease gene.  The rows with the
evidence code IMP, are from manual annotations based on experimental
evidences in the literature.

Hope this helps.
Ranjana Kishore
WormBase



On May 14, 2016, at 12:46 PM, no-reply@wormbase.org wrote:

How Do I ...?

  Hi,
How do I search the list of my human genes that have been implicated
to disease to your list in Wormbase or Gene to function.

Submitted From:
  support /tools/support

This issue has been assigned ticket number: #4814. Follow progress on
our issue tracker.


Reported by: Ricardo Harripaul (ricardo.harripaul@camh.ca)
14 May 16 19:48

Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like
Gecko) Chrome/50.0.2661.102 Safari/537.36

This question was reported via the web interface at wormbase.org. You
can also email us directly.


-- 
-- 
You received this message because you are subscribed to the "WormBase:
help" group.
To post to this group, send email to help@wormbase.org
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en

---
You received this message because you are subscribed to the Google
Groups "WormBase: help" group.
To unsubscribe from this group and stop receiving emails from it, send
an email to help+unsubscribe@wormbase.org.


--
--
You received this message because you are subscribed to the "WormBase:
help" group.
To post to this group, send email to help@wormbase.org
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
