### ISSUE TITLE
How can I switch off the auto-suggestion/auto-corr...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4817]
*Help Desk query collected when no chat operators were online. Follow up required.*

How can I switch off the auto-suggestion/auto-correction in the search box? I keep going to the wrong genes because it corrects what I'm typing...
/Marc

**Reported by:** Marc****** (marc****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/me#12-0-5">http://www.wormbase.org/me#12-0-5</a>
**Browser:** Safari 9.1

**Comment by chris-grove** [comment]
Hello Marc,

 Our web team can correct me if I'm wrong, but I don't think there is a way to turn off the auto-suggest feature in the search box. Also, I don't believe there is any true auto-correction; there should not be any auto-filling of the search field as you type, only suggestions below the field. Typing anything into the search field and simply pressing the ENTER/RETURN key should perform a search for exactly what you have typed, not more or less.

Best,

Chris Grove
WormBase

**Comment by scottcain** [comment]
Maybe it's something specific to the browser he's using?  Of course, if so, there's not much we can do about it.

**Comment by tuli** [comment]
---------- Forwarded message ----------
From: Sibyl Gao <sibyl@wormbase.org>
Date: 19 May 2016 at 15:53
Subject: Re: [wormbase-help] offline chat transcript: How can I switch
off the auto-suggestion/auto-corr... (Marc Pilon)
To: cgrove@caltech.edu
Cc: "marc.pilon@cmb.gu.se" <marc.pilon@cmb.gu.se>, "help@wormbase.org"
<help@wormbase.org>


Hi Marc,

Chris is right. Simply pressing the Enter/Return key will do a search
based on what you typed without autocompletion. Thank you very much,
Chris!

Currently autocompletion only suggests WormBase ID or name of an
entity. What were you searching for that gives you incorrect
autocompletion?

Best wishes,

Sibyl


On May 19, 2016, at 9:49 AM, Grove, Christian A. (Chris)
<cgrove@caltech.edu> wrote:

Hello Marc,

 Our web team can correct me if I'm wrong, but I don't think there is
a way to turn off the auto-suggest feature in the search box. Also, I
don't believe there is any true auto-correction; there should not be
any auto-filling of the search field as you type, only suggestions
below the field. Typing anything into the search field and simply
pressing the ENTER/RETURN key should perform a search for exactly what
you have typed, not more or less.

Best,

Chris Grove
WormBase

________________________________
From: no-reply@wormbase.org <no-reply@wormbase.org>
Sent: Monday, May 16, 2016 4:16:05 AM
To: help@wormbase.org
Cc: marc.pilon@cmb.gu.se
Subject: [wormbase-help] offline chat transcript: How can I switch off
the auto-suggestion/auto-corr... (Marc Pilon)

offline chat How can I switch off the auto-suggestion/auto-correction
in the search box? I keep going to the wrong genes because it corrects
what I'm typing... /Marc
Submitted From:
  http://www.wormbase.org/me#12-0-5 http://www.wormbase.org/me#12-0-5
This issue has been assigned ticket number: #4817. Follow progress on
our issue tracker.

Reported by: Marc Pilon (marc.pilon@cmb.gu.se)
16 May 16 11:18

This question was reported via the web interface at wormbase.org. You
can also email us directly.

-- 
-- 
You received this message because you are subscribed to the "WormBase:
help" group.
To post to this group, send email to help@wormbase.org
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en

---
You received this message because you are subscribed to the Google
Groups "WormBase: help" group.
To unsubscribe from this group and stop receiving emails from it, send
an email tohelp+unsubscribe@wormbase.org.

-- 
-- 
You received this message because you are subscribed to the "WormBase:
help" group.
To post to this group, send email to help@wormbase.org
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en


--
--
You received this message because you are subscribed to the "WormBase:
help" group.
To post to this group, send email to help@wormbase.org
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by epaule** [comment]
told Marc where to find the option in Safari
