### ISSUE TITLE
  i keep getting this message : "Can't ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4821]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;i keep getting this message :<br/>"Can't call method "segment" on an undefined value."<br/>when trying to access genome view when after successfully finding BLAST hits with the C.remanei genome.<br/>This only appears to be happening with C.remanei genome and not others. (e.g. blasting DAF-16 nuc. seq across species).</p>

**Reported by:** john******* (jhwi****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/601.5.17 (KHTML, like Gecko) Version/9.1 Safari/601.5.17

**Comment by scottcain** [comment]
I'm willing to bet this is due to there being two remanei assemblies.  I'll look at this first thing in the morning.

**Comment by scottcain** [comment]
Luckily, no one took me up on my bet; there was a problem with the c_remanei_PRJNA53967_WS252 database.  I repaired it and now it seems to be working.  I'm double checking with the user before I close

**Comment by scottcain** [comment]
Ha, in addition to the problem with the database, my first guess was right: there is a problem related to there being two remanei assemblies.  If I blast a sequence against PRJNA248909, the GBrowse URL that gets built is pointed at PRJNA53967, and clicking on the link results in a "Not found" result in GBrowse because the contigs are named differently between the two assemblies.  This is going to require a code fix (and it makes me wonder if the same thing happens if you blast against the Hawaiian assembly).

**Comment by scottcain** [comment]
Ugh, it's even worse for the Hawaiian strain: since the chromosomes are named the same, when the blast tool builds a url for the blast hit, it builds it for PRJNA13758 but uses the Hawaiian coordinates, giving misleading results.
