### ISSUE TITLE
  Is there a ftp file that includes all...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4830]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Is there a ftp file that includes all phenotypes of each gene, as well as the supportive evidence (variation or RNAi)?</p>

**Reported by:** Joyc* (qzha***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36

**Comment by tuli** [comment]
---------- Forwarded message ----------
From: Raymond Lee <raymond@caltech.edu>
Date: 20 May 2016 at 00:36
Subject: Re: [wormbase-help] How Do I ...?: Is there a ftp file that
includes all... (Joyce)
To: help@wormbase.org
Cc: qzhaozhao@gmail.com


I believe the phenotype association file is what you want, e.g.
<ftp://ftp.wormbase.org/pub/wormbase/releases/WS252/ONTOLOGY/phenotype_association.WS252.wb>.

raymond



On 05/19/2016 04:31 PM, no-reply@wormbase.org wrote:

How Do I ...?

  Is there a ftp file that includes all phenotypes of each gene, as
well as the supportive evidence (variation or RNAi)?

Submitted From:
  support /tools/support

This issue has been assigned ticket number: #4830. Follow progress on
our issue tracker.

Reported by: Joyce (qzhaozhao@gmail.com)
19 May 16 23:34

Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like
Gecko) Chrome/50.0.2661.102 Safari/537.36

This question was reported via the web interface at wormbase.org. You
can also email us directly.

--
--
You received this message because you are subscribed to the "WormBase:
help" group.
To post to this group, send email to help@wormbase.org
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en

---
You received this message because you are subscribed to the Google
Groups "WormBase: help" group.
To unsubscribe from this group and stop receiving emails from it, send
an email to help+unsubscribe@wormbase.org.



-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

--
--
You received this message because you are subscribed to the "WormBase:
help" group.
To post to this group, send email to help@wormbase.org
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
