### ISSUE TITLE
how do you blast a gene to find a homologous with ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4855]
*Help Desk query collected when no chat operators were online. Follow up required.*

how do you blast a gene to find a homologous with homo sapiens?

**Reported by:** trin* (trin**********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00001612#0-9g-3">http://www.wormbase.org/species/c_elegans/gene/WBGene00001612#0-9g-3</a>
**Browser:** Chrome 51.0.2704.63

**Comment by epaule** [comment]
I would recommend instead of blasting it yourself, to have a look in the homology section of the gene.
there are two tables of potential interest:
* the blastp matches, which show homologs
* the ortholog table, which shows predicted orthologous genes
in all the tables is a search box, where you can put in a.e. "sapiens" to filter for rows matching it.

or of course, you can get the protein sequence by clicking on the small helix symbol next to the protein name and blast it wherever you prefer.
