### ISSUE TITLE
  Hello, I want to check whether two of...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4878]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello, I want to check whether two of the strains (DR107 and VC30084) I am using are homozygous?<br/>How do I do that in wormbase?<br/>Thank you,</p>

**Reported by:** Paul************ (pfon*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36

**Comment by raymond91125** [comment]
Hi Pauline,

Top right corner on the front page, you can enter the name and chose 
(for a) "strain".

Raymond

**Comment by chris-grove** [comment]
Hello Pauline,


 WormBase won't be able to tell you if the strain you're using is homozygous or not. If you ordered the strains through a stock center, the strains should presumably be homozygous for the mutations listed upon receiving them. Once you use them for any crosses, though, you'll need another method to track the zygosity, such as looking for the "dumpy" or "uncoordinated" phenotypes in resulting progeny.


Best,


Chris Grove

WormBase

**Comment by raymond91125** [comment]
Hi Pauline,

The genotype of the strain is in the Overview widget. The default 
notation is homozygous, unless otherwise noted. Make sure you read the 
entirety of "Curatorial remarks" for helpful information on any strain 
you work with.

You might also want to read this WormBook chapter 
<http://www.wormbook.org/chapters/www_introandbasics/introandbasics.html> for 
general information.

Cheers,

Raymond
