### ISSUE TITLE
Phenotype Graph not working

### ISSUE THREAD

**Issue by raymond91125** [WormBase/website#4879]
graph not loading, e.g. <http://www.wormbase.org/species/c_elegans/gene/WBGene00000418#-bc0-10>

**Comment by azurebrd** [comment]
I think it's because there's no json data on wobr.caltech
http://wobr.caltech.edu:81/~azurebrd/cgi-bin/amigo.cgi?action=annotSummaryJsonp&focusTermId=WBGene00000418
is blank.
A different gene like http://wobr.caltech.edu:81/~azurebrd/cgi-bin/amigo.cgi?action=annotSummaryJsonp&focusTermId=WBGene00020580 has empty json.

**Comment by raymond91125** [comment]
SOLR backend issue caused by upstream changes in how the "id" field is represented. Reverted owltools to an earlier, working version so that "id" contains RNAi/variation information.
Problem solved for now.
