### ISSUE TITLE
I am preparing a smallRNA seq dataset, which I wou...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4880]
*Help Desk query collected when no chat operators were online. Follow up required.*

I am preparing a smallRNA seq dataset, which I would like to make accessible on wormbase (or genebrowser) upon publication. Do you have/ are you planning to have a category of 'small RNA expression'. This will be small RNA, but also other classes such as piRNAs and other endo-siRNAs.

**Reported by:** alex***** (alex********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00002994#0-cg1d46-10-cd">http://www.wormbase.org/species/c_elegans/gene/WBGene00002994#0-cg1d46-10-cd</a>
**Browser:** Safari 6.2.8

**Comment by gw3** [comment]
Alexandra,

We curate the structures of ncRNA genes based on the literature and 
using the data in some databases of ncRNA genes such as miRBase.

We use RNA-seq data from the SRA in gene structure curation and we 
display a track of aggregated RNA-seq data on our gene browser.

We are not currently planning to display small RNA tracks on the 
browser, however this may change if our browser, JBrowse, starts to 
support technologies like the UCSC Track Hubs.
If this happens, then we would be able to extract the RNA-seq data from 
the SRA and could provide the user with a selection of a large number of 
RNA-seq tracks to display.

I suggest that you submit your data to the SRA and then we will be in a 
position to use it when our browser technology improves.

Could you let us know when you publish so that we can take a look at 
your work.

Thanks,
Gary Williams
WormBase
