### ISSUE TITLE
This paper 
g3.114.012351v14/9/1765 
should be als...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4901]
*Help Desk query collected when no chat operators were online. Follow up required.*

This paper 
g3.114.012351v14/9/1765 
should be also included as reference in the gene description (for all genes in the dataset). It is much stronger evidence than Chi+ Reinke.

**Reported by:** alex***** (alex********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00009606#0-cg1d46239-10-d">http://www.wormbase.org/species/c_elegans/gene/WBGene00009606#0-cg1d46239-10-d</a>
**Browser:** Safari 6.2.8

**Comment by brucebolt** [comment]
Did anyone respond to Alexandra regarding their curation query?

**Comment by chris-grove** [comment]
From @rankishore 

"Hi Alexandra

Apologies, this seems to have fallen through the cracks!  Could you send the complete reference for this paper that you mention--g3.114.012351v14/9/1765, I’m not able to find it.

(Also, please note that the automated descriptions  are generated based on data already curated in WormBase, so if the paper wasn’t attached to the primary data in the first place, it wouldn’t have made it to the description  in the overview).  

So if you point me to the paper, I can check to see if the data is curated in WormBase and give you a better explanation.

Best
Ranjana Kishore"

**Comment by chris-grove** [comment]
From Alexandra:
" A New Dataset of Spermatogenic vs.Oogenic Transcriptomes in the Nematode Caenorhabditis elegans

    Marco A. Ortiz*, Daniel Noble*, Elena P. Sorokin† and Judith Kimble* 

This is the paper

there are >10000 germline transcripts detected by RNA-seq of dissected gonads.  I think it should get referenced for all genes listed (in addition to the outdated Reinke 2004 microarray)

thanks,
Alexandra"

**Comment by chris-grove** [comment]
From @rankishore 
"Hi Alexandra

I’ve now checked with our expression cluster curator (who curates RNA seq data) and she has confirmed that this data didn’t get into the pipeline that feeds our automated descriptions (what appears in the overview for most genes) because of an error.  She has included this for the WS256 release of WormBase that will appear in the few months, this will then make it’s way into the WS257 automated descriptions, because we base data on the previous release.
So unfortunately it will take a couple of months before this reference will start to appear in the descriptions, just because of the 2 month build and release schedule that WormBase operates on, but it will get in.

Thanks very much for bringing this to our attention.
Best
Ranjana Kishore"
