### ISSUE TITLE
Transcript C47E8.5.1 (of daf-21 gene) shows a very...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4911]
*Help Desk query collected when no chat operators were online. Follow up required.*

Transcript C47E8.5.1 (of daf-21 gene) shows a very long intron after the 3'UTR region (is it? there is no legend in Sequence features or in the new genome browser). I couldn't find where and how this region was determined as an intron. Other examinations of the gene shows all known transcription factors' binding sites inside this intron. Might this be some kind of a false positive data?

**Reported by:** Shir******* (shir*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00000915#01-9gf4a5-3">http://www.wormbase.org/species/c_elegans/gene/WBGene00000915#01-9gf4a5-3</a>
**Browser:** Chrome 49.0.2623.110

**Comment by gw3** [comment]
Hi,

Did you mean that there is a very long 5' UTR region in Transcript C47E8.5.2?

The display of genes shows pink ones as 5' on the left to 3' on the right and blue ones with 3' on the left and 5' on the right. So daf-21 is being shown as 5' to 3' (reading left to right).

The transcripts are not displayed in any particular order. The one currently being displayed at the top in daf-21 is C47E8.5.2. 

There is indeed a long intron in the 5' of Transcript C47E8.5.2.
This structure is based on the EST sequence alignmentss and the following are being used as evidence for this intron in the 5' UTR: 

CEK032E6F
BJ104335
BJ107982
BJ117733
BJ751584
EC034589
BJ771893
BJ106645
BJ808417
BJ106725
BJ807945
EC027588
BJ107896
BJ805283
BJ802754
BJ758770

There is also a lot of RNA-seq evidence for this intron. The number of reads spanning this intron are only about 1% of the number of reads spanning other introns in the coding regions of daf-21, but because this gene is expressed so strongly, there are still a large number of reads providing good evidence for this intron.

I am confident that this intron is real.

Gary Williams
WormBase
