### ISSUE TITLE
  Protein names are formatting incorrec...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4916]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Protein names are formatting incorrectly. The species prefix should be sentence case and italicised. For example, it should not be CBR-MAB-5, it should be "Cbr-" as in the gene name and then MAB-5. This format should be applied to all protein pages and protein name mentions for these objects from other species. </p>

**Reported by:** Kare****** (kare**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

**Comment by epaule** [comment]
I think our current nomenclature says: "A second way of referring to a protein is to use its Protein Name. This is composed of the Gene Name of the Gene of the CDS with the letters in uppercase". 
I don't think our non-elegans section has any exceptions to that.
If you would you like to change that and add to the non-elegans nomenclature, feel free to discuss any proposals with @tuli

**Comment by kyook** [comment]
I have already discussed these names and formats with Tim. The issue came
about while I was linking a paper for the GSA. Perhaps the nomenclature
guidelines need to be updated to clarify how species prefixes should be
used for proteins.

Karen

---------- Forwarded message ----------
From: Tim Schedl <ts@genetics.wustl.edu>
Date: Tue, Jun 21, 2016 at 1:34 PM
Subject: Re: genet191130
To: Karen Yook <karen@wormbase.org>


Hi Karen,

The species abbreviation should be Cbr, ideally in italics, and the same
for both genes and proteins (as it is a species designation).
Having CBR will generate multiple levels of confusion.

Thanks,

Tim

------------------------------
*From: *"Karen Yook" <karen@wormbase.org>
*To: *"Tim Schedl" <ts@genetics.wustl.edu>
*Sent: *Tuesday, June 21, 2016 3:14:38 PM
*Subject: *genet191130


Hi Tim,

This paper goes back and forth between elegans and briggsae genes and
proteins. The linking came out pretty chaotic because of mixed use italics.


I'm confused now about how prefixed protein names should be formatted,
there is no indication in the nomenclature page on WormBase how to format
Cbr- or other species names, but on a protein page ex. Cbr-MAB-5, it looks
like the proper way is CBR-MAB-5.  Is CBR-MAB-5 the official way to write
these proteins?

Thanks for your help.
karen
~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 415.306.4150
e-mail: kyook@caltech.edu
e-mail: karen@wormbase.org
skype name: wbkaren




-- 
Tim Schedl
WormBase Gene Name/Nomenclature Curator
Department of Genetics
Campus Box 8232
Washington University School of Medicine
St. Louis MO, 63110
Caenorhabditis Nomenclature Guidelines:
http://www.wormbase.org/about/userguide/nomenclature
WormBase: http://www.wormbase.org/
Email genenames@wormbase.org

**Comment by kyook** [comment]
I updated our pipeline, so the changed protein names should percolate
through with the next builds.
And I will leave the nomenclature documentation changes to Mary Ann.

**Comment by tuli** [comment]
Relevant email exchange below.

I will confirm exact changes to nomenclature documentation before making any changes. 

---------- Forwarded message ----------
From: Tim Schedl <ts@genetics.wustl.edu>
Date: Tue, Jun 21, 2016 at 1:34 PM
Subject: Re: genet191130
To: Karen Yook <karen@wormbase.org>


Hi Karen,  

The species abbreviation should be Cbr, ideally in italics, and the same for both genes and proteins (as it is a species designation).  
Having CBR will generate multiple levels of confusion.  

Thanks,

Tim

From: "Karen Yook" <karen@wormbase.org>
To: "Tim Schedl" <ts@genetics.wustl.edu>
Sent: Tuesday, June 21, 2016 3:14:38 PM
Subject: genet191130


Hi Tim, 

This paper goes back and forth between elegans and briggsae genes and proteins. The linking came out pretty chaotic because of mixed use italics.  

I'm confused now about how prefixed protein names should be formatted, there is no indication in the nomenclature page on WormBase how to format Cbr- or other species names, but on a protein page ex. Cbr-MAB-5, it looks like the proper way is CBR-MAB-5.  Is CBR-MAB-5 the official way to write these proteins?

Thanks for your help.
karen
~~~~
Karen Yook

Curator 
WormBase Caltech
Tel: 415.306.4150
e-mail: kyook@caltech.edu
e-mail: karen@wormbase.org
skype name: wbkaren

**Comment by kyook** [comment]
Thanks Mary Ann!

~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 415.306.4150
e-mail: kyook@caltech.edu
e-mail: karen@wormbase.org
skype name: wbkaren


On Thu, Jun 23, 2016 at 5:44 AM, tuli <notifications@github.com> wrote:

> Relevant email exchange below.
>
> I will confirm exact changes to nomenclature documentation before making
> any changes.
>
> ---------- Forwarded message ----------
> From: Tim Schedl ts@genetics.wustl.edu
> Date: Tue, Jun 21, 2016 at 1:34 PM
> Subject: Re: genet191130
> To: Karen Yook karen@wormbase.org
>
> Hi Karen,
>
> The species abbreviation should be Cbr, ideally in italics, and the same
> for both genes and proteins (as it is a species designation).
>
> Having CBR will generate multiple levels of confusion.
>
> Thanks,
>
> Tim
>
> From: "Karen Yook" karen@wormbase.org
> To: "Tim Schedl" ts@genetics.wustl.edu
> Sent: Tuesday, June 21, 2016 3:14:38 PM
> Subject: genet191130
>
> Hi Tim,
>
> This paper goes back and forth between elegans and briggsae genes and
> proteins. The linking came out pretty chaotic because of mixed use italics.
>
> I'm confused now about how prefixed protein names should be formatted,
> there is no indication in the nomenclature page on WormBase how to format
> Cbr- or other species names, but on a protein page ex. Cbr-MAB-5, it looks
> like the proper way is CBR-MAB-5. Is CBR-MAB-5 the official way to write
> these proteins?
>
> Thanks for your help.
> karen
>
> Karen Yook
>
> Curator
> WormBase Caltech
> Tel: 415.306.4150
> e-mail: kyook@caltech.edu
> e-mail: karen@wormbase.org
> skype name: wbkaren
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/WormBase/website/issues/4916#issuecomment-228038369>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAlVGp3-iUF0CpsStHUErDH4EeV1XzIsks5qOn-wgaJpZM4I7PkE>
> .
>
