### ISSUE TITLE
I am working on atl-1. I noticed that there are no...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4923]
*Help Desk query collected when no chat operators were online. Follow up required.*

I am working on atl-1. I noticed that there are now 4 predicted isoforms, one of which has a 3kb 5'UTR. I am trying to find out more information about how this short isoform was predicted. Also, I would like to find out why the prediction has changed from 6 months ago (when no 5'UTR was predicted for the short isoform). It is not clear from information shown. 

Thank you for your time.

**Reported by:** Evan******* (elis***********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/tools/comments">http://www.wormbase.org/tools/comments</a>
**Browser:** Firefox 47.0

**Comment by WenChenWormBase** [comment]
Hello Evan,


 Our sequence curation team will get back to you on this next week.


Best,


Chris Grove

WormBase

**Comment by gw3** [comment]
Hi Evan,

The coding transcript isoforms are produced by starting with the manually curated CDS structures (T06E4.3a - the major isoform, T06E4.3b - a very rare isoform which would normally be removed in the manual curation process except that it is based on a mRNA sequence - these have a high visibility and we sometimes get complaints from users if mRNA evidence is ignored when curating structures, T06E4.3c - this is based on the SL1 splice site which has some RNA-seq evidence to support it).

The CDS structures are then automatically matched against transcript evidence to extend then to attempt to produce the full transcript including the UTRs. The transcripts used include ESTs, mRNAs and Trinity transcripts.
The Trinity transcripts have recently been added to this process. They are produced by taking selected, high-quality RNA-seq libraries and using a program (https://github.com/trinityrnaseq/trinityrnaseq/wiki) to perform a de novo reassembly of the RNA-seq reads into transcript sequences.

This is the reason you are seeing a change in the structures of the coding transcripts: one of them (T06E4.3c) is based on the CDS T06E4.3c and has then been extended using the available transcripts. The longer EST, mRNA and Trinity transcripts have already been assigned to the matching, longer CDS structures and the one that remains is used to extend the shorter CDS structure.It turns out that the remaining Trinity transcript includes a rare intron that prevents its structure from being matched to the longer CDS structures. 

This is an artefact. 
I am sure that the coding transcript constructed from CDS T06E4.3c should simply start at the SL1 site and no 5' UTR should be assigned to it.

Gary Williams
WormBase
