### ISSUE TITLE
'transposon has been suppressed' is a confusing an...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4926]
*Help Desk query collected when no chat operators were online. Follow up required.*

'transposon has been suppressed' is a confusing annotation. Makes one think of genetic suppression. Did a survey of 10 people in the lab…
Better: Deleted? Removed?

**Reported by:** alex***** (alex********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00021712#0-d-10">http://www.wormbase.org/species/c_elegans/gene/WBGene00021712#0-d-10</a>
**Browser:** Safari 6.2.8

**Comment by Paul-Davis** [comment]
Dear Alexandra,

Thank you for the feedback. The way we deal with genes that are carried 
by Transposons has always been a special case as we don't remove them 
completely, but suppress them from the protein set. From the linked page 
I don't really see the text you quote?

http://www.wormbase.org/species/c_elegans/gene/WBGene00021712#0-d-10

We do however state the following:

" This gene was determined to be of Transposon in origin so has been 
suppressed from the C. elegans protein set. Detailed information about 
the origin of this gene can be found in the corresponding Transposon 
object associated with this gene."

The corresponding Transposon object appears to be a complete copy of the 
transposon 
http://www.wormbase.org/species/c_elegans/transposon/WBTransposon00000181#0123--10 
" [101116 pad] Transposon span entered to represent an member of the 
MARINER2 transposon family. This example has been assessed as Full based 
on the completeness of the sequence when compared to the consensus 
sequence available from repbase."

Could you send me additional info/context so that I can address this 
issue if the problem persists.

Thanks again.

Paul


On 28/06/2016 15:26, WormBase Helpdesk wrote:
>
> /Help Desk query collected when no chat operators were online. Follow 
> up required./
>
> 'transposon has been suppressed' is a confusing annotation. Makes one 
> think of genetic suppression. Did a survey of 10 people in the lab…
> Better: Deleted? Removed?
>
> *Reported by:* alex***** (alex******************/)
> */Submitted from:* 
> http://www.wormbase.org/species/c_elegans/gene/WBGene00021712#0-d-10
> *Browser:* Safari 6.2.8
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/WormBase/website/issues/4926>, or mute the thread 
> <https://github.com/notifications/unsubscribe/AArzi6nnB_PBoJDbkfqmVZ9h22yQ7PZSks5qQS8kgaJpZM4JAKIJ>.
>


-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
User clarified the issue and I'm going to update the remarks for transposon genes.....also make sure all genes have a standard remark as it looks like there are 2 in circulation.
