### ISSUE TITLE
the content of sek-1 gene is a mistake....

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4943]
*Help Desk query collected when no chat operators were online. Follow up required.*

the content of sek-1 gene is a mistake.

**Reported by:** Y. P*** (yong*********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00004758#0-9g-3">http://www.wormbase.org/species/c_elegans/gene/WBGene00004758#0-9g-3</a>
**Browser:** Chrome 51.0.2704.103

**Comment by tuli** [comment]
Hello,

Thank you for writing to WormBase.

Please can you explain more precisely the nature of the problem you
are reporting?

Is is some aspect of the curation or the sequence, or something else entirely?

Thank you,

Mary Ann


~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by tuli** [comment]
Dear Y.Peng,

Thank you for clarifying the nature of your update.

I am including my colleague Ranjana in this response, as she holds
responsibility for the content of the overview section.

You will hear from her in due course.

Best wishes,

Mary Ann


---------- Forwarded message ----------
From:  <yongpeng@mail.ustc.edu.cn>
Date: 12 July 2016 at 02:02
Subject: Re: Re: [wormbase-help] offline chat transcript: the content
of sek-1 gene is a mistake.... (Y. Peng)
To: Mary Ann Tuli <maryann.tuli@wormbase.org>


Dear Mary Ann,

I am writing this letter to tell you that the overview of sek-1 gene
has a tiny mistake. The overview says "SEK-1 encodes ...". I think
"sek-1" rather than "SEK-1" would be right.

If there is anything wrong please let me know.

Best

Y.Peng
2016.07.12


> -----原始邮件-----
> 发件人: "Mary Ann Tuli" <maryann.tuli@wormbase.org>
> 发送时间: 2016-07-11 17:31:59 (星期一)
> 收件人: yongpeng@mail.ustc.edu.cn
> 抄送: "help@wormbase.org" <help@wormbase.org>, WormBase/website <reply@reply.github.com>
> 主题: Re: [wormbase-help] offline chat transcript: the content of sek-1 gene is a mistake.... (Y. Peng)
>
> Hello,
>
> Thank you for writing to WormBase.
>
> Please can you explain more precisely the nature of the problem you
> are reporting?
>
> Is is some aspect of the curation or the sequence, or something else entirely?
>
> Thank you,
>
> Mary Ann
>
>
> ~ Mary Ann Tuli
>
> ~ email: maryann.tuli@wormbase.org
> ~ Database Curator, WormBase
>
> ~ Biology Division
> ~ California Institute of Technology
> ~ 1200 E. California Blvd
> ~ Pasadena, CA 91125
>
> On 11 July 2016 at 04:42,  <no-reply@wormbase.org> wrote:
> > offline chat the content of sek-1 gene is a mistake.
> >
> > Submitted From:
> >   http://www.wormbase.org/species/c_elegans/gene/WBGene00004758#0-9g-3
> > http://www.wormbase.org/species/c_elegans/gene/WBGene00004758#0-9g-3
> >
> > This issue has been assigned ticket number: #4943. Follow progress on our
> > issue tracker.
> >
> > Reported by: Y. Peng (yongpeng@mail.ustc.edu.cn)
> > 11 Jul 16 03:43
> >
> > This question was reported via the web interface at wormbase.org. You can
> > also email us directly.
> >
> > --
> > --
> > You received this message because you are subscribed to the "WormBase: help"
> > group.
> > To post to this group, send email to help@wormbase.org
> > To unsubscribe from this group, send email to
> > help+unsubscribe@wormbase.org
> > For more options, visit this group at
> > http://groups.google.com/a/wormbase.org/group/help?hl=en
> >


-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by vanaukenk** [comment]
Hi,
I just took a look at the original sek-1 description (that I wrote) and actually marked it to be replaced by the automated description that is now more up-to-date and informative.
This will also fix the case-sensitivity issue Y.Peng reported.
Thx.
--Kimberly
