### ISSUE TITLE
Hello,
Why do you have human and other chordates h...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4974]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello,
Why do you have human and other chordates homologs for MDT-15 protein. When I blasted on NCBI against human, there is no hit.
What could be the easiest explanation for this.
Regards

**Reported by:** Nish*** (thak*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00001900#06g581ed9c--10">http://www.wormbase.org/species/c_elegans/gene/WBGene00001900#06g581ed9c--10</a>
**Browser:** Chrome 48.0.2564.82

**Comment by epaule** [comment]
hat is because our Homology table shows the best hit "per species".

If you dig through all the invertebrate hits on NCBI, you will probably also find the chordate ones, considering their e-value is quite high. As proof of concept: take the protein and blast it only against the mouse and human and you will see.
