### ISSUE TITLE
How can I tell which genome version is used for ea...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#4998]
_Help Desk query collected when no chat operators were online. Follow up required._

How can I tell which genome version is used for each WS release?

Thanks,

Julie

**Reported by:** Juli*********\* (ja21**********_)
*_Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/about/wormbase_release_WS253#0--10">http://www.wormbase.org/about/wormbase_release_WS253#0--10</a>
**Browser:** Chrome 51.0.2704.103

**Comment by epaule** [comment]
have a look at: http://www.wormbase.org/species/c_elegans in the genome assembly section.
We only put "future releases" in there, so it is not a comprehensive list of past genome changes, but we can probably did historical ones outs if needed.

**Comment by epaule** [comment]
maybe something for a future feature (maybe even species specific):

It would be great to put this at the top of the home page so people don’t have to hunt for it!  (e.g, Version: WS253, Genome Assembly WBcel235)

**Comment by sibyl229** [comment]
Hi @epaule it seems that WBcel235 is C elegans specific. I wonder whether it might be misleading to have it in the main header, which appears on every page. So @miyukimouse and I decided to put the appropriate genome assembly name in the header and breadcrumb of each report page associated with a species. http://staging.wormbase.org/species/c_elegans/gene/WBGene00022850#0-c-10

 We also changed the breadcrumbs to have it always visible, so users can access the species page more easily. Do you think this works? Thanks!

**Comment by epaule** [comment]
looks functionally perfect

**Comment by khowe** [comment]
This is good as far as it goes, but you have to be on an entity page (Gene, Transcript etc). 

I think we need something in addition: a new widget on the home page, which shows a table of the species we have, and the assembly versions. We already have this page:

http://www.wormbase.org/species/all#0--10

...but because it is static and and maintained manually, we don't include any dynamic information it, for example the assembly versions. We could add assembly versions, but keeping it in sync with releases would be tricky. 

So, perhaps a new widget for the home page that contains a table with the genomes and their assembly versions? It could be populated from the ASSEMBLIES.json file, in the same way that the "Genome Assemblies" widget is populated for the Species landing pages (http://www.wormbase.org/species/c_elegans#03--10)?

**Comment by sibyl229** [comment]
Hi @khowe @kyook @tuli,  @miyukimouse and I have been thinking about reducing the space that content takes up on home page, while still having them accessible. So we created this mock up attached below to include a "Latest release" widget on home page, which includes links to release note, genome assemblies and gene name changes. 

This means that the gene name changes widget will be moved to another page and be linked from the Latest release widget. And so will be the Genome Assemblies widget that will be created.

What do you think about this proposal? Do you have other suggestions?

![screen shot 2016-08-12 at 10 55 30 am](https://cloud.githubusercontent.com/assets/1753893/17626818/ea464204-607c-11e6-9c44-bf2f83af2392.png)
![screen shot 2016-08-12 at 10 57 24 am](https://cloud.githubusercontent.com/assets/1753893/17626825/ed625d56-607c-11e6-87bf-184d7daf3739.png)

**Comment by khowe** [comment]
Hi @sibyl229 , I think this would be acceptable. Also, perhaps information widgets (gene name changes, species / genome assemblies ) could be collected together on a single "Information on WSXXX"  page?

**Comment by epaule** [comment]
not sure about the front page plans, but the implementation on the respective species specific pages looks fine.

**Comment by epaule** [comment]
looks good and is in production since a while
