### ISSUE TITLE
  Dear wormbase staff, I extracted a li...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5017]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Dear wormbase staff,<br/>I extracted a list of genes from publications. These are apparently in the form of cosmid-derived identifiers, and I wanted to convert them into `WBGene*` identifiers.<br/>However, some of them do not appear in <ftp://ftp.wormbase.org/pub/wormbase/releases/WS253/species/c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS253.xrefs.txt.gz>.<br/>A manual search on wormbase suggests that at least some of them are considered "dead" and were merged into another gene. For instance: <http://www.wormbase.org/species/c_elegans/gene/WBGene00044165#0-9g-3> (Appearing as "2RSSE.2" in my list).<br/>Is there a file somewhere that would allow me to associate dead genes with the live ones with which they have been merged ?<br/>Thanks.</p>

**Reported by:** Blai***** (blai****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0

**Comment by brucebolt** [comment]
Reply from Chris:

Hello Blaise,

 You can try our SimpleMine tool:

http://tazendra.caltech.edu/%7Eazurebrd/cgi-bin/forms/simplemine.cgi

Just paste in your list of genes (in any format) and click "query list". One of the output columns will indicate what genes dead genes have been merged into, if any.

Best,

Chris Grove

**Comment by brucebolt** [comment]
Reply from Blaise:

Hello Chris,

Thank you for your help.

This indeed seems to generate a list that is useful for me.

Identifier conversion is such an essential task in bioinformatics that
I'm surprised this tool isn't mentioned in the "Tools" menu on the
Wormbase site.

Is there an easy way to access the data underlying this conversion tool?
It would be more convenient for me to install the data locally on my
computer, so that I can use it from within automated pipelines instead
of having to manually fill an internet form whenever I need to convert a
new batch of identifiers.


Best regards.

Blaise Li

**Comment by brucebolt** [comment]
Reply from Chris:

Hi Blaise,

 You're welcome ��

I'm glad that works for you. Yes, the tool should be available under the Tools menu; I believe we are planning to add it soon.

You can find many files for parsing on our FTP site (see the "FTP site" link at the bottom of any WormBase page, under "Downloads"):

ftp://ftp.wormbase.org/pub/wormbase/

There is a zipped gene ID mapping file (c_elegans.PRJNA13758.current.geneIDs.txt.gz) in the following directory:

ftp://ftp.wormbase.org/pub/wormbase/species/c_elegans/annotation/geneIDs/

This provides WBGene ID, public name and sequence names, but doesn't list genes that dead genes have merged into. 

Can someone else at WormBase point Blaise to such a file?

Wen, Juancarlos, can you point Blaise to the underlying data for SimpleMine?


Chris
