### ISSUE TITLE
Broken image

### ISSUE THREAD

**Issue by draciti** [WormBase/website#5023]
Hi Sibyl,
Chris found a broken image- both staging and live site:

http://staging.wormbase.org/species/all/expr_pattern/Expr2859#01--10

could you please take a look when you have a moment?
thanks
d

**Comment by sibyl229** [comment]
Hi @draciti 
Is this image http://staging.wormbase.org/img-static/pictures/WBPaper00006427/F2.large_200.jpg what you would like to show? If so, I think the Name tag in the Picture object should probably be `F2.large.jpg` instead of `F2.large_A`. If not, we will need to look for the missing image, as the only images in `pictures/WBPaper00006427/` directory are the F2.large_SIZE.jpg.

**Comment by draciti** [comment]
Thanks Sibyl, the image I would like to display is F2.large_A. I see it in the Canopus folder in my computer but you are right it was not transferred over to Canopus.
I will  run the script again and see what is the issue.

Will keep you posted
thanks
d

**Comment by draciti** [comment]
Found the culprit. there was a missing '.jpg' in OA for the F2.large_A file and it did not get transferred. I think we can wait for the next release to have the picture incorporated, unless refreshing images is quick and easy for you guys.
I am regenerating the thumbnails right now. Let me know what's best for you.
thanks

**Comment by sibyl229** [comment]
Hi @draciti I think probably leaving it for the next release would be better, because it's not only about transferring the image. The value in acedb will be updated to say "F2.large_A.jpg".

**Comment by draciti** [comment]
sounds good sibyl. I keep the ticket open for testing. thanks!

**Comment by draciti** [comment]
resolved
