### ISSUE TITLE
visitor_name (visitor_email): Hi, I have aligned m...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5089]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_email): Hi, I have aligned my reads to the WS220 reference genome. No I wonder if I can use annotations from a later release. I think this is only possible if the sequence didn't change. How can I quickly find out if the sequence changed between two releases? Is there some kind of hash to compare. Is it legitimate to use WS235 gff file with WS220 assambly?

**Reported by:** Chri************* (chri*************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/about/Frequently_asked_questions#1bd29456c0e83a7--10">http://www.wormbase.org/about/Frequently_asked_questions#1bd29456c0e83a7--10</a>
**Browser:** Firefox 43.0

**Comment by chris-grove** [comment]
Dear Christian,

If you visit the C. elegans landing page, here:


http://www.wormbase.org/species/c_elegans

...and open up the "Genome Assemblies" panel, you will see that the current assembly for C.elegans, "WBcel235",  has been present in WormBase since WormBase release WS235. In the "Prior assemblies" table, you can see that the previous version of the assembly, "WBcel215", was live in WormBase between releases WS215 and WS234. 

You obtained the genome from WS220, so you have the "WBcel215" version. Only GFFs for WS215-WS234 can be used with that version of the genome. 

The best thing to do would be to re-align your reads using the latest version of the genome - which has been the latest version of the genome since 2012!

Best wishes, 

Kevin Howe
WormBase Helpdesk
