### ISSUE TITLE
  Hi, I am a long-time worm researcher,...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5121]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, I am a long-time worm researcher, and would like to download WormBase in its entirety to have a stable internet-independent resource in my lab.  I know it is huge, and I was wondering whether there is a known way to do this with the current version of WormBase?  And if not, how can we set up a mechanism to do it?    <br/>thanks, <br/>visitor_name</p>

**Reported by:** Nick********* (nico********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36

**Comment by khowe** [comment]
Reply:

The complete WormBase dataset for a given release is large, but not massive by todays "big data" standards! WS254, our current production release, comes in at around 38GB. 

The release files are available via FTP:

ftp://ftp.wormbase.org/pub/wormbase/releases/WS254

The release comprises many files, which are described in the file "letter.WS254". Rather than downloading each of these files one by one (which would be tedious, to say the least), you might consider using a command-line FTP client which supports recursive download of a whole directory structure, for example "wget".
