### ISSUE TITLE
  I find SPELL to be very useful, but i...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5157]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I find SPELL to be very useful, but it seems to be inaccessible about 1/2 the time- any solutions to this problem?<br/>Thanks,<br/>visitor_name<br/>Kaeberlein lab, UW</p><p>What were you doing? <br />&nbsp;&nbsp;Trying to access SPELL</p>

**Reported by:** Ryan******** (ryan********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:49.0) Gecko/20100101 Firefox/49.0

**Comment by WenChenWormBase** [comment]
Dear Ryan,

I am really sorry that SPELL is not stable. We have been running this tool
on a very outdated and small virtual machine since 2012 because SPELL lost
software support, although we have been updating the data all the time. Now
SPELL has 3 times more data than in 2012, making it much slower, even
unresponsive for minutes when it is used intensively by multiple users at
the same time.

We will actively work on long term solutions to solve the hardware problem
for SPELL, and set up more mirrors for it.

The SPELL server should be working now. You may try this mirror if the
official server fails:    http://spell2.caltech.edu:3000/

And I will appreciate very much if you can email us whenever you see
problem.


Wen Chen
Curator, WormBase


On Sat, Oct 8, 2016 at 10:18 PM, <no-reply@wormbase.org> wrote:

> Everything's broken!
>
>   I find SPELL to be very useful, but it seems to be inaccessible about
> 1/2 the time- any solutions to this problem?
> Thanks,
> Ryan Rossner
> Kaeberlein lab, UW
>
> What were you doing?
>   Trying to access SPELL
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #5157. Follow progress on our issue
> tracker <https://github.com/WormBase/website/issues/5157>.
>
> Reported by: Ryan Rossner (ryan.j.rossner@gmail.com)
> 09 Oct 16 05:16
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:49.0) Gecko/20100101
> Firefox/49.0
>
> This question was reported via the web interface at wormbase.org. You can
> also email us <help@wormbase.org> directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>


-- 
Wen Chen, Ph.D.
Curator, WormBase
