### ISSUE TITLE
Cannot add Chromosome location columns to list of genes in WormMine

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5160]
_Submitted from the feedback form on the WormBase website._

<p>&nbsp;&nbsp;Hi there!<br/>I am trying to use WormMine to generate the genomic coordinates of my list of genes, but it will not allow me to add the columns Chromosome location start and stop. Adding columns like description works fine.<br/>Here is the message I receive:<br/>No Results<br/>This query returns no results. You may wish to change its filters<br/>Help?</p>

**Reported by:** Ahil******\* (ahil**********************_)
*_Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36

**Comment by kyook** [comment]
Hi Ahliya,

If you have a list of genes, you can use ParaSite BioMart to do the
query. You can access this query tool from the Tools dropdown list on
the from WormBase page.  Let me know if you need help setting up the
query.

Best,
Karen

~~~~
Karen Yook

Curator
WormBase Caltech
Tel: 415.306.4150
e-mail: kyook@caltech.edu
e-mail: karen@wormbase.org
skype name: wbkaren



On Mon, Oct 10, 2016 at 11:21 AM,  <no-reply@wormbase.org> wrote:
> Bug Report
>
>   Hi there!
> I am trying to use WormMine to generate the genomic coordinates of my list
> of genes, but it will not allow me to add the columns Chromosome location
> start and stop. Adding columns like description works fine.
> Here is the message I receive:
> No Results
> This query returns no results. You may wish to change its filters
> Help?
>
> Submitted From:
>   support /tools/support
>
> This issue has been assigned ticket number: #5160. Follow progress on our
> issue tracker.
>
> Reported by: Ahilya Sawh (ahilya_sawh@fas.harvard.edu)
> 10 Oct 16 18:19
>
> Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko)
> Chrome/53.0.2785.143 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

**Comment by chris-grove** [comment]
Confirmed. Adding columns via the "Manage Columns" button on the results/list table leads to the message that there are no results. I believe the problem has to do with multiple copies of genes, some with and some without proper gene public names or sequence names or without chromosome location information. If you look up acr-10, for example, you can see that there are two copies of the gene:

![screen shot 2016-10-11 at 1 08 37 pm](https://cloud.githubusercontent.com/assets/611382/19280547/5c56c3da-8fb4-11e6-9a14-751a2c8a64c5.png)

One copy has WB Gene ID, sequence name and public name, but no chromosome location information and the other has chromosome location information but no WB Gene ID and no sequence name. Since the list generation in WormMine finds genes with the WB Gene ID, and adding columns through the "Manage Colums" button results in an inner join, the process results in "no results" because the genes with gene IDs (recognized by the list generation tool) do not have chromosome location info. You can restore results for the list of genes by using "Manage Relationships" and making chromosome location info optional instead of required, which uses inner join and results in no hits, but you'll end up with empty cells where chromosome info should be. I hope that's clear.

**Comment by chris-grove** [comment]
Hi Ahilya,


 Thanks for the reporting the issue and apologies for the inconvenience. We are now working on a fix for the WormMine issue.


Best,


Chris Grove

WormBase

**Comment by chris-grove** [comment]
Problem has been fixed. Thanks @nuin !!!
