### ISSUE TITLE
Cannot save list from table of results in WormMine

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#5174]
When clicking on the "Save as List" button on a WormMine results page in either Chrome or Safari browsers, the pop-up window isn't showing up to allow a user to specify creating a new list or adding to an existing list. This functionality appears to be working properly on Firefox.

**Comment by chris-grove** [comment]
As of now, it's not working in Firefox either.

**Comment by nuin** [comment]
Hi @chris-grove 

The functionality is being shown, but not as a pop-up window, but as an extra div on the screen
![wormmine__query_results_page](https://cloud.githubusercontent.com/assets/6273/20684051/a068d6bc-b56b-11e6-8fae-ef546fab0e7f.png)

![wormmine__query_results_page](https://cloud.githubusercontent.com/assets/6273/20684077/bbaf398e-b56b-11e6-8b62-93d470f9b6b8.png)

This seems to be an error on InterMine's code or due to some modification we made in the web design. I will check with the group to see if anything was changed.

**Comment by joshkh** [comment]
I think this might be the result of some external CSS rules that are leaking into im-tables. If you remove the `clearfix` CSS class from the div that contains the dropdowns then the menus become visible.

![image](https://cloud.githubusercontent.com/assets/4752532/20719159/083fccc2-b653-11e6-971c-c9509573e9f3.png)

If you're using a theme then it likely has a `cleafix` class with its own rules. I embedded the following style into the page and it fixed the problem:

```html
<style>
.imtables .clearfix {
  overflow: visible;
}
</style>
```

So you can either add that to the `<head>` of the page or include it one of your style sheets. Hope that helps!

**Comment by sibyl229** [comment]
Thank you very much @joshkh for the help. It works great!

Hi @chris-grove could you please double check the "Save as List" button for WormMine? http://im-254.wormbase.org/

**Comment by chris-grove** [comment]
@nuin 
Beautiful! It works nicely! Thanks!
I'll close the ticket

**Comment by nuin** [comment]
Thanks @chris-grove for the help, appreciated.
