### ISSUE TITLE
gbrowse links to mRNAs

### ISSUE THREAD

**Issue by epaule** [WormBase/website#5183]
http://www.wormbase.org/tools/genome/gbrowse/b_malayi_PRJNA10729/?name=Bm_v4_Chr1_scaffold_001%3A7085872..7092152

if you turn on the mRNA (best) and click on ay of the mRNAs, it ends up with a broken link.

**Comment by scottcain** [comment]
Hi @epaule,

I'm working on this; do you know if it ever worked?  It doesn't look to me like it should have.  I do see that the link is working in JBrowse, which surprises me, since I mostly did a straight port of most tracks, so you'd think I'd have inadvertently ported the broken behavior.  I'll continue to poke it.

**Comment by scottcain** [comment]
I fixed this on staging.  Since this fix will affect every organism that has "mRNAs/ncRNAs (best)" tracks, I'll take a little time now to verify that this fix will work with them to

**Comment by scottcain** [comment]
@epaule ,

I believe this is fixed for every organism on staging.  Let me know if you'd like this ported back to the 255 release on production (it wouldn't be hard, and since it will be a while before 256 goes live, it seems like a reasonable thing to do).

**Comment by epaule** [comment]
If it doesn't take too much work, it would be a good idea, since it is a
cross-cutting concern affected all species.

**Comment by scottcain** [comment]
Pulled on to production and tested.
