### ISSUE TITLE
  1. I have got a C.elegans gene list (...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5207]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;1. I have got a C.elegans gene list (e.g. ZK177.6; F08G2.6),nearly 20000 genes, I want to convert them into gene symbols like "fzy-1", but I only could find 8333 gene symbols which can match my list. Do you have a tool which can convert the sequence name into gene symbols?<br/>2. When I have the gene symbols of C. elegans, how can I find the homologous genes in human?<br/>This is my first time use the data from C. elegans, your early response will be greatly appreciated. <br/>Thank you so much!</p>

**Reported by:** Yunq******** (chri*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2902.0 Safari/537.36

**Comment by brucebolt** [comment]
Dear Yunqiu

This is possible using the WormBase ParaSite BioMart.

To convert from WormBase sequence names into gene symbols, set Query Filters —> GENE —> ID list limit —> WormBase Sequence Name, then insert your list of sequence names.  Then set Output Attributes —> GENE —> Gene name.  Click Results (button at top of page) are you will see the conversion.

In order to get the homologous gene in human, set Output Attributes —> ORTHOLOGUES —> Human gene stable ID & Human gene name.  Click Results.

This link will take you to an example query: http://parasite.wormbase.org/biomart/martview?VIRTUALSCHEMANAME=parasite_mart&ATTRIBUTES=wbps_gene.default.feature_page.production_name_1010|wbps_gene.default.feature_page.ensembl_gene_id|wbps_gene.default.feature_page.external_gene_id|wbps_gene.default.feature_page.hsapiens_gene|wbps_gene.default.feature_page.hsapiens_gene_name&FILTERS=wbps_gene.default.naive_filters.wormbase_gseqname."ZK177.6,F08G2.6"&VISIBLEPANEL=resultspanel

Best regards

Bruce


-----
Bruce Bolt
Software Engineer, Non-vertebrate Genomics

European Bioinformatics Institute (EMBL-EBI)
Wellcome Genome Campus
Hinxton
Cambridge
CB10 1SD
