### ISSUE TITLE
  Hello, I'm involved in writing a pape...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5217]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello,<br/>I'm involved in writing a paper using the current P.pacificus assembly.<br/>In WormBase, it says the current P.pacificus assembly in wormbase is v2: http://www.wormbase.org/species/p_pacificus#0--10<br/>However, in Ensembl Metazoa they say the version is version 5: http://metazoa.ensembl.org/Pristionchus_pacificus/Info/Annotation/#assembly<br/>I'm a bit confused, is it v2 or v5, please can you let me know?<br/>Regards,<br/>Avril</p>

**Reported by:** Avri********* (alc@************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:38.0) Gecko/20100101 Firefox/38.0

**Comment by chris-grove** [comment]
Hi Avril, 
 
Sorry for the confusion. Pristonchus assembly naming and tracking is a bit of a mess. 
 
The version is Ensembl Metazoa is the first version, dating from 2007. It was sequenced by WashU, and they called it (for reasons unknown to us) "P_pacificus-5.0", and this name is shown in Ensembl.  In 2008, an improved version of the assembly was produced by Ralf Sommer's group. It was never submitted to the archives so does not have an official name. When we incorporated into WB, we called it "v2", because we regarded it as the second (public) version of the genome. Because this version is not in ENA, we cannot put it into Ensembl Metazoa (who are obliged only to show assemblies in ENA/GenBank). 
 
Hopefully, this mess will be resolved early next year, when we get the new (PacBio) version of the P. pacificus genome (which will be submitted to the archives). We will probably call it "v3", but it will be updated in Ensembl too, so all references to "v5" will disappear. 
 
Best, 
 
Kevin
