### ISSUE TITLE
Jbrowse issues

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/website#5244]
Hey Scott,

Sorry this is a bit of a big ticket!!

I was answering a user query about a complicated locus:

http://www.wormbase.org/tools/genome/jbrowse-simple/full.html?overview=1&loc=II%3A161302..171701&data=data%2Fc_elegans_PRJNA13758&nav=1&tracklist=1&tracks=Curated%20Genes%20(protein%20coding)&highlight=

Luckily I had the "Curated Genes (protein coding)" track open or I would have been a bit confused as the "Curated Genes" had no data for this gene. I also found that the tracks have the error "Max Height Reached". So I edited the native config and found that increasing the he maxHeight to 2500 makes the gene models appear in the "Curated Genes" track and also reviels the missing transcripts in the "Curated Genes (protein coding)" track.

Note colour change in the glyphs which was abit unexpected:

![colourchange](https://cloud.githubusercontent.com/assets/717707/20396796/552b9318-acdf-11e6-8f59-0b2881f9b91e.png)
 
The "Curated Genes" track also has an issue as it contains false structures:

![invalid_structure](https://cloud.githubusercontent.com/assets/717707/20396527/6c87b63c-acde-11e6-9329-c3696b299e07.png)

The single block structure shouldn't exist as it's not in the database, maybe something in the consolidated track breaks?

The linking back to the gene page also appears to be broken.

![broken_linking](https://cloud.githubusercontent.com/assets/717707/20396888/9bfca048-acdf-11e6-82be-0600667101a8.png)
 
Cheers

Paul

**Comment by Paul-Davis** [comment]
Ah the colour change is because the config returned for the edit contains

```
   "color": "goldenrod",
    "clip_marker_color": "red"
```

**Comment by scottcain** [comment]
@Paul-Davis you've correctly identified the reason for the color change--by editing the config the javascript callback that calculates the color gets replaced with a simple static color.

The problem with the missing gene in the Curated Genes track is fairly disconcerting--I hate when data disappears and you have no indication that it's going away.  Increasing the height of the track appears to have been magic; good catch!

I will increase the default height of the track, and then start reading some GFF to see if I can figure out the source of the spurious "transcript".

**Comment by scottcain** [comment]
@Paul-Davis: a few things:

1. I increased the maxHeight attribute for those two tracks, as they are the ones that would most likely suffer from this problem.  While there are other tracks that have lots of data that get truncated like this, I am less worried about them since it's cutting off things like RNAseq reads or other similarity data.  Can you think of other tracks that might need their heights adjusted? And, what gene has the most transcripts, so I can look at it to see if the height needs bumped more.

2. About the strange transcript with no exons: it's due to that transcript being a nc_primary_transcript and I don't think the gene glyph knows what to do with it.  I'll work on it further.

**Comment by Paul-Davis** [comment]
Thanks @scottcain

**Comment by scottcain** [comment]
Ugh, and I just noticed that the non-coding transcript in that gene doesn't so up in the non-coding genes track, so the filter I'm using to find non-coding genes is missing something.

**Comment by khowe** [comment]
Some genes have both coding (mRNA) and non-coding (nc_primary_transcript) transcripts. We denote these as protein-coding genes, and they should appear in the protein-coding track, with all their transcripts (coding and non-coding)

**Comment by scottcain** [comment]
@khowe Oh, so the non-coding transcripts shouldn't go in the non-coding genes track? Well, good, I was doing the right thing by accident.  Had I noticed that before, I probably would have found a "fix" that would have changed things.

**Comment by khowe** [comment]
Well, we've classified the _gene_ as a whole as protein-coding. So, the whole gene (i.e. all of its transcripts) should go in the protein-coding track. But that's just my opinion. Others may disagree.

**Comment by scottcain** [comment]
@Paul-Davis and @khowe I modified the existing JBrowse code to display both mRNA and nc_primary_transcript features, and a convenient side effect of the way I implemented it is that the non-coding transcripts are grey so that you can tell where they are in the pile up.  When there is a combination of coding and non-coding transcripts like this, will the non-coding transcripts always be nc_primary_transcript or could it potentially be something else?  I'm just trying to make this as general as it needs to be without putting too much time into it.

![screen shot 2016-11-18 at 6 13 24 pm](https://cloud.githubusercontent.com/assets/274751/20450097/a0a124ca-adbb-11e6-81fe-0a3e96bf8152.png)

**Comment by khowe** [comment]
@scottcain in our GFF3, the the non-coding transcripts in a protein-coding gene are always nc_primary_transcript. 

This all looks good to me.

**Comment by scottcain** [comment]
Code committed to staging branch; will go live with 256
