### ISSUE TITLE
  Tree display of CB4856 strain.   What...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5255]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Tree display of CB4856 strain. </p><p>What were you doing? <br />&nbsp;&nbsp;Looking at the tree display of CB4856 </p>

**Reported by:** Mary********* (mary*********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36

**Comment by raymond91125** [comment]
Sorry! An error has occured.

Bad Gateway

**Comment by raymond91125** [comment]
This 'feature' is specific to CB4856, as RC301, N2 strains show tree view fine.

**Comment by raymond91125** [comment]
May be associated with large amounts of variations: CB4853, CB4858, ED3057 are all affected.

**Comment by mgrbyte** [comment]
The live site currently gives 500 errors (for me at least) on trying to show Tree Display for genes:
e.g:
http://www.wormbase.org/species/c_elegans/gene/WBGene00000001#0-4h-10
http://www.wormbase.org/species/c_elegans/gene/WBGene00044720#0-4h-10

**Comment by mgrbyte** [comment]
Replying to a comment on the WB help desk agenda/wiki:

> Can we replace ACEDB Tree Display with Datomic? We should continue to provide Tree Display. Hold for Matt's input.

I think we should continue to provide tree display (or a way to visualise the schema for an entity), since I think it's useful (for staff at least, if not generally for users).

However, implementing Tree Display (as it is currently formatted) using the migrated datomic database is currently not possible due to:
* The original ACeDB names cannot be re-constructed from the datomic database.
  (The names in ACeDB are transformed to clojure style names during the migration process
  such that, e.g: `Structured_description` becomes `structured-description`)

This could be made possible by storing the original tag name as meta-data in the datomic database.

I'm in the early stages of work on a tool to visualise the datomic schema - I hope this tool (or code from it) could be used to provide an equivalent rendering.

**Comment by sibyl229** [comment]
Thanks @mgrbyte for the comment! I'm not sure whether it's important to keep the ACeDB tag name in the tree display. (@raymond91125 what do you think?) Suppose we only need to display datomic tags and the data associated, what do you think about this problem?

**Comment by tharris** [comment]
@mgrbyte I don't think we need to replicate the tree display precisely as it functions now, but in spirit only would be useful.  For example, I don't think it's a tremendously big deal if case and punctuation of tag names is different.

The tree display can be brought to its knees (as can many functions that I don't care to name) with appropriate queries. I typically intervene manually or programmatically when I can in short order.  The original issue here was resolved long ago, but it can crop up browsing objects with lots of XREFs.  I am closing this issue for now since a) it's known; b) we have a mechanism to deal with and c) it's not worth development effort at this point to build a more robust tree display on top of acedb.
