### ISSUE TITLE
  Hello let-75 (WBGene00202503) is refe...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5263]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello<br/>let-75 (WBGene00202503) is referenced in RNAseq datasets, but is not associated with a sequence ("Sequence: unknown").<br/>Thanks</p>

**Reported by:** Jona************* (ewba*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:49.0) Gecko/20100101 Firefox/49.0

**Comment by raymond91125** [comment]
Hi Jonathan,

My guess is that it probably has something to do with the split from 
myo-1 in 2010. We'll investigate and correct the problem.

Best,

Raymond

**Comment by raymond91125** [comment]
Hi Jonathan,

We've traced the history of this gene. It seems that there was debate a
decade ago (or more) about whether let-75 and myo-1 are the same gene. Up
until 2010, we had them as synonyms for the same gene. In 2010, Jonathan
Hodgkin decided that because the evidence for them being the same gene was
inconclusive, we should split off let-75 to its own, uncloned gene.

So let-75 has popped up in the results of a number of sequence analyses
performed prior to 2010. But even since the update, there have been
sequences in other resources denoted as "let-75". An example is UniProtKB,
who only updated the primary name of P02567 from let-75 to myo-1 last
year.

Since the sequence for let-75 is unknown, any sequence-based analysis
referring to let-75 is actually based on the sequence of (what we now call)
myo-1. We will therefore substitute the links to let-75 with myo-1 in all
of our Expression Clusters. This will be done for the WS258 release of
WormBase.

Best wishes,

Kevin

**Comment by raymond91125** [comment]
FROM WEN 11/28/2016 11:33

Yes Kevin, I will fix them before uploading to WS258.

On Thu, Nov 24, 2016 at 10:16 AM, Raymond Lee <raymond@caltech.edu> wrote:

    Hi Kevin,

    Wen handles Expression_cluster data. I believe the transfer is what we should do.

    Thanks.

    Raymond
