### ISSUE TITLE
  Hi, I would like to know if there is ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5308]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi,<br/>I would like to know if there is a way to download the coding sequences plus annotated 3'UTR for a set of given genes? Genome databases for other organisms allow you to do this (e.g. S. cerevisiae) and I was wondering if there is an easy way to do the same in Wormbase. <br/>Thanks! <br/>Sandra</p>

**Reported by:** Sand********** (savi******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36

**Comment by chris-grove** [comment]
Hi Sandra,


You can use the WormBase ParaSite BioMart tool to retrieve coding sequences and UTR sequences:


http://parasite.wormbase.org/biomart/martview/


I've generated an example query to retrieve coding sequences for three C. elegans genes:

http://parasite.wormbase.org/biomart/martview?VIRTUALSCHEMANAME=parasite_mart&ATTRIBUTES=wbps_gene.default.sequences.production_name_1010|wbps_gene.default.sequences.wbps_gene_id|wbps_gene.default.sequences.coding&FILTERS=wbps_gene.default.naive_filters.species_id_1010."elegaprjna13758"|wbps_gene.default.naive_filters.gene_name."unc-26,hlh-2,pal-1"&VISIBLEPANEL=resultspanel

You'll want to change the list of gene names/IDs in the "Query Filters" section, and possibly the species. To get the UTR sequences you'll want to specify in the "Output Attributes" under "Retrieve sequences" and "SEQUENCES" that you want UTR sequences returned. This will return coding, 3'UTR, 5'UTR sequences separately. Note that there will likely be multiple sequences (of each type) for each gene due to multiple splice variants.


I hope that helps.


Best,


Chris Grove

WormBase
