### ISSUE TITLE
  I am trying to email WormBase to ask ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5325]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I am trying to email WormBase to ask about downloading a sequence set. When I tried to email staff@wormbase.org according to the instructions, I received a notification that the email may have been bounced back or that I may not have permission to send emails to that email. Can you please clarify what is going on and how I can contact WormBase staff for my download request? Thank you.</p>

**Reported by:** bwey********************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36

**Comment by tuli** [comment]
staff@wormbase is a closed list, isn't it?
Should this be help@wormbase? 

![screen shot 2016-12-16 at 09 31 49](https://cloud.githubusercontent.com/assets/1359170/21257929/858f5f36-c372-11e6-8ada-cc791a25cb38.png)

**Comment by khowe** [comment]
@tuli yes it should be help@wormbase.org. I've just changed it.

**Comment by tuli** [comment]
Dear Colleague,

Thank you for writing to WormBase. It seems that the instructions
listed an incorrect email address.
It should be help@wormbase.org rather than staff@wormbase.org

Please can you resend your query to help@wormbase.org and someone will
get back to you.

We apologise for any inconvenience.

Best wishes,

Mary Ann

On 16 December 2016 at 04:25,  <no-reply@wormbase.org> wrote:
> How Do I ...?
>
>   I am trying to email WormBase to ask about downloading a sequence set.
> When I tried to email staff@wormbase.org according to the instructions, I
> received a notification that the email may have been bounced back or that I
> may not have permission to send emails to that email. Can you please clarify
> what is going on and how I can contact WormBase staff for my download
> request? Thank you.
>
> Submitted From:
>   support /tools/support
>
> This issue has been assigned ticket number: #5325. Follow progress on our
> issue tracker.
>
> Reported by: bwey@gradcenter.cuny.edu
> 16 Dec 16 04:26
>
> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
> Gecko) Chrome/54.0.2840.99 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
