### ISSUE TITLE
  Hello With new releases, genes get sp...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5331]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello<br/>With new releases, genes get split and merged. My understanding was that the functional annotations followed the evolution of gene structure. But it seems that this may not always be the case. As a concrete example, WBGene00018600 (F48C1.8) 2010-6-23 Split_into F48C1.11. So any annotation acquired by F48C1.8 using gene predictions prior to WS216 should a priori apply to F48C1.8 and F48C1.11, unless the data argues against it (e.g. a specific microarray probe, or an RNAi clone that match only F48C1.11).<br/>F48C1.8 is associated with the Expression Cluster WBPaper00038438:D.coniospora_12hr_upregulated_RNAseq<br/>This is from one of our studies and is derived from Table S7 "Expression of transcripts after infection with D. coniospora for 12 hours using RNA-seq. Public gene, sequence and transcript names come from WS170".<br/>So there is no reason for the annotation not to be shared with F48C1.11.<br/>In one sense, the consequences are generally relatively minor. In this case, an extra 28 genes (<2%, see below) should be added to the Expression Cluster. But if I am writing, it is because it has caused us a problem. This discrepancy causes difficulties for analytical tools that use accurately updated lists for queries.<br/>Thanks<br/>Jonathan<br/>WBGene00045386<br/>WBGene00045392<br/>WBGene00045393<br/>WBGene00045412<br/>WBGene00050885<br/>WBGene00050919<br/>WBGene00077514<br/>WBGene00077572<br/>WBGene00077573<br/>WBGene00077574<br/>WBGene00077583<br/>WBGene00077704<br/>WBGene00077762<br/>WBGene00194734<br/>WBGene00195176<br/>WBGene00195177<br/>WBGene00195179<br/>WBGene00219308<br/>WBGene00219362<br/>WBGene00219368<br/>WBGene00219369<br/>WBGene00219372<br/>WBGene00236809<br/>WBGene00255703<br/>WBGene00268216<br/>WBGene00269355<br/>WBGene00269373<br/>WBGene00270320</p>

**Reported by:** Jona************* (ewba*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:50.0) Gecko/20100101 Firefox/50.0

**Comment by WenChenWormBase** [comment]
Dear Jonathan,

Would you provide me updated gene lists for all expression clusters
published in this paper so that I can re-annotate them?

I am sorry for this problem. In WS257, we have expression clusters from 428
papers. 64% of them are based on outdated WormBase releases and we have no
access to the original expression data. At this moment, I do not have a
good way to update them unless authors submit the data again.

Wen.

On Wed, Dec 21, 2016 at 4:20 AM, <no-reply@wormbase.org> wrote:

> Content Correction
>
>   Hello
> With new releases, genes get split and merged. My understanding was that
> the functional annotations followed the evolution of gene structure. But it
> seems that this may not always be the case. As a concrete example,
> WBGene00018600 (F48C1.8) 2010-6-23 Split_into F48C1.11. So any annotation
> acquired by F48C1.8 using gene predictions prior to WS216 should a priori
> apply to F48C1.8 and F48C1.11, unless the data argues against it (e.g. a
> specific microarray probe, or an RNAi clone that match only F48C1.11).
> F48C1.8 is associated with the Expression Cluster
> WBPaper00038438:D.coniospora_12hr_upregulated_RNAseq
> This is from one of our studies and is derived from Table S7 "Expression
> of transcripts after infection with D. coniospora for 12 hours using
> RNA-seq. Public gene, sequence and transcript names come from WS170".
> So there is no reason for the annotation not to be shared with F48C1.11.
> In one sense, the consequences are generally relatively minor. In this
> case, an extra 28 genes (<2%, see below) should be added to the Expression
> Cluster. But if I am writing, it is because it has caused us a problem.
> This discrepancy causes difficulties for analytical tools that use
> accurately updated lists for queries.
> Thanks
> Jonathan
> WBGene00045386
> WBGene00045392
> WBGene00045393
> WBGene00045412
> WBGene00050885
> WBGene00050919
> WBGene00077514
> WBGene00077572
> WBGene00077573
> WBGene00077574
> WBGene00077583
> WBGene00077704
> WBGene00077762
> WBGene00194734
> WBGene00195176
> WBGene00195177
> WBGene00195179
> WBGene00219308
> WBGene00219362
> WBGene00219368
> WBGene00219369
> WBGene00219372
> WBGene00236809
> WBGene00255703
> WBGene00268216
> WBGene00269355
> WBGene00269373
> WBGene00270320
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #5331. Follow progress on our issue
> tracker <https://github.com/WormBase/website/issues/5331>.
>
> Reported by: Jonathan J Ewbank (ewbank@ciml.univ-mrs.fr)
> 21 Dec 16 12:20
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:50.0) Gecko/20100101
> Firefox/50.0
>
> This question was reported via the web interface at wormbase.org. You can
> also email us <help@wormbase.org> directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>


-- 
Wen Chen, Ph.D.
Curator, WormBase

**Comment by WenChenWormBase** [comment]
Dear Wen,

Thanks for getting back to me. My comment was a general one. I don’t think that providing the update for our particular datasets would be a good solution, and it wouldn’t solve the analysis problems we have because other SPELL lists will still be outdated. But it is useful for me to know that this is indeed an issue. Do you know whether it applies equally to other types of data, like RNAi phenotypes too, or does sequence mapping allow these to evolve?

BTW, for our own purposes, I use a tool we developed some years ago. You can try the client version.  Click on this link<http://www.ciml.univ-mrs.fr/applications/WB_converter/WBC_install.htm>, for instruction and then read the quick start guide.<http://www.ciml.univ-mrs.fr/applications/WB_converter/downloads/Tutorial%20-%20WB%20Converter.pdf>  As I wrote when we described it in the WBG, "We’d be delighted if anyone else would like to host this service!”

Thanks

Jonathan


On 21 Dec 2016, at 21:05, Wen Chen <wen@wormbase.org<mailto:wen@wormbase.org>> wrote:


Dear Jonathan,

Would you provide me updated gene lists for all expression clusters published in this paper so that I can re-annotate them?

I am sorry for this problem. In WS257, we have expression clusters from 428 papers. 64% of them are based on outdated WormBase releases and we have no access to the original expression data. At this moment, I do not have a good way to update them unless authors submit the data again.

Wen.

On Wed, Dec 21, 2016 at 4:20 AM, <no-reply@wormbase.org<mailto:no-reply@wormbase.org>> wrote:
Content Correction
  Hello
With new releases, genes get split and merged. My understanding was that the functional annotations followed the evolution of gene structure. But it seems that this may not always be the case. As a concrete example, WBGene00018600 (F48C1.8) 2010-6-23 Split_into F48C1.11. So any annotation acquired by F48C1.8 using gene predictions prior to WS216 should a priori apply to F48C1.8 and F48C1.11, unless the data argues against it (e.g. a specific microarray probe, or an RNAi clone that match only F48C1.11).
F48C1.8 is associated with the Expression Cluster WBPaper00038438:D.coniospora_12hr_upregulated_RNAseq
This is from one of our studies and is derived from Table S7 "Expression of transcripts after infection with D. coniospora for 12 hours using RNA-seq. Public gene, sequence and transcript names come from WS170".
So there is no reason for the annotation not to be shared with F48C1.11.
In one sense, the consequences are generally relatively minor. In this case, an extra 28 genes (<2%, see below) should be added to the Expression Cluster. But if I am writing, it is because it has caused us a problem. This discrepancy causes difficulties for analytical tools that use accurately updated lists for queries.
Thanks
Jonathan
WBGene00045386
WBGene00045392
WBGene00045393
WBGene00045412
WBGene00050885
WBGene00050919
WBGene00077514
WBGene00077572
WBGene00077573
WBGene00077574
WBGene00077583
WBGene00077704
WBGene00077762
WBGene00194734
WBGene00195176
WBGene00195177
WBGene00195179
WBGene00219308
WBGene00219362
WBGene00219368
WBGene00219369
WBGene00219372
WBGene00236809
WBGene00255703
WBGene00268216
WBGene00269355
WBGene00269373
WBGene00270320

Submitted From:
  support /tools/support

This issue has been assigned ticket number: #5331. Follow progress on our issue tracker.


Reported by: Jonathan J Ewbank (ewbank@ciml.univ-mrs.fr)
21 Dec 16 12:20

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:50.0) Gecko/20100101 Firefox/50.0

This question was reported via the web interface at wormbase.org. You can also email us directly.


--
--
You received this message because you are subscribed to the "WormBase: help" group.
To post to this group, send email to help@wormbase.org
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en






--
Wen Chen, Ph.D.
Curator, WormBase

**Comment by WenChenWormBase** [comment]
Hi Jonathan,

For RNAi, we connect the data to RNAi sequences (or PCR products) at point
of curation. The connections to genes is done dynamically each WormBase
release, by mapping the sequences to the latest gene models.

For microarray-based data, we try to take the same approach where possible.
If the authors have provided enough information to express an expression
cluster in terms of probe sequences (rather than genes), it is these that
are captured at point of curation. The corresponding genes for such
expression clusters are then computed dynamically each release, by mapping
the microarray probes to the latest gene models.

However, if the authors have not provided enough info to able to express
the cluster in terms of probes, then curation has to default to expressing
it in terms of genes directly. And as the gene models evolve, these
clusters get out of date.

We do do some things to "patch" these out-of-date clusters, e.g. remove
dead genes. But you're right: if a gene A is split into A and B, A remains
in the cluster but B is not added. This might be something we can fix
automatically, using our split/merge history. We'll discuss it at our next
conference call.

Best,

Kevin
