### ISSUE TITLE
Many tracks in many (most?) parts of the genome are not rendering properly in GBrowse

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#5340]
For example, if I click on the genomic position coordinates in the Location widget on the unc-26 gene page I get the following:

![screen shot 2017-01-04 at 11 33 13 am](https://cloud.githubusercontent.com/assets/611382/21650036/b2ebc042-d271-11e6-8074-ee1836c12721.png)

In some instances I can get the Curated Genes track to render, but then if I navigate over a few windows the track doesn't render again.

**Comment by scottcain** [comment]
Thanks for the heads up; I'm looking into it.

**Comment by scottcain** [comment]
Hmm, maybe it was a transient problem, like the browser being it by a spider, because it seems fine now, and I didn't do anything.  Closing, but let me know if it still looks bad to you.

**Comment by chris-grove** [comment]
@scottcain 
I'm still consistently getting track loading errors when trying to load GBrowse from the unc-26 gene page

**Comment by scottcain** [comment]
Hi @chris-grove can you try zooming in or out a little bit to see if it helps? I'm wondering if you're seeing some image caching issues, where the "failed to load" images are being served to you even though it's working ok now.

**Comment by chris-grove** [comment]
@scottcain 
OK, well, I've deleted my cache, restarted the browser, and did a hard refresh on both Firefox and Chrome and I'm still getting the error when I open up the unc-26 locus, although the problem goes away once I zoom in or out. If there's nothing we can do about the persistent initial error, I guess we can close the ticket.

**Comment by scottcain** [comment]
Hi @chris-grove 
I was actually referring to the images cached on the server to save it time in recreating images that it has recently created--it knows the boundaries of the region you're requesting, and since you're requesting the exact same region when you go from the unc-26 page, you're probably getting served up the exact same broken images.  I just deleted an cached images on the server older than 5 minutes (I think--the unix "find" command can be a little obscure), so hopefully that problem should go away.  If it doesn't, can you give me the list list of tracks you're using so I can see if there is something odd about them?

**Comment by chris-grove** [comment]
@scottcain 
Here's a screen capture video of what I'm still seeing:

https://dl.dropboxusercontent.com/u/4290782/WormBase/GBrowse_error_Jan_5_2017.mov

**Comment by scottcain** [comment]
@chris-grove Thanks for the video; that really helps demonstrate the problem.

It is quite weird, but I can also get it to do that some of the time for some tracks.  The strange thing about it is that it doesn't seem like the mysql server is hanging, because then you'd wait longer and then get a time out message.  Instead, it's more like mysql is very quickly throwing up it's hands and saying "I just can't deal with this right now."  

What I'd like to do is ask @tharris if he can make the mysql server a little bigger as a test to see if a little more resources will make this problem go away, or at least if there is anything he can think of that might cause mysql to choke in this seemingly random way.

**Comment by chris-grove** [comment]
@scottcain 
OK, sounds good!

**Comment by tharris** [comment]
That is at least partially a cached image problem. Scott you need to fully and completely blow away the image Cache. Start there.  Purging the cache via the find syntax rarely works in real world setting. I highly doubt this is an instance size problem. Is memory constrained?

**Comment by tharris** [comment]
I doubt seriously that the queries are memory-constrained. Both the gbrowse and rdbms instances are xlarge. 

The find incantation can be really, really slow on caches with many files and directories. And wouldn't you want files to persist longer than 5 minutes?

**Comment by scottcain** [comment]
@chris-grove We made some changes to the mysql server yesterday.  Can you try today to see if GBrowse is behaving better for you today?  Thanks.

**Comment by chris-grove** [comment]
@scottcain 
Yep, that seems to have done the trick. Thanks!
