### ISSUE TITLE
  If I have a list of 1000 genes of C.e...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5375]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;If I have a list of 1000 genes of C.elegans and I want how much homology (% similarity not % identity) each gene have with humans. Is their is any tool in which I can make 1000 entries of genes at a time that can generate a table directly of all genes with homology, instead of making manual entries of each gene in worm base and then retrieving its homology information. </p><p>What were you doing? <br />&nbsp;&nbsp;I am a Research Scholar</p>

**Reported by:** ARUN********** (arun***********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; rv:49.0) Gecko/20100101 Firefox/49.0

**Comment by a8wright** [comment]
I have enquired with the staff at WormBase regarding what you would like to accomplish.

Unfortunately, users can use WormBase Parasite BioMart to get % identity, but not % similarity.

The solution that has been recommended is to see if this is reported in BLAST. In order to do this you would need to get the sequences for the 1000 human genes that you are interested. This can be found in WormBase Parasite BioMart.  and then re-align each pair with BLAST.
