### ISSUE TITLE
  How do I find; . a. the standard/comm...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5399]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How do I find; .<br/>a. the standard/common name of the gene<br/>b. the type of gene is it<br/>c. a description of the gene and its function.<br/>d. Gene Ontology terms used to define this gene.<br/>e. What chromosome the gene is located on and how many chromosomes it has<br/>f. How many nucleotides the gene has in the genomic DNA<br/>g. How many nucleotides are present in the cDNA <br/>h. How many exons does the gene have?<br/>i. How many amino acids are present in the protein<br/>j. What is the molecular weight of the protein<br/>k. Are there any predicted domains in the protein<br/>l. Are there mutant phenotypes exhibited upon disruption/mutation of this gene? If so, what<br/>are they?<br/>m. Does the gene have significant homology to other known genes in either of the other two<br/>model organisms?</p><p>What were you doing? <br />&nbsp;&nbsp;Homework</p>

**Reported by:** Raie************ (raie*********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36

**Comment by tuli** [comment]
Dear Raiesha,

Thank you for writing to WormBase.

I see that your questions are part of a homework assignment, and
therefore rather than give you the answers I will give you pointers to
enable you to find the answers yourself.

I suggest you pick a gene of interest e.g. unc-119. Enter this into
the WormBase search box (top right of every page) and then browse the
information within the widgets (listed on the left in blue). You
should find all the information you are looking for there.

Please do write back if you get stuck!

Best wishes,

Mary Ann

On 3 February 2017 at 20:18,  <no-reply@wormbase.org> wrote:
> How Do I ...?
>
>   How do I find; .
> a. the standard/common name of the gene
> b. the type of gene is it
> c. a description of the gene and its function.
> d. Gene Ontology terms used to define this gene.
> e. What chromosome the gene is located on and how many chromosomes it has
> f. How many nucleotides the gene has in the genomic DNA
> g. How many nucleotides are present in the cDNA
> h. How many exons does the gene have?
> i. How many amino acids are present in the protein
> j. What is the molecular weight of the protein
> k. Are there any predicted domains in the protein
> l. Are there mutant phenotypes exhibited upon disruption/mutation of this
> gene? If so, what
> are they?
> m. Does the gene have significant homology to other known genes in either of
> the other two
> model organisms?
>
> What were you doing?
>   Homework
>
> Submitted From:
>   support /tools/support
>
> This issue has been assigned ticket number: #5399. Follow progress on our
> issue tracker.
>
> Reported by: Raiesha Robbalaa (raieshadanielle@gmail.com)
> 03 Feb 17 20:19
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML,
> like Gecko) Chrome/55.0.2883.95 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
