### ISSUE TITLE
  Hi wormbase staff,  I am checking the...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5427]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi wormbase staff, <br/>I am checking the information of the gene ZC443.3 on the wormbase. <br/>It reads as following in the overview section "ZC443.3 is an ortholog of human EIF3C (eukaryotic translation initiation factor 3 subunit C) and EIF3CL (eukaryotic translation initiation factor 3 subunit C-like); RNA sequencing and microarray studies indicate that ZC443.3 is regulated by Ethanol, 1-methylnicotinamide, Progesterone, Testosterone, Atrazine, Diazinon, Cry5B, Quercetin, Humic substances, single-walled carbon nanotubes, Colistin, and Sirolimus; microarray, tiling array, and RNA sequencing studies indicate that ZC443.3 is enriched in the germ line and in neurons including the PVD, OLL, DA, VA, and dopaminergic neurons."<br/>But the homolog item does not show ZC443.3 as the ortholog of an human EIF3C. When I blast the protein sequence of ZC443.3 in NCBI blast for human proteins, the result is negative. <br/>When I blast the the protein sequence of ZC443.3 at wormbase, the result only show ZC443.3 as the perfect hit and ZC443.4 as the second hit. This again does agree with the paralogs of eif3.c in the wormbase.<br/>Can you please explain the inconsistency problem here?<br/>Thanks, <br/>visitor_name</p>

**Reported by:** Han **** (han.****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

**Comment by epaule** [comment]
if you look in the homology widget, you will find one table for homology (which are blastp) and one table for orthologs. In the ortholog section you can find the H.sapiens EIF3C as ortholog predicted by PantherDB.
It looks a bit like PantherDB didn't resolve the 2:3 into one 1:1 and one 1:2 set ... potentially because the homology is not that great.

If you look into the paralog section, you can also see that the .3 / .4 paralogy is supported by two independent sources, whereas the eif-3.C is only predicted by Panther.

On the grand scheme of things, you can say that Panther is more sensitive, but less specific than other sources.
