### ISSUE TITLE
  Hello, is it possible to download/exp...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5429]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello,<br/>is it possible to download/export full list of C.elegnas strains and their characteristics that are available through Caenorhabditis Genetics Center? They have a txt file online but it is obsolete. They told me that they do not update it anymore but that WormBase offers up-to-date information regarding cgc strains.  thank you jiri</p><p>What were you doing? <br />&nbsp;&nbsp;I would like to find which strains useful for neurodegeneration studies are available through cgc.</p>

**Reported by:** jiri******* (jiri****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0

**Comment by tuli** [comment]
Dear Jiri,

Thank you for writing to WormBase. I am trying to work out the best
way for you to do this yourself, but in the meantime I am happy to
dump the data directly out of the database and send you the file.

In order to ensure I'm sending you the information you need, please
can you tell me exactly what you mean by "and their characteristics"?

If you are interesting in strains used in neurodegeneration you may
well find it preferable to go through the literature and see which
strains are associated with publications of interest.

Best wishes,

Mary Ann

On 20 February 2017 at 08:19,  <no-reply@wormbase.org> wrote:
> Question:
>
>   Hello,
> is it possible to download/export full list of C.elegnas strains and their
> characteristics that are available through Caenorhabditis Genetics Center?
> They have a txt file online but it is obsolete. They told me that they do
> not update it anymore but that WormBase offers up-to-date information
> regarding cgc strains. thank you jiri
>
> What were you doing?
>   I would like to find which strains useful for neurodegeneration studies
> are available through cgc.
>
> Submitted From:
>   support /tools/support
>
> This issue has been assigned ticket number: #5429. Follow progress on our
> issue tracker.
>
> Reported by: jiri voller (jirivoller@gmail.com)
> 20 Feb 17 08:18
>
> Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by tuli** [comment]
Lots of communication with user and a happy ending. Thank you @brucebolt for you help in file wrestling! 

Dear Mary Ann, 
that is exactly what I wanted, thank you
jiri
