### ISSUE TITLE
Question about disappeared concise_description for dpy-3

### ISSUE THREAD

**Issue by sibyl229** [WormBase/website#5460]
Hi @rankishore I'm not sure if this is a problem. Seems to be an isolated instance. I happened to notice that this gene dpy-3 used to have concise description and provisional description, but in WS258 it only has automated description. http://staging.wormbase.org/tools/tree/run?name=WBGene00001065;class=Gene;expand=Gene_info#Gene_info Please feel free to close this issue if it's not a problem. Thanks!

**Comment by rankishore** [comment]
@sibyl229, @epaule: Sometimes Kimberly or I will choose which description should get dumped, depending on the information in it, this is the case for dpy-3, where we have put a 'NO DUMP' flag on the concise and provisional ones in our local curation database, so that the automated description can make it through the pipeline.  So all is well with dpy-3.
