### ISSUE TITLE
Hello,
I think there is something wrong about the ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5471]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello,
I think there is something wrong about the annotation of rpa-4 / F59A3.6. The sequence you have as F59A3.6a in the gene page doesn't match any of the isoforms in the gene browser map. Strangely than that: when I started to align F59A3.6a exon by exon by used the BLAST page you have, exon 1 through 3 are fine (align to F59A3.6a) but the rest (exon 4 through 8) align half to F59A3.6a and half to F59A3.6e. I mean- each exon is half and half, not the whole transcript...
My questions: 
How can you explain that strange alignment?
Which one is right- the sequence in the gene page or the gene annotation browser map?

**Reported by:** Sari*********** (sari*********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/tools/blast_blat/run">http://www.wormbase.org/tools/blast_blat/run</a>
**Browser:** Chrome 56.0.2924.87

**Comment by gw3** [comment]
Sarit,

rpa-4 is an unusual locus.

rpa-4 appears to have started as a homolog of human replication protein 
A2 (HGNC:RPA2).

This locus then appears to have been partially duplicated.

The second (copied) part of the locus lacked a promoter and both copies 
appear to be transcribed together.
It is unclear whether the isoforms in the second half of this locus 
(isoforms F59A3.6e and F59A3.6f) are translated or not; we have curated 
the structure assuming that they are, because they have SL1 and SL2 
sites and so these isoforms are probably trans-spliced as separate isoforms.

When you do a Blast search with the exons of F59A3.6a against this 
locus, you will get matches of exons 4 through 8 aligning against both 
the first half of the locus and to the second half of the locus because 
they are partial duplicates of each other.

Gary Williams
WormBase
