### ISSUE TITLE
  Dear WormBase-Team, recently we were ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5485]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Dear WormBase-Team,<br/>recently we were checking our plasmids for cell-specific expression in the PVD neuron and found that according to the annotation on your website  (http://www.wormbase.org/species/c_elegans/cds/F49H12.4#05--10) we use a promoter sequence for PVD which includes the coding region for the first exon of F49H12.4  + approx. 95% of the following intron up to TTCCTCAAAGAAAATAGAC. In our vector the following ATG was replaced by a BamHI site followed by a Channelrhodopsin-2::mCherry. If the annotation (see link) is correct the start of the ChR2::mCherry would be located in that specific intron and therefore would be spliced during mRNA maturation. Since it would not be in frame anymore it should not be functional. The thing that confuses us is that ChR2 expression works fine/ the protein is functional and we could also express GFP in PVD using our promoter sequence. So there must be something else… Do you by any chance have some information/any idea which could help us? Would it be possible to send me that EST data mentioned in the curatorial remarks? That would help me a lot.<br/>Thank you in advance and best regards,<br/>visitor_name<br/>PhD student<br/>Prof. Dr. Alexander Gottschalk's Group<br/>Buchmann Institute for Molecular Life Sciences<br/>Goethe University<br/>Room 1.656<br/>Max-von-Laue-Str. 15<br/>D-60438 Frankfurt/Main<br/>Germany </p>

**Reported by:** Jona****** (jona****************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0

**Comment by gw3** [comment]
Jonas,

Please accept our apologies for the delay in answering this query.

The current structure of F49H12.4 looks correct.

There is a possible SL1 site at the start of the second exon. Because 
there is no AUG codon in the correct frame in this second exon, an 
isoform can only be made starting in the third exon with the protein 
sequence:
MDSCVELSSPQISSKEESVLL
We have not created this isoform in the annotation because this SL1 site 
is trans-spliced at a very low level.

There is an AUG codon in the first intron just after your sequence 
TTCCTCAAAGAAAATAGAC.
There is a VERY faint indication in the RNA-seq data that there might be 
an isoform starting at this AUG, giving the protein sequence:
MVADESSDVFFLVSVVAPLLFCCFAIFVCALNSIWKTRSKLEALTQVAKQREPTEYTEFTIDLTTKMDSCVELSSPQISSKEESVLL
but this does not look likely.

There are 4 EST sequences at this locus:
FN897639 (full-length of the locus - this is the EST mentioned in the 
curatorial remarks)
FN897640 (5' half of the locus)
FN897641 (full-length of the locus)
FN897642 (5' half of the locus)

The sequence of FN897639 is:
http://www.ebi.ac.uk/ena/data/view/FN897639&display=fasta


Gary Williams
WormBase
