### ISSUE TITLE
  I am trying to look at expression pat...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5550]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I am trying to look at expression patterns for genes and the table that lists where a gene is expressed and how we know this seems to either be having an issue or been severely downgraded. It used to tell you what cell(s) the gene is expressed in and list the reporter construct used to make that observation. Now it just gives a few random cells and a link under "supporting evidence" that just makes for more clicking and less centralized info. Is this an intentional change and, if so, would you consider changing it back? I found the previous version much more useful.</p>

**Reported by:** josh******************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

**Comment by chris-grove** [comment]
Hello Joshsaul,


We recently updated the view of expression so that the data displayed would be anatomy term, life stage, and cellular component centric. Previously, the expression patterns were listed one at a time with anatomy, life stage, and cellular component information for each expression pattern experiment listed in-line with the experiment info. The purpose of the new view is to consolidate all evidence for the gene's expression in a particular anatomical entity, life stage, or cellular component so one would not have to search for spatial and temporal expression across a (potentially large) list of expression experiments. This new view also allows for a quick view of how many independent experiments support the gene's expression in that particular time and place. In the "Expressed in" table of anatomical expression, the cells and tissues are listed alphabetically and are not a random list. In the future, we hope to have a more compact graphical display of tissue expression that visualizes expression according to the anatomy ontology.


I'm sorry you find this new view less useful, but maybe now that you understand the motivation behind it you can see it's benefit.


Best,


Chris Grove

WormBase
