### ISSUE TITLE
  I noticed that the ok1255 variant in ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5551]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I noticed that the ok1255 variant in the rsks-1 gene is still pending curation.  We would like to know the boundaries of the deletion.  Please let me know if this is known, if it simply needs to be curated or if the experiment still needs to be done.  Thank you.</p><p>What were you doing? <br />&nbsp;&nbsp;Trying to determine if the wild-type amino acid Thr404 is present in the rsks-1(ok1255) mutant.</p>

**Reported by:** John******* (murp**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

**Comment by tuli** [comment]
Dear John,

Thank you for writing to WormBase.

The boundaries of the ok1255 deletion have not been submitted to WormBase.

I did have a look at the literature and found that it is a 1700bp
deletion. The transcript is 3050bp long so it is not possible for me
to speculate whether Thr404 is present in the mutant.

I am cc'ing Mark Edgley from the Gene Knockout project who may have
more information.

I am sorry to not be able to help you further.

Best wishes,

Mary Ann

On 13 April 2017 at 21:04,  <no-reply@wormbase.org> wrote:
> Content Correction
>
>   I noticed that the ok1255 variant in the rsks-1 gene is still pending
> curation. We would like to know the boundaries of the deletion. Please let
> me know if this is known, if it simply needs to be curated or if the
> experiment still needs to be done. Thank you.
>
> What were you doing?
>   Trying to determine if the wild-type amino acid Thr404 is present in the
> rsks-1(ok1255) mutant.
>
> Submitted From:
>   support /tools/support
>
> This issue has been assigned ticket number: #5551. Follow progress on our
> issue tracker.
>
> Reported by: John Murphy (murphyjt@wustl.edu)
> 13 Apr 17 20:03
>
> Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko)
> Chrome/57.0.2987.133 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by tuli** [comment]
Leave open for a little while to see what Mark says.

**Comment by tuli** [comment]
---------- Forwarded message ----------
From: Mark Edgley <edgley@mail.ubc.ca>
Date: 19 April 2017 at 00:17
Subject: Re: [wormbase-help] Content Correction: I noticed that the
ok1255 variant in ... (John Murphy)
To: Mary Ann Tuli <maryann.tuli@wormbase.org>, murphyjt@wustl.edu


Hi kids (I can say this legitimately now due to my newly advanced age),

I only have a little to add, and it isn't much help.  First, this is
not an allele from the
Barstead lab that we ever got in Vancouver to sequence, so I have no
sequence data
and no way to get any.  The best thing for you to do if you have it in
hand is to
sequence a PCR product.  The only thing I was able to do is to map the internal
primers of the original PCR detection set and see where they lie in
relation to Thr404
and in relation to the reported deletion size.  Maybe you did this
already and were just
hoping there was some sequence data some place?  Worth a shot, but to
no avail in
this case.  Those primers make a thing 3267 bp long, and a deletion of
approximately
1700 bp lies in there, leaving a total of arount 1567 bp not deleted.
Unfortunately, the
space between the left primer and Thr404 is about 2 kb, so there's
plenty of room for
the deletion not to hit Thr404 at all.  Also, keep in mind that in
some cases with nested
PCR we recovered deletions where one of the two internal primer sites
was deleted,
which would make it possible to shift the deletion even further away
from Thr404.

If you're going to do a PCR and sequence the product, I recommend that
you get all four
primers made (the sequences are listed under Molecular Details for
ok1255) and do a
proper nested pair of reactions, then purify and sequence from both
the internal left and
internal right.  Note that for some reason "left" and "right" are
reversed for these primers.
Usually that means that the primers are in relation to canonical
sequence and the gene
is on the opposite strand, but that doesn't appear to be true here.

Sorry this isn't better news!  I've attached a marked-up Word document
to show you
what I did.  This is a download of the unspliced gene with the exons
outlined in blue
and the primers and Thr404 sites commented.

cheers,

Mark


At 07:30 AM 2017-04-18, Mary Ann Tuli wrote:

Dear John,

Thank you for writing to WormBase.

The boundaries of the ok1255 deletion have not been submitted to WormBase.

I did have a look at the literature and found that it is a 1700bp
deletion. The transcript is 3050bp long so it is not possible for me
to speculate whether Thr404 is present in the mutant.

I am cc'ing Mark Edgley from the Gene Knockout project who may have
more information.

I am sorry to not be able to help you further.

Best wishes,

Mary Ann

On 13 April 2017 at 21:04,  <no-reply@wormbase.org> wrote:
> Content Correction
>
>   I noticed that the ok1255 variant in the rsks-1 gene is still pending
> curation. We would like to know the boundaries of the deletion. Please let
> me know if this is known, if it simply needs to be curated or if the
> experiment still needs to be done. Thank you.
>
> What were you doing?
>   Trying to determine if the wild-type amino acid Thr404 is present in the
> rsks-1(ok1255) mutant.
>
> Submitted From:
>   support /tools/support
>
> This issue has been assigned ticket number: #5551. Follow progress on our
> issue tracker.
>
> Reported by: John Murphy (murphyjt@wustl.edu)
> 13 Apr 17 20:03
>
> Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko)
> Chrome/57.0.2987.133 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



--
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125


Mark Edgley
C. elegans Gene Knockout Lab
University of British Columbia
2350 Health Sciences Mall
Vancouver, BC  V6T 1Z3
Canada

604-822-0221
edgley@mail.ubc.ca

Whatever hits the fan will not be distributed evenly.


-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
