### ISSUE TITLE
it's my first time using your website, and Im havi...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5559]
*Help Desk query collected when no chat operators were online. Follow up required.*

it's my first time using your website, and Im having some difficulties finding what I need. I'm looking for a file that contains all the Caenorhabditis elegans's genes according to chromosomes. Does such a thing exist? 
thank you for your help,
Liran

**Reported by:** Lira****** (lira**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/resources/advanced/?from=http://www.wormbase.org/db/searches/advanced/dumper">http://www.wormbase.org/resources/advanced/?from=http://www.wormbase.org/db/searches/advanced/dumper</a>
**Browser:** Chrome 57.0.2987.133

**Comment by chris-grove** [comment]
Hello Liran,


You can the WormBase ParaSite BioMart (link is available under the Tools menu). Here's a URL for the query:

http://parasite.wormbase.org/biomart/martview?VIRTUALSCHEMANAME=parasite_mart&ATTRIBUTES=wbps_gene.default.feature_page.wbps_gene_id|wbps_gene.default.feature_page.external_gene_id|wbps_gene.default.feature_page.chromosome_name&FILTERS=wbps_gene.default.naive_filters.species_id_1010."elegaprjna13758"&VISIBLEPANEL=resultspanel

You can download the results as tab-delimited (.TSV) or as an Excel file (.XLS). Make sure that if you import the gene list into Excel from a tab-delimited file that you import the gene names as text, otherwise Excel (or another spreadsheet program) will likely convert many gene names into dates (e.g. sep-1, oct-1). For this reason it is probably best to download directly as an Excel file to avoid this problem.


Let us know if you need something else.


Best,


Chris Grove

WormBase
