### ISSUE TITLE
  I tried to look at the specific allel...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5570]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I tried to look at the specific allele molecular defect for a gene. When I couldn't find it I checked on other genes I know had shown their defect and they too did not show up on wormbase (rgs-2(vs17) & chd-1(ok2798)). All of these say "pending curation"<br/>Seems like something not connected?<br/>Thanks<br/>Laura</p>

**Reported by:** Laur*********** (labe**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

**Comment by tuli** [comment]
Dear Laura,

Thank you for writing to WormBase.

Molecular details of individual variations are manually curated from
the literature or from direct submissions from authors/users.
As such, we are aware that WormBase does not have the details of all
alleles which have been published.

I have done a literature search for vs17 and found that it (and other
alleles) are described in Dong M-Q et al. (2000) Genes Dev "Multiple
RGS proteins alter neural G protein signaling to allow C. elegans to
....", so I have just curated these. They will be available in release
WS260 of WormBase.

I could not find reference to ok2798 in the literature so if you can
send me the details of this lesion I will then be able to add it to
WormBase.

If you are aware of other alleles that have been characterised but are
not in WormBase you may submit them to us using our Community Curation
form: http://www.wormbase.org/submissions/allele_sequence.cgi

Best wishes,

Mary Ann

On 22 April 2017 at 14:07,  <no-reply@wormbase.org> wrote:
> Bug Report
>
>   I tried to look at the specific allele molecular defect for a gene. When I
> couldn't find it I checked on other genes I know had shown their defect and
> they too did not show up on wormbase (rgs-2(vs17) & chd-1(ok2798)). All of
> these say "pending curation"
> Seems like something not connected?
> Thanks
> Laura
>
> Submitted From:
>   support /tools/support
>
> This issue has been assigned ticket number: #5570. Follow progress on our
> issue tracker.
>
> Reported by: Laura Berkowitz (laberkowitz@ua.edu)
> 22 Apr 17 13:05
>
> Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko)
> Chrome/57.0.2987.133 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by tuli** [comment]
Dear Mary Ann,
I am sorry I was not more clear in my note. The information of the genes I was asking about had been previously available on Wormbase, which is where I found the deletion/mutant lesion info to begin with. All of those alleles had been posted and described in Wormbase in the past.
Info for the chd-1 was found by me August 2015:
RB2613
H06O01.2 ok2798:
Homozygous. Outer Left Sequence: gggaagattggggaaaagaa. Outer Right Sequence: tgcacaaaaagcttgaacca. Inner Left Sequence: catcgaaaactttcggaatga [rev: tcattccgaaagttttcgatg]. Inner Right Sequence: ggctcaccagaagcagtttt. Inner Primer PCR Length: 1197. Estimated Deletion Size: about 400 bp.

Whereas the rgs-2(vs17) info was already on Wormbase back in 2010!!

I had also looked up several other mutant alleles to make sure it wasn't a glitch with a single gene (or two) and none of these others showed their allele mutants also. I rechecked them again this morning before responding to you and they "got better"-- in other words the allele info had returned.
I am very puzzled and sorry to have bothered you.
I just want to emphasize that my e-mail was not in any way written to ask you to curate these alleles, rather to try to find out where info I thought was already in Wormbase had disappeared to?

Thank you so much for assistance.

One follow-up question: for the Community curation, does the info need to be published to be submitted?

Again, thank you for your help!

Regards,
Laura

On Apr 24, 2017, at 3:53 AM, Mary Ann Tuli <maryann.tuli@wormbase.org<mailto:maryann.tuli@wormbase.org>>
 wrote:

Dear Laura,

Thank you for writing to WormBase.

Molecular details of individual variations are manually curated from
the literature or from direct submissions from authors/users.
As such, we are aware that WormBase does not have the details of all
alleles which have been published.

I have done a literature search for vs17 and found that it (and other
alleles) are described in Dong M-Q et al. (2000) Genes Dev "Multiple
RGS proteins alter neural G protein signaling to allow C. elegans to
....", so I have just curated these. They will be available in release
WS260 of WormBase.

I could not find reference to ok2798 in the literature so if you can
send me the details of this lesion I will then be able to add it to
WormBase.

If you are aware of other alleles that have been characterised but are
not in WormBase you may submit them to us using our Community Curation
form: http://www.wormbase.org/submissions/allele_sequence.cgi

Best wishes,

Mary Ann

On 22 April 2017 at 14:07,  <no-reply@wormbase.org<mailto:no-reply@wormbase.org>> wrote:
Bug Report

 I tried to look at the specific allele molecular defect for a gene. When I
couldn't find it I checked on other genes I know had shown their defect and
they too did not show up on wormbase (rgs-2(vs17) & chd-1(ok2798)). All of
these say "pending curation"
Seems like something not connected?
Thanks
Laura

Submitted From:
 support /tools/support

This issue has been assigned ticket number: #5570. Follow progress on our
issue tracker.

Reported by: Laura Berkowitz (laberkowitz@ua.edu<mailto:laberkowitz@ua.edu>)
22 Apr 17 13:05

Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko)
Chrome/57.0.2987.133 Safari/537.36

This question was reported via the web interface at wormbase.org<http://wormbase.org>. You can
also email us directly.

--
--
You received this message because you are subscribed to the "WormBase: help"
group.
To post to this group, send email to help@wormbase.org<mailto:help@wormbase.org>
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en




--
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org<mailto:maryann.tuli@wormbase.org>
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125

**Comment by tuli** [comment]
---------- Forwarded message ----------
From: Mary Ann Tuli <maryann.tuli@wormbase.org>
Date: 25 April 2017 at 11:02
Subject: Re: [wormbase-help] Bug Report: I tried to look at the
specific allel... (Laura Berkowitz)
To: "Berkowitz, Laura" <laberkowitz@ua.edu>


Dear Laura,

Thank you for your email and for clarifying the nature of the problem.
I understand now.

Are you sure the lesion details of the ok2798 allele were associated
with the allele object in Aug 2015? Do you have an email acknowledging
inclusion in WormBase, or do you know which WS release you saw it in?
I can see the Remark in the Strain object:
http://www.wormbase.org/species/c_elegans/strain/RB2613#023416--10
(see Curatorial remarks in the Overview widget). Are the Outer Left
and Outer Right sequences the flanking sequences of the deletion? If
so, then I can curate the deletion.

Likewise, the details of the vs17 allele appear as a Curatorial Remark
in strain LX160
http://www.wormbase.org/species/c_elegans/strain/LX160#023416--10
This strain was added to WormBase in 2004.

WormBase receives Strain data from the CGC and so I shall talk to them
about alerting us to information in the Remarks which could be used to
curate other data types. It may not be straight forward since plain
text remarks are hide to mine.

I am hoping therefore that it was the Strain data you had remembered
seeing in WormBase and not the Variation data as I am pretty sure
neither
of those alleles had that information prior to yesterday!

Regarding Community Curation - no the information does not need to be
published. We will add Evidence as appropriate.

Thank you,

Mary Ann


On 24 April 2017 at 16:19, Berkowitz, Laura <laberkowitz@ua.edu> wrote:
> Dear Mary Ann,
> I am sorry I was not more clear in my note. The information of the genes I
> was asking about had been previously available on Wormbase, which is where I
> found the deletion/mutant lesion info to begin with. All of those alleles
> had been posted and described in Wormbase in the past.
> Info for the chd-1 was found by me August 2015:
>
> RB2613
>
> H06O01.2 ok2798:
>
> Homozygous. Outer Left Sequence: gggaagattggggaaaagaa. Outer Right Sequence:
> tgcacaaaaagcttgaacca. Inner Left Sequence: catcgaaaactttcggaatga [rev:
> tcattccgaaagttttcgatg]. Inner Right Sequence: ggctcaccagaagcagtttt. Inner
> Primer PCR Length: 1197. Estimated Deletion Size: about 400 bp.
>
>
> Whereas the rgs-2(vs17) info was already on Wormbase back in 2010!!
>
> I had also looked up several other mutant alleles to make sure it wasn't a
> glitch with a single gene (or two) and none of these others showed their
> allele mutants also. I rechecked them again this morning before responding
> to you and they "got better"-- in other words the allele info had returned.
> I am very puzzled and sorry to have bothered you.
> I just want to emphasize that my e-mail was not in any way written to ask
> you to curate these alleles, rather to try to find out where info I thought
> was already in Wormbase had disappeared to?
>
> Thank you so much for assistance.
>
> One follow-up question: for the Community curation, does the info need to be
> published to be submitted?
>
> Again, thank you for your help!
>
> Regards,
> Laura
>
> On Apr 24, 2017, at 3:53 AM, Mary Ann Tuli <maryann.tuli@wormbase.org>
>  wrote:
>
> Dear Laura,
>
> Thank you for writing to WormBase.
>
> Molecular details of individual variations are manually curated from
> the literature or from direct submissions from authors/users.
> As such, we are aware that WormBase does not have the details of all
> alleles which have been published.
>
> I have done a literature search for vs17 and found that it (and other
> alleles) are described in Dong M-Q et al. (2000) Genes Dev "Multiple
> RGS proteins alter neural G protein signaling to allow C. elegans to
> ....", so I have just curated these. They will be available in release
> WS260 of WormBase.
>
> I could not find reference to ok2798 in the literature so if you can
> send me the details of this lesion I will then be able to add it to
> WormBase.
>
> If you are aware of other alleles that have been characterised but are
> not in WormBase you may submit them to us using our Community Curation
> form: http://www.wormbase.org/submissions/allele_sequence.cgi
>
> Best wishes,
>
> Mary Ann
>
> On 22 April 2017 at 14:07,  <no-reply@wormbase.org> wrote:
>
> Bug Report
>
>  I tried to look at the specific allele molecular defect for a gene. When I
> couldn't find it I checked on other genes I know had shown their defect and
> they too did not show up on wormbase (rgs-2(vs17) & chd-1(ok2798)). All of
> these say "pending curation"
> Seems like something not connected?
> Thanks
> Laura
>
> Submitted From:
>  support /tools/support
>
> This issue has been assigned ticket number: #5570. Follow progress on our
> issue tracker.
>
> Reported by: Laura Berkowitz (laberkowitz@ua.edu)
> 22 Apr 17 13:05
>
> Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko)
> Chrome/57.0.2987.133 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You can
> also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help"
> group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>
>
>
> --
> ~ Mary Ann Tuli
>
> ~ email: maryann.tuli@wormbase.org
> ~ Database Curator, WormBase
>
> ~ Biology Division
> ~ California Institute of Technology
> ~ 1200 E. California Blvd
> ~ Pasadena, CA 91125
>
>



--
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125


-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
