### ISSUE TITLE
  I have a nice anatomy dictionary of w...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5606]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I have a nice anatomy dictionary of wormbase expressed reporters from wormbase's tissue enrichment analysis tool. This is a binary dictionary where's zeros represent unknown marker expression. For many gene reporters, we know that they are specifically absent in tissue subsets. Is it possible to extract this type of negative data from wormbase? I know the wormbase gene pages do NOT include information about where reporters are known NOT to be expressed, but perhaps someone has done a rough compilation of this information. The ideal anatomy dictionary would have 'X' for unknown, '0' for absent, and '1' for presence of reporter genes in specific tissues. </p><p>What were you doing? <br />&nbsp;&nbsp;clustering C. elegans single cell RNA sequencing data using semi-supervised learning -Hobert lab.</p>

**Reported by:** Lori (lag2****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36

**Comment by raymond91125** [comment]
Hi Lori,

I believe we have not really annotated 'NOT' expression data. I think 
the meaning of NOT expression has to be rather context dependent and 
it's not clear to me how useful it would be to support a large-scale 
analysis without sufficient and specific screening for the 
appropriateness of each piece of information.

When we say something is expressed, we are saying that this gene 
(product) can be found in this cell at some time, some condition. What 
do we mean if we say something is NOT expressed? Do we mean that this 
gene is not found expressed here at any time under any circumstances? 
Probably not. Most people don't even look at male animal, e.g. So then 
do we mean that this gene is not found here at a very specific time and 
circumstance? Probably not either because that may not be very 
interesting as one can probably always find a time and condition when a 
gene is not expressed even though it is expressed most of the time. Thus 
I would argue that the NOT data is meaningful or useful only with 
sufficient context. Of course positive data also have their caveats but 
just a bit less severe.

I do think expression data is a 'can of worms', if you will when we 
start to seriously consider the meaning of positive vs. negative, 
qualitative vs. quantitative, endogenous vs. artificial transgenic data. 
So we are all ears for opinions and suggestions. Your input is much 
appreciated.

Our expression data curator Daniela also works on the micropublication 
project that encourages negative data submission. She may elaborate more 
on this matter.

Best regards,

Raymond


On 05/11/2017 01:24 PM, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   I have a nice anatomy dictionary of wormbase expressed reporters 
> from wormbase's tissue enrichment analysis tool. This is a binary 
> dictionary where's zeros represent unknown marker expression. For many 
> gene reporters, we know that they are specifically absent in tissue 
> subsets. Is it possible to extract this type of negative data from 
> wormbase? I know the wormbase gene pages do NOT include information 
> about where reporters are known NOT to be expressed, but perhaps 
> someone has done a rough compilation of this information. The ideal 
> anatomy dictionary would have 'X' for unknown, '0' for absent, and '1' 
> for presence of reporter genes in specific tissues.
>
> What were you doing?
>   clustering C. elegans single cell RNA sequencing data using 
> semi-supervised learning -Hobert lab.
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #5606. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/5606>.
>
> Reported by: Lori (lag2175@columbia.edu)
> 11 May 17 20:22
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 
> (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google 
> Groups "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by raymond91125** [comment]
Hi Lori,

sorry for the late reply. To add on what Raymond said, you might find useful to take a look at the BGEE database, where they assign a positive negative call for expression based on RNAseq and microarray data.

http://bgee.org/?page=download&action=expr_calls#id5

[http://bgee.org/img/species/9606_light.jpg]<http://bgee.org/?page=download&action=expr_calls#id5>

Bgee gene expression call download page<http://bgee.org/?page=download&action=expr_calls#id5>
bgee.org
Bgee allows to automatically compare gene expression patterns between species, by referencing expression data on anatomical ontologies, and designing homology ...





Do not hesitate to reach out if you have additional questions and always consider to micropublish your unpublished results on Micropublication:biology<http://www.micropublicationbiology.org> (and convince Oliver to do so 😉)


Best,

Daniela


________________________________
