### ISSUE TITLE
I am trying to find out the sequence of daf-2(m130...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5614]
*Help Desk query collected when no chat operators were online. Follow up required.*

I am trying to find out the sequence of daf-2(m130) allele, and I think there might be a mistake in the sequence posted in the "Molecular Details". In Butcher et al, 2009, they describe a G to R missense mutation for this allele, but the DNA sequence posted on WormBase is showing a c/t mutation which does not result in a G/R substitution. However, I couldn't find the DNA sequence from the paper. Please let me know if I misunderstood what's being shown, or when the mistake is corrected. Thank you for your attention.

**Reported by:** Io L******** (IoLo********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/variation/WBVar00088593#02-45-3">http://www.wormbase.org/species/c_elegans/variation/WBVar00088593#02-45-3</a>
**Browser:** Chrome 58.0.3029.110

**Comment by tuli** [comment]
---------- Forwarded message ----------
From: Mary Ann Tuli <maryann.tuli@wormbase.org>
Date: 19 May 2017 at 10:54
Subject: Re: [wormbase-help] offline chat transcript: I am trying to find
out the sequence of daf-2(m130... (Io Long Chan)
To: no-reply@wormbase.org
Cc: "help@wormbase.org" <help@wormbase.org>, IoLong.Chan@umassmed.edu


Dear Io Long Chan,

Thank you for writing to WormBase.
I can confirm that allele m130 is annotated correctly. The confusion arises
because the daf-22 gene lies on the negative strand but WormBase reports
the lesion on the positive strand. Thus c/t corresponds to a g/a
substitution which results in gga -> aga (G to R).

It may help if you look at the Tree Display (at the bottom of the variation
summary page) where you will see that the lesion was curated on the
negative strand.

I hope this clarifies things for you, but please do not hesitate to write
again if you have further questions.

Best wishes,

Mary Ann

On 18 May 2017 at 18:22, <no-reply@wormbase.org> wrote:

> offline chat I am trying to find out the sequence of daf-2(m130) allele,
> and I think there might be a mistake in the sequence posted in the
> "Molecular Details". In Butcher et al, 2009, they describe a G to R
> missense mutation for this allele, but the DNA sequence posted on WormBase
> is showing a c/t mutation which does not result in a G/R substitution.
> However, I couldn't find the DNA sequence from the paper. Please let me
> know if I misunderstood what's being shown, or when the mistake is
> corrected. Thank you for your attention.
>
> Submitted From:
>   http://www.wormbase.org/species/c_elegans/variation/WBVar0
> 0088593#02-45-3 http://www.wormbase.org/specie
> s/c_elegans/variation/WBVar00088593#02-45-3
> <http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/variation/WBVar00088593#02-45-3>
>
> This issue has been assigned ticket number: #5614. Follow progress on our issue
> tracker <https://github.com/WormBase/website/issues/5614>.
>
> Reported by: Io Long Chan (IoLong.Chan@umassmed.edu)
> 18 May 17 17:22
>
> This question was reported via the web interface at wormbase.org. You can
> also email us <help@wormbase.org> directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>


-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125



-- 
~ Mary Ann Tuli

~ email: maryann.tuli@wormbase.org
~ Database Curator, WormBase

~ Biology Division
~ California Institute of Technology
~ 1200 E. California Blvd
~ Pasadena, CA 91125
