### ISSUE TITLE
Search for exact GO term not returning the correct result

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#5692]
When I perform a search for a specific GO term "protein glycosylation" in the search box with the "for a go term" option selected:

1) I don't see "protein glycosylation" in the suggested list of terms and

2) When I perform the search, I get the "Query too large: wildcard, synonym and phrase search disabled. Please try a more specific search term." and the correct term "protein glycosylation" is not listed anywhere in the first 30 results that do show.

This is despite the fact that there is the term and page:

http://www.wormbase.org/species/all/go_term/GO:0006486#0--10

so that the only way to find it by search is to search with the GO ID.

It would be good if we could fix that.

**Comment by tharris** [comment]
@sibyl229 this sounds like an important issue. Do you mind having a look?

**Comment by sibyl229** [comment]
Some notes for myself before I forget:
- Quoting the query `"protein glycosylation"` will help with search (but not autocompletion)
- Auto-completion on phrase doesn't seem to work (even after setting flags in the query parser, all of flag_phrase, flag_partial, flag_wildcard). 
- "Query too large" is caused by the "protein" word being indexed in a lot of places. Xapian estimates that the result would be large
- To rank "protein glycosylation" higher "regulation of protein glycosylation", the weighting scheme needs to take into account the proportion of a field that match a query (not sure how to do this in Xapian)

**Comment by chris-grove** [comment]
@sibyl229 
I found another problematic example, the GO term "histone kinase activity" (GO:0035173):

http://www.wormbase.org/species/all/go_term/GO:0035173#02--10

On live site and on staging, the autocomplete/autosuggest never matches to the correct term. Searching "for a GO term" with unquoted text "histone kinase activity" returns a search results page with 60K GO terms with the term in question not appearing on the first 7 pages of results. If I search with the quoted phrase '"histone kinase activity"', the list of results is narrowed down to 13 hits, but the exact match is at the bottom of the list (on the second page of results).

**Comment by chris-grove** [comment]
@sibyl229 
Excellent! Looks perfect! Thanks so much Sibyl!!
I will close this ticket.
