### ISSUE TITLE
Hi I am looking at srv-4 transcript b which has be...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5714]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi I am looking at srv-4 transcript b which has been 'partially confirmed by cDNA' - am I able to get any further information about this? I have also validated the transcript and just want to see if this data is worth submitting to Wormbase? Cheers, Kayla

**Reported by:** Kayl****** (u501***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00005715#0f-9e1g-10-fe">http://www.wormbase.org/species/c_elegans/gene/WBGene00005715#0f-9e1g-10-fe</a>
**Browser:** Safari 10.0

**Comment by Paul-Davis** [comment]
Dear Kayla,

We always welcome additional sequence data for confirming gene 
structures. We encourage community members to submit their sequence data 
to the public INSDC databases so that the confirming data is accessioned 
and attribution is given.

I'd definitely be interested in seeing the sequence data.

Paul

On 27/06/2017 03:42, no-reply@wormbase.org wrote:
> offline chat Hi I am looking at srv-4 transcript b which has been 
> 'partially confirmed by cDNA' - am I able to get any further 
> information about this? I have also validated the transcript and just 
> want to see if this data is worth submitting to Wormbase? Cheers, Kayla
>
> Submitted From:
>   http://www.wormbase.org/species/c_elegans/gene/WBGene00005715#0f-9e1g-10-fe 
> http://www.wormbase.org/species/c_elegans/gene/WBGene00005715#0f-9e1g-10-fe 
> <http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00005715#0f-9e1g-10-fe> 
>
>
> This issue has been assigned ticket number: #5714. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/5714>.
>
> Reported by: Kayla Venn (u5011162@anu.edu.au)
> 27 Jun 17 02:41
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
User hasn't responded but hopefully they will submit their sequence data to INSDC
