### ISSUE TITLE
  Hello I have been trying to access th...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5731]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello<br/>I have been trying to access the SPELL Gene expression website with no success. URL = http://spell.caltech.edu:3000. I believe this is a site affiliated with Wormbase? </p><p>What were you doing? <br />&nbsp;&nbsp;Just trying to search for genes correlated in their expression with dat-1, cat-1, cat-2 etc. Tried Safari, Firefox, Google Chrome. Just can't get beyond home page. Search crashes. Any help would be great</p>

**Reported by:** Rand********* (rbla*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/601.6.17 (KHTML, like Gecko) Version/9.1.1 Safari/601.6.17

**Comment by WenChenWormBase** [comment]
Randy, I just tried the site, it works. Please try again.

SPELL sometimes freezes when heavily used by multiple users.

On Sun, Jul 9, 2017 at 3:32 PM, <no-reply@wormbase.org> wrote:

> Bug Report
>
>   Hello
> I have been trying to access the SPELL Gene expression website with no
> success. URL = http://spell.caltech.edu:3000. I believe this is a site
> affiliated with Wormbase?
>
> What were you doing?
>   Just trying to search for genes correlated in their expression with
> dat-1, cat-1, cat-2 etc. Tried Safari, Firefox, Google Chrome. Just can't
> get beyond home page. Search crashes. Any help would be great
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #5731. Follow progress on our issue
> tracker <https://github.com/WormBase/website/issues/5731>.
>
> Reported by: Randy Blakely (rblakely@health.fau.edu)
> 09 Jul 17 22:30
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/601.6.17
> (KHTML, like Gecko) Version/9.1.1 Safari/601.6.17
>
> This question was reported via the web interface at wormbase.org. You can
> also email us <help@wormbase.org> directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>


-- 
Wen Chen, Ph.D.
Curator, WormBase

**Comment by WenChenWormBase** [comment]
Hi there
Tell me what gene you searched and which browser were you using?
Thanks!

Randy

On Jul 9, 2017, at 7:33 PM, Wen Chen <wen@wormbase.org<mailto:wen@wormbase.org>> wrote:

Randy, I just tried the site, it works. Please try again.

SPELL sometimes freezes when heavily used by multiple users.

On Sun, Jul 9, 2017 at 3:32 PM, <no-reply@wormbase.org<mailto:no-reply@wormbase.org>> wrote:
Bug Report

  Hello
I have been trying to access the SPELL Gene expression website with no success. URL = http://spell.caltech.edu:3000. I believe this is a site affiliated with Wormbase?

What were you doing?
  Just trying to search for genes correlated in their expression with dat-1, cat-1, cat-2 etc. Tried Safari, Firefox, Google Chrome. Just can't get beyond home page. Search crashes. Any help would be great

Submitted From:
  support /tools/support<http://www.wormbase.org//tools/support>

This issue has been assigned ticket number: #5731. Follow progress on our issue tracker<https://github.com/WormBase/website/issues/5731>.

Reported by: Randy Blakely (rblakely@health.fau.edu<mailto:rblakely@health.fau.edu>)
09 Jul 17 22:30

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/601.6.17 (KHTML, like Gecko) Version/9.1.1 Safari/601.6.17

This question was reported via the web interface at wormbase.org<http://wormbase.org>. You can also email us<mailto:help@wormbase.org> directly.

--
--
You received this message because you are subscribed to the "WormBase: help" group.
To post to this group, send email to help@wormbase.org<mailto:help@wormbase.org>
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org<mailto:help%2Bunsubscribe@wormbase.org>
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en




--
Wen Chen, Ph.D.
Curator, WormBase
________________________________
CONFIDENTIALITY NOTICE: The information contained in this transmission may contain privileged and confidential information, including patient information protected by federal and state privacy laws. It is intended only for the use of the person(s) named above. If you are not the intended recipient, you are hereby notified that any review, dissemination, distribution, or duplication of this communication is strictly prohibited. If you are not the intended recipient, please contact the sender by reply email, report the error to FAU’s Chief Compliance Officer, and destroy all copies of the original message.
________________________________

**Comment by WenChenWormBase** [comment]
Sorry Randy, I just restarted the server. It should be working now.

http://spell.caltech.edu:3000/

I searched for lin-3 and it worked.


On Sun, Jul 9, 2017 at 4:34 PM, Randy Blakely <rblakely@health.fau.edu>
wrote:

> Hi there
> Tell me what gene you searched and which browser were you using?
> Thanks!
>
> Randy
>
> On Jul 9, 2017, at 7:33 PM, Wen Chen <wen@wormbase.org> wrote:
>
> Randy, I just tried the site, it works. Please try again.
>
> SPELL sometimes freezes when heavily used by multiple users.
>
> On Sun, Jul 9, 2017 at 3:32 PM, <no-reply@wormbase.org> wrote:
>
>> Bug Report
>>
>>   Hello
>> I have been trying to access the SPELL Gene expression website with no
>> success. URL = http://spell.caltech.edu:3000. I believe this is a site
>> affiliated with Wormbase?
>>
>> What were you doing?
>>   Just trying to search for genes correlated in their expression with
>> dat-1, cat-1, cat-2 etc. Tried Safari, Firefox, Google Chrome. Just can't
>> get beyond home page. Search crashes. Any help would be great
>>
>> Submitted From:
>>   support /tools/support <http://www.wormbase.org//tools/support>
>>
>> This issue has been assigned ticket number: #5731. Follow progress on our issue
>> tracker <https://github.com/WormBase/website/issues/5731>.
>>
>> Reported by: Randy Blakely (rblakely@health.fau.edu)
>> 09 Jul 17 22:30
>>
>> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/601.6.17
>> (KHTML, like Gecko) Version/9.1.1 Safari/601.6.17
>>
>> This question was reported via the web interface at wormbase.org. You
>> can also email us <help@wormbase.org> directly.
>>
>> --
>> --
>> You received this message because you are subscribed to the "WormBase:
>> help" group.
>> To post to this group, send email to help@wormbase.org
>> To unsubscribe from this group, send email to
>> help+unsubscribe@wormbase.org
>> For more options, visit this group at
>> http://groups.google.com/a/wormbase.org/group/help?hl=en
>>
>>
>
>
> --
> Wen Chen, Ph.D.
> Curator, WormBase
>
> ------------------------------
> CONFIDENTIALITY NOTICE: The information contained in this transmission may
> contain privileged and confidential information, including patient
> information protected by federal and state privacy laws. It is intended
> only for the use of the person(s) named above. If you are not the intended
> recipient, you are hereby notified that any review, dissemination,
> distribution, or duplication of this communication is strictly prohibited.
> If you are not the intended recipient, please contact the sender by reply
> email, report the error to FAU’s Chief Compliance Officer, and destroy all
> copies of the original message.
> ------------------------------
>



-- 
Wen Chen, Ph.D.
Curator, WormBase

**Comment by Paul-Davis** [comment]
Assume resolved
