### ISSUE TITLE
  Is there somewhere a good explanation...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5755]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Is there somewhere a good explanation of the features in the genome browser? For example - I'm looking at modencode transcription factor binding data for a promoter I'm interested in, and some transcription factors show orange boxes over parts of the sequence - what do these represent and how were they identified? it looks like those regions have been called as peaks in some way, but sometimes it isn't clear to me why some peaks have a box and others do not. Is there an explanation of this and other similar features somewhere? Thanks!</p>

**Reported by:** Tama* (resn************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

**Comment by gw3** [comment]
Tamar,

I assume you are using Gbrowse. I managed to reproduce the orange box 
using it (see attached picture).
The peaks of most of the modENCODE tracks are displayed with a vertical 
scale that is dynamically changed (by default) to represent the local 
min and max value in a track.
If the value to be displayed goes above the max value in the track then 
the orange box is displayed to warn the user that the peak should be 
higher than displayed.

I don't know why the vertical scale is not changed instead of displaying 
the orange box.
The Y-axis scaling can be changed by clicking on the small red box with 
a spanner in on the track label on the left.

Gary Williams

------------------------------------------------------------------------
*From:* no-reply@wormbase.org <no-reply@wormbase.org>
*Sent:* Monday, July 17, 2017 3:35 PM
*To:* help@wormbase.org
*Cc:* resni030@Umn.edu
*Subject:* [MARKETING] [wormbase-help] How Do I ...?: Is there somewhere 
a good explanation... (Tamar)
How Do I ...?

   Is there somewhere a good explanation of the features in the genome 
browser? For example - I'm looking at modencode transcription factor 
binding data for a promoter I'm interested in, and some transcription 
factors show orange boxes over parts of the sequence - what do these 
represent and how were they identified? it looks like those regions have 
been called as peaks in some way, but sometimes it isn't clear to me why 
some peaks have a box and others do not. Is there an explanation of this 
and other similar features somewhere? Thanks!

Submitted From:
   support /tools/support <http://www.wormbase.org//tools/support>

This issue has been assigned ticket number: #5755. Follow progress on 
our issue tracker <https://github.com/WormBase/website/issues/5755>.

Reported by: Tamar (resni030@Umn.edu)
17 Jul 17 22:36

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 
(KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

This question was reported via the web interface at wormbase.org. You 
can also email us <mailto:help@wormbase.org> directly.

-- 
-- 
You received this message because you are subscribed to the "WormBase: 
help" group.
To post to this group, send email to help@wormbase.org
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en

---
You received this message because you are subscribed to the Google 
Groups "WormBase: help" group.
To unsubscribe from this group and stop receiving emails from it, send 
an email to help+unsubscribe@wormbase.org 
<mailto:help+unsubscribe@wormbase.org>.

**Comment by scottcain** [comment]
This was sent to the requester:

I'm the maintainer of GBrowse and JBrowse at WormBase. Can you give me a little more information about what exactly you want to do (like what promotor and region you want to look at)?  I would like to improve the way data like that from modENCODE are found and used, and so having example problems to solve would be great.
