### ISSUE TITLE
  Dear WormBase team, I was wondering i...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5794]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Dear WormBase team,<br/>I was wondering if you have included the information about the improved 3'UTR annotation published by Jan et al. (Nature 2011) and Mangone et al. (Science 2010) into the C. elegans genome annotation? Is it already included in WS250? <br/>Thanks in advance.<br/>Kind regards,<br/>Asija</p><p>What were you doing? <br />&nbsp;&nbsp;PhD student</p>

**Reported by:** asij********************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7

**Comment by chris-grove** [comment]
Hello Asija,


Thank you for writing to WormBase. I do not know the answer to your question off hand. Someone from our sequence curation will get back to you soon with an answer.


Best,


Chris Grove

WormBase Help Desk

**Comment by Paul-Davis** [comment]
Dear Asija,

We did incorporate the UTRome data into WormBase back prior to WS250, 
but this data is available as a separate track on the genome browser. 
The decision to make them into features rather than adding them to the 
gene models was that as these were primarily PCR based utilising primers 
designed against both WormBase and predicted gene structures then there 
might be artificial false +ves produced because the existing annotation 
was incorrect. Also some of the sequencing was incomplete so splicing in 
the UTR was also missing/not represented in the data we were given.

Here is a link to the genome browser to view the UTRome data: 
*http://tinyurl.com/Example-UTRome-gbrowse*

I hope this answers your question.

Paul


On 01/08/2017 14:28, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   Dear WormBase team,
> I was wondering if you have included the information about the 
> improved 3'UTR annotation published by Jan et al. (Nature 2011) and 
> Mangone et al. (Science 2010) into the C. elegans genome annotation? 
> Is it already included in WS250?
> Thanks in advance.
> Kind regards,
> Asija
>
> What were you doing?
>   PhD student
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #5794. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/5794>.
>
> Reported by: asija.diag@mdc-berlin.de
> 01 Aug 17 13:28
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 
> (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by chris-grove** [comment]
Thanks @Paul-Davis !
