### ISSUE TITLE
For gene tag-307 (ZK652.10), I think the phenotype...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5832]
*Help Desk query collected when no chat operators were online. Follow up required.*

For gene tag-307 (ZK652.10), I think the phenotype annotation is wrong. It says the following phenotypes have been observed: coenzyme Q depleted, life span variant, and mitochondrial metabolism variant. Evidence is from Asencio et al, 2003 paper. However, these phenotypes are reported for neighboring gene coq-5 (ZK652.10) in the paper, not ZK652.9

**Reported by:** Maul******** (maul*************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00022787#0f2c49g1de638b--10">http://www.wormbase.org/species/c_elegans/gene/WBGene00022787#0f2c49g1de638b--10</a>
**Browser:** Firefox 50.0

**Comment by raymond91125** [comment]
Hi Maulik,

Our RNAi record indicates that the target sequences cover both genes. Do 
you think the paper says something different?

Thanks.

Raymond

**Comment by raymond91125** [comment]
Maulik,
According to the paper, the primers used for coq-5 amplify the following which covers parts of coq-5 and tag-307

tcacgaggtccaagccatgatctgtttggatttgtgtatctttcaacaagttctggcttcattgcaatatcataaagtccaatgccatcgtgagatgcgttgaaaatgtggtcgaagagatcgtggtcaaaattgacacctccggatggagtaaatgggataatatcttcatgtgagacacagtccataccactgaaaataatttttgaattgaaggagtttttattatgaaaaaatttctttaaaatatacgaaatcatatttttattttgattttttagaaaactgattttgtcgctttcaaaaaaggtgttggtgttgaggattgttccaatcaataatattttttaattatctcatttacaaaaatcaccgtacttgattagagtcaacattttttgtccgtgtcttttattctccattggtgcatctaccaaatacgatgtaatatctactgggaatcccatatgactccagtcatagcgatgaatgagaacttggtagaaatcacgcgtaagaagatgcttttcgctaaaaaaaaatttaaaatcagaatagcagaaatttattgctacttacttttgttgacttcttttttcatgtaatctacatggaaaagagcaaacaacgactcctttgtaagcaaatgttttgtgaatgaaaatctgcaatttaatatttttgcaaaataactggattgagtcaaccaacttgtccagcttcaaatgttggtttattagttgatggcaagagaagtccaatttctttcaatattggcgttgtggcgcttctgaatcttaaaaatgatgattatcgagtctgaaatcatctataaattaccttgacagtaagactttcccagcggaaaagtttcttacactgtgctgaatagcacttcgaagtttcatatctgaaattgttggaataaacatgaattttttcagattttttgagtaacaacgggaataaaccacggaatcatagatgtcaggaaatacaaatataacaactttaattaaatttatgcaaaaattctacacgaaaaatactgaatatcacctagaaaaatggaattaaatgaaattttaaaaagaacaaacaaacaggaataaattattttcttggtttcatccccttatgaatcgagcacactccaaatgtcaaattctcgtatcgaacattactaaagccttcttctctaattattcttgcaaactcgtcttgattcgggaatttacgaatactctcaaccaaatattgataactggcacgatcactggcaagaatttctccaagaaccgggatcacattgaaggagtatgcatcgtaaattggtttcagtgcagaattcacttctgagaactccaaaatagcaagttgacctccaggtttgagtacacgaaaagcttcacgaacaaccttttcagggtgtgtacaatttctgattccgaaggacattgtgaacagatcgtaagtgttcgactcaaatggcatttgctcggcgttagcgcatacccattccgcgcgagatggttggatctgaagtaatacattaaggatatggaattttttcaaaaacaattacatctctctccttctccgctcgtttttttccaacatcgagcattggttgattaatatcggaaactgtcacttttgcggtaggcgaatgtc
Hope this helps
Gary

On Sep 5, 2017, at 8:39 AM, raymond <raymond@caltech.edu<mailto:raymond@caltech.edu>> wrote:


Hi Maulik,

Our RNAi record indicates that the target sequences cover both genes. Do you think the paper says something different?

Thanks.

Raymond


On 09/05/2017 08:21 AM, no-reply@wormbase.org<mailto:no-reply@wormbase.org> wrote:
offline chat For gene tag-307 (ZK652.10), I think the phenotype annotation is wrong. It says the following phenotypes have been observed: coenzyme Q depleted, life span variant, and mitochondrial metabolism variant. Evidence is from Asencio et al, 2003 paper. However, these phenotypes are reported for neighboring gene coq-5 (ZK652.10) in the paper, not ZK652.9

Submitted From:
  http://www.wormbase.org/species/c_elegans/gene/WBGene00022787#0f2c49g1de638b--10http://www.wormbase.org/species/c_elegans/gene/WBGene00022787#0f2c49g1de638b--10<http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00022787#0f2c49g1de638b--10>

This issue has been assigned ticket number: #5832. Follow progress on our issue tracker<https://github.com/WormBase/website/issues/5832>.


Reported by: Maulik Patel (maulik.r.patel@vanderbilt.edu<mailto:maulik.r.patel@vanderbilt.edu>)
05 Sep 17 15:22


This question was reported via the web interface at wormbase.org<http://wormbase.org>. You can also email us<mailto:help@wormbase.org> directly.

--
--
You received this message because you are subscribed to the "WormBase: help" group.
To post to this group, send email to help@wormbase.org<mailto:help@wormbase.org>
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en

---
You received this message because you are subscribed to the Google Groups "WormBase: help" group.
To unsubscribe from this group and stop receiving emails from it, send an email to help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>.


--
--
You received this message because you are subscribed to the "WormBase: help" group.
To post to this group, send email to help@wormbase.org<mailto:help@wormbase.org>
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en

---
You received this message because you are subscribed to the Google Groups "WormBase: help" group.
To unsubscribe from this group and stop receiving emails from it, send an email to help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>.

**Comment by raymond91125** [comment]
Hi Gary,

So looks like they inadvertently targeted two genes, one of which they were unaware of. That’s very useful and good to know. Thank you for the information.

Best,
Maulik

From: "Schindelman, Gary C." <garys@caltech.edu<mailto:garys@caltech.edu>>
Date: Tuesday, September 5, 2017 at 1:14 PM
To: "Lee, Raymond" <raymond@caltech.edu<mailto:raymond@caltech.edu>>
Cc: Maulik Patel <maulik.r.patel@vanderbilt.edu<mailto:maulik.r.patel@vanderbilt.edu>>, "reply@reply.github.com<mailto:reply@reply.github.com>" <reply@reply.github.com<mailto:reply@reply.github.com>>, "help@wormbase.org<mailto:help@wormbase.org>" <help@wormbase.org<mailto:help@wormbase.org>>
Subject: Re: [MARKETING] [wormbase-help] offline chat transcript: For gene tag-307 (ZK652.10), I think the phenotype... (Maulik Patel)

Maulik,
According to the paper, the primers used for coq-5 amplify the following which covers parts of coq-5 and tag-307

tcacgaggtccaagccatgatctgtttggatttgtgtatctttcaacaagttctggcttcattgcaatatcataaagtccaatgccatcgtgagatgcgttgaaaatgtggtcgaagagatcgtggtcaaaattgacacctccggatggagtaaatgggataatatcttcatgtgagacacagtccataccactgaaaataatttttgaattgaaggagtttttattatgaaaaaatttctttaaaatatacgaaatcatatttttattttgattttttagaaaactgattttgtcgctttcaaaaaaggtgttggtgttgaggattgttccaatcaataatattttttaattatctcatttacaaaaatcaccgtacttgattagagtcaacattttttgtccgtgtcttttattctccattggtgcatctaccaaatacgatgtaatatctactgggaatcccatatgactccagtcatagcgatgaatgagaacttggtagaaatcacgcgtaagaagatgcttttcgctaaaaaaaaatttaaaatcagaatagcagaaatttattgctacttacttttgttgacttcttttttcatgtaatctacatggaaaagagcaaacaacgactcctttgtaagcaaatgttttgtgaatgaaaatctgcaatttaatatttttgcaaaataactggattgagtcaaccaacttgtccagcttcaaatgttggtttattagttgatggcaagagaagtccaatttctttcaatattggcgttgtggcgcttctgaatcttaaaaatgatgattatcgagtctgaaatcatctataaattaccttgacagtaagactttcccagcggaaaagtttcttacactgtgctgaatagcacttcgaagtttcatatctgaaattgttggaataaacatgaattttttcagattttttgagtaacaacgggaataaaccacggaatcatagatgtcaggaaatacaaatataacaactttaattaaatttatgcaaaaattctacacgaaaaatactgaatatcacctagaaaaatggaattaaatgaaattttaaaaagaacaaacaaacaggaataaattattttcttggtttcatccccttatgaatcgagcacactccaaatgtcaaattctcgtatcgaacattactaaagccttcttctctaattattcttgcaaactcgtcttgattcgggaatttacgaatactctcaaccaaatattgataactggcacgatcactggcaagaatttctccaagaaccgggatcacattgaaggagtatgcatcgtaaattggtttcagtgcagaattcacttctgagaactccaaaatagcaagttgacctccaggtttgagtacacgaaaagcttcacgaacaaccttttcagggtgtgtacaatttctgattccgaaggacattgtgaacagatcgtaagtgttcgactcaaatggcatttgctcggcgttagcgcatacccattccgcgcgagatggttggatctgaagtaatacattaaggatatggaattttttcaaaaacaattacatctctctccttctccgctcgtttttttccaacatcgagcattggttgattaatatcggaaactgtcacttttgcggtaggcgaatgtc
Hope this helps
Gary

On Sep 5, 2017, at 8:39 AM, raymond <raymond@caltech.edu<mailto:raymond@caltech.edu>> wrote:


Hi Maulik,

Our RNAi record indicates that the target sequences cover both genes. Do you think the paper says something different?

Thanks.

Raymond


On 09/05/2017 08:21 AM, no-reply@wormbase.org<mailto:no-reply@wormbase.org> wrote:
offline chat For gene tag-307 (ZK652.10), I think the phenotype annotation is wrong. It says the following phenotypes have been observed: coenzyme Q depleted, life span variant, and mitochondrial metabolism variant. Evidence is from Asencio et al, 2003 paper. However, these phenotypes are reported for neighboring gene coq-5 (ZK652.10) in the paper, not ZK652.9

Submitted From:
  http://www.wormbase.org/species/c_elegans/gene/WBGene00022787#0f2c49g1de638b--10<https://na01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.wormbase.org%2Fspecies%2Fc_elegans%2Fgene%2FWBGene00022787%230f2c49g1de638b--10&data=02%7C01%7Cmaulik.r.patel%40vanderbilt.edu%7Cadf14a56499f4d7b244e08d4f489ea08%7Cba5a7f39e3be4ab3b45067fa80faecad%7C0%7C0%7C636402320556657024&sdata=qW5Yw8nwilMFXnEP2MLBfLNjvDoqki1HxRzgXnxxENw%3D&reserved=0>http://www.wormbase.org/species/c_elegans/gene/WBGene00022787#0f2c49g1de638b--10<https://na01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.wormbase.org%2Fhttp%3A%2F%2Fwww.wormbase.org%2Fspecies%2Fc_elegans%2Fgene%2FWBGene00022787%230f2c49g1de638b--10&data=02%7C01%7Cmaulik.r.patel%40vanderbilt.edu%7Cadf14a56499f4d7b244e08d4f489ea08%7Cba5a7f39e3be4ab3b45067fa80faecad%7C0%7C0%7C636402320556657024&sdata=PCegq989VaZpsAijefALr7KrTvM0y%2FTo3dGxcbkeiLU%3D&reserved=0>

This issue has been assigned ticket number: #5832. Follow progress on our issue tracker<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FWormBase%2Fwebsite%2Fissues%2F5832&data=02%7C01%7Cmaulik.r.patel%40vanderbilt.edu%7Cadf14a56499f4d7b244e08d4f489ea08%7Cba5a7f39e3be4ab3b45067fa80faecad%7C0%7C0%7C636402320556657024&sdata=AZEIdcYUzBHmw4FBD1E3McU%2F41x1wy%2F7XAEHJWySeFo%3D&reserved=0>.


Reported by: Maulik Patel (maulik.r.patel@vanderbilt.edu<mailto:maulik.r.patel@vanderbilt.edu>)
05 Sep 17 15:22


This question was reported via the web interface at wormbase.org<https://na01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwormbase.org&data=02%7C01%7Cmaulik.r.patel%40vanderbilt.edu%7Cadf14a56499f4d7b244e08d4f489ea08%7Cba5a7f39e3be4ab3b45067fa80faecad%7C0%7C0%7C636402320556657024&sdata=PVWkoVcpUY1FM5jm3%2FuSpK8SXaCW%2BKI16HxHhrlV1Jk%3D&reserved=0>. You can also email us<mailto:help@wormbase.org> directly.

--
--
You received this message because you are subscribed to the "WormBase: help" group.
To post to this group, send email to help@wormbase.org<mailto:help@wormbase.org>
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en<https://na01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fgroups.google.com%2Fa%2Fwormbase.org%2Fgroup%2Fhelp%3Fhl%3Den&data=02%7C01%7Cmaulik.r.patel%40vanderbilt.edu%7Cadf14a56499f4d7b244e08d4f489ea08%7Cba5a7f39e3be4ab3b45067fa80faecad%7C0%7C0%7C636402320556657024&sdata=vw2zOVLjiLp1S1KNr5j%2B7%2FfZzneN7jemCizVwv2yGEA%3D&reserved=0>

---
You received this message because you are subscribed to the Google Groups "WormBase: help" group.
To unsubscribe from this group and stop receiving emails from it, send an email to help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>.


--
--
You received this message because you are subscribed to the "WormBase: help" group.
To post to this group, send email to help@wormbase.org<mailto:help@wormbase.org>
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en<https://na01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fgroups.google.com%2Fa%2Fwormbase.org%2Fgroup%2Fhelp%3Fhl%3Den&data=02%7C01%7Cmaulik.r.patel%40vanderbilt.edu%7Cadf14a56499f4d7b244e08d4f489ea08%7Cba5a7f39e3be4ab3b45067fa80faecad%7C0%7C0%7C636402320556813272&sdata=J3Zbj%2BDUqFH0Y101jdKRF4MOmM%2Ffn%2FnaX1saEfwQt4g%3D&reserved=0>

---
You received this message because you are subscribed to the Google Groups "WormBase: help" group.
To unsubscribe from this group and stop receiving emails from it, send an email to help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>.

**Comment by raymond91125** [comment]
Hi Gary,

So looks like they inadvertently targeted two genes, one of which they were unaware of. That’s very useful and good to know. Thank you for the information.

Best,
Maulik

**Comment by raymond91125** [comment]
Maulik,
No worries, glad to be of help.
Gary
On Sep 5, 2017, at 12:41 PM, Patel, Maulik R <maulik.r.patel@vanderbilt.edu<mailto:maulik.r.patel@vanderbilt.edu>> wrote:

Hi Gary,

So looks like they inadvertently targeted two genes, one of which they were unaware of. That’s very useful and good to know. Thank you for the information.

Best,
Maulik

From: "Schindelman, Gary C." <garys@caltech.edu<mailto:garys@caltech.edu>>
Date: Tuesday, September 5, 2017 at 1:14 PM
To: "Lee, Raymond" <raymond@caltech.edu<mailto:raymond@caltech.edu>>
Cc: Maulik Patel <maulik.r.patel@vanderbilt.edu<mailto:maulik.r.patel@vanderbilt.edu>>, "reply@reply.github.com<mailto:reply@reply.github.com>" <reply@reply.github.com<mailto:reply@reply.github.com>>, "help@wormbase.org<mailto:help@wormbase.org>" <help@wormbase.org<mailto:help@wormbase.org>>
Subject: Re: [MARKETING] [wormbase-help] offline chat transcript: For gene tag-307 (ZK652.10), I think the phenotype... (Maulik Patel)

Maulik,
According to the paper, the primers used for coq-5 amplify the following which covers parts of coq-5 and tag-307

tcacgaggtccaagccatgatctgtttggatttgtgtatctttcaacaagttctggcttcattgcaatatcataaagtccaatgccatcgtgagatgcgttgaaaatgtggtcgaagagatcgtggtcaaaattgacacctccggatggagtaaatgggataatatcttcatgtgagacacagtccataccactgaaaataatttttgaattgaaggagtttttattatgaaaaaatttctttaaaatatacgaaatcatatttttattttgattttttagaaaactgattttgtcgctttcaaaaaaggtgttggtgttgaggattgttccaatcaataatattttttaattatctcatttacaaaaatcaccgtacttgattagagtcaacattttttgtccgtgtcttttattctccattggtgcatctaccaaatacgatgtaatatctactgggaatcccatatgactccagtcatagcgatgaatgagaacttggtagaaatcacgcgtaagaagatgcttttcgctaaaaaaaaatttaaaatcagaatagcagaaatttattgctacttacttttgttgacttcttttttcatgtaatctacatggaaaagagcaaacaacgactcctttgtaagcaaatgttttgtgaatgaaaatctgcaatttaatatttttgcaaaataactggattgagtcaaccaacttgtccagcttcaaatgttggtttattagttgatggcaagagaagtccaatttctttcaatattggcgttgtggcgcttctgaatcttaaaaatgatgattatcgagtctgaaatcatctataaattaccttgacagtaagactttcccagcggaaaagtttcttacactgtgctgaatagcacttcgaagtttcatatctgaaattgttggaataaacatgaattttttcagattttttgagtaacaacgggaataaaccacggaatcatagatgtcaggaaatacaaatataacaactttaattaaatttatgcaaaaattctacacgaaaaatactgaatatcacctagaaaaatggaattaaatgaaattttaaaaagaacaaacaaacaggaataaattattttcttggtttcatccccttatgaatcgagcacactccaaatgtcaaattctcgtatcgaacattactaaagccttcttctctaattattcttgcaaactcgtcttgattcgggaatttacgaatactctcaaccaaatattgataactggcacgatcactggcaagaatttctccaagaaccgggatcacattgaaggagtatgcatcgtaaattggtttcagtgcagaattcacttctgagaactccaaaatagcaagttgacctccaggtttgagtacacgaaaagcttcacgaacaaccttttcagggtgtgtacaatttctgattccgaaggacattgtgaacagatcgtaagtgttcgactcaaatggcatttgctcggcgttagcgcatacccattccgcgcgagatggttggatctgaagtaatacattaaggatatggaattttttcaaaaacaattacatctctctccttctccgctcgtttttttccaacatcgagcattggttgattaatatcggaaactgtcacttttgcggtaggcgaatgtc
Hope this helps
Gary

On Sep 5, 2017, at 8:39 AM, raymond <raymond@caltech.edu<mailto:raymond@caltech.edu>> wrote:


Hi Maulik,

Our RNAi record indicates that the target sequences cover both genes. Do you think the paper says something different?

Thanks.

Raymond


On 09/05/2017 08:21 AM, no-reply@wormbase.org<mailto:no-reply@wormbase.org> wrote:
offline chat For gene tag-307 (ZK652.10), I think the phenotype annotation is wrong. It says the following phenotypes have been observed: coenzyme Q depleted, life span variant, and mitochondrial metabolism variant. Evidence is from Asencio et al, 2003 paper. However, these phenotypes are reported for neighboring gene coq-5 (ZK652.10) in the paper, not ZK652.9

Submitted From:
  http://www.wormbase.org/species/c_elegans/gene/WBGene00022787#0f2c49g1de638b--10<https://na01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.wormbase.org%2Fspecies%2Fc_elegans%2Fgene%2FWBGene00022787%230f2c49g1de638b--10&data=02%7C01%7Cmaulik.r.patel%40vanderbilt.edu%7Cadf14a56499f4d7b244e08d4f489ea08%7Cba5a7f39e3be4ab3b45067fa80faecad%7C0%7C0%7C636402320556657024&sdata=qW5Yw8nwilMFXnEP2MLBfLNjvDoqki1HxRzgXnxxENw%3D&reserved=0>http://www.wormbase.org/species/c_elegans/gene/WBGene00022787#0f2c49g1de638b--10<https://na01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.wormbase.org%2Fhttp%3A%2F%2Fwww.wormbase.org%2Fspecies%2Fc_elegans%2Fgene%2FWBGene00022787%230f2c49g1de638b--10&data=02%7C01%7Cmaulik.r.patel%40vanderbilt.edu%7Cadf14a56499f4d7b244e08d4f489ea08%7Cba5a7f39e3be4ab3b45067fa80faecad%7C0%7C0%7C636402320556657024&sdata=PCegq989VaZpsAijefALr7KrTvM0y%2FTo3dGxcbkeiLU%3D&reserved=0>

This issue has been assigned ticket number: #5832. Follow progress on our issue tracker<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FWormBase%2Fwebsite%2Fissues%2F5832&data=02%7C01%7Cmaulik.r.patel%40vanderbilt.edu%7Cadf14a56499f4d7b244e08d4f489ea08%7Cba5a7f39e3be4ab3b45067fa80faecad%7C0%7C0%7C636402320556657024&sdata=AZEIdcYUzBHmw4FBD1E3McU%2F41x1wy%2F7XAEHJWySeFo%3D&reserved=0>.


Reported by: Maulik Patel (maulik.r.patel@vanderbilt.edu<mailto:maulik.r.patel@vanderbilt.edu>)
05 Sep 17 15:22


This question was reported via the web interface at wormbase.org<https://na01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwormbase.org&data=02%7C01%7Cmaulik.r.patel%40vanderbilt.edu%7Cadf14a56499f4d7b244e08d4f489ea08%7Cba5a7f39e3be4ab3b45067fa80faecad%7C0%7C0%7C636402320556657024&sdata=PVWkoVcpUY1FM5jm3%2FuSpK8SXaCW%2BKI16HxHhrlV1Jk%3D&reserved=0>. You can also email us<mailto:help@wormbase.org> directly.

--
--
You received this message because you are subscribed to the "WormBase: help" group.
To post to this group, send email to help@wormbase.org<mailto:help@wormbase.org>
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en<https://na01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fgroups.google.com%2Fa%2Fwormbase.org%2Fgroup%2Fhelp%3Fhl%3Den&data=02%7C01%7Cmaulik.r.patel%40vanderbilt.edu%7Cadf14a56499f4d7b244e08d4f489ea08%7Cba5a7f39e3be4ab3b45067fa80faecad%7C0%7C0%7C636402320556657024&sdata=vw2zOVLjiLp1S1KNr5j%2B7%2FfZzneN7jemCizVwv2yGEA%3D&reserved=0>

---
You received this message because you are subscribed to the Google Groups "WormBase: help" group.
To unsubscribe from this group and stop receiving emails from it, send an email to help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>.


--
--
You received this message because you are subscribed to the "WormBase: help" group.
To post to this group, send email to help@wormbase.org<mailto:help@wormbase.org>
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en<https://na01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fgroups.google.com%2Fa%2Fwormbase.org%2Fgroup%2Fhelp%3Fhl%3Den&data=02%7C01%7Cmaulik.r.patel%40vanderbilt.edu%7Cadf14a56499f4d7b244e08d4f489ea08%7Cba5a7f39e3be4ab3b45067fa80faecad%7C0%7C0%7C636402320556813272&sdata=J3Zbj%2BDUqFH0Y101jdKRF4MOmM%2Ffn%2FnaX1saEfwQt4g%3D&reserved=0>

---
You received this message because you are subscribed to the Google Groups "WormBase: help" group.
To unsubscribe from this group and stop receiving emails from it, send an email to help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>.


--
--
You received this message because you are subscribed to the "WormBase: help" group.
To post to this group, send email to help@wormbase.org<mailto:help@wormbase.org>
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en

---
You received this message because you are subscribed to the Google Groups "WormBase: help" group.
To unsubscribe from this group and stop receiving emails from it, send an email to help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>.
