### ISSUE TITLE
what's the whole name of neuron CANL or CANR in wo...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5838]
*Help Desk query collected when no chat operators were online. Follow up required.*

what's the whole name of neuron CANL or CANR in worm.

**Reported by:** Mei (shid**********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/search/basic/CAN?from=http://www.wormbase.org/db/searches/basic?class=Cell&amp;query=CAN">http://www.wormbase.org/search/basic/CAN?from=http://www.wormbase.org/db/searches/basic?class=Cell&amp;query=CAN</a>
**Browser:** MSEdge 15.15063

**Comment by raymond91125** [comment]
Sorry, could you clarify by providing an example of a whole name?

Raymond

**Comment by raymond91125** [comment]
Canal associated neuron, left

Paul

On Sep 8, 2017, at 18:28, raymond <raymond@caltech.edu<mailto:raymond@caltech.edu>> wrote:


Sorry, could you clarify by providing an example of a whole name?

Raymond

On 09/08/2017 05:59 AM, no-reply@wormbase.org<mailto:no-reply@wormbase.org> wrote:
offline chat what's the whole name of neuron CANL or CANR in worm.

Submitted From:
  http://www.wormbase.org/search/basic/CAN?from=http://www.wormbase.org/db/searches/basic?class=Cell&query=CAN http://www.wormbase.org/search/basic/CAN?from=http://www.wormbase.org/db/searches/basic?class=Cell&query=CAN<http://www.wormbase.org/http://www.wormbase.org/search/basic/CAN?from=http://www.wormbase.org/db/searches/basic?class=Cell&query=CAN>

This issue has been assigned ticket number: #5838. Follow progress on our issue tracker<https://github.com/WormBase/website/issues/5838>.

Reported by: Mei (shidongmei211314@gmail.com<mailto:shidongmei211314@gmail.com>)
08 Sep 17 12:59


This question was reported via the web interface at wormbase.org<http://wormbase.org>. You can also email us<mailto:help@wormbase.org> directly.

--
--
You received this message because you are subscribed to the "WormBase: help" group.
To post to this group, send email to help@wormbase.org<mailto:help@wormbase.org>
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en

---
You received this message because you are subscribed to the Google Groups "WormBase: help" group.
To unsubscribe from this group and stop receiving emails from it, send an email to help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>.


--
--
You received this message because you are subscribed to the "WormBase: help" group.
To post to this group, send email to help@wormbase.org<mailto:help@wormbase.org>
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en

---
You received this message because you are subscribed to the Google Groups "WormBase: help" group.
To unsubscribe from this group and stop receiving emails from it, send an email to help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>.
