### ISSUE TITLE
  I was looking up information on the s...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5899]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I was looking up information on the strain JK3437.  The transgene included in this strain, qIs74, is described as [sys-1::pop-1::GFP unc-119(+)].  This description is a bit confusing, as it seems to indicate that GFP is fused at the C terminus of pop-1.  In the paper "The sys-1 and sys-3 Genes Cooperate With Wnt Signaling to Establish the Proximal-Distal Axis of the Caenorhabditis elegans Gonad" by Siegfried et al. 2004, the construct used to make this transgene, pJK908, has GFP fused to pop-1 at the N terminus.  On the Worm Base pages for the strain, transgene, and construct, can you make it more obvious that GFP is fused at the N terminus of pop-1 to avoid confusion?</p>

**Reported by:** Jona*********** (jrum**************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:56.0) Gecko/20100101 Firefox/56.0

**Comment by draciti** [comment]
Hi Jonathan, 

Thanks for bringing this to our attention. We modified the construct and transgene genotype to reflect the N-term localization of GFP according to your suggestion. 
[sys-1::GFP::pop-1 unc-119(+)]

Data will be available online with the WS263 release.
Click below to access the release schedule:
http://www.wormbase.org/about/release_schedule#01--10

Best,
Daniela

**Comment by chris-grove** [comment]
@draciti 
The underlying issue here is the strain summary which is coming from the CGC. I'm going to reopen and then close once we know the CGC has changed their description.

**Comment by chris-grove** [comment]
My email to Aric Daul at CGC:

"Hi Aric,

 Jonathan just pointed out that the description for strain JK3437 is a bit misleading. It begins:

"qIs74 [sys-1p::pop-1::GFP + unc-119(+)]"

which may have originally come from WormBase (we just corrected it on our end), but I think the description that we (WormBase) are displaying on our strain page:

http://www.wormbase.org/species/c_elegans/strain/JK3437#023514--10

is being automatically pulled in from the CGC. Could you make the correction on the strain summary on your end so that the description indicates the genotype as:

"qIs74 [sys-1p::GFP::POP-1 + unc-119(+)]"

?

Thanks!

Best,

Chris Grove
WormBase"

**Comment by draciti** [comment]
ok thanks Chris

**Comment by chris-grove** [comment]
Response from Aric:
"Hi Christian,

Thanks for calling it to our attention.  The arrival of that strain to the CGC predates me, so I cannot comment on why it was annotated this way or what information had been provided with the strain.  Nonetheless, it is an easy fix.  I've rearranged the order in the description of the transgene.

Aric"

**Comment by chris-grove** [comment]
My email to Aric and Jonathan:
"OK great! Thanks Aric!

Jonathan, thanks for bringing this issue to our attention. I think it should be resolved now. The changes will be made available in the WS263 release of WormBase. The release schedule can be found here:

http://www.wormbase.org/about/release_schedule#0--10

Best,

Chris Grove
WormBase"
