### ISSUE TITLE
Variation location not displayed on WB Variation page despite presence in GBrowse and curated molecular details

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#5916]
I've noticed several variation/allele pages in which the molecular details are known, and the allele is displayed in an allele track in GBrowse, but the Location widget on the respective page is not showing the genomic location and instead has the text:

"Genomic position:  This variation has not been placed on the physical map or its coordinates are unknown."

For example, two deletion alleles of the itsn-1 gene, tm725 and ok268, have this problem:

http://www.wormbase.org/species/c_elegans/variation/WBVar00249755#0456--10
http://www.wormbase.org/species/c_elegans/variation/WBVar00091568#0456--10

If I look up itsn-1 in GBrowse and turn on the "High-throughput alleles" track I see this:

![image](https://user-images.githubusercontent.com/611382/31832512-4960a568-b595-11e7-851e-eba738a21e6e.png)

**Comment by scottcain** [comment]
Hi @chris-grove Just to be clear, GBrowse here is doing the right thing, whereas the location widget seems to be missing something, assuming of course, that the location data in the GFF that resulted in these features being displayed is correct.  If that assumption is faulty, then the GFF is at fault.  Like how I deflected blame in both directions and then walked away unscathed? :-)

Since the GFF does seem to have this location data, I have to assume that AceDB has it as well.  When I look at these pages on staging, I can see that these widgets are served by Datomic, so the question is, are the location data in Datomic, or is the widget not correctly getting the data from Datomic?  @sibyl229 and @a8wright, can you please weigh in?

**Comment by chris-grove** [comment]
@scottcain 
OK thanks for taking a look.

**Comment by a8wright** [comment]
Hi @scottcain and @chris-grove I just looked into it. I am pulling the information from the sequence database that I believe has been created from the GFF files. I learnt that here is another possibility to query to get the attribute. I am now have a fix on staging. Please take a look to check my work.

**Comment by chris-grove** [comment]
Yes! Looks good! Thanks @a8wright !
