### ISSUE TITLE
  Set up a local installation of wormba...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5938]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Set up a local installation of wormbase?  I know this used to be a thing, can it still be done?  If so, is there a Faq or instructions?<br/>Thanks,<br/>visitor_name</p>

**Reported by:** Bria* (krae***********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

**Comment by kyook** [comment]
Todd replied to user
"Hi Brian -

We no longer support local installations of the resource, mainly due to its size and complexity, but also to hosting requirements tied to cloud architecture beyond a simple single box topology. We may reinstate the ability to host locally in the future.

For now, is there a specific aspect of WormBase which you need locally?  We may be able to provide instruction on a piecemeal basis.

Best,

Todd
