### ISSUE TITLE
how to buy  C.elegens...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5957]
*Help Desk query collected when no chat operators were online. Follow up required.*

how to buy  C.elegens

**Reported by:** meng*** (1884***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/me#1-0-5">http://www.wormbase.org/me#1-0-5</a>
**Browser:** Chrome 53.0.2785.104

**Comment by Paul-Davis** [comment]
Hi,

C. elegans strains can be purchased from the Caenorhabditis Genetics Center

https://cgc.umn.edu/

Thanks

Paul



On 02/11/2017 08:09, no-reply@wormbase.org wrote:
> offline chat how to buy C.elegens
>
> Submitted From:
>   http://www.wormbase.org/me#1-0-5 http://www.wormbase.org/me#1-0-5 
> <http://www.wormbase.org/http://www.wormbase.org/me#1-0-5>
>
> This issue has been assigned ticket number: #5957. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/5957>.
>
> Reported by: mengjie (18840844407@163.com)
> 02 Nov 17 08:10
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
Dear Paul,


I have just received . 


Thank you so much for the reply. 
We will contact with the link which you support us.


best regards,
Jie Meng





--
发自我的网易邮箱手机智能版



在 2017-11-02 17:50:38，"Paul Davis" <paul.davis@wormbase.org> 写道：

Hi,

C. elegans strains can be purchased from the Caenorhabditis Genetics Center

https://cgc.umn.edu/

Thanks

Paul



On 02/11/2017 08:09, no-reply@wormbase.org wrote:

offline chat how to buy C.elegens

Submitted From:
  http://www.wormbase.org/me#1-0-5http://www.wormbase.org/me#1-0-5

This issue has been assigned ticket number: #5957. Follow progress on our issue tracker.

Reported by: mengjie (18840844407@163.com)
02 Nov 17 08:10



This question was reported via the web interface at wormbase.org. You can also email us directly.

--
--
You received this message because you are subscribed to the "WormBase: help" group.
To post to this group, send email to help@wormbase.org
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en






-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom 
===========================================
