### ISSUE TITLE
  Hello,  On the front page, you have a...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5963]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello, <br/>On the front page, you have a table presenting the name changes. Where can I get exactly the same table (gene symbol, gene ID, locus ID), with all C elegans genes? Including the Loci that do not have gene symbol yet (NA is fine). Sorry to be lazy and not build it myself. I thought maybe you have this query often and already have a table ready with the most recent changes included.</p><p>What were you doing? <br />&nbsp;&nbsp;I am one of the coordinators of the reconstruction of C elegans metabolism (WormJam)</p>

**Reported by:** Nico************* (n.le****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0

**Comment by kyook** [comment]
Hi Nicolas, 

You can get this information in WormMine. I’ve done a query for you and attached an outfile, perhaps it has everything you asked for? Otherwise, you should be able to modify the query in WormMine or get back to us and we will help you get what you are looking for. The columns are WBGeneID, gene symbol (there are “ “ when one doesn’t exist), LocusID, and last time the gene record was updated.

Best, 
Karen

**Comment by kyook** [comment]
From Nicolas: 

"Awesome, thank you very much.

-- 
Nicolas LE NOVERE, Babraham Institute, Babraham Campus Cambridge, CB22 3AT
Tel: +441223496433   Mob:+447833147074
orcid.org//0000-0002-6309-7327  http://lenoverelab.org/"
