### ISSUE TITLE
  rab-3 isoform a can not show the sequ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5968]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;rab-3 isoform a can not show the sequence</p>

**Reported by:** kkk1**************************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

**Comment by chris-grove** [comment]
Hello,
I cannot find a problem with retrieving the protein/amino acid sequence of RAB-3 isoform a, as demonstrated in this screen capture video:

https://www.dropbox.com/s/ve32z9xxzow6bs5/RAB-3_isoform_a_protein_sequence.mov?dl=0

Are you still experiencing an issue? Could you clarify what the problem is?

Thank you,

Chris Grove
WormBase

**Comment by chris-grove** [comment]
From user:

"It' all right after 1hr. Maybe some problem in my internet.
Thanks."

**Comment by chris-grove** [comment]
OK, thanks for letting me know. Let us know if you experience any more issues.


Thanks,


Chris
