### ISSUE TITLE
visitor_name (visitor_email): Hi, I am at the unc-...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5987]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_email): Hi, I am at the unc-31 gene page and I noticed that the molecular lesions associated with the alleles e69, n422,n577, u377 and n1304 have been listed as "not curated". However th molecular changes in these  alelles have been analysed by Speese et al. The Journal of Neuroscience, June 6, 2007 • 27(23):6150–6162 in Table1.</br>visitor_name (visitor_email): I was wiondering what is meant by "not curated" in this regard. Thanks.

**Reported by:** Gaut****** (gaut************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/gene/WBGene00006767#0-9gc4be1if-10">http://www.wormbase.org/species/c_elegans/gene/WBGene00006767#0-9gc4be1if-10</a>
**Browser:** Firefox 52.0

**Comment by Paul-Davis** [comment]
Hi,

Thanks for contacting WormBase. This status is given when the exact molecular details are not available. This can be because they are unknown/unpublished or in the case of some of the ones you mentioned they are available in the literature but they have not been manually curated and checked.  There are a large number of papers with such details and we are working to get all the data into the database for our community, but this will take time. Thank you for highlighting this paper, I will create a ticket to prioritise the curation of these lesions.

Paul
