### ISSUE TITLE
rod-1 (F55G1.4) gene sequence discrepancy (439bp insertion compared to N2?)

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6038]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Dear Sir or Madam,<br/>while creating a CRISPR mutant for the gene rod-1 (F55G1.4) a company and I recognized a 439 bp long insertion in the second to last exon according to the sequence an wormbase. The company had analyzed several wild-type samples and always found the same additional bp in their sequences. I did it by myself for two more different strains and found the same. <br/>Now I writing you because I thought maybe something is wrong with the gene sequence in wormbase? If you want I can send you my sequencing results telling you exactly where we found the insertion. So you would have the chance to double check and maybe correct the sequence.<br/>For further questions just feel free to contact me and thank you for your help in advance.<br/>Kind regards,<br/>visitor_name</p>

**Reported by:** Elis************ (emal*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:31.0) Gecko/20100101 Firefox/31.0

**Comment by epaule** [comment]
Hi Elisabeth,

I guess you mean the last exon rather than the second last?
[image: Inline images 1]

I will forward it to our sequence curators, but it has been long known that
the N2 strain diverged between the labs before sequence, so there are a few
N2 variations that are specific to the WormBase N2.
We are actually working with some labs to come up with a new clean strain
and sequence and redistribute it to replace N2 as reference, as you might
have heard at the International Worm Meeting in LA and others.

regards,

Michael

**Comment by gw3** [comment]
Dear Elisabeth,

This insertion has already been noted in the paper PubMed: 26039588 
"Illumina Synthetic Long Read Sequencing Allows Recovery of Missing 
Sequences even in the "Finished" C. elegans Genome." Sci Rep 2015.

We had created a Feature to mark the position which can be seen in the 
genome browser track "Genome sequence errors":

http://www.wormbase.org/tools/genome/jbrowse-simple/?data=data%2Fc_elegans_PRJNA13758&loc=IV%3A7484965..7485642&tracks=Curated_Genes%2CGenome%20sequence%20errors&highlight=

We are reluctant to make further changes to the reference genome 
sequence to correct these errors because changing the sequence causes 
problems for our users.

There is an initiative in the worm community to convert from N2 to using 
the strain VC2012, which has a cleaner assembly and reference sequence:

https://ep70.eventpilotadmin.com/web/page.php?page=IntHtml&project=ICEC17&id=175110272

Regards,
Gary Williams
