### ISSUE TITLE
References not being displayed in References widget on several pages

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6040]
This could be an overarching issue that affects 

#6036  
#5579 
#5958 

Maybe if this issue is resolved, those tickets can be closed.

There appears to be a couple of problems with respect to displaying relevant references in the "References" widget on several classes of pages. 

First issue: on pages for several classes, if there are one or more references associated (as indicated by the Tree Display) the "References" widget displays only this:

![screen shot 2017-12-11 at 11 10 11 am](https://user-images.githubusercontent.com/611382/33840787-eef25700-de63-11e7-85a9-292e18044725.png)

Saying there are "2 references found" with two empty lines. This particular problem appears to affect the following classes:

Expression Patterns:
http://www.wormbase.org/species/all/expr_pattern/Expr12257#23--10
(same on staging)

Analysis:
http://www.wormbase.org/resources/analysis/RNASeq.elegans.BA671.WBls:0000041.Hermaphrodite.WBbt:0007833.SRP000401.SRX008136#23--10
(same on staging)

Antibody:
http://www.wormbase.org/species/all/antibody/[cgc3083]:unc-3#23--10
(same on staging)

Strain:
http://www.wormbase.org/species/c_elegans/strain/N2#45--10
(same on staging)

This first issue persists on these pages regardless of how many times I refresh the page.

Second issue (may need a separate ticket?): on pages for several classes, if there are one or more references associated (as indicated by the Tree Display) the "References" widget indicates that there are "No references associated with this [object class]". This affects the following classes:

RNAi:
http://www.wormbase.org/species/c_elegans/rnai/WBRNAi00062789#56--10
(same on staging)

Expression cluster:
http://www.wormbase.org/species/c_elegans/expression_cluster/WBPaper00025032:cluster_194#46--10
(same on staging)

Construct:
http://www.wormbase.org/species/all/construct/WBCnstr00014760#35--10
(same on staging)

Transgene:
http://www.wormbase.org/species/all/transgene/WBTransgene00010204#45--10
(same on staging)

This second issue is a bit strange in that (at least for the RNAi, expression cluster, and transgene examples above), refreshing the page will sometimes cause the reference info to load and other times not. Here's a screen capture video:

https://www.dropbox.com/s/wmsvz4mydqdsmwd/References_widget_variable_loading_WS261.mov?dl=0

**Comment by chris-grove** [comment]
I've found that the second issue also affects Interaction pages (on many but not all page loads):

http://www.wormbase.org/species/all/interaction/WBInteraction000502322#34--10
http://www.wormbase.org/species/all/interaction/WBInteraction000517476#34--10
http://www.wormbase.org/species/all/interaction/WBInteraction000521628#34--10
http://www.wormbase.org/species/all/interaction/WBInteraction000002275#34--10

![screen shot 2017-12-11 at 11 57 32 am](https://user-images.githubusercontent.com/611382/33843139-870763f4-de6a-11e7-8f7c-db163af98588.png)

**Comment by chris-grove** [comment]
Also, second issue affecting Variation pages on variable loads:

http://www.wormbase.org/species/c_elegans/variation/WBVar00250733#-78-10

![screen shot 2017-12-11 at 12 01 20 pm](https://user-images.githubusercontent.com/611382/33843358-21c793a0-de6b-11e7-8a4b-75eefe926651.png)

![screen shot 2017-12-11 at 12 01 37 pm](https://user-images.githubusercontent.com/611382/33843363-24ff4db0-de6b-11e7-87e3-046d72c6921d.png)


http://www.wormbase.org/species/c_elegans/variation/WBVar00000600#-78-10

![screen shot 2017-12-11 at 12 03 45 pm](https://user-images.githubusercontent.com/611382/33843433-5eddcbe2-de6b-11e7-835c-667a3999ebbf.png)


http://www.wormbase.org/species/c_elegans/variation/WBVar00000602#-78-10

![screen shot 2017-12-11 at 12 04 12 pm](https://user-images.githubusercontent.com/611382/33843452-6d819a02-de6b-11e7-966a-4f72330a4bf7.png)

**Comment by chris-grove** [comment]
Also, second issue affects life stage:

http://www.wormbase.org/species/all/life_stage/WBls:0000041#34--10

![screen shot 2017-12-11 at 12 06 58 pm](https://user-images.githubusercontent.com/611382/33843597-d3e58862-de6b-11e7-9d60-48b3ec81d709.png)

**Comment by chris-grove** [comment]
... and molecule pages:

http://www.wormbase.org/resources/molecule/WBMol:00004019#36--10

![screen shot 2017-12-11 at 12 09 40 pm](https://user-images.githubusercontent.com/611382/33843769-44e0f420-de6c-11e7-9820-0833b99233c8.png)

![screen shot 2017-12-11 at 12 09 55 pm](https://user-images.githubusercontent.com/611382/33843775-489c2f94-de6c-11e7-87ad-896f70923955.png)


My point with all these examples is that it seems to be a general problem with the References widget across the site.

**Comment by chris-grove** [comment]
... and gene pages:

http://www.wormbase.org/species/c_elegans/gene/WBGene00001965#eh--10

![screen shot 2017-12-11 at 12 14 00 pm](https://user-images.githubusercontent.com/611382/33843967-e581ba9a-de6c-11e7-9974-f6ff47ab1987.png)

![screen shot 2017-12-11 at 12 14 15 pm](https://user-images.githubusercontent.com/611382/33843970-e9e7e596-de6c-11e7-8a94-0b8ecca6690a.png)

**Comment by sibyl229** [comment]
Hi @chris-grove thank you very much for investigating into this and for your thorough description! The problem should be fixed on staging now, except for intereactions, which is caused by a different Ace tag being used to hold references (Paper instead of Reference) and I will fix it in a moment. 

It's probably not necessary to verify all the examples below, as all these pages use the same code to display references.

Expression Patterns:
http://staging.wormbase.org/species/all/expr_pattern/Expr12257#23--10

Analysis:
http://staging.wormbase.org/resources/analysis/RNASeq.elegans.BA671.WBls:0000041.Hermaphrodite.WBbt:0007833.SRP000401.SRX008136#23--10

Antibody:
http://staging.wormbase.org/species/all/antibody/[cgc3083]:unc-3#23--10

Strain:
http://staging.wormbase.org/species/c_elegans/strain/N2#45--10

RNAi:
http://staging.wormbase.org/species/c_elegans/rnai/WBRNAi00062789#56--10

Expression cluster:
http://staging.wormbase.org/species/c_elegans/expression_cluster/WBPaper00025032:cluster_194#46--10

Construct:
http://staging.wormbase.org/species/all/construct/WBCnstr00014760#35--10

Transgene:
http://staging.wormbase.org/species/all/transgene/WBTransgene00010204#45--10

Interaction:
(not working yet)
http://staging.wormbase.org/species/all/interaction/WBInteraction000502322#34--10
http://staging.wormbase.org/species/all/interaction/WBInteraction000517476#34--10
http://staging.wormbase.org/species/all/interaction/WBInteraction000521628#34--10
http://staging.wormbase.org/species/all/interaction/WBInteraction000002275#34--10

Variation
http://staging.wormbase.org/species/c_elegans/variation/WBVar00000602#-78-10

Life stage:
http://staging.wormbase.org/species/all/life_stage/WBls:0000041#34--10

Molecule:
http://staging.wormbase.org/resources/molecule/WBMol:00004019#36--10

Gene:
http://staging.wormbase.org/species/c_elegans/gene/WBGene00001965#eh--10

**Comment by chris-grove** [comment]
@sibyl229 
OK, great! Looks good thanks! I'll wait for you to fix the interactions pages and then I'll close the ticket.

**Comment by sibyl229** [comment]
@chris-grove Thanks for checking! Reference widget for interaction should be working now:

http://staging.wormbase.org/species/all/interaction/WBInteraction000502322#34--10
http://staging.wormbase.org/species/all/interaction/WBInteraction000517476#34--10
http://staging.wormbase.org/species/all/interaction/WBInteraction000521628#34--10
http://staging.wormbase.org/species/all/interaction/WBInteraction000002275#34--10

**Comment by chris-grove** [comment]
@sibyl229 
Beautiful! Thanks Sibyl!
