### ISSUE TITLE
Fixing gene name typo xhd-1 to xdh-1

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6045]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Dear Curators,<br/>I noticed that a gene name (xhd-1) is annotated to WBGene00010083. For gene names of other species, "XDH" is used after "Xanthine DeHydrogenase". How did you decide to use gene name xhd-1 instead of xdh-1, although no xdh is used for any other genes in WormBase?<br/>Thank you for your help in advance.<br/>Sincerely,<br/>visitor_name<br/>Department of Physiology, Tokyo Women's Medical University School of Medicine, Tokyo, Japan</p>

**Reported by:** Shoh********* (mita********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/604.4.7 (KHTML, like Gecko) Version/11.0.2 Safari/604.4.7

**Comment by Paul-Davis** [comment]
Dear Shohei,

This appears to be a typo in one of the gene nomenclature updates from 
January this year. It has already been corrected but will not be 
publicly visible on WormBase until WS264.

xdh-1 is the official name of this gene with the xdh gene class association.

Thank you for letting us know.

Paul


On 12/12/2017 03:35, no-reply@wormbase.org wrote:
> Content Correction
>
>   Dear Curators,
> I noticed that a gene name (xhd-1) is annotated to WBGene00010083. For 
> gene names of other species, "XDH" is used after "Xanthine 
> DeHydrogenase". How did you decide to use gene name xhd-1 instead of 
> xdh-1, although no xdh is used for any other genes in WormBase?
> Thank you for your help in advance.
> Sincerely,
> Shohei Mitani
> Department of Physiology, Tokyo Women's Medical University School of 
> Medicine, Tokyo, Japan
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #6045. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6045>.
>
> Reported by: Shohei Mitani (mitani.shohei@twmu.ac.jp)
> 12 Dec 17 03:35
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/604.4.7 
> (KHTML, like Gecko) Version/11.0.2 Safari/604.4.7
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
Dear Paul,

 

Thank you very much for your kind help.

 

Sincerely,

 

Shohei

==============================================

Shohei Mitani, M.D., Ph.D.

Department of Physiology,

Tokyo Women's Medical University School of Medicine

                    &

Tokyo Women's Medical University

Institute for Integrated Medical Sciences

8-1, Kawada-cho, Shinjuku-ku, Tokyo, 162-8666, Japan

Tel & FAX: 81-3-5269-7414

e-mail: mitani.shohei@twmu.ac.jp

==============================================

 

差出人: Paul Davis <paul.davis@wormbase.org>
日付: 2017年 12月 12日 火曜日 19:05
宛先: "help@wormbase.org" <help@wormbase.org>
Cc: <mitani.shohei@twmu.ac.jp>, <reply@reply.github.com>
件名: Re: [wormbase-help] Content Correction: Dear Curators, I noticed that a gene ... (Shohei Mitani)

 


Dear Shohei,

This appears to be a typo in one of the gene nomenclature updates from January this year. It has already been corrected but will not be publicly visible on WormBase until WS264.

xdh-1 is the official name of this gene with the xdh gene class association.

Thank you for letting us know.

Paul


On 12/12/2017 03:35, no-reply@wormbase.org wrote:

Content Correction 

  Dear Curators,
I noticed that a gene name (xhd-1) is annotated to WBGene00010083. For gene names of other species, "XDH" is used after "Xanthine DeHydrogenase". How did you decide to use gene name xhd-1 instead of xdh-1, although no xdh is used for any other genes in WormBase?
Thank you for your help in advance.
Sincerely,
Shohei Mitani
Department of Physiology, Tokyo Women's Medical University School of Medicine, Tokyo, Japan

Submitted From: 
  support /tools/support 

This issue has been assigned ticket number: #6045. Follow progress on our issue tracker. 

Reported by: Shohei Mitani (mitani.shohei@twmu.ac.jp) 
12 Dec 17 03:35 

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/604.4.7 (KHTML, like Gecko) Version/11.0.2 Safari/604.4.7 

This question was reported via the web interface at wormbase.org. You can also email us directly. 

-- 
-- 
You received this message because you are subscribed to the "WormBase: help" group.
To post to this group, send email to help@wormbase.org
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en

 
-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom 
===========================================
