### ISSUE TITLE
  I downloaded the let-363 protein sequ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6047]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I downloaded the let-363 protein sequence from WB. It should be 2695 AA. It downloaded as a .fasta file, and opened in my APE program. No errors, no warnings. But the sequence I got was very wrong. After download, it contained only 1733 AA, with several specific AAs being excluded from the sequence. This may be a defect in the APE program. However, if there is anything that can be changed on the WB side, you might help the next person from having this same trouble. Thanks!</p>

**Reported by:** Aile** (asew****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:57.0) Gecko/20100101 Firefox/57.0

**Comment by chris-grove** [comment]
Hi,

Can you specify exactly where on WormBase you retrieved the protein sequence for let-363? I've looked at the let-363 gene page:

http://www.wormbase.org/species/c_elegans/gene/WBGene00002583#0-g9-3

which specifies two protein isoforms, one of 2695 aa in length and the other 2692 aa in length. The 2695 isoform sequence in all cases I've looked at (on the let-363 gene page, the protein isoform page, and protein sequence FASTA files from the FTP site) has the complete 2695 aa sequence.

Thanks!

Chris Grove
WormBase

**Comment by raymond91125** [comment]
Hi Aileen,

Have you counted the number of AA's in the .fasta? Perhaps use this tool 
<https://web.expasy.org/protparam/> to make it easier.

If you're still getting something other than 2695 aa from WormBase, 
please include some screen shots so that we can see exactly how it occurred.

Raymond


On 12/12/17 13:59, no-reply@wormbase.org wrote:
> Bug Report
>
>   I downloaded the let-363 protein sequence from WB. It should be 2695 
> AA. It downloaded as a .fasta file, and opened in my APE program. No 
> errors, no warnings. But the sequence I got was very wrong. After 
> download, it contained only 1733 AA, with several specific AAs being 
> excluded from the sequence. This may be a defect in the APE program. 
> However, if there is anything that can be changed on the WB side, you 
> might help the next person from having this same trouble. Thanks!
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #6047. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6047>.
>
> Reported by: Aileen (asewell@colorado.edu)
> 12 Dec 17 21:59
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:57.0) Gecko/20100101 
> Firefox/57.0
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> You received this message because you are subscribed to the Google 
> Groups "WormBase: help" group.
> To unsubscribe from this group and stop receiving emails from it, send 
> an email to help+unsubscribe@wormbase.org 
> <mailto:help+unsubscribe@wormbase.org>.


-- 
__
Raymond Lee
raymond@caltech.edu
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by raymond91125** [comment]
Hi guys,

Thanks for checking into this. It sounds like the problem occurs when the .fasta file is opened in APE (aka “it’s not you, it’s me” :). I’ll be wary of that type of thing in the future.

Thanks!
Aileen

On Dec 13, 2017, at 9:34 AM, Raymond Lee <raymond@caltech.edu<mailto:raymond@caltech.edu>> wrote:

Hi Aileen,

Have you counted the number of AA's in the .fasta? Perhaps use this tool <https://web.expasy.org/protparam/><https://web.expasy.org/protparam/> to make it easier.

If you're still getting something other than 2695 aa from WormBase, please include some screen shots so that we can see exactly how it occurred.

Raymond


On 12/12/17 13:59, no-reply@wormbase.org<mailto:no-reply@wormbase.org> wrote:
Bug Report

  I downloaded the let-363 protein sequence from WB. It should be 2695 AA. It downloaded as a .fasta file, and opened in my APE program. No errors, no warnings. But the sequence I got was very wrong. After download, it contained only 1733 AA, with several specific AAs being excluded from the sequence. This may be a defect in the APE program. However, if there is anything that can be changed on the WB side, you might help the next person from having this same trouble. Thanks!

Submitted From:
  support /tools/support<http://www.wormbase.org//tools/support>

This issue has been assigned ticket number: #6047. Follow progress on our issue tracker<https://github.com/WormBase/website/issues/6047>.


Reported by: Aileen (asewell@colorado.edu<mailto:asewell@colorado.edu>)
12 Dec 17 21:59

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:57.0) Gecko/20100101 Firefox/57.0

This question was reported via the web interface at wormbase.org<http://wormbase.org>. You can also email us<mailto:help@wormbase.org> directly.

--
--
You received this message because you are subscribed to the "WormBase: help" group.
To post to this group, send email to help@wormbase.org<mailto:help@wormbase.org>
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en

---
You received this message because you are subscribed to the Google Groups "WormBase: help" group.
To unsubscribe from this group and stop receiving emails from it, send an email to help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>.


--
__
Raymond Lee
raymond@caltech.edu<mailto:raymond@caltech.edu>
http://www.WormBase.org/<http://www.wormbase.org/>
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
