### ISSUE TITLE
skn-1 Interactions widget times out

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6062]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;The website (gateway) times out after a few seconds when trying to render the interactions list for skn-1.  I presume many interactions are in the list because this function slows down for other genes with a large number of interactions.  But this is the only one that gets an error message.<br/>Thanks</p><p>What were you doing? <br />&nbsp;&nbsp;Trying to access the interactions list for skn-1.</p>

**Reported by:** Dona** (ddwy*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36

**Comment by chris-grove** [comment]
Probably related to #5999

**Comment by chris-grove** [comment]
From @a8wright 
"Hi Donard,

I am a core developer working on the REST interface that pulls the data out of the database.

You are correct a few of the interaction widgets are timing out with the current release. As you said this is a challenge arises because of the number of interactions found on some of the genes. In order to tackle this issue, for the next release, we have been working on making the code more efficient and will be bypassing the timeout during the caching step. I anticipate that the changes will reduce the number of timeouts significantly for the next release.

Thanks for reporting the issue.

Cheers,
Adam Wright"

**Comment by chris-grove** [comment]
Hi Donard,

 Just to add: if you are looking for something in particular regarding skn-1 interactions, let us know and we can generate a data file for you manually. Or we can send you a table of all interactions for skn-1. Either way let us know how we can help.

Best,

Chris Grove

**Comment by chris-grove** [comment]
From user:
"Hi Chris,
 
Thanks for the reply and offer of help.  The only information I need at the moment regarding skn-1 is simply the number of interactions in its list.  For example when you probe with daf-16, it lists 595 interactions found.  I wanted to have the equivalent number for skn-1.  At this point, I don’t need any details about the interaction members on the list, just the total.  It would be great to get this number, if possible."

**Comment by chris-grove** [comment]
From user:
"Thanks, Chris.
 
No, the types of interactions don’t matter at this point.  The number 412 was what I needed."

**Comment by chris-grove** [comment]
skn-1 Interactions widget now loads on live WS262, but the Cytoscape network viewer is timing out

**Comment by chris-grove** [comment]
OK loading now, closing
