### ISSUE TITLE
  Hi, I am trying find the SNP variatio...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6090]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, I am trying find the SNP variations reported in the paper below Table1, which is supposedly giving the Wormbase identifiers. However, if I search these I get many hits in most cases. Is there a way to access all these SNP sequences? <br/>https://bmcgenomics.biomedcentral.com/articles/10.1186/1471-2164-6-118</p>

**Reported by:** Alpe****** (aa74***********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/604.4.7 (KHTML, like Gecko) Version/11.0.2 Safari/604.4.7

**Comment by chris-grove** [comment]
Hi Alper,

 I would recommend taking advantage of all of the information provided in the table to narrow down the results. I'm not sure why there are so many variations in WormBase that have the same other name (often appended with a number in brackets like [1]), but because the table provides chromosome locations as well, that can help us identify which SNPs they were referring to. They also provide primers which can be submitted to our ePCR tool to possibly help identify the correct SNP.

First, as I think you've already tried, I would perform a search "for a variation" from the main WormBase search box using the "Wormbase Identifier" they provide in the last column of the table. In some cases, e.g. "pkP1052", searching returns a single hit:

http://www.wormbase.org/species/c_elegans/variation/WBVar00240395#04--10

You can see in the "Overview" widget that "pkP1052" is an "Other name" for WBVar00240395. Also check the "Location" widget to confirm the chromosomal location matches that given in the paper. The paper gives chromosome I at position 2,818,973. The position on WormBase for WBVar00240395 is chromosome I at position 2,818,972. This is off by one base pair, which may be the result of small modifications to the reference genome since the paper was published in 2005.

For the others that return multiple hits (and all have the "Wormbase Identifier" in some form as an other name), I would open GBrowse or JBrowse and navigate to the chromosomal location provided in the paper's table and make sure the "Polymorphisms" track is turned on. That should help you unambiguously identify the SNP that they were referring to.

In the event that both of those approaches fails, you can try to use the primers provided to find the correct SNP using the ePCR tool:

http://www.wormbase.org/tools/epcr

For the record, I believe the second "Wormbase Identifier" provided in the table "snp_Y71G12" is probably a typo and was meant to be "snp_Y71G12A".


Let us know if you need any further assistance.


Best,

Chris Grove
WormBase
