### ISSUE TITLE
correction lin-5(n3066): is correctly annotated as...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6095]
*Help Desk query collected when no chat operators were online. Follow up required.*

correction lin-5(n3066): is correctly annotated as ochre STOP at aa 538 in CGC (see Larson 2000), wrong annotated in Genome browser/ classical alleles as Q to amber 542. please correct

**Reported by:** Alex************ (alex********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/variation/WBVar00090651#02-45-3">http://www.wormbase.org/species/c_elegans/variation/WBVar00090651#02-45-3</a>
**Browser:** Safari 11.0.2

**Comment by Paul-Davis** [comment]
Hi Alexandra,

Thanks for reporting this, I haven't gone back to the Author on this yet 
as I'm checking with the curator who annotated this back in 2003 1st, 
but either there was a lucky mutation that caused 2 point mutations in 
the codon or the author got the wrong type?

Rather than a simple c to t as currently reported you need both c to t 
and g to a to go from Q to STOP(ochre).

AA                             E  E  Q  N  K

Reported                       E  E  *  N  K
Genome   aaggacgatatcatcaaatttcaagaggagcagaacaaacgagctgccaatctgataaaga
required aaggacgatatcatcaaatttcaagaggag agaacaaacgagctgccaatctgataaaga


If you have sequenced the allele it would clear this up if you could 
provide the sequence data. I will continue to look into this.

Paul



On 11/01/2018 10:30, no-reply@wormbase.org wrote:
> offline chat correction lin-5(n3066): is correctly annotated as ochre 
> STOP at aa 538 in CGC (see Larson 2000), wrong annotated in Genome 
> browser/ classical alleles as Q to amber 542. please correct
>
> Submitted From:
>   http://www.wormbase.org/species/c_elegans/variation/WBVar00090651#02-45-3 
> http://www.wormbase.org/species/c_elegans/variation/WBVar00090651#02-45-3 
> <http://www.wormbase.org/http://www.wormbase.org/species/c_elegans/variation/WBVar00090651#02-45-3> 
>
>
> This issue has been assigned ticket number: #6095. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6095>.
>
> Reported by: Alexandra Bezler (alexandra.bezler@epfl.ch)
> 11 Jan 18 10:30
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
