### ISSUE TITLE
Hi, I have a question concerning worm base sequenc...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6124]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi, I have a question concerning worm base sequence names. Do some genes share a sequence name? My assumption was that each gene has a unique WB number and sequence id. 

Indeed, that seems to be true for almost all cases. However, recently I was merging some tables using python, and found a few instances where two genes will share a sequence name. In these, cases the genes are adjacent so I can see how this might have arisen. However, I think that each gene should be given a unique sequence name, just as each has  a unique worm base identifier or common name. 

Everyone I talked to in my lab assumed that each gene had a unique sequence name. Further, this could complicate bioinformatic analysis. 

Thanks for your time. I apologize if this is a foolish or naive question. Perhaps I lack some common knowledge about C. elegans annotation. Thanks for   all you guys do for worm base! 

Here are the examples:

ZC416.8 cha-1 and unc-17	

Y105E8A.7 eat-18 and lev-10 

B0564.1 exos-4.1	and tin-9.2

**Reported by:** Will********** (wsch*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/search/gene/ZC416.8">http://www.wormbase.org/search/gene/ZC416.8</a>
**Browser:** Safari 11.0.2

**Comment by gw3** [comment]
Hi Will,

Yes, some genes share a sequence name.
Or to put it another way, some loci producing a single transcript have 
non-overlapping protein products and share two Gene IDs (WB Gene numbers)

Some loci appear to share a single promoter and produce a single 
transcript which has two large non-overlapping open reading frames.
The transcript is then translated to produce a different protein product 
from each of the open reading frames.

There are over 40 of these genes that have been identified in C. elegans.
See the articles on SL1 operons and Dicistronic mRNA loci in the 
Wormbook chapter on Operons:

http://www.wormbook.org/chapters/www_operongeneclusters/operongeneclusters.html

The annotation of these loci has been inconsistent in the past.
We used to try to describe these as a single locus with two isoforms and 
so they had one sequence name and one WB Gene number.
However, some loci were worked on by two different groups at the same 
time and they would insist on having different WB Gene numbers and CGC 
names for each part.
This resulted in the examples that you have found.

We have recently decided that because the reading frames are 
non-overlapping and so the protein products will have very different 
properties that should be described independently, it makes more sense 
to assign each protein its own Gene, as in a normal operon,  and so 
there will be two sequence names and WB Gene numbers.
We have not yet made the transition to the new way of naming these loci.

Gary Williams
