### ISSUE TITLE
WormMine issues

### ISSUE THREAD

**Issue by nuin** [WormBase/website#6155]
Captured from WormBase help

Dear help team,

I’m using WormMine to download a variety of data to update my own databases. This includes downloading all alleles for all protein-coding genes. I came across the following problems with this data set.

1. Some alleles are associated with the wrong gene

The reason seems to be that the gene in the output table of a WormMine query does not always match the query gene.

Example: try the following query

```
<query name="" model="genomic" view="Protein.secondaryIdentifier Protein.CDSs.gene.alleles.method Protein.CDSs.gene.alleles.naturalVariant Protein.CDSs.gene.alleles.primaryIdentifier Protein.CDSs.gene.alleles.symbol" longDescription="returns the protein sequences of all current proteins of a species" sortOrder="Protein.secondaryIdentifier asc" constraintLogic="B and A">
  <constraint path="Protein.organism.name" code="B" op="=" value="Caenorhabditis elegans"/>
  <constraint path="Protein.CDSs.primaryIdentifier" code="A" op="=" value="T07D10.4"/>
</query>
```

The result table lists H16D19.1 not T07D10.4 as gene name.
Likewise a WormMine query for ZK1251.6 give a result table with C04G2.4 as gene name.
(and I’m sure there are more).

2. Some alleles in regions with nested genes are associated with the wrong gene

Example: allele gk819585 is associated with gene C03A7.14 (query for alleles of C03A7.14).
This allele is in an exon of the overlapping gene C03A7.8 (corresponding to an intron of C03A7.14) and results in a stop codon in C03A7.8, not C03A7.14. WormMine does not list gk819585 as an allele of C03A7.8 (query for alleles of C03A7.8).

gk819585_location.png

3. The data set is incomplete, i.e. some alleles are not found

example: gk964133 is a large deletion covering the region between R05D3.6 and ZC262.2.
WormMine does not list it as allele of either R05D3.6 or ZC262.2.
In fact several deletions cover this region, none show up as alleles for the two genes. 

Could you please look into this.

Thank you very much for your help.

Best regards,
Harald Hutter

**Comment by nuin** [comment]
Regarding number 2 and 4 

The grep command I used was on the data that is actually loaded into WormMine from sources, including GFF3. From GFF3 we currently load lines that have

gene
mRNA
CDS
exon

on the third column. These lines are still present on WS262 (this is the raw, non-preprocessed file)

```
datadir/wormbase-gff3/raw ‹im-263*› % grep gk819585 c_elegans.PRJNA13758.WS262.annotations.gff3
V       Million_mutation        point_mutation  5163836 5163836 .       +       .       variation=WBVar01010301;public_name=gk819585;strain=VC40799;substitution=G/A;consequence=Nonsense;aachange=Q to amber stop (293)
V       PCoF_Million_mutation   point_mutation  5163836 5163836 .       +       .       variation=WBVar01010301;public_name=gk819585;strain=VC40799;substitution=G/A;consequence=Nonsense;aachange=Q to amber stop (293)
```

but the third column are point_mutation. From the more than 3 millions lines in the GFF3 we load around half a million of them. This ID is also present in the Variation.xml (from AceDB, my initial grep might have missed it) 

```
<Variation>WBVar01010301
  <Name>
    <Public_name>
      <Variation_name>gk819585</Variation_name>
    </Public_name>
  </Name>
  <Sequence_details>
    <SMap>
      <S_parent>
        <Sequence>
          <Sequence>C03A7</Sequence>
        </Sequence>
      </S_parent>
    </SMap>
```

And it seems to being loaded correctly into the DB

```
 othername | affects | linkedto | interpolatedmapposition | lastupdated | koallele | sequencestatus | nemaallele | rearrangement | natureofvariation | phenotype | intermine_method | status | nbpallele | mutagen |       amber_uag       | publicname | type | species |    id    | name | productionmethod | missensechange | nemagenetagconsortiumallele | secondaryidentifier | positiveclone | naturalvariant | sequencedetails | opal_uga | ochre_uaa | typeofmutation | phenotypenotobserved | donorsplicesite | missense |  symbol  | acceptorsplicesite | primaryidentifier | detectionmethod | koconsortiumallele | organismid | sequenceontologytermid | geneid  |             class
-----------+---------+----------+-------------------------+-------------+----------+----------------+------------+---------------+-------------------+-----------+------------------+--------+-----------+---------+-----------------------+------------+------+---------+----------+------+------------------+----------------+-----------------------------+---------------------+---------------+----------------+-----------------+----------+-----------+----------------+----------------------+-----------------+----------+----------+--------------------+-------------------+-----------------+--------------------+------------+------------------------+---------+--------------------------------
           |         |          |                         |             |          |                |            |               |                   |           | Million_mutation |        | false     |         | Q to amber stop (293) |            |      |         | 11908132 |      |                  |                | false                       |                     |               | false          |                 |          |           |                |                      |                 |          | gk819585 |                    | WBVar01010301     |                 | false              |            |               23000000 | 4000658 | org.intermine.model.bio.Allele
```

(I know it’s hard to see, but gk819585 goes to symbol and not public name as it’s on the GFF3 file). In AceDB, it shows that the variation/allele affects

```
<Affects>
    <Gene>
      <Gene>WBGene00000031</Gene>
      <Gene>WBGene00000030</Gene>
    </Gene>
    <Predicted_CDS>
      <CDS>C03A7.8
        <Nonsense>
```

where `WBGene00000031` is `C03A7.14` and `30` is `C03A7.8`. Everything related to `gk819585` is created from AceDB data, and technically the link should be many-to-many between alleles and genes. It seems as you can see above the affects column is empty for this variation/allele, what might result in the problem you are seeing. We rolled back our newer code for loading this data and it seems that our old procedure wasn’t up to date to minimal changes in the data model. Hopefully, we can add a patch release as soon as the newer code is fully tested and approved for production.

**Comment by nuin** [comment]
Regarding 1

I see the same result, I tested the query the first time you sent it. I understand that you can only report what you see on the site, but on the backend I don’t see a protein with T07D10.4 as a secondary identifier

select * from protein where secondaryidentifier = 'T07D10.4’;

 secondaryidentifier | molecularweight | md5checksum | symbol | primaryidentifier | lastupdated | length | id | name | genename | primaryaccession | organismid | sequenceid | class
---------------------+-----------------+-------------+--------+-------------------+-------------+--------+----+------+----------+------------------+------------+------------+-------
(0 rows)


while I see

select * from protein where secondaryidentifier = 'H16D19.1';

 secondaryidentifier | molecularweight |           md5checksum            | symbol  | primaryidentifier | lastupdated | length |   id    | name | genename | primaryaccession | organismid | sequenceid |              class
---------------------+-----------------+----------------------------------+---------+-------------------+-------------+--------+---------+------+----------+------------------+------------+------------+---------------------------------
 H16D19.1            |            45.1 | 6cbd121f12802802b515294fc3ea3249 | CLEC-15 | WP:CE13381        |             |    413 | 6041880 |      |          | WP:CE13381       |    1000009 |    6041878 | org.intermine.model.bio.Protein


It seems from the database build, secondary identifier is coming from the FASTA headers (below is the processed one), where the protein ID is linked to the CDS id

im-dev1 :: ip-10-0-1-221 :: c_elegans/proteins/prepped ‹im-263*› % grep H16D19.1 c_elegans.PRJNA13758.WS262.protein.fa
>CE13381|H16D19.1
im-dev1 :: ip-10-0-1-221 :: c_elegans/proteins/prepped ‹im-263*› % grep T07D10.4 c_elegans.PRJNA13758.WS262.protein.fa

Both CDSs are being created correctly, but there’s not logical direct connection from Protein to CDS in our model (at least on the backend). Chris might be able to help further on this, but what you’re seeing might be related to a incomplete merge of the items. I need to investigate further on my end to see what is exactly happening.

**Comment by chris-grove** [comment]
Hi Harald, Paulo,

OK, so it's been a little hectic this morning. WormBase is currently performing sub-optimally, perhaps due to an attack on the site, causing pages and widgets to time-out and never load.

We can still use staging.wormbase.org for the moment, so I'll post links to that site instead.

As for issue #1, I think the problem here very likely stems from the fact that there are some genes, CDS's, and transcripts that all share the exact same protein sequence and, hence, the same protein primary identifier in WormBase, including the T07D10.4 and H16D19.1 genes/cds/transcripts (clec genes clec-13 and clec-15) and the ZK1251.6 and C04G2.4 genes/cds/transcripts (msp genes msp-76 and msp-36). Take a look at the protein pages for WP:CE13381 and WP:CE03853, for example:

http://staging.wormbase.org/species/c_elegans/protein/WP:CE13381#08--10

http://staging.wormbase.org/species/c_elegans/protein/WP:CE03853#0--10

Paulo, this suggests to me that there is a disconnect in the way WormMine is loading and associating proteins to CDS objects, Transcript objects, and Gene objects. We need to make sure that the loading look up works like this:

Gene --> CDS --> Transcript --> Protein

and not the reverse:

Protein --> Transcript --> CDS --> Gene

the important point being that the same protein object can be affiliated with multiple distinct transcripts, CDS's and genes.

I'm looking into the other issues and will respond as soon as I know more information.

Apologies for the issues Harald. We'll try to sort this out as soon as possible.

Chris

**Comment by chris-grove** [comment]
You can see my point about issue 1 more clearly, perhaps, by creating a list of the genes msp-10, msp-36, msp-56, and msp-76 and then by performing the following query constrained to that list (you would have to use your own list):

`<query name="" model="genomic" view="Gene.primaryIdentifier Gene.secondaryIdentifier Gene.symbol Gene.CDSs.primaryIdentifier Gene.CDSs.symbol Gene.CDSs.protein.primaryAccession Gene.CDSs.protein.primaryIdentifier Gene.CDSs.protein.secondaryIdentifier Gene.CDSs.protein.symbol" longDescription="" sortOrder="Gene.primaryIdentifier asc">
  <constraint path="Gene" op="IN" value="Gene list for all organisms 2 Feb 2018 11.51"/>
</query>`

![screen shot 2018-02-02 at 11 55 17 am](https://user-images.githubusercontent.com/611382/35745289-bf7b453c-0810-11e8-95b8-d2177eb794d7.png)


It seems that of the multiple CDS/Transcript names and Protein names actually associated with the protein WP:CE03583, one gets chosen over all the others to represent a single secondary identifier and Protein Name. We'll need to think of a suitable solution to this so that there isn't confusion going forward.


Chris

**Comment by chris-grove** [comment]
These issues are represented in tickets #6141 and #6159 

Closing this ticket.
