### ISSUE TITLE
Dear wormbase staff, 
This is visitor_name, a post...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6156]
*Help Desk query collected when no chat operators were online. Follow up required.*

Dear wormbase staff, 
This is visitor_name, a postdoc from the Sternberg lab at Caltech. I would like to ask what version of C elegans genome (ce10 or ce11?) is used when reported the the coordinates of genes in the current version of wormbase? Is there an easy way to switch between them?
Thanks, 
Han

**Reported by:** Han **** (han.****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/#012-34-5">http://www.wormbase.org/#012-34-5</a>
**Browser:** Firefox 57.0

**Comment by gw3** [comment]
Dear Han,

The current version of the C. elegans reference genomes is WBcel235. This is what UCSC call "ce11". It has been the current version in WormBase since 2012.  All C. elegans chromosome coordinates you see across the site refer to WBcel235/ce11. 

We no longer display WBcel215 ("ce10") coordinates in WormBase. 

Best,

Kevin
