### ISSUE TITLE
Variations in WormMine missing public names

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6161]
I first noticed that I couldn't find the allele e1370 in WormMine by its public name:

http://www.wormbase.org/species/c_elegans/variation/WBVar00143949#012345678--10

I realized that it was in WormMine, but only with the ID WBVar00143949, no public name. I sampled from variations with public names in WS263 and looked for these variations in WormMine that might be missing the public name in WormMine. Here's a list of 51 variations (a sample; I found 51 variations out of 100,000 variations checked among 1.9 million with public names; I couldn't check the whole list of course):

WBVar00000263
WBVar00054167
WBVar00087937
WBVar00088400
WBVar00088858
WBVar00089209
WBVar00089284
WBVar00089401
WBVar00089478
WBVar00089659
WBVar00089664
WBVar00090123
WBVar00090198
WBVar00090218
WBVar00090706
WBVar00090954
WBVar00091303
WBVar00091484
WBVar00091574
WBVar00091989
WBVar00092073
WBVar00092146
WBVar00092161
WBVar00092352
WBVar00093288
WBVar00093398
WBVar00093499
WBVar00142941
WBVar00143078
WBVar00143616
WBVar00143949
WBVar00144267
WBVar00144287
WBVar00144649
WBVar00145224
WBVar00145254
WBVar00145412
WBVar00146344
WBVar00242482
WBVar00242554
WBVar00248951
WBVar00250993
WBVar00251564
WBVar00266471
WBVar00274962
WBVar02146399
WBVar02147189
WBVar02147239
WBVar02147446
WBVar02148399
WBVar02148433

I don't know why these public names are not making it into WormMine, but maybe they're not being appropriately loaded from the ACEDB XML.

**Comment by chris-grove** [comment]
WBVar02147239 apparently only has a public name as of WS263, so we can ignore that one.

**Comment by nuin** [comment]
@chris-grove These are the only ones without a `public name` or all of them appear to not have it?

**Comment by chris-grove** [comment]
@nuin 
These are 50 variations from a random sample of 100,000 from a total of 1.9 million variations in ACEDB that have a public name. Extrapolating would estimate that there are ~1000 variations with this problem, but I have no idea the actual number. I can only upload 100,000 objects into a WormMine list at a time, when logged in. Somewhat humorously, when not logged in the number of items that can be uploaded at a time is limited to 99,999.

**Comment by nuin** [comment]
I am assuming this error might be related to the problems we are having with loading Variation and Strains. It might be related to unclosed/improperly closed tags. I will investigate further.

**Comment by nuin** [comment]
I will put this on hold until the new Variation mapping is tested.

**Comment by chris-grove** [comment]
@nuin 
FYI, this is still an issue on im-dev1 (maybe that was expected/obvious):

`<query name="" model="genomic" view="Allele.primaryIdentifier Allele.symbol" longDescription="" sortOrder="Allele.primaryIdentifier asc" constraintLogic="A or B">
  <constraint path="Allele.primaryIdentifier" code="A" op="=" value="WBVar00143949"/>
  <constraint path="Allele.primaryIdentifier" code="B" op="=" value="WBVar00146344"/>
</query>`

**Comment by chris-grove** [comment]
@nuin 
Still an issue on WS263 production FYI

**Comment by nuin** [comment]
This seems to be resolved in the past releases, closing it.

**Comment by chris-grove** [comment]
There are still 4 variations/alleles from the list above that should have public names, but do not:

WBVar02147446
WBVar02148433
WBVar00144649
WBVar00093288

Not sure why this is happening.

**Comment by nuin** [comment]
@chris-grove All these IDs are in the rejects file, which are entry that are rejected by one way or another from the loading process. Errors in the XML would trigger rejection and the offending item won't be loaded in the DB (please note that the problems we had in the past with `<beta>` and other strings that look like XML tags won't be rejected).

I isolated these from the main XML to get a better understanding of the problems. Here are what is happening with these:

- for WBVar00093288

```xml
  <Remark>
    <Text>This allele has a nine base pair duplication (insertion)
replacing the 1,606 bp found in the wild type.  The truncated protein is
predicted to be comprised of only 27 amino acids, thus this is a probable null allele.


</Text>
```
our Perl script that wraps all `<Text>` with CDATA missed this one, and I am betting it's because of the empty lines, which I can see are carriage returns.

- for WBVar00144649 is a similar situation

```xml
  <Remark>
    <Text>an insertion of a Tc4 transposable element at the exon 6/intron 6 boundary.


      <Paper_evidence>
```

- for WBVar02147446 is more or less the same thing

```xml
  <Remark>
    <Text>ky1015 replaces 32 bp in the MY14 region upstream of srx-44 with
38 bp from N2 (AATCATGTTAAAAAATCAATTTTTGGGTAGTCAACGGA replaces TATCA
TTTAAAAACTCACTTTTTGAGTAGTCG).


      <Paper_evidence>
```

- for WBVar02148433

```xml
   <Flanking_sequences>
      <Txt>CTATAAAATAGGCCCGTTACCACCTTGAGA


        <Txt><![CDATA[ATGTGAGCTCCGCTTGTTAGGAGTTGTCAA]]></Txt>
      </Txt>
    </Flanking_sequences>
```

the problem is empty lines on the flanking sequences. The script gets the second one, but misses the first one.

I will contact you on Slack to find possible solutions.

**Comment by chris-grove** [comment]
@Paul-Davis 
It looks like there are extra newline characters floating around some remarks and flanking sequence entries for variation objects (see above). Could you fix those at the source? This is causing these alleles to not be loaded into WormMine.

**Comment by Paul-Davis** [comment]
Sure, I'll do it now

**Comment by Paul-Davis** [comment]
I think all these come about as Mary Ann used to use the native editor within xace to add remarks and if you hit return when you have finished typing as you do when you just edit the Text field normally instead of save you get these extra newline characters saved in the ?Text field. I confirm I have removed the newline characters in the above examples. The flanking sequences on might just be a manual cut and paste error.

**Comment by Paul-Davis** [comment]
Editor
![xaceeditor](https://user-images.githubusercontent.com/717707/59426446-267dbf80-8dd0-11e9-8e26-7a6d45c3bf3f.png)

Vs

Edit
![xaceedit](https://user-images.githubusercontent.com/717707/59426461-2f6e9100-8dd0-11e9-9bff-b4ec149dc451.png)

**Comment by nuin** [comment]
@Paul-Davis Is this on WS271? 

Thanks for fixing it.

**Comment by chris-grove** [comment]
OK thanks @Paul-Davis !
I wonder if there's an easy way to search for cases like this?

**Comment by tharris** [comment]
Yes, I'm sure it's more widespread.  We've done global replaces before with things like escaped URLs, but that might have required reloading data and not just one-off fixes.

**Comment by Paul-Davis** [comment]
Unfortunately the fix will have to percolate through the production pipeline, the fix is only in the live curation database and will only go into the WS273 release. Maybe we (hinxton) could put something in place that removed extra new lines as source during the initial ace dump and load phase of production?

**Comment by nuin** [comment]
@Paul-Davis I will monitor the rejects file and will work on a patch for 271 and 272.

**Comment by chris-grove** [comment]
Issue appears resolved in WS273 WormMine. Closing
