### ISSUE TITLE
  Hi there,  For math-48, I am trying t...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6225]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi there, <br/>For math-48, I am trying to find out where the piece of information below is coming from because I cannot find it in the references that are associated with math-48 page.<br/>"Microarray and RNA sequencing studies indicate that math-48 is affected by cyc-1, wdr-23, nhr-62, eat-2, ahr-1, npr-1, jmjd-3.1, hsf-1, let-418, chd-3, and aak-2; microarray studies indicate that math-48 is affected by Methylmercuric chloride and Paraquat; RNA sequencing studies indicate that math-48 is enriched in the male" <br/>Thank you, <br/>visitor_name</p>

**Reported by:** Zeen* (zabu***********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36

**Comment by Gschindelman** [comment]
Zeena
This description was Inferred automatically, partly using tissue expression data from the WS261 version of WormBase. If you look at the data in the math-48 “expression” widget (under page content on the left side of the math-48 gene page), you should be able to track down the references.

Sincerely
Gary Schindelman
WormBase helpdesk
On Mar 3, 2018, at 1:06 AM, no-reply@wormbase.org<mailto:no-reply@wormbase.org> wrote:

How Do I ...?

  Hi there,
For math-48, I am trying to find out where the piece of information below is coming from because I cannot find it in the references that are associated with math-48 page.
"Microarray and RNA sequencing studies indicate that math-48 is affected by cyc-1, wdr-23, nhr-62, eat-2, ahr-1, npr-1, jmjd-3.1, hsf-1, let-418, chd-3, and aak-2; microarray studies indicate that math-48 is affected by Methylmercuric chloride and Paraquat; RNA sequencing studies indicate that math-48 is enriched in the male"
Thank you,
Zeena

Submitted From:
  support /tools/support<http://www.wormbase.org//tools/support>

This issue has been assigned ticket number: #6225. Follow progress on our issue tracker<https://github.com/WormBase/website/issues/6225>.


Reported by: Zeena (zaburege@sfu.ca<mailto:zaburege@sfu.ca>)
03 Mar 18 09:06

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36

This question was reported via the web interface at wormbase.org<http://wormbase.org/>. You can also email us<mailto:help@wormbase.org> directly.

--
--
You received this message because you are subscribed to the "WormBase: help" group.
To post to this group, send email to help@wormbase.org<mailto:help@wormbase.org>
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en

---
You received this message because you are subscribed to the Google Groups "WormBase: help" group.
To unsubscribe from this group and stop receiving emails from it, send an email to help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>.
