### ISSUE TITLE
  Hi. I would like to look with you a p...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6236]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi.<br/>I would like to look with you a possible discrepency reported in WormBase vs genotype in the dlk-1 mutant JU476. I obtained this strain from CGC in october 2017. Using it for double mutant production I found that the genotype is different from what is reported in WormBase. I found an insertion of 5 base pairs as mentioned but it is different and localized 5 base pairs downstream from what is reported. Did you already received such notice from other groups regarding this strain?<br/>Thank you.</p>

**Reported by:** Fran********** (fran**********************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36

**Comment by Paul-Davis** [comment]
Hi,

Thank you for reporting this issue. I would be more than happy to look 
at fixing the data if you could forward me the sequence details you have 
obtained.

Paul

**Comment by Paul-Davis** [comment]
Hello.
I send you the last sequencing I got with the JU476 strain (two .ab1 files). You will find a Word file with primer information as well. If you have any questions, fell free to contact me.
Thank's.
Francois

________________________________________
De : Paul D. [paul.davis@wormbase.org]
Date d'envoi : 13 mars 2018 10:45
À : reply@reply.github.com; help@wormbase.org
Cc : François Houle
Objet : Re: [wormbase-help] Content Correction: Hi. I would like to look with you a p... (Francois Houle)

Hi,

Thank you for reporting this issue. I would be more than happy to look at fixing the data if you could forward me the sequence details you have obtained.

Paul

On 07/03/2018 17:44, no-reply@wormbase.org<mailto:no-reply@wormbase.org> wrote:
Content Correction

  Hi.
I would like to look with you a possible discrepency reported in WormBase vs genotype in the dlk-1 mutant JU476. I obtained this strain from CGC in october 2017. Using it for double mutant production I found that the genotype is different from what is reported in WormBase. I found an insertion of 5 base pairs as mentioned but it is different and localized 5 base pairs downstream from what is reported. Did you already received such notice from other groups regarding this strain?
Thank you.

Submitted From:
  support /tools/support<http://www.wormbase.org//tools/support>

This issue has been assigned ticket number: #6236. Follow progress on our issue tracker<https://github.com/WormBase/website/issues/6236>.

Reported by: Francois Houle (francois.houle@crchudequebec.ulaval.ca<mailto:francois.houle@crchudequebec.ulaval.ca>)
07 Mar 18 17:44

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36

This question was reported via the web interface at wormbase.org. You can also email us<mailto:help@wormbase.org> directly.

--
--
You received this message because you are subscribed to the "WormBase: help" group.
To post to this group, send email to help@wormbase.org<mailto:help@wormbase.org>
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en

**Comment by Paul-Davis** [comment]
Hi,

I have updated the information based on the data you sent for the WS266 
release.

Thanks again for forwarding this on to us.

Paul


On 13/03/2018 16:50, François Houle wrote:
> Hello.
> I send you the last sequencing I got with the JU476 strain (two .ab1 files). You will find a Word file with primer information as well. If you have any questions, fell free to contact me.
> Thank's.
> Francois
>
> ________________________________________
> De : Paul D. [paul.davis@wormbase.org]
> Date d'envoi : 13 mars 2018 10:45
> À : reply@reply.github.com; help@wormbase.org
> Cc : François Houle
> Objet : Re: [wormbase-help] Content Correction: Hi. I would like to look with you a p... (Francois Houle)
>
> Hi,
>
> Thank you for reporting this issue. I would be more than happy to look at fixing the data if you could forward me the sequence details you have obtained.
>
> Paul
>
> On 07/03/2018 17:44, no-reply@wormbase.org<mailto:no-reply@wormbase.org> wrote:
> Content Correction
>
>    Hi.
> I would like to look with you a possible discrepency reported in WormBase vs genotype in the dlk-1 mutant JU476. I obtained this strain from CGC in october 2017. Using it for double mutant production I found that the genotype is different from what is reported in WormBase. I found an insertion of 5 base pairs as mentioned but it is different and localized 5 base pairs downstream from what is reported. Did you already received such notice from other groups regarding this strain?
> Thank you.
>
> Submitted From:
>    support /tools/support<http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #6236. Follow progress on our issue tracker<https://github.com/WormBase/website/issues/6236>.
>
> Reported by: Francois Houle (francois.houle@crchudequebec.ulaval.ca<mailto:francois.houle@crchudequebec.ulaval.ca>)
> 07 Mar 18 17:44
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You can also email us<mailto:help@wormbase.org> directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help" group.
> To post to this group, send email to help@wormbase.org<mailto:help@wormbase.org>
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
