### ISSUE TITLE
I can't seem to get the Phenotypes   Genes tool...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6245]
*Help Desk query collected when no chat operators were online. Follow up required.*

I can't seem to get the Phenotypes &gt; Genes tool to work on WormMine, even if I use the example queries. I just get 'No Results
This query returns no results. You may wish to change its filters'

**Reported by:** Step************** (step*******************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/http://www.wormbase.org/tools/support?url=/">http://www.wormbase.org/tools/support?url=/</a>
**Browser:** Chrome 57.0.2987.133

**Comment by nuin** [comment]
We still need to update the template to incorporate the changes made to the mapping of Alleles on the backend.

**Comment by chris-grove** [comment]
@nuin 
If we can change this template query, can we change others as well?

**Comment by nuin** [comment]
@chris-grove My next goal is to work on templates. We should be able to modify them. Do you have a solution for `Phenotypes > Genes`?

**Comment by chris-grove** [comment]
@nuin 
Yes, there is a solution to the Phenotypes > Genes template query:

Currently the query is constructed as:

`<query name="" model="genomic" view="Gene.primaryIdentifier Gene.symbol" longDescription="Return all genes annotated with a particular phenotype.  Select either observed or not observed." sortOrder="Gene.symbol asc" constraintLogic="B and A">
  <constraint path="Gene.alleles.phenotypesObserved.name" code="A" op="=" value="transgene expression variant"/>
  <constraint path="Gene.alleles.phenotypesNotObserved.name" code="B" op="=" value="transgene expression variant"/>
</query>`

but to be consistent with the current model needs to be:

`<query name="" model="genomic" view="Gene.primaryIdentifier Gene.symbol" longDescription="Return all genes annotated with a particular phenotype.  Select either observed or not observed." sortOrder="Gene.symbol asc" constraintLogic="A and B">
  <constraint path="Gene.alleles.phenotype.name" code="A" op="=" value=" transgene expression variant"/>
  <constraint path="Gene.alleles.phenotypeNotObserved.name" code="B" op="=" value=" transgene expression variant"/>
</query>`

There are several other template queries that either need to be eliminated or edited, so I'd like to know to what extent you, I, or others are able to edit them.

**Comment by nuin** [comment]
I should re-start on templates tomorrow morning. I have some other things to test before (templates), and I will work on them later today. Keep you posted.

**Comment by chris-grove** [comment]
As mentioned on Slack, the query XML I posted above for this template was problematic due to whitespace in the constraint. The query XML for the template should be:

`<query name="" model="genomic" view="Gene.primaryIdentifier Gene.symbol" longDescription="Return all genes annotated with a particular phenotype. Select either observed or not observed." sortOrder="Gene.symbol asc" constraintLogic="A and B">
  <constraint path="Gene.alleles.phenotype.name" code="A" op="=" value="transgene expression variant"/>
  <constraint path="Gene.alleles.phenotypeNotObserved.name" code="B" op="=" value="transgene expression variant"/>
</query>`

and when generating the template, the options need to be set to make one of the phenotype name constraints to "optional, ON by default" and the phenotype not observed name constraint to "optional, OFF by default"

**Comment by chris-grove** [comment]
The "Genes > Phenotypes" template query is also not working, presumably for the same reason as the "Phenotype > Genes" template query (above) is not working:

The attribute name in the Allele class has changed from "Phenotypes Observed" to "Phenotype", so the template query as written will not work.

**Comment by chris-grove** [comment]
Hi Stephanie,

 Apologies for the error. The template has been fixed (see the "Phenotype --> Genes (new)" template query available).

Please let us know if you encounter an additional issues.

Best,

Chris Grove
WormBase
