### ISSUE TITLE
  The SimpleMine query for mdh-1 (F46E1...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6261]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;The SimpleMine query for mdh-1 (F46E10.10) outputs multiple genes as below.<br/>WBGene00003162, WBGene00018491<br/>The first one is for mdh-1 and the other is mdh-2.<br/>Both genes are not same genes and share very low sequence similarity. I haven't yet found the biochemical evidence for the cellular localization, but mdh-1 has a homology to cytoplasmic MDH in other species whereas mdh-2 is homologous to mitochondial MDH.<br/>mdh-1 gene page has confusing informations regarding the cellular localization like GO-cellular component.<br/>Can we make this clear?</p>

**Reported by:** Jae *** (jae.****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36

**Comment by chris-grove** [comment]
Hi Jae,


Could you clarify what it is you'd like to change?


"mdh-1", unfortunately, is also an other name of the gene mdh-2, so that's why mdh-2 is coming up in SimpleMine when you query for mdh-1.


As for the localization, MDH-1 is reported to be mitochondrial in Table 1 of WBPaper00035985 (Haynes et al. 2010). It is annotated to cytosol based on the IBA ("Inferred from Biological aspect of Ancestor") evidence code, and the annotation is likely automatic.


Thanks,


Chris

**Comment by chris-grove** [comment]
Thanks Chris,

I read the paper you linked, however it is still unclear what gene they want to say with "MDH-1". Since mdh-1 is another name of mdh-2 (maybe adopted the naming form yeast, but it is very confusing), they may want to say MDH-2 (mitochondrial) rather than MDH-1 (cytoplasmic). I could not see their mass-spec data for the aa sequence coverage to clarify this issue. mdh-1 and mdh-2 are quite different genes in their biological functions in other specise (maybe same to worm). 
(if they purified mitochondrial fraction well, cytoplasmic MDH-1 coul not be there, based on my experience for mitochondria research).


I have tested the aa seq of both (mdh-1 and mdh-2) for the possible cellular localization using TargetP.
Only MDH-2 has a mitochondria targeting sequence as other species.

So, any annotation for the cellular localization of mdh-1 should be wrong. This annotation is copied in other site (http://www.uniprot.org/uniprot/Q8IA50).

**Comment by chris-grove** [comment]
Hi Jae,

I can look further into the basis for the GO CC annotation.  From the evidence code, it looks to be from the PAINT, phylogenetic-based, annotation pipeline and there may have been an error there.  Either way, we'll sort it out.

Thanks,
--Kimberly
