### ISSUE TITLE
Phenotype Graph not rendering on gene pages

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#6326]
It seems that the Phenotype Graph widget is not rendering the phenotype graph on gene pages:

https://wormbase.org/species/c_elegans/gene/WBGene00006763#0b--10

Maybe due to the transition to https?

**Comment by azurebrd** [comment]
I thought that was fixed.  Is this what happens when solr stops working ?

**Comment by azurebrd** [comment]
@raymond91125 You mentioned https was set up on wobr, but this url doesn't work https://wobr.caltech.edu:81/~azurebrd/cgi-bin/amigo.cgi?action=annotSummaryJsonp&focusTermId=WBGene00006763&callback=jsonCallback&_=1523293844620  
If there's a way to make it work, I can change the javascript call to use that.  Otherwise, I suppose Todd could set up https://wormbase.org/wobr to be a reverse proxy to some URL, and I would suggest whatever domain is stable, so that we can tack on ~azurebrd or ~raymond as appropriate to have more flexibility on where we develop.  I don't know how good or bad this is though, since we need different URLs that you also proxy to point at live vs dev versions of solr, and we'd only have the one proxy.  Unless we ask for two proxies, and then have to remember to switch between them when making the code live.  (I guess, if https works, that's easiest)

**Comment by raymond91125** [comment]
it would work if we remove the hard coded port :81, I think.

**Comment by raymond91125** [comment]
https://wobr.caltech.edu/~azurebrd/cgi-bin/amigo.cgi?action=annotSummaryJsonp&focusTermId=WBGene00006763&callback=jsonCallback&_=1523293844620

**Comment by raymond91125** [comment]
@azurebrd

**Comment by azurebrd** [comment]
Made a pull request https://github.com/WormBase/website/pull/6375 that fixes this.
