### ISSUE TITLE
For the rog3 variation, the page incorrectly state...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6329]
*Help Desk query collected when no chat operators were online. Follow up required.*

For the rog3 variation, the page incorrectly states that insertion sequence is unknown. The insertion sequence is given in the overview and is agtGAGCTCg. This omission leads to the 'features affected' to predict that the mutation leads to a frameshift, which is does not. The insertion leads to a his results in a silent mutation Ser46-TCC &gt; AGT to remove the PAM site used for CRISPR-cas9 and a missense mutation of S(49)A (TCT &gt; TCG). The missense mutation is the important part of this variation as it removes a known phosphorylation site of eif-2alpha. I appreciate that wormbase is still updating its format to accommodate for CRISPR lines and want to thank you all for maintaining such an important hub of the worm community.

**Reported by:** Jaro********* (jrol**************)
**Submitted from:** <a target="_blank" href="https://wormbase.org/https://wormbase.org/species/all/strain/ANR165#02--10">https://wormbase.org/species/all/strain/ANR165#02--10</a>
**Browser:** Chrome 63.0.3239.132

**Comment by Paul-Davis** [comment]
Dear Jarod,

Thank you for pointing this out.

Currently we do not have a 100% satisfactory way of incorporating 
complex modifications and getting them to display correctly. For rog3 
the DNA change data was not captured correctly but only stored in the 
text you see in the Overview. I will correct this so that the display 
changes from a deletion into a modified block as seen in similar examples.

Hopefully in the future we will be able to display the exact nature of 
the modification with appropriate highlighting.

Paul


On 05/04/2018 23:16, no-reply@wormbase.org wrote:
> offline chat For the rog3 variation, the page incorrectly states that 
> insertion sequence is unknown. The insertion sequence is given in the 
> overview and is agtGAGCTCg. This omission leads to the 'features 
> affected' to predict that the mutation leads to a frameshift, which is 
> does not. The insertion leads to a his results in a silent mutation 
> Ser46-TCC > AGT to remove the PAM site used for CRISPR-cas9 and a 
> missense mutation of S(49)A (TCT > TCG). The missense mutation is the 
> important part of this variation as it removes a known phosphorylation 
> site of eif-2alpha. I appreciate that wormbase is still updating its 
> format to accommodate for CRISPR lines and want to thank you all for 
> maintaining such an important hub of the worm community.
>
> Submitted From:
>   https://wormbase.org/species/all/strain/ANR165#02--10 
> https://wormbase.org/species/all/strain/ANR165#02--10 
> <https://wormbase.org/https://wormbase.org/species/all/strain/ANR165#02--10> 
>
>
> This issue has been assigned ticket number: #6329. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6329>.
>
> Reported by: Jarod Rollins (jrollins@mdibl.org)
> 05 Apr 18 22:16
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
The change will not be visible until WS265 becomes available from the web services but here is a screen grab of the data that went into WS265.

![rog3](https://user-images.githubusercontent.com/717707/39577015-0b843d7c-4ed8-11e8-87db-c317e3e6c6c8.png)

**Comment by Paul-Davis** [comment]
leaving open until WS265 is available for testing
