### ISSUE TITLE
  Hi, We are trying to pull down the un...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6337]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi,<br/>We are trying to pull down the unspliced, nucleotide sequences for all the genes in C. elegans starting 2000bp before and ending 2000bp after the gene. We are using the Wormbase Parasite Biomart to retrieve these sequences using the parameters: Unspliced (Gene), Upstream Flank: 2000bp, Downstream Flank: 2000bp. We are wondering if this is the correct way to pull down the genes with 2000 bps flanks on either side, or is there a better way?<br/>We were concerned because when we BLAST the sequences returned from Wormbase Parasite, we see gaps in the hits that align to the genome. Thank you for your help.<br/>Best,<br/>Thomas</p>

**Reported by:** Thom******* (thom****************)
**Submitted from:** <a target="_blank" href="https://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0

**Comment by chris-grove** [comment]
Yes, WormBase ParaSite BioMart is the best tool to get this sequence information, and it sounds like you've constructed the appropriate query. The issue with running BLAST is that the algorithm will find the exact match but then also look for similar sequences nearby, often making it look like the hit has gaps in the match/alignment but this is really an artifact of the algorithm searching for nearby matches or near-matches. When searching for exact sequence matches in the genome I would recommend using the BLAT algorithm which is more efficient (faster) and may result in a cleaner hit. The BLAT results may also appear to have gaps in the alignment, but again, this is because it is searching for additional near-matches. The best thing is to actually look at the sequence track in the genome browser and zoom in to see the beginning and end of the exact match and/or download the sequence surrounding the "core" match and confirm that it is an exact match to your sequence (by basic text search in a text editor or using an alignment tool like Clustal Omega).


I hope that helps. Let us know if you need anything else or have questions.
