### ISSUE TITLE
  Hello, I am wondering where I can dow...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6364]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello,<br/>I am wondering where I can download physical to genetic position coordinates for C. elegans. I know you have an online tool to look genetic positions of genes, but I would like to have the data for other purposes. I checked the gff and I couldn't find it. <br/>Thank you!</p>

**Reported by:** Stef************* (szdr**************)
**Submitted from:** <a target="_blank" href="https://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

**Comment by chris-grove** [comment]
We don't currently have a tool to query for physical and genetic positions of genes simultaneously, or a file that has both, but you can get this information using our data mining tools WormMine and SimpleMine.

To get genetic map positions, go to SimpleMine (discoverable under the WormBase Tools menu on any WormBase page):

https://wormbase.org/tools/mine/simplemine.cgi

Choose the fields you would like to see in your output table, like Gene ID and Public Name, and make sure to include "Genetic Map Position" and then click on "query all C elegans". This will produce a tab-delimited file with the gene names and their respective genetic positions.

To acquire the list of physical coordinates, use the WormMine tool (also discoverable under the WormBase Tools menu on any WormBase page):

http://intermine.wormbase.org/tools/wormmine/begin.do

Go to the QueryBuilder tab, click on "Import query from XML", and paste in the following XML query:

`<query name="" model="genomic" view="Gene.primaryIdentifier Gene.secondaryIdentifier Gene.symbol Gene.chromosome.primaryIdentifier Gene.chromosomeLocation.strand Gene.chromosomeLocation.start Gene.chromosomeLocation.end" longDescription="" sortOrder="Gene.primaryIdentifier asc">
  <constraint path="Gene.organism.name" op="=" value="Caenorhabditis elegans"/>
</query>`

click "Submit" and on the following screen click on "Show results". This should direct you to the table of results showing all C. elegans genes and their physical coordinates. You can then use the "Export" function to download a tab-delimited file with the data.

You would then need to merge the files to get a single file with both data sets. One way to effectively achieve this is to take the list of gene IDs from the WormMine output, paste them (in order) into the SimpleMine interface, select the "allow duplicate genes" to make sure to preserve input order, select "Genetic Map Position", click on "query list", and then take the resulting output from a spreadsheet program like Excel (watch out for gene names being converted to dates! Import as "Text" instead of "General" to avoid this), copy the list of genetic map positions and paste them (in order) back into your WormMine output table. That will save you from having to write a script to merge the files.
