### ISSUE TITLE
  I am trying to have access to fosmid ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6417]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I am trying to have access to fosmid clones sequences but I cannot (I tried for several microRNAs). Do you have any idea why?<br/>Thanks a lot, I hope we can solve this problem soon!<br/>Best,<br/>Chiara</p>

**Reported by:** Chia********** (chia********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.76 Safari/537.36

**Comment by chris-grove** [comment]
Apologies for the difficulties. Could you specify exactly what you tried and what failed? I'm unable to replicate an error like the one you describe.

**Comment by chris-grove** [comment]
@vanaukenk 
OK, thanks!

**Comment by chris-grove** [comment]
From user:
"Sorry if I was not super clear. Basically, I need to design fosmid reporters for several microRNAs and the way I usually do this is to write the gene name in wormbase, go to location and choose the available fosmid clone which is covering better the locus of interest. Once I decide for one fosmid clone, I usually click on it and I am introduced to another “page” of the fosmid clone, where I can download the sequence of the entire fosmid locus. Yesterday and today this operation was not possible, meaning that:

<img width="323" alt="image001" src="https://user-images.githubusercontent.com/611382/40120852-30d02cb0-58ee-11e8-9981-f14425c95610.png">

I cannot visualize the sequence of the locus (here is just an example, for fosmid WRM0636cG07). Indeed, if I click on the corresponding sequence using this command , I only get the following (and not the ape file with nucleotide sequence):

<img width="285" alt="image003" src="https://user-images.githubusercontent.com/611382/40120867-36465480-58ee-11e8-868e-7c998dc759fb.png">
 
I hope now it is clearer. In case of any doubt, please ask me! I will be happy to answer!
Thanks a lot for your help and all the best!"

**Comment by a8wright** [comment]
@chris-grove  I looked in the database and found that the sequence does not exist for the Fosmid clones. I have talked with @khowe and he says that for Fosmids we do not have the full sequence of the clone... we only have the sequences from the ends. I am not sure where the sequence that the Ace code is producing is coming from. @khowe said that I should make it say that there isn't a sequence available. So that is what I have done. https://staging.wormbase.org/species/c_elegans/clone/WRM061dC06#47--10

@chris-grove if this looks right to you I will release the change to production.

**Comment by sibyl229** [comment]
Hi @khowe @a8wright told me that he can produce sequence length for pair-end reads, even though the full sequence isn't available. Is it useful to show the length? The website code currently doesn't handle this scenario. I wonder if this needs to be fixed. Thanks!

**Comment by chris-grove** [comment]
@a8wright 
OK, thanks, staging looks good.
@sibyl229 
Sure, sequence length is helpful to know.

**Comment by khowe** [comment]
@sibyl229 @chris-grove @a8wright If you map the sequences of the clone ends to the reference genome, and then calculate the distance between the start of the left end and the end of the right end, you will obtain an estimate of the length of the fosmid. But it is only an estimate, because the fosmid may have different sequence compared with the reference genome over that region (i.e. indels). 

So technically, we should report it as estimated sequence length where we do not have the full sequence.

**Comment by chris-grove** [comment]
@khowe 
Yep, good point. Thanks!

**Comment by chris-grove** [comment]
The production site is still showing the "HASH(0xe894798)" in the "Sequence" field of the "Sequences" widget on the clone page. I will close this ticket once the fix has propagated to production indicating to users that the complete sequence is unavailable.

**Comment by Paul-Davis** [comment]
@chris-grove 

Staging seems to have been patched.

Paul

**Comment by chris-grove** [comment]
@Paul-Davis 
Yes, I was aware that a fix had been made available on staging, but my understanding was that the fix was supposed to migrate to production, at which point I would close the ticket.
@a8wright 
If I should close the ticket because the fix is on staging (but not on production), let me know.

**Comment by a8wright** [comment]
Hi @chris-grove and @Paul-Davis I had created the fix. It is on staging and on production. @sibyl229 had looked into it a little yesterday but our cache is supposed to expire every 24 hours. We are not sure why it is not expiring. @sibyl229 said she would be looking into it. I vote for closing the ticket :)

**Comment by chris-grove** [comment]
OK, thanks. Closing.
