### ISSUE TITLE
need help with two different worm-mine queries - one returns data, the other doesn't :-

### ISSUE THREAD

**Issue by vanaukenk** [WormBase/website#6420]
Hi,

I’ve inherited a wormine REST API query which was returning data fine in Feb, but isn’t any more :-(

I’ve reproduced it in the website, and its seems to be driven by the fields I _select_, rather than the way I’m filtering:

This code returns a single gene with a couple of alleles, one of which has a lethal phenotype:

require "rubygems"             
require "intermine/service"    
service = Service.new("http://intermine.wormbase.org/tools/wormmine")
service.new_query("Gene").
    select(["alleles.phenotype.description", "alleles.phenotype.identifier", "alleles.phenotype.name"]).
    where("Gene.primaryIdentifier" => "WBGene00000276").
    # where("Gene.alleles.phenotype.name" => {:contains => "lethal"}).
    order_by("alleles.phenotype.description", "ASC").
    limit(10).                 
    each_row { |r| puts r}

<< prints out
Gene: alleles.phenotype.description=Animals die prematurely at any stage of the life cycle …
Gene: alleles.phenotype.description=Animals generate defective gametes …
>>

WHEREAS by simply adding a few fields to the select statement, I manage to get NO results returned at all

require "rubygems"             
require "intermine/service"    
service = Service.new("http://intermine.wormbase.org/tools/wormmine")
service.new_query("Gene").
    select(["alleles.phenotype.description", "alleles.phenotype.identifier", "alleles.phenotype.name", "alleles.phenotypesObserved.description", "alleles.phenotypesObserved.name", "alleles.phenotypesObserved.identifier"]).
    where("Gene.primaryIdentifier" => "WBGene00000276").
    # where("Gene.alleles.phenotype.name" => {:contains => "lethal"}).
    order_by("alleles.phenotype.description", "ASC").
    limit(10).                 
    each_row { |r| puts r}

<<nothing printed out>>

I’ve reproduced this behaviour in the query builder web form, and it seems to be the way the intermine works. BUT it didn’t use to do this: as late as February, the second query was returning results. The basic problem is that I don’t know what the interpretation of the “alleles.phenotypesObserved.name” and “alleles.phenotypesNotObserved.name” fields/entities are, compared to “alleles.phenotype.name” field / entity, but I do know that this code was querying them before, and they are stopping any results coming through now. 

Has the data model been changed in the meantime? Can someone help me with this?

Thanks,

Vivek

**Comment by chris-grove** [comment]
From @nuin 
"""
Thanks for reporting the error. A couple of things before I try your queries on our latest release:

- from February’s production version to the current one we have on the website, there has been some changes in the underlying model of our WormMine database, mainly affecting the Alleles class and its relationship to the Phenotype class, among others. These changes would affect most queries that were set before this release, especially with the Alleles class.
- you might want to try one the templates related to the classes you are trying to query, in order to understand the changes that were implemented


Would you be able to send your queries in InterMine’s Xml format? I don’t have the required Ruby packages installed to reproduce your queries and help your further.
"""

**Comment by chris-grove** [comment]
From user:
"""
Thanks for the response. 

Ok, in XML format, this query was similar to the one that I was running in Feb, that has now stopped returning any data:

`<query model="genomic" view="Gene.alleles.phenotypeNotObserved.description Gene.alleles.phenotypeNotObserved.identifier Gene.alleles.phenotypeNotObserved.name Gene.alleles.phenotype.description Gene.alleles.phenotype.identifier Gene.alleles.phenotype.name" sortOrder="Gene.alleles.phenotypeNotObserved.description ASC" >
<constraint path="Gene.primaryIdentifier" op="=" value="WBGene00000276" code="A" />
</query>`

- this query pulls back nothing. However,  by removing PhenotypeNotObserved columns, I actually get data back:

`<query model="genomic" view="Gene.alleles.phenotype.description Gene.alleles.phenotype.identifier Gene.alleles.phenotype.name" >
<constraint path="Gene.primaryIdentifier" op="=" value="WBGene00000276" code="A" />
</query>`

- 2 rows come back!


Also, the actual query I was running in Feb (which I can’t exactly reproduce with the web interface) referred to additional fields that don’t seem to exist any more: namely the “phenotypesObserved.description”, “Gene.alleles.phenotypesObserved.name”, “Gene.alleles.phenotypesObserved.identifier” fields - have they been removed?
"""

**Comment by chris-grove** [comment]
From @nuin:
"""
Thanks for the queries.

Regarding the first one, it seems that you are constraining the display for Alleles IF they have BOTH conditions, which I don’t think would happen in this case (I am not a curator or specialist in C elegant biology). If you allow for the query to show all alleles EVEN if they don’t have the condition I got the same result as the second query, but with other items in the table. Try this one

`<query model="genomic" view="Gene.alleles.phenotypeNotObserved.description Gene.alleles.phenotypeNotObserved.identifier Gene.alleles.phenotypeNotObserved.name Gene.alleles.phenotype.description Gene.alleles.phenotype.identifier Gene.alleles.phenotype.name" >
  <join path="Gene.alleles.phenotype" style="OUTER"/>
  <join path="Gene.alleles.phenotypeNotObserved" style="OUTER"/>
  <constraint path="Gene.primaryIdentifier" op="=" value="WBGene00000276" code="A" />
</query>`

In this you would do an outer join of the tables and this would make the join to actually work. I forwarded you message to Chris Grove, one of the curators and he can help you more on the biological side of things as long as querying InterMine.

Also, the actual query I was running in Feb (which I can’t exactly reproduce with the web interface) referred to additional fields that don’t seem to exist any more: namely the “phenotypesObserved.description”, “Gene.alleles.phenotypesObserved.name”, “Gene.alleles.phenotypesObserved.identifier” fields - have they been removed?


I will double check the changes we made to model and will get back to you.
"""

**Comment by chris-grove** [comment]
From me:
"""
Yes, Paulo is correct about the first query. The query as you sent it:

`<query model="genomic" view="Gene.alleles.phenotypeNotObserved.description Gene.alleles.phenotypeNotObserved.identifier Gene.alleles.phenotypeNotObserved.name Gene.alleles.phenotype.description Gene.alleles.phenotype.identifier Gene.alleles.phenotype.name" sortOrder="Gene.alleles.phenotypeNotObserved.description ASC" >
<constraint path="Gene.primaryIdentifier" op="=" value="WBGene00000276" code="A" />
</query>`

is actually using inner joins to ask for all alleles of the gene WBGene00000276 (byn-1) for which there are both observed phenotypes AND not observed phenotypes. This would only work if there were any alleles reported with both observed AND not observed phenotypes (and only return that subset of alleles that met both criteria), but for this gene there aren't any single alleles that have both types of data. It would be best to run separate queries for observed and not observed phenotype data, like:

1)
`<query name="" model="genomic" view="Gene.alleles.phenotype.description Gene.alleles.phenotype.identifier Gene.alleles.phenotype.name" longDescription="">
  <constraint path="Gene.primaryIdentifier" op="=" value="WBGene00000276"/>
</query>`

which is essentially the stripped down version that you got to work (because it is only asking for observed phenotypes).

and

2)
`<query name="" model="genomic" view="Gene.alleles.phenotypeNotObserved.description Gene.alleles.phenotypeNotObserved.identifier Gene.alleles.phenotypeNotObserved.name" longDescription="">
  <constraint path="Gene.primaryIdentifier" op="=" value="WBGene00000276"/>
</query>`

which returns 0 results because there are no alleles of byn-1 that have been annotated with a "not observed" phenotype.

To clarify, observed phenotypes are those actually observed to be brought about or affected by some genetic perturbation (in this case alleles), whereas "not observed" phenotypes are phenotypes that have been reported to be assayed for but that were not observed when tested with that particular genetic perturbation (again, in this case alleles).

As for your other question about the fields:

“phenotypesObserved.description”
“Gene.alleles.phenotypesObserved.name”
“Gene.alleles.phenotypesObserved.identifier”

Yes, there has since been a model change and the equivalent fields are now titled:

"Phenotype.description"
"Gene.alleles.phenotype.name"
"Gene.alleles.phenotype.identifier"

As for your original Ruby code queries, your first query would be:

`require "rubygems"
require "intermine/service"
service = Service.new("http://intermine.wormbase.org/tools/wormmine")

service.new_query("Gene").
    select(["alleles.phenotype.description", "alleles.phenotype.identifier", "alleles.phenotype.name"]).
    where("Gene.primaryIdentifier" => "WBGene00000276").
    order_by("alleles.phenotype.description", "ASC").
    limit(10).
    each_row { |r| puts r}`

As for your second Ruby query, it wouldn't work because there is no longer the "phenotypesObserved" attribute of alleles; it has since been changed to simply "phenotype".

Also note that gene phenotypes are stored in two places in WormMine, under Alleles and under RNAi. So, if you wanted to get a list of all observed phenotypes for the gene byn-1, you would want to run the following XML queries separately:

`<query name="" model="genomic" view="Gene.alleles.phenotype.description Gene.alleles.phenotype.identifier Gene.alleles.phenotype.name" longDescription="">
  <constraint path="Gene.primaryIdentifier" op="=" value="WBGene00000276"/>
</query>`

and

`<query name="" model="genomic" view="Gene.RNAiResult.phenotype.description Gene.RNAiResult.phenotype.identifier Gene.RNAiResult.phenotype.name" longDescription="" sortOrder="Gene.RNAiResult.phenotype.description asc">
  <constraint path="Gene.primaryIdentifier" op="=" value="WBGene00000276"/>
</query>`

or respectively in Ruby:

`require "rubygems"
require "intermine/service"
service = Service.new("http://intermine.wormbase.org/tools/wormmine")

service.new_query("Gene").
    select(["alleles.phenotype.description", "alleles.phenotype.identifier", "alleles.phenotype.name"]).
    where("Gene.primaryIdentifier" => "WBGene00000276").
    order_by("alleles.phenotype.description", "ASC").
    limit(10).
    each_row { |r| puts r}`

and

`require "rubygems"
require "intermine/service"
service = Service.new("http://intermine.wormbase.org/tools/wormmine")

service.new_query("Gene").
    select(["RNAiResult.phenotype.description", "RNAiResult.phenotype.identifier", "RNAiResult.phenotype.name"]).
    where("Gene.primaryIdentifier" => "WBGene00000276").
    order_by("RNAiResult.phenotype.description", "ASC").
    limit(10).
    each_row { |r| puts r}`


I hope that helps. Please let us know if you have any additional questions.
"""
