### ISSUE TITLE
Hello, I need to convert a large list of C. elegan...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6442]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello, I need to convert a large list of C. elegans genes into one of the following formats: DbSNP, Entrez Gene, GenBank, GenPept, NCBI GI number, UniGene, and SwissProt/UniProt identifiers. Can you recommend how to do that? Entrez Gene, GenBank and NCBI GI number would be my preferences. Thank you, visitor_name

**Reported by:** Elen* (evay****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/resources/person/WBPerson1710#01--10">https://wormbase.org/resources/person/WBPerson1710#01--10</a>
**Browser:** Chrome 66.0.3359.139

**Comment by chris-grove** [comment]
You can use the WormBase ParaSite BioMart tool to retrieve the GenBank, NCBI, RefSeq and UniProt IDs, for example in this query:

http://parasite.wormbase.org/biomart/martview?VIRTUALSCHEMANAME=parasite_mart_10&ATTRIBUTES=wbps_gene.default.feature_page.display_name_1010|wbps_gene.default.feature_page.wormbase_gene|wbps_gene.default.feature_page.external_gene_id|wbps_gene.default.feature_page.wormbase_gseq|wbps_gene.default.feature_page.wormbase_transcript|wbps_gene.default.feature_page.embl|wbps_gene.default.feature_page.entrezgene_id|wbps_gene.default.feature_page.entrezgene_name|wbps_gene.default.feature_page.refseq_mrna|wbps_gene.default.feature_page.refseq_peptide|wbps_gene.default.feature_page.uniprot_swissprot_accession|wbps_gene.default.feature_page.uniprot_sptrembl&FILTERS=wbps_gene.default.naive_filters.wbps_gene_id."WBGene00001597,WBGene00185067,WBGene00006983,WBGene00004506"|wbps_gene.default.naive_filters.species_id_1010."elegaprjna13758"&VISIBLEPANEL=resultspanel

You can apply the same query to your gene list by replacing the current gene list with your gene list in the Query Filters section of the BioMart tool.

Once you have UniProt IDs, you can use the UniProtKB mapping tool:

https://www.uniprot.org/uploadlists/

to get the IDs in other formats, like Entrez Gene and UniGene.

Let us know if you have further questions.

**Comment by chris-grove** [comment]
From user:
"Thanks very much for the prompt response and including the link to the actual query! I've actually been exploring ParaSite over the last hour and have come close to getting it to give me the results that I need, but am still struggling with getting them in the required format.

I notice that many of the UniProt IDs are missing from your list (and this will likely be the case for mine). If there is no UniProt ID, does this mean that I cannot convert that gene to Entrez (and some other formats)? Or is there a workaround?"

**Comment by chris-grove** [comment]
My email response to user:
"""
Can you give me some examples of genes that are missing UniProt IDs? In the example query I provided, there is one isoform of the gld-3 gene, transcript T07F8.3b, that doesn't have a UniProt ID listed, but looking into it, it is actually just the same as the ID for isoform a: "Q95ZK7". I'll look into why that particular transcript isoform isn't displaying a UniProt ID. I've checked some other gene lists, and in all cases when a UniProt ID is missing for some isoforms, at least one isoform of the gene has a UniProt ID and my hunch is that that ID will be the representative ID for the gene.

So, I think as long as you can acquire at least one UniProt ID for a gene (even if not explicitly for all isoforms) that should be sufficient.
"""

**Comment by chris-grove** [comment]
Looking more into this I've found several instances of genes that have a UniProt ID on WormBase, but completely lack a UniProt ID in ParaSite BioMart. Will create a separate ticket.

**Comment by chris-grove** [comment]
My email to user:
"""
OK, I've looked into the issue a bit more and it seems that there are many UniProt IDs missing for specific isoforms, but in most cases at least one isoform has an ID. In a more limited set of cases, it seems that some C. elegans protein coding genes do not have any UniProt ID. I generated a GitHub ticket where you can follow progress on the issue:

https://github.com/WormBase/website/issues/6443

I'm still assessing the extent of the problem but randomly looking at ~3,300 genes, 6 (0.2%) had no UniProt ID at all.

No, there's no reason you can't feed a large list (20K-100K items) into BioMart. In fact, to do the query for all C. elegans genes in ParaSite BioMart you would just need to remove the input gene list as in this query:

http://parasite.wormbase.org/biomart/martview?VIRTUALSCHEMANAME=parasite_mart_10&ATTRIBUTES=wbps_gene.default.feature_page.display_name_1010|wbps_gene.default.feature_page.wormbase_gene|wbps_gene.default.feature_page.external_gene_id|wbps_gene.default.feature_page.wormbase_gseq|wbps_gene.default.feature_page.wormbase_transcript|wbps_gene.default.feature_page.uniprot_swissprot_accession|wbps_gene.default.feature_page.uniprot_sptrembl&FILTERS=wbps_gene.default.naive_filters.species_id_1010."elegaprjna13758"&VISIBLEPANEL=resultspanel

Or you can paste in a list (or upload a file with a list) of gene IDs or names, transcript IDs, or protein IDs etc. (see screenshot) under:

Query Filters > GENE > ID list limit

Let me know if you have any questions.
"""

**Comment by chris-grove** [comment]
From user:
"I am having trouble with feeding a large list and getting the results. I created a file (see attached) which I upload in Query Filters to "ID List Limit" as you suggested. The output that I get (below) does not make any sense. Can you advise?"

**Comment by chris-grove** [comment]
My response:
"""
A few things:


1) I would recommend only uploading simple *.txt text files with the list of gene names (with no header "GeneName"); I don't think the BioMart tool can upload/process an Excel file


2) Do you have the original list, before being imported into Excel? The reason I ask is that your gene list appears to have suffered a common problem when gene names are imported into Excel: gene names like "mars-2", "mars-4", "apr-2", "jun-2", "sep-2" and "oct-2" are being automatically converted to data objects in Excel so that they now read "2-Mar", "4-Mar", "2-Apr", "2-Jun", "2-Sep", and "2-Oct", respectively. To avoid this problem in Excel, you need to make sure that you are importing all gene names in the "Text" format and not the "General" format which will always automatically convert (irreversibly) gene names like those above into date objects.


3) The output you provided, albeit lacking delimiters and newlines, makes sense if your input list consisted of the gene names "gld-3", "rpt-6", "zig-6", and "Y54G11A.17". You can download the table in CSV, TSV, or directly into Excel (XLS) formats. When I take a sample of genes from your list and run the query:


http://parasite.wormbase.org/biomart/martview?VIRTUALSCHEMANAME=parasite_mart_10&ATTRIBUTES=wbps_gene.default.feature_page.display_name_1010|wbps_gene.default.feature_page.wormbase_gene|wbps_gene.default.feature_page.wormbase_gseq|wbps_gene.default.feature_page.external_gene_id|wbps_gene.default.feature_page.wormbase_transcript|wbps_gene.default.feature_page.uniprot_swissprot_accession|wbps_gene.default.feature_page.uniprot_sptrembl|wbps_gene.default.feature_page.entrezgene_id|wbps_gene.default.feature_page.entrezgene_name&FILTERS=wbps_gene.default.naive_filters.species_id_1010."elegaprjna13758"|wbps_gene.default.naive_filters.gene_name."2L52.1,2RSSE.1,4R79.2,aagr-1,aagr-2,aagr-3,aagr-4,aak-1,aak-2,aakb-1,aakb-2,aakg-1"&VISIBLEPANEL=resultspanel


I can get an Excel file output that looks good (attached). It seems that the Excel file generated by BioMart gets around the gene name conversion to dates issue.


4) Because many genes do not have a UniProt/SwissProt ID but do have a UniProt/TrEMBL ID, I would recommend querying for both UniProt ID types (as in the query linked above), otherwise you'll get lots of genes that will be missing a UniProt ID.


5) I would also recommend querying out the Transcript ID, as UniProt IDs are usually directly linked to Transcript IDs and without pulling them out, you'll likely see many apparently redundant lines in your output for the same gene (the reason being that the query still returns a line for each transcript).
"""

**Comment by chris-grove** [comment]
User response:
"""
Thank you for your last email. I ran my list of genes as per your instructions and received an output in the correct format, however, I am confused because the output genes do not match the input gene that I provided!? I am attaching my txt input file as well as my .xls output file so you can have a look. Am I missing something obvious here?

Also, for your point #5 below, are you referring to the "Transcript stable ID" under Output Attributes? 
"""

My response:
"""
The default behavior of BioMart (and many other such tools) is to return the list of genes in order of name or ID, as opposed to the original input order. In this case, the results are ordered according WormBase Gene ID (e.g. WBGene00000001), even if that ID isn't returned/displayed in the table. In the case of BioMart, I don't think there is an option to output the list of genes in the order in which they were received.

The other complication here is that your BioMart output for your query is going to have multiple lines per gene (one line per transcript), so if you need the output in the order in which you put the list in, you also would need to account for multiple lines per gene.

If you let me know what your requirements are, I may be able to suggest a solution to your problem.

Yes, either "Transcript stable ID" under:

Output Attributes > Create a data table > GENE > Gene Attributes

or "WormBase transcript ID" under:

Output Attributes > Create a data table > EXTERNAL DATABASE REFERENCES AND ID CONVERSION > External References

They return the same thing.
"""

**Comment by chris-grove** [comment]
I just wanted to point out that your attached file "LargeDataSetTestUpReg.txt" contains a number of entries in the list that are not official gene names:


2-Mar
4-Mar
5-Mar
6-Mar
7-Mar
2-Apr
2-Jun
2-Sep
2-Oct
3-Oct


These are all likely the result of gene names being automatically converted to dates upon import into Excel or a similar program. Any attempt to import these names into BioMart or other tools will fail to recognize them as genes. I would suggest going back to the original source of the gene list to make sure you have the gene names in the correct, unaltered format before proceeding.

**Comment by chris-grove** [comment]
From user:
"""
Thanks very much for catching those wrong date entries! 

Basically, what I am trying to do is to convert C. elegans common gene names to one of the formats I mentioned previously. It is important for me to preserve the same order because each gene entry matches several columns of associated data including fold change, p-value and FDR - results from an RNAseq study. My goal is to convert the genes, then paste them into a program called IPA which can provide information about mechanistic linkages, enrichment pathways, visualization, etc. IPA only takes in inputs of a certain format: http://qiagen.force.com/KnowledgeBase/articles/Basic_Technical_Q_A/Data-Upload-definitions

When I sort my output file in Excel based on the original gene names, I get multiple gene entries for each gene, which makes it so that I cannot match each row with its original associated data. I think what I need to do is to pick a single format and then click on "Unique IDs" so that Biomart only returns a single entry in one of the desired formats and I can then match that entry to the other associated data. I will be trying to do that next, but if you have any suggestions about which of the output formats may work best for that or how to sort to get the output gene list and their associated data columns in the right order, please let me know. 
"""

**Comment by chris-grove** [comment]
My email repsonse:
"""
OK, you may want to try our SimpleMine tool (discoverable under the Tools menu):

https://www.wormbase.org/tools/mine/simplemine.cgi

SimpleMine takes in a list of genes and returns a table with data for each gene, and only one row per gene. Also, if you turn on the "allow duplicate genes" option, your output table will preserve your input gene list order. The issue is that SimpleMine doesn't offer as many external DB IDs as ParaSite BioMart, but it does offer UniProt, TreeFam, and RefSeq IDs. If you can work with the UniProt IDs provided by SimpleMine, then I think that should address your problem.

If not, let me know.
"""

**Comment by chris-grove** [comment]
User:
"I ran SimpleMine and it preserves the order - great! Now the problem I am running into is multiple types of data types in the same column after I delimit in Excel. For example, column 2 in the attached SimpleMine output file has BOTH CAEEL and Uniprot ID. What is CAEEL?

Column 3 has BOTH Wormbase ID and Uniprot ID even though I did not tick the Wormbase ID box for the output, but the Wormbase IDs are only present for some genes but not others? 

I suspect the issue is with the way Excel delimits (I sat maximum number of delimiters to open the txt file in Excel and saved as csv). I think I should also be able to combine columns. Can you recommend the simplest way to do this based on the attached files? Attached: First file = txt input; second file = SimpleMine txt output; third file = my delimited SimpleMine csv Excel output file.   

Thank you! PS Still have not dealt with the month issue will do that right after I figure out the basic formatting issue."

**Comment by chris-grove** [comment]
My response:
"""
The SimpleMine output like:

CAEEL|WormBase=WBGene00044315|UniProtKB=Q4TTB5

is actually a PANTHER database ID for the gene. I believe one of our SimpleMine developers considered that a useful source of UniProt IDs, but I think it is always redundant with the actual UniProt IDs we have on file for the gene. I've asked her to consider removing the PANTHER ID so that we just show unique UniProt IDs. She's looking into it now.

For the record, "CAEEL" is a short-hand code for C. elegans. I'm not sure which other database(s) are the primary source for this code, but I think UniProt is one of them. I'm not exactly sure why some genes have these PANTHER IDs and others do not, but I think it's simply an asynchronous database issue. The SimpleMine output is tab-delimited, so if you are using tabs as delimiters in Excel, that should be good enough.

I'm not sure I understand your request about combining the columns. What is the format of your ideal output?
"""

**Comment by chris-grove** [comment]
User:
"Ideal format:

Column 1: common gene name (from my input file)

Column 2: UniProt ID - as in ALL UniProt IDs in the SAME column. Right now they are spread across 3 different columns or if I delimit so they are all in the same column, in addition to the UniProt ID, I also get a lot of other information and I cannot use that column as my input file for the other software. It needs to contain just the UniProt ID alone and now the UniProt IDs are gathered across three different columns."

**Comment by chris-grove** [comment]
My response:
"OK, could you try the SimpleMine query again? The issue with the other IDs showing up has been fixed and duplicates have been removed. There will still often be multiple UniProt IDs per gene.

Let us know if that works for you."

**Comment by chris-grove** [comment]
User:
"Thank you for letting me know. We went ahead and wrote a short script yesterday to pull out only the UniProt IDs in one column next to the gene names, but I just ran SimpleMine right now and the output looks much better but still has some issues (see attached). You can still see examples of "extra" entries in column 2. I'll be happy to do it again if need me too. I think it would be greta to be able to have cleaned up results and it looks like we are almost there.

One more question for you. I am hunting for a program that would allow me to analyze a large RNAseq dataset - pathway enrichment, upstream regulators, biological functions and disease associations. Something beyond DAVID, and GO terms. I know I can't have it all in a GUI but something approaching that would be great. Do you have any suggestions? Are there any tools through Wormbase or anything else that you can recommend? 

I am currently testing Qiagen's IPA and am finding that less than 25% of all C. elegans genes have a UniProt ID that also shares a human homolog using HomoloGene (that's how IPA determines if it will include a given gene in its analysis pipeline)

Thank you!"

**Comment by chris-grove** [comment]
My response:
"""
OK, as I mentioned in my last email, there will often times be multiple UniProt IDs per gene. These aren't really "extra", it's just that genes may have a one-to-many relationship with UniProt IDs, often to account for multiple protein isoforms expressed from the same locus. Do you need a single UniProt ID for each gene, as opposed to multiple?

There has been an attempt to assign a single, unique UniProt ID for each gene to act as a "reference" UniProt ID for the gene. This is called the Gene-Centric Reference Proteome (GCRP) ID and is usually an existing SwissProt or TrEMBL ID that has been selected to represent the gene. We don't currently have an easy way (using publicly facing data mining tools like SimpleMine, WormMine or BioMart) to query specifically for the unique GCRP ID, but I've queried the underlying database and am attaching a mapping file linking each gene (ID or name) to each single GCRP ID. I don't think we want, at this point, to restrict the SimpleMine UniProt output to only GCRP IDs, as I think often times users want the complete list.

I don't have any suggestions for analysis of raw RNAseq data. Once you have a set of genes to analyze for enrichment, I could recommend the (relatively new) Gene Set Enrichment Analysis tool available at WormBase (discoverable under the Tools menu):

https://www.wormbase.org/tools/enrichment/tea/tea.cgi

which will perform tissue enrichment, phenotype enrichment, and GO-term (for biological function) enrichment analysis , but it sounds like you may be looking for more sophisticated analysis tools. You can also use SimpleMine to retrieve disease associations ("Disease Info" attribute) and interacting genes ("Interacting Gene" attribute) in which you may find regulators. Other than that, I don't really have other suggestions off hand.
"""

**Comment by chris-grove** [comment]
My email to user:

"Our SimpleMine developer has added a new attribute to the list of possible outputs, "Reference UniProt ID", which should be the single GCRP ID per gene. I should point out that SimpleMine looks for matches of gene names in the primary Public_name attribute of the gene as well as the Other_name attribute. Some genes (including 62 from your input list) match multiple (usually two) genes. These are listed at the bottom of the SimpleMine output under the heading "Multiple Output Below".

To clarify which of these is the "correct" one I would recommend retrieving the "Public Name" attribute from each gene in your list to make sure that output matches your input. In general, this is why it is better to use WBGene IDs than public gene names so as to avoid ambiguity."

**Comment by chris-grove** [comment]
From user:
"""
Thank you for the information in your last email, the list of resources and the gene mapping file. Yes, exactly. I do need just a single UniProt ID in the second column and I understand that it is not a straightforward process to get that because it involves making inferences on the user's behalf about what kind of IDs are more relevant. One might not want to discard the other choices because they do not appear first, and I get that. What I was suggesting is that it would be really useful to have each UniProt ID appear in its own column. So have it exactly as it is now, but cleaned up to where only a single UniProt ID appears in each column and there are no commas, spaces etc within a single column that separate the different UniProt IDs. So perhaps the first column (after the common name gene column) would start with the GCPR ID, and the subsequent columns would include one each additional UniProt IDs based on whatever logical defined order you guys decide on your end. I think that type of output would be useful for many researchers working with large datasets. Right now, the easiest way for me to get at my whole list of genes and just have one properly formatted UniProt column is to use a custom Python script to clean up the original output file in SimpleMine.

I appreciate the data mining resources you listed. I did not know about TEA, PEA, GEA and Interacting Gene features. My RNA-Seq data set is not raw. It has already been run through the Tuxedo Suite and has fold change, FDR, p-values and other data associated with each gene. I am now at a point where I am trying to make sense of the data basically using all of the functionalities you described. So essentially what I was asking is for recommendations of resources that would take this kind of processed data with associated values (significances) for each gene and provide all the attributes you described - pathway enrichment, upstream regulators, disease associations - but drawing on my own processed data rather than external references like TEA. That's the strength of the program I am currently using - it takes into account the actual significances associated with each gene (unfortunately at a ridiculous monetary cost! and of course it is not open source so those are major limitations). If you know of any programs that can do that using the user's own processed data, even for one or two attributes, please let me know.

By the way, I did run TEA, PEA and GEA, but for some reason am not able to download my results file. When I click on "download results table here" for TEA, PEA and for GEA, a new tab pops up but then nothing happens. I used just a single column of common gene names in txt format as my input file and the program did tell me that many of them were recognized (e.g. "Your list has 18 valid WormBase genes included in statistical testing"). My Chrome version is 66.0.3359.181 in case that helps.

Thanks again for your continued help and suggestions!
"""

**Comment by chris-grove** [comment]
My response:
"""OK, so for the single UniProt output I believe the new "Reference UniProt ID" attribute in SimpleMine should work. As for returning each UniProt ID in its own column, this might make sense for a specialized query tool that specifically deals with returning UniProt IDs, but is beyond the scope of what SimpleMine (or, honestly, any of our other data mining tools) is intended for. Usually with large data mining queries and analyses there's just no way to avoid having to do some scripting to post-process the data/files.

I don't know of any tools that will take your list of genes and associated significance values and return the information you're looking for.

I cannot replicate the problem with downloading the results file in the enrichment analysis tool. Can you send me the exact list of gene names that you entered into the tool for which you encountered the problem? I'm also using the same version of Chrome."""

**Comment by chris-grove** [comment]
From user:
"Thank you for adding the GCPR feature! The results look really clean now (all except for when there are multiple entries for each gene which I suppose is unavoidable but is easy enough to resolve by hand or a short script).  

I think I figured out why I wasn't getting the Results text file for my TEA/GEA/PEA analysis. It's because I have no significant enrichment for any of those attributes! Duh! What confused me is that the files still looked like they were available and a new window does pop up when I clicked on 'download results' so I was expecting something, but nothing came up (in SimpleMine even if you query an empty gene list a Results window still pops up but its blank). Anyway, just a minor issue and my own fault for not reading through the page more carefully to see that there is no enrichment. 

Thank you for all of your help over the last week. It is much appreciated!"

**Comment by chris-grove** [comment]
My response:
"OK, great! I'm glad you like the GCPR ID feature.

About the TEA tool: OK, that makes more sense. Although you raise a good point that either the site should say that the file is unavailable due to lack of enrichment results (and have no link) or, when you click on the file link, you see a page explaining that no file is available (I think I prefer the first option).

You're welcome. It really helps us to hear this feedback so we can improve our tools. Thanks!"

**Comment by raymond91125** [comment]
Regarding the enrichment tool's handling of NO significantly enriched terms, it's revised now so that the user is told as such and not presented with a empty files.

**Comment by chris-grove** [comment]
@raymond91125 
I noticed! Thanks!
