### ISSUE TITLE
  I am the director of a specialized sc...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6469]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I am the director of a specialized science and mathematics school in Roanoke, Virginia in the US.  We provide advanced instruction to 9-12th grade students in a research-focused environment, and - as part of our school’s model – students complete independent research projects akin to undergraduate/graduate research projects.  This past year, I assisted a student in a project of manually examining, supplementing, and cross-referencing some gene families within C. elegans, C. remanei, and C. briggsae.  In a number a cases, the data suggested some additional identification information for sequences that are currently only referred to by sequence ID.<br/>First of all, I would like to thank you for your work in making this tremendous resource available- it not only assists professional researchers, but can also serve to inspire young scientists – as in our case.  I did want to inquire if it was possible for us to submit our research data to further enrich your database.  While I could obviously understand a hesitation to accept data from a non-university lab, I can certainly provide the evidence we used for our findings, such as alignment scores, phylogenetic trees, etc.<br/>Please let me know whether you think this is a possibility.  If not, do you have any recommendations?<br/>Thank you for your time,  </p>

**Reported by:** Mark***** (mlev****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299

**Comment by draciti** [comment]
We will discuss this with the micropub team and get back to the user when ready

**Comment by gw3** [comment]
Hi Mark,

First of all, thank you for undertaking this exercise with your 
students, I am sure we can use your work.

We assign gene names to the C. elegans genes based on the advice of our 
gene nomenclature specialist.
These gene names are then automatically transferred to the best mutual 
1-to-1 ortholog in curated, non-elegans, nematode species.
The procedure used to automatically transfer the gene names was reviewed 
and improved for WormBase release WS265, so there should be many 
improvements in the naming of C. briggsae and C. remanei genes appearing 
on the website very soon when this release becomes public.

We would still like to see the results of your work to find genes that 
our automatic system has missed and possibly to find genes whose curated 
structure should be corrected.

We look forward to hearing from you soon.
Gary Williams
WormBase

**Comment by gw3** [comment]
Subject: | RE: [wormbase-help] How Do I ...?: I am the director of               a specialized sc... (Mark Levy)
-- | --
Fri, 22 Jun 2018 04:35:51 +0000
Mark A. Levy <mlevy@****************>
'Gary Williams' <gw3@ebi.ac.uk>


Gary,

Thank you for your reply and your openness to collaborating with us on this.  As a brief background, the student’s original intent was to search for ortholog pseudogenes across C. elegans, C. remanei, and C. briggsae with the intent of comparing the rates of ‘decay’ in the pseudogene sequence.  He hit a few barriers, as you might predict.  He needed to dig deep in exploring the fringes of gene families to find pseudogenes (and needed to decide if these targets were actually functional genes that simply weren’t previously identified as part of the gene family, which was difficult to be precise with).  Additionally, most ‘old’ pseudogenes have suffered too many mutations to be recognizable across species, but ‘newer’ pseudogenes that would useable for his goals are often ‘too close to call’ as a pseudogene (still making mRNA and potentially being aimlessly translated). 

 

While the original idea ended up better in theory than reality, it did lead to him doing fairly deep characterizations of a number of gene families as he searched for possible pseudogene sequences.  Along that path, we identified a number of sequences that we felt should be named members of the family or were orthologs that weren’t already labeled.

 

I’ll start off by supplying the two most interesting families we explored: PCP and DSL.  At this point, I’m not going to go overboard with details (he wrote a research paper, but I’m not going to polish it up if you end up telling me you can’t do much with this data).  I have attached a spreadsheet that includes tabs for each of these two gene families (split by species), with our changes in designation highlighted in orange (new name in 2nd column) as well as a phylogenetic tree for each.  I’m happy to provide additional information, but I’d rather you have your folks look at it first so I don’t end up wasting time over or under explaining things.

 

Let me know if you have any questions about the data or notations.

 

Thanks again,

 

Mark A. Levy

**Comment by gw3** [comment]
[Gene Family Data for wormbase.xlsx](https://github.com/WormBase/website/files/2127002/Gene.Family.Data.for.wormbase.xlsx)

**Comment by gw3** [comment]
Mark,

I fully sympathise with you problems in deciding when a locus is a 
pseudogene, especially when the genome assembly is not good.
With elegans, we think we know where nearly all the reference genome 
errors are, but with C. briggsae, C remanei and the other non-elegans 
species it is sometimes impossible to distinguish between a region of 
poor assembly and a pseudogene.

My rule of thumb in briggsae (where I've been working recently) is:
  - if it is by a gap in the assembly it is probably a fragment of a 
coding gene.
  - if it has a large, active transposon insertion in an exon it is 
probably a pseudogene
  - if it has lots of paralogs and the structure has problems, it is 
probably a pseudogene
  - if it has just one frameshift (especially at a run of the same base) 
or just one premature STOP codon and no paralogs it is probably a coding 
gene with a reference genome error.
  - I err on the side of making genes coding.

I've taken a look at your data. Thanks you for sharing the way you've 
thought about the nomenclature and we should think about improving our 
system for naming the orthologs.
Some comments:

1) The nomenclature you use for pseudogenes, e.g. 'pcp-ps1', will not be 
used by us; it does not conform to our nomenclature guidelines. We 
sometimes assign gene names to pseudogenes in elegans. Our procedure for 
automatically transferring elegans gene names to non-elegans species 
requires that there be protein orthology to the genes in the non-elegans 
species, so if a gene in either elegans or the non-elegans species is 
non-coding, then there will not be a protein product, no orthology will 
be found and so no gene name will be transferred.

2) Changing 'Cbr-pcp-1.1' and 'Cbr-pcp1.2' to 'Cbr-pcp-1' and 
'Cbr-pcp-6' will not work in our nomenclature system because there is no 
C. elegans gene named 'pcp-6'. If such a gene existed and had a closer 
similarity to 'Cbr-pcp1.2' than 'pcp-1', then your suggestion would be 
reasonable. As it is, 'Cbr-pcp-1.1' and 'Cbr-pcp1.2' have an 
approximately equal amount of similarity to 'pcp-1' and so the name 
'pcp-1' is transferred over to both of them, the 'Cbr-' prefix is added 
to indicate the species and the suffix '.1' or '.2' is added to 
distinguish them as being approximately equally similar to the 
originally named elegans gene. Note that adding '.1' and '2' suffixes 
does not imply any sort of isoform relationship. We distinguish isoforms 
of gene names as: "mec-2, isoform a", and "mec-2, isoform b", etc.

3) You named CBG21794 as 'Cbr-pcp-8'. This would not work in our 
nomenclature system because there is no 'pcp-8' in C. elegans to 
transfer the name from.
CBG21794 has approximately equal similarity to F23B2.12 (pcp-2) and 
F23B2.11 (pcp-3). Your phylogenetic tree seems to indicate that there 
was a duplication event to give rise to the ancestor of 'pcp-2' and 
'pcp-3' before the speciation events.

We should certainly look into improving our automatic naming system, as 
currently CBG21794 is not given a gene name, whereas CBG21793 is 
correctly named 'Cbr-pcp-3'.
I think that CBG21794 has possibly a slightly better ortholog to 
F23B2.12 (pcp-2) than to F23B2.11 (pcp-3) and should be named 'Cbr-pcp-2'.
As it is, our system drops CBG21794 because it has approximately equally 
good orthology to the elegans genes F23B2.12 (pcp-2) and F23B2.11 
(pcp-3) - and the latter has a better homology to another briggsae gene, 
CBG21793.

4) You named CRE21520 as 'Cre-dsl-1'. Our automatic system also names it 
'Cre-dsl-1'. (I think I mentioned that we had done some work to improve 
this system for release WS265.) So we are in agreement!

5) Y41D4B.10 (dsl-3) has approximately equal orthology to the following 
C. remanei loci: CRE26785, CRE27895, CRE11491, and CRE20120. These have 
now (in release WS265) got the automatically assigned names: 
'Cre-dsl-3.1', 'Cre-dsl-3.2', 'Cre-dsl-3.3', and 'Cre-dsl-3.4'.

Many thanks for showing us this work.
We definitely need to improve the way we score orthology so that we can 
catch problems like naming the orthologs of 'pcp-2' and 'pcp-3' correctly.

Gary Williams
WormBase
