### ISSUE TITLE
How to find 7S RNA genes (of Signal Recognition Particle)?

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6475]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

Chris: Hello Amy, how can I help?</br>visitor_name (visitor_email): I'm looking for the 7s RNA gene name in C elegans. It is a part of the signal recognition particle and is transcribed by pol III</br>Chris: Hmmm, OK let me take a look at the best way to get those</br>visitor_name (visitor_email): Ok, thanks for helping. Just let me know if you find it. I have a meeting in ten minutes.</br>Chris: Hi Amy, I'm going to have to look into this a bit and get back to you. Is it OK that I email you back later when I find an asnwer?

**Reported by:** amy ***** (cook***********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/search/all/7s RNA">https://www.wormbase.org/search/all/7s RNA</a>
**Browser:** Firefox 60.0

**Comment by Paul-Davis** [comment]
Hi @chris-grove 

It seems this publication references the C. elegans genes (4 of them on chromosome 3 and a novel pseudogene on 5) but I have found the names of the genes https://www.ncbi.nlm.nih.gov/pmc/articles/PMC137091/ Will look into identifying them later.

**Comment by chris-grove** [comment]
From user:
"No problem. Just email me when you have an answer. "

My repsonse:
"My colleague, Paul Davis, is looking into it now and found this 2002 NAR paper:

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC137091/

in which the authors claim to have predicted 4 SRP RNA genes (and one possible pseudogene) as listed in Table 1 of the paper, but they use what appear to be outdated/expired GenBank accession numbers when referring to the genes, which is making it difficult to track down which genes exactly they are referring to.

We'll keep you updated as we find anything else."

**Comment by Paul-Davis** [comment]
Found the functional SRP genes

SRP-A = ZC155.8 (WBGene00195016)
SRP-B = Unknown (Possibly the pseudogene they referenced in the publication)
SRP-C = B0285.12 (WBGene00045168)
SRP-D = R144.15 (WBGene00195017)
SRP-E = F44A2.8 (WBGene00195018)

Going to work with Tim on naming this family of ncRNAs so that they don't dissapear again. Also need to look at better classification provcesses for ncRNA genes in general.

**Comment by chris-grove** [comment]
@Paul-Davis 
OK, thanks for that. How did you find them, in case it comes up?

**Comment by chris-grove** [comment]
Email to user:
"""
Just following up. Paul (CC'ed) managed to track down the identities of some of the C. elegans SRP RNA genes:

"
Found the functional SRP genes will keep looking for the pseudo copy they mention.

SRP-A = ZC155.8 (WBGene00195016)
SRP-B = Unknown (Possibly the pseudogene they referenced in the publication)
SRP-C = B0285.12 (WBGene00045168)
SRP-D = R144.15 (WBGene00195017)
SRP-E = F44A2.8 (WBGene00195018)
"

It isn't clear that any of these are particularly the 7S RNAs, but maybe you have a way to confirm if that's the case? We will try to name/annotate these genes so that they will be easier to find in the future.

I hope that helps.
"""

**Comment by Paul-Davis** [comment]
@chris-grove so in the model there is a Transcript type with a limited number of properties including ncRNA with a Text attribute which contains the SRP designations above.

**Comment by chris-grove** [comment]
@Paul-Davis 
Ah, OK, I see it. Thanks!!
