### ISSUE TITLE
in transgene nomenclature GFP is indicated in capi...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6548]
*Help Desk query collected when no chat operators were online. Follow up required.*

in transgene nomenclature GFP is indicated in capital letters, while in genotypes it is indicated as gfp italics lowercase. For consistency with gene names it would be better to use gfp lowercase italics only (otherwise it refers to a protein!). If both should be used equally please mention specifically both in the nomenclature section

**Reported by:** alex***** (alex********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/about/userguide/nomenclature#5i96fb8ch2ed4maj03k1gl7--10">https://wormbase.org/about/userguide/nomenclature#5i96fb8ch2ed4maj03k1gl7--10</a>
**Browser:** Safari 11.1.2

**Comment by Paul-Davis** [comment]
Dear Alexandra,

We have been discussing the use of GFP in the transgene nomenclature and 
as a result the following change has been made to the WormBase 
nomenclature guide.

Change /mab-9::GFP /and /mab-9p::GFP /to/mab-9::gfp /and///mab-9p::gfp.

/If this does not fully address the issue you raised please feel free to 
reply to this email so that all interested members of WormBase staff can 
comment.

Kind regards.

Paul



On 06/08/2018 13:48, no-reply@wormbase.org wrote:
> offline chat in transgene nomenclature GFP is indicated in capital 
> letters, while in genotypes it is indicated as gfp italics lowercase. 
> For consistency with gene names it would be better to use gfp 
> lowercase italics only (otherwise it refers to a protein!). If both 
> should be used equally please mention specifically both in the 
> nomenclature section
>
> Submitted From:
>   https://wormbase.org/about/userguide/nomenclature#5i96fb8ch2ed4maj03k1gl7--10 
> https://wormbase.org/about/userguide/nomenclature#5i96fb8ch2ed4maj03k1gl7--10 
> <http://www.wormbase.org/https://wormbase.org/about/userguide/nomenclature#5i96fb8ch2ed4maj03k1gl7--10> 
>
>
> This issue has been assigned ticket number: #6548. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6548>.
>
> Reported by: alexandra (alexandra.bezler@epfl.ch)
> 06 Aug 18 12:48
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
I believe Karen has been talking to the user and we have agreed a nomenclature update where lowercase gfp is now used for Transgenes.  The nomenclature guide has also been updated. I have just replied to the user so closing the ticket for now.
