### ISSUE TITLE
  Hi! I am getting an error message (fo...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6554]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi!<br/>I am getting an error message (for about a week) when I am trying to download editable svg files from the Gbrowse. <br/>Is the svg functionality not available anymore?<br/>Is there an alternative way to download an editable file of my genes of interest?<br/>Thank you!<br/>Best,<br/>Nikos</p>

**Reported by:** Niko************ (ns25***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:61.0) Gecko/20100101 Firefox/61.0

**Comment by scottcain** [comment]
Sent to the user:

Hi Nikos,

Greetings from Midtown (I’ve been in nyc the last few days); anyway, we switched to a new server last we and I didn’t configure that correctly. I should have it fixed tomorrow.

**Comment by scottcain** [comment]
Sent to the user:

Hi Nikos,

I wanted to let you know I fixed the SVG problem with GBrowse; it was a little harder than I expected to fix so it took a little longer, but it's good now.

Thanks for pointing out the problem!
Scott

----
So yes, it is fixed.  It was actually a bug in GBrowse which has been fixed in github but hasn't made it into a full release.
