### ISSUE TITLE
  Hi, I have 2 questions: 1. Can I down...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6591]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi,<br/>I have 2 questions:<br/>1. Can I download \ copy a specific sequence using the genome browser? If not, how else can I get a sequence if I know the chromosomal region?<br/>2.According to wormbase there is a gene annotated as F11G11.15. It is absent in both Ensembl and UCSC genome browser (I am using WBcel235 in all three). Why is that?<br/>Thanks,<br/>Yonatan</p>

**Reported by:** Yona******** (yona**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0

**Comment by scottcain** [comment]
@chris-grove answered this yesterday.  I'll close it for him since it seemed like a pretty good answer :-)  Of course, reopen if necessary.  Chris wrote:

Yes, there are several ways to acquire/download sequence from both the GBrowse genome browser as well as the newer JBrowse. I've made a screen recording video to demonstrate the different methods:

https://www.dropbox.com/s/h86cn9ex389anuu/Getting_sequence_from_genome_browsers_Aug_28_2018.mov?dl=0
Please let us know if you still have any questions.

As for the gene F11G11.15, looking at the history widget for this gene:

https://www.wormbase.org/species/c_elegans/gene/WBGene00271822#05--10

It seems this gene was created in September 2017, less than a year ago. So, the gene probably hasn't made its way into Ensembl or the UCSC genome browser. My colleagues can verify if that isn't the case.
