### ISSUE TITLE
  The gene B0564.1 appears twice in the...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6595]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;The gene B0564.1 appears twice in the dataset, once as exos-4.1 	WBGene00007201 and also as tin-9.2 WBGene00044083. exos-4.1 and tin-9.2 seem to be different transcripts of the same B0564.1 gene.</p>

**Reported by:** mliu*************
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

**Comment by gw3** [comment]
Yes, this is correct.
The locus B0564.1 produces a dicistronic mRNA transcript that has two 
non-overlapping open reading frames.
This transcript is processed to produce two very different protein 
products EXOS-4.1 and TIN-9.2.

This is one of about 50 loci that have two non-overlapping open-reading 
frames on a single transcript.
More information on them can be found in the WormBook chapter on operons
http://www.wormbook.org/chapters/www_operongeneclusters/operongeneclusters.html
Sections 8 and 9 deal with SL1-type operons and Dicistronic mRNA.

We assign Gene IDs to each of the open reading frames in the locus, just 
as we do to the open reading frames in an operon so that the protein 
products can be more easily distinguished and annotated.

Gary Williams
WormBase
