### ISSUE TITLE
Bug when searching for publications

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/website#6618]
If you have the title (or fragment) of a publication and you want to see it in wormbase it seems that there is a bug in the search behaviour.

I have linked a screen cast of the issue: https://app.box.com/s/36wnsz3q7imlk8is7lcsc08082wbqm2q

The Auto-complete can find the exact paper I want but the search results return 0 hits.

P

**Comment by sibyl229** [comment]
Problem typing in the search box: "FOG-2, a novel F-box containing protein, associates with the GLD-1 RNA binding protein and directs male sex determination in the C. elegans hermaphrodite germline"

The problem is probably a combination of:
- the brief citation is indexed as the title instead of the actual title
- search isn't handling query containing additional text that doesn't match what's being indexed.

**Comment by sibyl229** [comment]
Hi @Paul-Davis the problem with paper search should be fixed now. It's for testing on staging.

The problem is due to search relies on the Brief_citation tag to have the full paper title. When it doesn't, in this case, the title wasn't being indexed into search. 

The problem is fixed by replacing the title fragments in the Brief_citation text with the full title of the paper.

**Comment by Paul-Davis** [comment]
This works well and I see it's on www.wormbase.org already....closing
