### ISSUE TITLE
Hi. there used to be the gene sequence and the exo...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6622]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi. there used to be the gene sequence and the exons marked within that sequence on wormbase when I used it 5 years ago. How do I now find the exon sequences? Cheers,
Maike

**Reported by:** Maik************ (maik**************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/tools/genome/jbrowse-simple/?tracks=Curated_Genes,Classical_alleles,YACs_Fosmids_Cosmids&amp;loc=II:6994784..7010821&amp;data=data/c_elegans_PRJNA13758&amp;highlight=">https://www.wormbase.org/tools/genome/jbrowse-simple/?tracks=Curated_Genes,Classical_alleles,YACs_Fosmids_Cosmids&amp;loc=II:6994784..7010821&amp;data=data/c_elegans_PRJNA13758&amp;highlight=</a>
**Browser:** Firefox 62.0

**Comment by scottcain** [comment]
Shoot.  I think this may be another example of help desk email that didn't send with the unmasked email address.  Does anybody have a guess who Maike is?  @tharris any idea what's going on with this mail gateway?

**Comment by tharris** [comment]
Yes I know what’s happening. It will be resolved when 266 is released. I have sent you her address

**Comment by scottcain** [comment]
Send to the user:

Hi Maike,

Since it looks like you where using JBrowse when you sent this email, I'll give you directions for doing this with JBrowse.  If it doesn't address your underlying question (like if you need *all* of the exon sequences), please reply and we can go from there.

To get exon sequences from a single transcript, open the "Curated Genes (protein coding)" track and find the transcript you're interested in, and right or control click on it.  Select the "View Sequence" option and a dialog box will pop up.  In that dialog box, there will be options for highlighting, changing the case and hiding different types of features.  If you select 'exon', it will highlight the exon features and you can either cut and paste individual exons or cut and paste the whole thing into word processor and the highlights will be maintained (this works better in some browsers than others--I've had luck with Firefox).

Please let us know if you have anymore questions,
Scott
