### ISSUE TITLE
  We noticed that the sequence report o...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6638]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;We noticed that the sequence report of our nsy-1(ums8) allele is incorrect (https://www.wormbase.org/species/c_elegans/variation/WBVar02145386#02-45-3).  It should be cGa —> cAa. The location and rest of the flanking sequence seems to be correct.   For reference, please see the paper where this allele is published (PMID 26818074).<br/>Thank you,<br/>Read </p>

**Reported by:** Read*************** (Read****************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:62.0) Gecko/20100101 Firefox/62.0

**Comment by sibyl229** [comment]
Potentially related issue on q71 (reported through help desk email directly) https://www.wormbase.org/species/c_elegans/variation/WBVar00240995#02-5a-10

**Comment by Paul-Davis** [comment]
Dear Read,

Thank you for reporting this issue.

I can confirm that the original annotation is incorrect when compared to 
the publication.

Paper does report "This study revealed that the /ums8 
<http://www.wormbase.org/db/get?name=WBVar02145386%20;class=Variation>/ 
mutant contained a G→A missense mutation in the coding region of /nsy-1 
<http://www.wormbase.org/db/get?name=WBGene00003822;class=Gene>/ that 
resulted in the substitution of a strongly conserved Arg^246 to Gln^246 "

Codon CGA current mutated base Tga (Opal_STOP) paper reports cGa = cAa = Gln

I will correct this for the WS268 release of WormBase.

Paul




On 19/09/2018 16:52, no-reply@wormbase.org wrote:
> Content Correction
>
>   We noticed that the sequence report of our nsy-1(ums8) allele is 
> incorrect 
> (https://www.wormbase.org/species/c_elegans/variation/WBVar02145386#02-45-3). 
> It should be cGa —> cAa. The location and rest of the flanking 
> sequence seems to be correct. For reference, please see the paper 
> where this allele is published (PMID 26818074).
> Thank you,
> Read
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #6638. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6638>.
>
> Reported by: Read Pukkila-Worley (Read.Pukkila-Worley@umassmed.edu)
> 19 Sep 18 15:52
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:62.0) Gecko/20100101 
> Firefox/62.0
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
Thanks Paul.  When will WS268 be released?

Read

On Sep 20, 2018, at 5:57 AM, Paul Davis <paul.davis@wormbase.org<mailto:paul.davis@wormbase.org>> wrote:


Dear Read,

Thank you for reporting this issue.

I can confirm that the original annotation is incorrect when compared to the publication.

Paper does report "This study revealed that the ums8<https://urldefense.proofpoint.com/v2/url?u=http-3A__www.wormbase.org_db_get-3Fname-3DWBVar02145386-2520-3Bclass-3DVariation&d=DwMDaQ&c=WJBj9sUF1mbpVIAf3biu3CPHX4MeRjY_w4DerPlOmhQ&r=QBKUtQX7rATyf5ITnFpgfUTGJVl-MzDMIK-IAEwMf9s&m=TdqkPw6ni4nNejvJeXkgZLN-SwCf1y472qDuKAPmbMo&s=uLI-lKsEeo8NnoQRSJ9kSR4nCmF1uVlxZtYj9wtN_4M&e=> mutant contained a G→A missense mutation in the coding region of nsy-1<https://urldefense.proofpoint.com/v2/url?u=http-3A__www.wormbase.org_db_get-3Fname-3DWBGene00003822-3Bclass-3DGene&d=DwMDaQ&c=WJBj9sUF1mbpVIAf3biu3CPHX4MeRjY_w4DerPlOmhQ&r=QBKUtQX7rATyf5ITnFpgfUTGJVl-MzDMIK-IAEwMf9s&m=TdqkPw6ni4nNejvJeXkgZLN-SwCf1y472qDuKAPmbMo&s=WZRCy_7p5lVRmhpmK6HXk4jH-TMrIvoP8B7NzvpTRsM&e=> that resulted in the substitution of a strongly conserved Arg246 to Gln246 "

Codon CGA current mutated base Tga (Opal_STOP) paper reports cGa = cAa = Gln

I will correct this for the WS268 release of WormBase.

Paul




On 19/09/2018 16:52, no-reply@wormbase.org<mailto:no-reply@wormbase.org> wrote:
Content Correction

  We noticed that the sequence report of our nsy-1(ums8) allele is incorrect (https://www.wormbase.org/species/c_elegans/variation/WBVar02145386#02-45-3<https://urldefense.proofpoint.com/v2/url?u=https-3A__www.wormbase.org_species_c-5Felegans_variation_WBVar02145386-2302-2D45-2D3&d=DwMDaQ&c=WJBj9sUF1mbpVIAf3biu3CPHX4MeRjY_w4DerPlOmhQ&r=QBKUtQX7rATyf5ITnFpgfUTGJVl-MzDMIK-IAEwMf9s&m=TdqkPw6ni4nNejvJeXkgZLN-SwCf1y472qDuKAPmbMo&s=F8o6XX_lndAbPuIHeB2LdNLK4fr2WuOfVGHVP2RDjos&e=>). It should be cGa —> cAa. The location and rest of the flanking sequence seems to be correct. For reference, please see the paper where this allele is published (PMID 26818074).
Thank you,
Read

Submitted From:
  support /tools/support<https://urldefense.proofpoint.com/v2/url?u=http-3A__www.wormbase.org__tools_support&d=DwMDaQ&c=WJBj9sUF1mbpVIAf3biu3CPHX4MeRjY_w4DerPlOmhQ&r=QBKUtQX7rATyf5ITnFpgfUTGJVl-MzDMIK-IAEwMf9s&m=TdqkPw6ni4nNejvJeXkgZLN-SwCf1y472qDuKAPmbMo&s=ii3WQV2BR-0FEx5L2K9OPfq2Ho25xJW66qJ5QZPrf_o&e=>

This issue has been assigned ticket number: #6638. Follow progress on our issue tracker<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_WormBase_website_issues_6638&d=DwMDaQ&c=WJBj9sUF1mbpVIAf3biu3CPHX4MeRjY_w4DerPlOmhQ&r=QBKUtQX7rATyf5ITnFpgfUTGJVl-MzDMIK-IAEwMf9s&m=TdqkPw6ni4nNejvJeXkgZLN-SwCf1y472qDuKAPmbMo&s=60zU4s1jkL8TLWOAOC7ER_JDLpwutS0TZe9UAPesmrk&e=>.


Reported by: Read Pukkila-Worley (Read.Pukkila-Worley@umassmed.edu<mailto:Read.Pukkila-Worley@umassmed.edu>)
19 Sep 18 15:52

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:62.0) Gecko/20100101 Firefox/62.0

This question was reported via the web interface at wormbase.org<https://urldefense.proofpoint.com/v2/url?u=http-3A__wormbase.org&d=DwQDaQ&c=WJBj9sUF1mbpVIAf3biu3CPHX4MeRjY_w4DerPlOmhQ&r=QBKUtQX7rATyf5ITnFpgfUTGJVl-MzDMIK-IAEwMf9s&m=TdqkPw6ni4nNejvJeXkgZLN-SwCf1y472qDuKAPmbMo&s=gXIP1joQxA9X3ASZofs_POlGsQTmzEi89mFaZYydmmk&e=>. You can also email us<mailto:help@wormbase.org> directly.

--
--
You received this message because you are subscribed to the "WormBase: help" group.
To post to this group, send email to help@wormbase.org<mailto:help@wormbase.org>
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en<https://urldefense.proofpoint.com/v2/url?u=http-3A__groups.google.com_a_wormbase.org_group_help-3Fhl-3Den&d=DwMDaQ&c=WJBj9sUF1mbpVIAf3biu3CPHX4MeRjY_w4DerPlOmhQ&r=QBKUtQX7rATyf5ITnFpgfUTGJVl-MzDMIK-IAEwMf9s&m=TdqkPw6ni4nNejvJeXkgZLN-SwCf1y472qDuKAPmbMo&s=AhzeA-ZD_1eYTjmek4MeJIZ9bsScBBRXzeARInQpSyY&e=>



--
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

-----------------------------
Read Pukkila-Worley, MD, FIDSA | Assistant Professor | Program in Innate Immunity | Division of Infectious Diseases and Immunology | UMass Medical School
+1.508.856.3596 (o) | +1.508.856.5463 (f) | umassmed.edu/pukkila-worleylab<http://umassmed.edu/pukkila-worleylab>

**Comment by Paul-Davis** [comment]
Hi,

We are just entering the WS268 production cycle so this should be on the 
live site towards the end of December.

Paul


On 20/09/2018 14:33, Pukkila-Worley, Read wrote:
>
> Thanks Paul.  When will WS268 be released?
>
> Read
>
>> On Sep 20, 2018, at 5:57 AM, Paul Davis <paul.davis@wormbase.org 
>> <mailto:paul.davis@wormbase.org>> wrote:
>>
>>
>> Dear Read,
>>
>> Thank you for reporting this issue.
>>
>> I can confirm that the original annotation is incorrect when compared 
>> to the publication.
>>
>> Paper does report "This study revealed that the/ums8 
>> <https://urldefense.proofpoint.com/v2/url?u=http-3A__www.wormbase.org_db_get-3Fname-3DWBVar02145386-2520-3Bclass-3DVariation&d=DwMDaQ&c=WJBj9sUF1mbpVIAf3biu3CPHX4MeRjY_w4DerPlOmhQ&r=QBKUtQX7rATyf5ITnFpgfUTGJVl-MzDMIK-IAEwMf9s&m=TdqkPw6ni4nNejvJeXkgZLN-SwCf1y472qDuKAPmbMo&s=uLI-lKsEeo8NnoQRSJ9kSR4nCmF1uVlxZtYj9wtN_4M&e=>/mutant 
>> contained a G→A missense mutation in the coding region of/nsy-1 
>> <https://urldefense.proofpoint.com/v2/url?u=http-3A__www.wormbase.org_db_get-3Fname-3DWBGene00003822-3Bclass-3DGene&d=DwMDaQ&c=WJBj9sUF1mbpVIAf3biu3CPHX4MeRjY_w4DerPlOmhQ&r=QBKUtQX7rATyf5ITnFpgfUTGJVl-MzDMIK-IAEwMf9s&m=TdqkPw6ni4nNejvJeXkgZLN-SwCf1y472qDuKAPmbMo&s=WZRCy_7p5lVRmhpmK6HXk4jH-TMrIvoP8B7NzvpTRsM&e=>/that 
>> resulted in the substitution of a strongly conserved Arg^246 to Gln^246 "
>>
>> Codon CGA current mutated base Tga (Opal_STOP) paper reports cGa = 
>> cAa = Gln
>>
>> I will correct this for the WS268 release of WormBase.
>>
>> Paul
>>
>>
>>
>>
>> On 19/09/2018 16:52,no-reply@wormbase.orgwrote:
>>> Content Correction
>>>
>>>   We noticed that the sequence report of our nsy-1(ums8) allele is 
>>> incorrect 
>>> (https://www.wormbase.org/species/c_elegans/variation/WBVar02145386#02-45-3). 
>>> It should be cGa —> cAa. The location and rest of the flanking 
>>> sequence seems to be correct. For reference, please see the paper 
>>> where this allele is published (PMID 26818074).
>>> Thank you,
>>> Read
>>>
>>> Submitted From:
>>>   support/tools/support 
>>> <https://urldefense.proofpoint.com/v2/url?u=http-3A__www.wormbase.org__tools_support&d=DwMDaQ&c=WJBj9sUF1mbpVIAf3biu3CPHX4MeRjY_w4DerPlOmhQ&r=QBKUtQX7rATyf5ITnFpgfUTGJVl-MzDMIK-IAEwMf9s&m=TdqkPw6ni4nNejvJeXkgZLN-SwCf1y472qDuKAPmbMo&s=ii3WQV2BR-0FEx5L2K9OPfq2Ho25xJW66qJ5QZPrf_o&e=>
>>>
>>> This issue has been assigned ticket number: #6638. Follow progress 
>>> on ourissue tracker 
>>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_WormBase_website_issues_6638&d=DwMDaQ&c=WJBj9sUF1mbpVIAf3biu3CPHX4MeRjY_w4DerPlOmhQ&r=QBKUtQX7rATyf5ITnFpgfUTGJVl-MzDMIK-IAEwMf9s&m=TdqkPw6ni4nNejvJeXkgZLN-SwCf1y472qDuKAPmbMo&s=60zU4s1jkL8TLWOAOC7ER_JDLpwutS0TZe9UAPesmrk&e=>.
>>>
>>>
>>> Reported by: Read Pukkila-Worley (Read.Pukkila-Worley@umassmed.edu)
>>> 19 Sep 18 15:52
>>>
>>> Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:62.0) 
>>> Gecko/20100101 Firefox/62.0
>>>
>>> This question was reported via the web interface atwormbase.org 
>>> <https://urldefense.proofpoint.com/v2/url?u=http-3A__wormbase.org&d=DwQDaQ&c=WJBj9sUF1mbpVIAf3biu3CPHX4MeRjY_w4DerPlOmhQ&r=QBKUtQX7rATyf5ITnFpgfUTGJVl-MzDMIK-IAEwMf9s&m=TdqkPw6ni4nNejvJeXkgZLN-SwCf1y472qDuKAPmbMo&s=gXIP1joQxA9X3ASZofs_POlGsQTmzEi89mFaZYydmmk&e=>. 
>>> You can alsoemail us <mailto:help@wormbase.org>directly.
>>>
>>> --
>>> --
>>> You received this message because you are subscribed to the 
>>> "WormBase: help" group.
>>> To post to this group, send email tohelp@wormbase.org
>>> To unsubscribe from this group, send email to
>>> help+unsubscribe@wormbase.org
>>> For more options, visit this group at
>>> http://groups.google.com/a/wormbase.org/group/help?hl=en 
>>> <https://urldefense.proofpoint.com/v2/url?u=http-3A__groups.google.com_a_wormbase.org_group_help-3Fhl-3Den&d=DwMDaQ&c=WJBj9sUF1mbpVIAf3biu3CPHX4MeRjY_w4DerPlOmhQ&r=QBKUtQX7rATyf5ITnFpgfUTGJVl-MzDMIK-IAEwMf9s&m=TdqkPw6ni4nNejvJeXkgZLN-SwCf1y472qDuKAPmbMo&s=AhzeA-ZD_1eYTjmek4MeJIZ9bsScBBRXzeARInQpSyY&e=>
>>>
>>
>> -- 
>> ===========================================
>> WormBase
>> European Bioinformatics Institute (EMBL-EBI)
>> European Molecular Biology Laboratory
>> Wellcome Trust Genome Campus
>> Hinxton
>> Cambridge CB10 1SD
>> United Kingdom
>> ===========================================
>
> -----------------------------
> Read Pukkila-Worley, MD, FIDSA | Assistant Professor | Program 
> in Innate Immunity | Division of Infectious Diseases and Immunology 
> | UMass Medical School
> +1.508.856.3596 (o) | +1.508.856.5463 (f) | 
> umassmed.edu/pukkila-worleylab <http://umassmed.edu/pukkila-worleylab>
>
>
>
>
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
