### ISSUE TITLE
Hi, I am looking at the DNA sequences of the wrt g...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6639]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi, I am looking at the DNA sequences of the wrt genes in C. elegans but the reference DNA sequence that I am obtaining from JBrowse isn't matching the sequence I am getting from the wrt-x 'home' page, is this because I am doing something wrong?
 Many thanks,
visitor_name

**Reported by:** Elli* (esba*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/species/c_elegans/transcript/F38E11.7a.1#063--10">https://www.wormbase.org/species/c_elegans/transcript/F38E11.7a.1#063--10</a>
**Browser:** MSEdge 17.17134

**Comment by scottcain** [comment]
Sent to the user:


Can you send me some more information to see if I can reproduce what you're doing?  The gene name should probably do the job. What I think you're doing is getting comparing the sequence from the sequence widget on a gene's WormBase page to what you get when you "save track data" in JBrowse. 

Quick question: when save track data in JBrowse do you zoom in to just the gene before you save?

**Comment by scottcain** [comment]
Sent to the user:

Hi Ellie,

My brain was too into computer space this morning--I saw "wrt-x" and thought that meant some strange mouse-keystroke thing that I was unfamiliar with :-)

Anyway, I grabbed the sequence from JBrowse by zooming to the exact coordinates of wrt-3 (IV:9475863..9477446) in the JBrowse search bar, clicked go, and then did "save track data" for the reference sequence.  I think that should give me the reverse complement of the genomic sequence of wrt-3 (since it's a negative strand gene).  Comparing the first and last several base pairs in both the transcript page for F38E11.7a.1 and my downloaded sequence makes me think that's right, and to convince myself it's right, I BLASTed the jbrowse sequence against the elegans genome and it hit wrt-3.  So, two possible suggestions:

1. You didn't take into account that the jbrowse sequence would be reverse complemented, or
2. You weren't using the exact coordinates of the gene and got some flanking sequence along with the wrt-3 sequence.

Going forward, if you want to grab exact sequence for transcripts/genes, I'd suggest using the "Curated Genes (protein coding)" track, and right/control clicking on a transcript, and then selecting "View Sequence" from the menu.  After giving you a warning you can ignore, it gives you a nice dialog where you can get flanking sequence, hide, highlight or change case of subfeatures like introns and exons and will handle the reverse complementing for you.  This feature isn't available for the main "Curated Genes" track because this widget doesn't know how to pick which transcript you'd want to do this for (though I am working on improving this).

Thanks, and please let me know if you have any more questions,
Scott
