### ISSUE TITLE
  Hi, I have two Postdoctoral positions...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6664]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi,<br/>I have two Postdoctoral positions funded for C. elegans research. Is there any way to send a E-mail with the job add to all C. elegans researchers?<br/>thanks,<br/>Anton</p><p>What were you doing? <br />&nbsp;&nbsp;group leader of C. elegans lab
https://www.lifesci.dundee.ac.uk/people/anton-gartner
</p>

**Reported by:** agar**** (a.ga******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

**Comment by raymond91125** [comment]
Hi Anton,

That's great. You can post them on Worm Community Forum <http://forums.wormbase.org/><http://forums.wormbase.org/>.

Cheers,

Raymond


On 08/10/18 10:44, no-reply@wormbase.org<mailto:no-reply@wormbase.org> wrote:
Feature Request

  Hi,
I have two Postdoctoral positions funded for C. elegans research. Is there any way to send a E-mail with the job add to all C. elegans researchers?
thanks,
Anton

What were you doing?
  group leader of C. elegans lab https://www.lifesci.dundee.ac.uk/people/anton-gartner

Submitted From:
  support /tools/support<http://www.wormbase.org//tools/support>

This issue has been assigned ticket number: #6664. Follow progress on our issue tracker<https://github.com/WormBase/website/issues/6664>.

Reported by: agartner (a.gartner@dundee.ac.uk<mailto:a.gartner@dundee.ac.uk>)
08 Oct 18 17:44

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

This question was reported via the web interface at wormbase.org. You can also email us<mailto:help@wormbase.org> directly.

--
--
You received this message because you are subscribed to the "WormBase: help" group.
To post to this group, send email to help@wormbase.org<mailto:help@wormbase.org>
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en

---
You received this message because you are subscribed to the Google Groups "WormBase: help" group.
To unsubscribe from this group and stop receiving emails from it, send an email to help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>.


--
__
Raymond Lee
raymond@caltech.edu<mailto:raymond@caltech.edu>
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
