### ISSUE TITLE
I am looking at the phenotypes of C08B11.9. Is ind...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6686]
*Help Desk query collected when no chat operators were online. Follow up required.*

I am looking at the phenotypes of C08B11.9. Is indicated "ectopic expression transgene" and the supporting evidence is Cui, Kim &amp; Han, 2006, but I do not find this data in the paper.
Many thanks for your help

**Reported by:** Paul* (paul****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/species/c_elegans/gene/WBGene00007436#02-9gbc-3">https://www.wormbase.org/species/c_elegans/gene/WBGene00007436#02-9gbc-3</a>
**Browser:** Firefox 52.0

**Comment by chris-grove** [comment]
After discussing with @khowe , I sent this email to user:

"The scenario you point out, where a gene is said to be knocked down in a paper but the paper doesn't mention that gene, can often happen due to our RNAi mapping pipeline. Every database build, we take the sequences used to knockdown the gene of interest in an RNAi experiment and we map it to the transcriptome to see what genes that sequence likely targets. This results in predictions of what genes are likely knocked down by a particular RNAi reagent and sometimes the predictions include genes not explicitly mentioned in the paper (off target effects).

You can see the predicted targets on the RNAi page (click on the RNAi experiment number on the gene page Phenotypes widget to be directed to the respective RNAi page). In this particular case, the gene targeted was arp-6 (which is mentioned in the paper).

In this case you point out, however, it seems that you have found a bug, which we will work on fixing as soon as possible. So, thank you for pointing this out, as it means that we need to fix something in our pipeline. The gene C08B11.9 should not be listed as a target.

Thanks, and let us know if you have any other questions."

@khowe  will take a look at and fix once he's back from vacation.

**Comment by Paul-Davis** [comment]
Hi @chris-grove @khowe this "bug" is due to the trinity Transcript being used to generate the Coding_transcript which does overlap with the RNAi product by 11bp. I guess one could argue that an RNAi product targeting an operon might knock down all gene components within the operon? But the issue here is the Trinity transcript and not a pipeline code issue.

Paul

**Comment by chris-grove** [comment]
@Paul-Davis 
OK, thanks. @khowe had implemented a minimum cutoff for the number of required overlapping nucleotides as 50bp for the RNAi mapping pipeline, so 11bp shouldn't be enough to qualify the gene as a "primary target", so we think it is in fact a bug. @khowe  can correct me if I'm wrong

**Comment by khowe** [comment]
This was a bug in Modules/Map_helper. Now fixed. The specific problem reported will be fixed in WS269 (unfortunately didn't make it in it time for WS268)
