### ISSUE TITLE
tm2121 should be listed as a deletion that removes...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6701]
*Help Desk query collected when no chat operators were online. Follow up required.*

tm2121 should be listed as a deletion that removes rab-18 on the rab-18 gene page.  A different tm allele is listed that only removes some of the 5'UTR of rab-18 and the upstream gene.
Thanks

**Reported by:** Chri*************** (chri*************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/species/c_elegans/variation/WBVar00251060#02-45-3">https://www.wormbase.org/species/c_elegans/variation/WBVar00251060#02-45-3</a>
**Browser:** Safari 10.1.2

**Comment by chris-grove** [comment]
Thanks for the feedback. The tm2121 allele is listed as an allele on the rab-18 gene page in the "Genetics" widget, albeit under the "Other alleles" section that is not opened by default when the widget is loaded (you can find the allele by entering "tm" into the table's "Search" box to enable a filter on "tm" alleles). This is because tm2121 does not currently have phenotypes annotated to it in WormBase. At the request of several users, we made this distinction ("Alleles with phenotype" vs. "Other alleles") to help filter out the often many million mutation project alleles (and other whole genome sequencing alleles/SNPs) from those that have functional information. We had discussed several options for filtering alleles to those that were most informative, including possibly filtering out "high-throughput" alleles from the default display, but these would include the knockout consortium alleles such as the Mitani "tm" alleles and the "ok" consortium alleles. Thus, we decided on the presence of one or more phenotype annotations as a filter.


We would be very interested in your input on this matter.
