### ISSUE TITLE
  I believe there's an information erro...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6727]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I believe there's an information error for Cel-cutl-19.  It seems that a typo in a paper led a data scraper to incorrectly link results for syx-16/ZC155.7 to cutl-19/ZC155.5.<br/>Specifically, the cutl-19 page links it to Luo et al.'s (2011 Mol Biol Cell) study of Golgi SNARE proteins (in both the Overview and in the Interactions section).  Luo et al, who studied various syx genes.  They make reference to studying "syx-16/ZC155.5".  ZC155.5 is the sequence name for cutl-19.  The correct sequence name for syx-16 is ZC155.7.  </p>

**Reported by:** Came*********** (came*********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1.2 Safari/605.1.15

**Comment by raymond91125** [comment]
Hi Cameron,

Thanks much for your report. While we make necessary corrections to our database, the soonest the corrections can appear on our web site is in a couple of months. On the other hand, to the benefits of everyone interested in these two genes, your important information could appear on the gene pages immediately as a comment (see left side panel there).

Note that you'll need to log in to add comments. If you prefer, we could enter comments on your behalf (using your email text, that is).

Cheers,

Raymond


On 09/11/2018 8:37 AM, no-reply@wormbase.org<mailto:no-reply@wormbase.org> wrote:
Content Correction

  I believe there's an information error for Cel-cutl-19. It seems that a typo in a paper led a data scraper to incorrectly link results for syx-16/ZC155.7 to cutl-19/ZC155.5.
Specifically, the cutl-19 page links it to Luo et al.'s (2011 Mol Biol Cell) study of Golgi SNARE proteins (in both the Overview and in the Interactions section). Luo et al, who studied various syx genes. They make reference to studying "syx-16/ZC155.5". ZC155.5 is the sequence name for cutl-19. The correct sequence name for syx-16 is ZC155.7.

Submitted From:
  support /tools/support<http://www.wormbase.org//tools/support>

This issue has been assigned ticket number: #6727. Follow progress on our issue tracker<https://github.com/WormBase/website/issues/6727>.

Reported by: Cameron Weadick (cameron.weadick@gmail.com<mailto:cameron.weadick@gmail.com>)
09 Nov 18 16:37

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1.2 Safari/605.1.15

This question was reported via the web interface at wormbase.org. You can also email us<mailto:help@wormbase.org> directly.

--
--
You received this message because you are subscribed to the "WormBase: help" group.
To post to this group, send email to help@wormbase.org<mailto:help@wormbase.org>
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en

---
You received this message because you are subscribed to the Google Groups "WormBase: help" group.
To unsubscribe from this group and stop receiving emails from it, send an email to help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>.


--
__
Raymond Lee
raymond@caltech.edu<mailto:raymond@caltech.edu>
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by chris-grove** [comment]
Good catch. Thanks for reporting this. We had imported two interactions from this paper from our collaborator database BioGRID, who also seems to have an incorrect association between syx-16 and cutl-19 due to the misreporting of the sequence name of syx-16 by the authors of Luo et al. We will make the appropriate corrections in our database and will inform BioGRID of the incorrect connection and identifiers.

**Comment by chris-grove** [comment]
I've informed BioGRID of the error
