### ISSUE TITLE
Is there a way to find IRES elements in WormBase?

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6739]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello, Is there a way for Wormbase to identify IRES elements?<br/>Thanks, Dan</p>

**Reported by:** Dani******** (dsc3**********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36

**Comment by raymond91125** [comment]
Hi Daniel,

I don't believe we have a secondary structure prediction tool or annotations.

Cheers,

Raymond

On 15/11/2018 12:37 PM, no-reply@wormbase.org<mailto:no-reply@wormbase.org> wrote:
Question:

  Hello, Is there a way for Wormbase to identify IRES elements?
Thanks, Dan

Submitted From:
  support /tools/support<http://www.wormbase.org//tools/support>

This issue has been assigned ticket number: #6739. Follow progress on our issue tracker<https://github.com/WormBase/website/issues/6739>.

Reported by: Daniel Costa (dsc38@duke.edu<mailto:dsc38@duke.edu>)
15 Nov 18 20:37

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36

This question was reported via the web interface at wormbase.org. You can also email us<mailto:help@wormbase.org> directly.

--
--
You received this message because you are subscribed to the "WormBase: help" group.
To post to this group, send email to help@wormbase.org<mailto:help@wormbase.org>
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en

---
You received this message because you are subscribed to the Google Groups "WormBase: help" group.
To unsubscribe from this group and stop receiving emails from it, send an email to help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>.


--
__
Raymond Lee
raymond@caltech.edu<mailto:raymond@caltech.edu>
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
