### ISSUE TITLE
Hi, I would like to know why prg-2 is categorized ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6751]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi, I would like to know why prg-2 is categorized as a pseudogene. Cox et al 1998 showed the protein alignment of prg-2 with prg-1 and piwi in flies.

**Reported by:** Yun ***** (yzha******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/species/c_elegans/gene/WBGene00004179#01-9g743ac-3">https://www.wormbase.org/species/c_elegans/gene/WBGene00004179#01-9g743ac-3</a>
**Browser:** Chrome 70.0.3538.77

**Comment by chris-grove** [comment]
@Paul-Davis 's email to user:
"""
Thanks for contacting WormBase.

prg-2 was assessed by one of our curators and deemed to be non-functional in 2017. looking at the RNASeq data available for the gene and also comparing it to prg-1 via protein homology two observations were made. Exon 1 has an in-frame stop codon and while there is a downstream ATG, all available transcriptional evidence points to the transcripts starting in the same position as prg-1. The second observation is that intron 2 has been disrupted/degraded so that it is retained in ~98% of transcripts from the locus (I think the Pseudogene structure needs updating to include the intron).

You can generate a predicted protein from the region and while this can give a good alignment with the ancestral/paralog prg-1 this doesn't indicate function. If you have additional evidence that it is functional, we are more than happy to look at the gene annotation again.

I hope this helps.
"""

**Comment by Paul-Davis** [comment]
Hi Yun,

Thank you for the additional information, if you have clear experimental evidence for function then it seems we need to look at the locus again......it might be that the reference sequence contains and error or that we missed something, I will create a ticket to get this reviewed.

Paul

I have created a ticket in our internal tracker for this issue so leaving it open until we have a chance to evaluate it.

**Comment by gw3** [comment]
There is a premature STOP codon in the first exon and a frameshift in the second exon.
Unless further evidence demonstrates otherwise, this is a pseudogene.

**Comment by Paul-Davis** [comment]
Additional correspondence from the user:

```
Dear Paul,

Thanks much for the information.

Is it possible that the region before the downstream ATG is a part of the 5’UTR?

What evidence is needed to indicate the function of the predicted PRG-2 protein? We tested the prg-2 deletion mutant in a behavioral assay and obtained a clear phenotype. The mutant has been crossed with N2 for more than 10 times – what would you suggest to show the function of PRG-2?

Best, Yun
```

And:
```
Hi Paul,

Thanks much for your help.

The mutant phenotype is convincing to us. So please let me know what you will find out by looking into the locus. This information will be helpful for us to plan further experiments.

Best regards,

Yun
```
