### ISSUE TITLE
Where can I find the significance of the peak  tha...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6761]
*Help Desk query collected when no chat operators were online. Follow up required.*

Where can I find the significance of the peak  that I find in the ChIP seq data track which I found Gbrowser

**Reported by:** Mali** (mail******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/species/c_elegans/cds/C54F6.14#06--10">https://www.wormbase.org/species/c_elegans/cds/C54F6.14#06--10</a>
**Browser:** Chrome 70.0.3538.77

**Comment by chris-grove** [comment]
If you use our newer genome browser JBrowse, you can find statistics in the track information and then use that to configure the view to only show statistically significant peaks. We are in the process of making this a default view, but we need to work out a few details first.


So, if you go to JBrowse with a ChIP-Seq track open, like this:


https://www.wormbase.org/tools/genome/jbrowse-simple/full.html?tracks=ALR-1%20Combined%20(GFP%20ChIP)%2CCurated_Genes&loc=II%3A4180401..4233500&addFeatures=%5B%7B%22seq_id%22%3A%22I%22%2C%22start%22%3A6563906%2C%22end%22%3A6565183%2C%22name%22%3A%22Hits%22%2C%22type%22%3A%22match%22%2C%22subfeatures%22%3A%5B%7B%22seq_id%22%3A%22I%22%2C%22start%22%3A6563906%2C%22end%22%3A6565183%2C%22type%22%3A%22match_part%22%7D%5D%7D%5D&data=data%2Fc_elegans_PRJNA13758&addTracks=%5B%7B%22label%22%3A%22Hits%22%2C%22type%22%3A%22JBrowse%2FView%2FTrack%2FCanvasFeatures%22%2C%22store%22%3A%22url%22%2C%22subParts%22%3A%22match_part%22%2C%22glyph%22%3A%22JBrowse%2FView%2FFeatureGlyph%2FSegments%22%7D%5D&highlight=


you can see that we have the "Curated Genes" track open as well as the "ALR-1 Combined (GFP ChIP)" track which shows some blue peaks on a default scale of 0 to 100. If you click on the "ALR-1..." track label drop down menu, you can click on the "About this track" option to see statistical information about the track, including score mean and score standard deviation. For this track, the mean is ~8 and the standard deviation is ~14.5. Since two standard deviations (z-score of 2) is an approximate threshold for a generic p-value of ~0.05 we can set the minimum score to display to be mean + 2*stddev, or in this case 37, and a maximum score of about mean + 4*stddev, or 66. To set this, click on the track label drop down menu again, and this time click on "Edit config". In the config file that opens, find the lines that say:


  "min_score": 0,


and


  "max_score": 100,

and change each of these, respectively, to:


  "min_score": 37,

and

  "max_score": 66,


and click on "Apply". This should now only show you peaks that are 2 standard deviations or more above the mean/average track value.


You can apply a similar approach to your DNA-binding-protein/track of interest.


We hope to make such a view (or something similar) a default view for all applicable tracks soon.


Please let us know if you have additional questions or comments.
