### ISSUE TITLE
  I am trying to use the Gbrowse to dow...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6769]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I am trying to use the Gbrowse to download DNA sequence in a FASTA format. But when I try to show "decorated FASTA File", it does not throw out DNA sequence, it simply refreshes the page and displays the Gbrowse again. I have been using wormbase for over 9 years and this is the first time it happens. Do you have any ideas what is the problem? By the way, I am not familiar with the Jbrowse (very hard to use). If Gbrosw is being deprecated, how does someone download FASTA files of the displayed region in Jbrowse? Thanks,</p><p>What were you doing? <br />&nbsp;&nbsp;Trying to download FASTA file of a displayed region in Gbrowse</p>

**Reported by:** Chao******** (cgzh**********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

**Comment by scottcain** [comment]
Sent to the user:

I just tried both the download decorated FASTA from dropdown menu that has things like annotate restriction sites and annotate sequence motifs as well as the "dump selection as FASTA" from the region highlight menu and both opened new tabs that contained the sequence.  Could your browser be blocking requests to open new tabs?  It might be helpful to try another browser.

As for GBrowse being deprecated, there is not a plan to get rid of it any time soon because it doesn't require that much extra effort to build it along with JBrowse.  Depending on what you want your sequence for, you might find the sequence tools in JBrowse more useful.  For example, if you want the sequence around a particular gene or transcript, you can turn on the "type" specific gene track (like "Curated Genes (protein coding)" and right or control click on a transcript.  When you get the popup menu, select "View Sequence".  The resulting window will let you do a variety of useful operations like highlighting, upper/lower casing, and hiding features, as well as letting you display up to a few kb of up or downstream sequence.

**Comment by scottcain** [comment]
reply from user:

Thank you so much for your help. It seems to work now. There may be some problems with my browser before.
