### ISSUE TITLE
How do you interpret the "Chromatin Silencing ChiP...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6787]
*Help Desk query collected when no chat operators were online. Follow up required.*

How do you interpret the "Chromatin Silencing ChiP-chip arrays" track?  What are blue (above line) and red (below line) peaks? Thanks.

**Reported by:** Tom ***** (tom.******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/tools/blast_blat/run">https://wormbase.org/tools/blast_blat/run</a>
**Browser:** Firefox 64.0

**Comment by chris-grove** [comment]
@scottcain  Can you answer this question?

**Comment by scottcain** [comment]
Hmm, can I?  I would probably say "The values in the tracks range from approximately -1 to 4, but as far as I know, the below zero values have no additional informational value.  They are marked in red only because the default behavior of the browser is to visually differentiate negative values since they would otherwise be difficult to distinguish.  In this instance, this functionality should be turned off."  Do you think that answers the question in a helpful way?

**Comment by scottcain** [comment]
I suppose I would also like to add "if you need information about the experiments themselves, see the modENCODE publication: blah blah blah" but I don't really know what to direct them to.

**Comment by scottcain** [comment]
Replied to user (but forgot to close this for a while).

**Comment by chris-grove** [comment]
@scottcain 's response to user (via email):
"The values in the tracks range from approximately -1 to 4, but as far as I know, the below zero values have no additional informational value. They are marked in red only because the default behavior of the browser is to visually differentiate negative values since they would otherwise be difficult to distinguish. In this instance, this functionality should be turned off."
