### ISSUE TITLE
  We would like to ask you if the pheno...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6809]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;We would like to ask you if the phenotype curation of the paper " COX16 is required for assembly of cytochrome c oxidase in human cells and is involved in copper delivery to COX2 " was done by you. Writing the pubmed ID, a message told me that this paper has already been curated, but I can't find the data if I click on cox-16 phenotypes </p>

**Reported by:** Cris*********** (c.ce***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

**Comment by chris-grove** [comment]
This paper has been curated for 2 RNAi phenotypes, one for cox-5B and the other for cox-16, but the curation has not made it to the live website yet. You can see the annotation to cox-16 on our staging site here:


https://staging.wormbase.org/species/c_elegans/rnai/WBRNAi00112314#041--10


This will go live on our web site in the WS268 release due to go live within the next week or so. Please note that our staging site is not stable and not intended for regular use.


Please let us know if you have further questions.
