### ISSUE TITLE
  I was looking at the modENCODE ChIP-S...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6841]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I was looking at the modENCODE ChIP-Seq data on GBrowse, and I noticed that some regions with high peaks were highlighted with a yellow box.  I assume that yellow box means the peak indicates significance over background, but I was unable to find a legend.<br/>What does the yellow box on ChIP tracks on GBrowse specifically indicate?</p>

**Reported by:** Kath********* (kl27***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

**Comment by chris-grove** [comment]
My email to user:
"""
I can't say for sure what the yellow box in GBrowse means in terms of significance, but our genome browser expert Scott Cain (CC'ed) may know the answer.

I would actually recommend using our newest genome browser JBrowse to view these tracks, as those tracks have some more useful information attached which can be used to get a better view of what is a significant peak or not. For example, looking at the track "CEH-14 Combined (GFP ChIP) recalled peaks":

https://wormbase.org/tools/genome/jbrowse-simple/?data=data%2Fc_elegans_PRJNA13758&loc=III%3A8863201..8883240&tracks=Curated_Genes%2CCEH-14%20Combined%20(GFP%20ChIP)%20recalled%20peaks&highlight=

if you click on the track label drop down menu, you will see "? About this track", which if you click will display a brief description and track statistics, including the score mean and standard deviation (SD). We are in the process of automatically setting the minimum and maximum thresholds for ChIP-Seq tracks, but in the meantime you can set these manually. Since this track has a mean of ~9 and a standard deviation of ~7, I would recommend viewing the track with a minimum threshold set at mean + 2SD (23) and the maximum threshold set at mean + 5SD (44). To set this, click on the track label's drop down menu again, click on "Edit config" and where it says

"min_score": -4

change it to

"min_score": 23

and where it says

"max_score": 4

change it to

"max_score": 44

and click on the "Apply" button. This should only display peaks that extend beyond 2 SDs above the mean (z score of 2, for a one-tailed hypothesis test giving a p-value of about .02). You can decide your minimum viewing threshold based on what significance level you're looking for.

Apologies that this isn't yet automatic. We hope to implement that soon.

I hope that helps.
"""
