### ISSUE TITLE
Tissue specifically expressed is a misnomer

### ISSUE THREAD

**Issue by raymond91125** [WormBase/website#6847]
@chris-grove raised this issue. In the ontology browser of anatomy pages, there may be a table for specifically expressed genes, based on Expr_pattern and Expr_cluster. However, we consider Expr_cluster of the type Enriched, but not Expressed because the expressed type tends to carry thousands of genes that may not have high levels of expression. Thus, it is inaccurate to say that the list of genes are specifically expressed.

**Comment by raymond91125** [comment]
Perhaps a really simple answer is to change the wording from (in the case of https://wormbase.org/species/all/anatomy_term/WBbt:0005759#14--10)
"There are 395 genes that may be specifically expressed." to
"There are 395 genes that may be specifically enriched."

**Comment by chris-grove** [comment]
@raymond91125 
The problem I have with your last solution suggestion is that if the anatomy association comes from an Expr_pattern object, there really has not been any assessment of enrichment, so as long as we're combining the two types of annotations (Expr_pattern and Expr_cluster) that phrase won't be accurate either. I would argue for keeping the phrase "may be specifically expressed" and including ALL Expr_pattern and Expr_cluster evidence (expressed AND enriched), or change to "may be enriched" or "is enriched" or something and only including the Expr_cluster enriched calls. I'd like to hear others' opinions.

**Comment by raymond91125** [comment]
We propose to change the wording from "There are N genes that may be specifically expressed." to "There are N genes predominantly expressed. (When one considers all gene expression pattern data and only the 'enriched' type of expression cluster data)."

**Comment by chris-grove** [comment]
@raymond91125   Looks OK to me. Thanks

**Comment by rankishore** [comment]
@raymond91125: If you mean the set includes all gene expression pattern data and only the 'enriched' type of expression cluster data, I would say exactly that, so:
'There are N genes predominantly expressed (includes gene expression pattern data and only the 'enriched' type of expression cluster data)'

**Comment by raymond91125** [comment]
Sure, that's good. @azurebrd Could you implement the change of label to what @rankishore proposed? Thanks.

**Comment by azurebrd** [comment]
Hi @sibyl229 !  I haven't done anything with the website or datomic-to-catalyst since August 2018.  Right now juancarlos.wormbase.org is loading, but the pages aren't loading, and I can't tell if it's a website/ or a datomic-to-catalyst/ issue.  This fix should be really easy though, would you mind making it for us ?

In the website/ repo, the file lib/WormBase/API/Service/ontology_browser.pm
Line 268 :         
  my $exclusively_message = "There are " . $count . " genes that may be specifically expressed. ";
should become : 
  my $exclusively_message = "There are " . $count . " genes predominantly expressed (includes gene expression pattern data and only the 'enriched' type of expression cluster data)";

If you could separately help me get juancarlos.wormbase.org working again also, that would be great, but there's no rush, as I haven't needed to do anything with it for a long while.

Thanks !

**Comment by azurebrd** [comment]
Thanks @sibyl229 for the temporary fix for datomic-to-catalyst to work ! :) 

@raymond91125 @rankishore It's working on juancarlos.wormbase
https://juancarlos.wormbase.org/species/all/anatomy_term/WBbt:0005759#14--10-1
And there's a pull request
https://github.com/WormBase/website/pull/6914
