### ISSUE TITLE
molecular details widget to handle range feature for protein sequence display

### ISSUE THREAD

**Issue by sibyl229** [WormBase/website#6854]
Molecular details widget currently handles only single position features in the protein display. We want it to handle range features such as deletion.

Having discussed with @a8wright the API will return data in the following format:

```
// for single position feature
{
  start: ,
  stop: ,
  position: ,  // for backward compatibility
}

// for region feature 
{
  start: ,
  stop: ,
}
```

**Comment by a8wright** [comment]
I have made it so that we are using mutant_start mutant_stop and wildtype_start wildtype_stop.

With this change, we are adding protein sequence to Readthrough and Nonsense mutations.

Here are some:
**Missense:** https://wormbase.org/species/c_elegans/variation/WBVar01684110#-58-10
**Readthrough:** https://wormbase.org/species/c_elegans/variation/WBVar00941611#-58-10
**Nonsense:** https://wormbase.org/species/c_elegans/variation/WBVar00466445#-58-10

I have also made it so that information on Missense and Nonsense show up in the location affect part of the predicted-cds table. This all should be checked by curators:)

**Comment by chris-grove** [comment]
@a8wright 
I see the indication of the missense and readthrough alleles in the predicted-cds table (and they look OK), but I don't see any indication of the nonsense mutation in your last example:

https://wormbase.org/species/c_elegans/variation/WBVar00466445#-58-10

**Comment by sibyl229** [comment]
@a8wright I updated the UI code to handle range effects. It's deployed on staging now. Please take a look to see if the result is what you expect.

I also updated the links you posted above to use the staging site (instead of production) for easier test.

**Comment by a8wright** [comment]
@chris-grove thanks for taking a look. I think the issue is your URL was for production. Here is the staging link: https://staging.wormbase.org/species/c_elegans/variation/WBVar00466445#-58-10

Sorry about putting them as production links initially. 

Let me know if that works for you.

**Comment by chris-grove** [comment]
OK, thanks @sibyl229 , @a8wright 

Looking at:

https://staging.wormbase.org/species/c_elegans/variation/WBVar01684110#-58-10

In the "Predicted CDS" table (which I think might better be named "Predicted effects on CDS"), the "Affects" column has the entry:

"""
Effect on protein: Missense
174
E to K
Affects: Coding exon
Affects: Missense
"""

That is all fine except the last line "Affects: Missense" doesn't make any sense and should be removed. It's already been stated that it is a missense mutation in the "Effect on protein" entry.

Looking at:

https://staging.wormbase.org/species/c_elegans/variation/WBVar00941611#-58-10

a couple of things:

1) I like that we try to show the consequence of a readthrough mutation, but I think it may be a little misleading, as the change from a stop (*) to a cysteine (C) codon will likely add the C to the end of the protein sequence, but that's likely just the beginning of many more amino acids being (aberrantly) added to the C-terminal end of the protein. We could try to follow the sequence in-frame up to the next stop codon and add in all predicted extra amino acids to the protein sequence but maybe that's overkill. I'd like to know what other curators think about this display.

2) The stop on this readthrough mutation page is referred to by an asterisk '*', whereas the stop is specifically spelled out as "amber stop" on the next example page for the nonsense mutation:

https://staging.wormbase.org/species/c_elegans/variation/WBVar00466445#-58-10

Since the readthrough mutation is TGA (opal stop) to TGT (C), maybe we could say "opal stop" instead of "*" for consistency.

3) The "Affects" column of the Predicted CDS table on the gk765402 variation page reads:

"""
Effect on protein: Readthrough

* to C
Affects: Readthrough
Affects: Coding exon
"""

I think the extra empty line is unnecessary, and similar to my comment for the last page, "Affects: Readthrough" doesn't make sense and can be removed. So, I think it should simply read:

"""
Effect on protein: Readthrough
Opal stop to C
Affects: Coding exon
"""

For the last example page:

https://staging.wormbase.org/species/c_elegans/variation/WBVar00466445#-580-10

I think it looks good; I like the protein change depiction showing the truncated protein sequence. My only comment is, again, about the display in the "Affects" column of the Predicted CDS table. It currently reads:

"""
Effect on protein: Nonsense

Q to amber stop (80)
Affects: Coding exon
Affects: Nonsense
"""

I think the empty line is unnecessary and the "Affects: Nonsense" should be removed, so that it reads:

"""
Effect on protein: Nonsense
Q to amber stop (80)
Affects: Coding exon
"""

**Comment by sibyl229** [comment]
![screen shot 2019-02-19 at 12 23 46 pm](https://user-images.githubusercontent.com/1753893/53034918-49135380-3442-11e9-8aba-0ebb07c08c35.png)
@a8wright

**Comment by a8wright** [comment]
@sibyl229 I have removed the redundant "Readthrough" information in the location_effects section.

**Comment by a8wright** [comment]
@sibyl229 here is a link to a page where the readthrough field in the database has some aa's and other aa's added to the end of the protein sequence: https://staging.wormbase.org/species/c_elegans/variation/WBVar02099230#6--10

@chris-grove we are going to inquire with EBI on what is actually provided in the database for readthrough, later in the week. I will comment out the code for the readthrough sequence if it is not what we want (sequence up to predicted end based on stop codon).

**Comment by sibyl229** [comment]
Hi @chris-grove I think @a8wright has fixed the problems you mentioned above:
- removed readthrough sequence for now (as we can't get the translation until the next stop codon easily)
- fixed the "Effects on protein" and "Affects"
- fixed "* to C"
Do you mind take a look again? See if we missed anything. Thanks!

**Comment by chris-grove** [comment]
@sibyl229  Thanks

    * removed readthrough sequence for now (as we can't get the translation until the next stop codon easily)

OK, I think it's fine not to include a conceptual translation of a readthrough mutation. Checking this page:

https://staging.wormbase.org/species/c_elegans/variation/WBVar00941611#6--10

The entry for the Predicted CDS table "Affects" column had been:

"""
Effect on protein: Readthrough

    * to C
      Affects: Readthrough
      Affects: Coding exon
"""

which I was suggesting should change to just:

"""
Effect on protein: Readthrough
Opal stop to C
Affects: Coding exon
"""

but now just reads "Affects: Coding exon". I still think it's useful for users to see the line "Effect on protein: Readthrough" and the "* to C" or "STOP to C" or "Opal stop to C" (I prefer either of the latter two options.

    * fixed the "Effects on protein" and "Affects"

Checking this page:

https://staging.wormbase.org/species/c_elegans/variation/WBVar01684110#6--10

I still see the same entry for the "Affects" column in the "Predicted CDS" table:

"""
Effect on protein: Missense
174
E to K
Affects: Missense
Affects: Coding exon
"""

It's not a big issue, but the "Affects: Missense" is a bit non-sensical and redundant, so I was suggesting removing it from the field, such that it would read:

"""
Effect on protein: Missense
174
E to K
Affects: Coding exon
"""

    * fixed "* to C"

On the readthrough mutation example page:

https://staging.wormbase.org/species/c_elegans/variation/WBVar00941611#6--10

In the "Protein Change" field it reads "(* to C)", which I was suggesting could change to "(Opal stop to C)" but even "(STOP to C)" or something would be fine. This was to be consistent with how we represent a stop codon, for example on the nonsense mutation page:

https://staging.wormbase.org/species/c_elegans/variation/WBVar00466445#6--10

which, in the "Protein Change" field, reads "(Q to STOP)" and in the Predicted CDS table "Affects" column reads "Q to amber stop (80)".

Also, on that same nonsense mutation page and same "Affects" column entry, it reads:

"""
Effect on protein: Nonsense

Q to amber stop (80)
Affects: Coding exon
Affects: Nonsense
"""

and I was suggesting it would look nicer as

"""
Effect on protein: Nonsense
Q to amber stop (80)
Affects: Coding exon
"""

as the blank line just takes up space and the "Affects: Nonsense" is non-sensical and redundant.

I'm not sure if I should be looking somewhere else. I did empty my cache and do a hard refresh on each page.

**Comment by sibyl229** [comment]
@chris-grove sorry about that. Thanks for checking this again. I will coordinate with @a8wright to get those fixed.

@a8wright could you take a look into this?

**1)**  make sure for a nonsense mutation, the `description` in `protein_effects` say STOP instead of *. Ideally, instead of STOP, it would say the exact type of stop, such as "amber stop".

Example for testing: https://staging.wormbase.org/species/c_elegans/variation/WBVar00941611#6--10

**2)** remember you removed the "readthrough" attributes from **`location_effects`**? Could you make sure to remove other effects, that's considered a **protein effect**?** For example, nonsense, missense, etc. You can check the `protein_effects` field to see what's considered a protein effect.

Otherwise, the Predicted CDS table will produce sentence that doesn't make sense.

Example for testing: https://staging.wormbase.org/species/c_elegans/variation/WBVar00466445#6--10

FYI: The template code is here: https://github.com/WormBase/website/blob/staging/root/templates/classes/variation/molecular_details.tt2#L222-L275

If you have any questions, please let me know.

**Comment by a8wright** [comment]
@chris-grove @sibyl229 These have now been updated on Staging. all that is left in location effects is intron and exon types.

**Comment by sibyl229** [comment]
@a8wright great, thanks!

@chris-grove i tested the following example to ensure 1) `* to C` now says "STOP to C" 2) the "Affects:" no longer says missense or nonsense:

https://staging.wormbase.org/species/c_elegans/variation/WBVar01684110#6--10
https://staging.wormbase.org/species/c_elegans/variation/WBVar00941611#6--10
https://staging.wormbase.org/species/c_elegans/variation/WBVar00466445#6--10

In the WBVar01684110, it might sound more natural (and consistent with how we show nonsense mutation) to say:
```
Effect on protein: Missense
E to K (174)
Affects: Coding exon
```

Instead of:
```
Effect on protein: Missense
174
E to K
Affects: Coding exon
```

What do you think @chris-grove @a8wright ?

**Comment by chris-grove** [comment]
@sibyl229 @a8wright 
OK, thanks, looks good. Yes the text:

```
Effect on protein: Missense
E to K (174)
Affects: Coding exon
```

looks good. I don't want to hold this issue up over it, but, as I've said, I'll just point out that on this page:

https://staging.wormbase.org/species/c_elegans/variation/WBVar00941611#6--10

The entry for the Predicted CDS table "Affects" column had been:

```
Effect on protein: Readthrough

* to C
Affects: Readthrough
Affects: Coding exon
```

which I was suggesting should change to just:

```
Effect on protein: Readthrough
Opal stop to C
Affects: Coding exon
```

but now just reads "Affects: Coding exon", so I think we've lost some useful information. If it's trivial to add back, it would be nice, but if it isn't trivial, leave it and we'll deal with it later.

**Comment by sibyl229** [comment]
@chris-grove thanks for your patience doing all the testing. I think it's a bug.

@a8wright could you make sure the `protein_effects` return the right data? To be more specific, the attributes you removed from **`location_effects`** (such as, readthrough, missense, nonsene) should be present IN the **`protein_effects`** and ONLY IN protein effects. 

Note: the `protein_effects` and `location_effects` are mutually exclusive. They are respectively about effects on the protein (missense, nonsense, readthrough, etc) and location (like exon, intro, etc).

Thanks!

**Comment by a8wright** [comment]
This is a long ticket. @sibyl229 and I just discussed this and looked at the template code for this widget to figure out what needs to be done. I added the Readthrough field back in the Protein_effects section. In order to make sure that this didn't cause the sequence to be displayed in for Readthrough I filtered our these sequences from making it to the response.

**Comment by sibyl229** [comment]
@a8wright there is another item in @chris-grove comment:

```
Effect on protein: Readthrough
Opal stop to C
Affects: Coding exon
```

That means the `description` attribute should say `Opal stop` instead of `*`. 

Thanks!

**Comment by a8wright** [comment]
@chris-grove I just looked in the database and I don't think we have this information. For Missense we have information on the stop codon that is created: https://staging.wormbase.org/species/c_elegans/variation/WBVar00979994#69--10 But I have not been able to find this in the database/db-schema. If you have an example where you can find this information in the tree display but not where you would expect it in the display please let me know and I will add it in. On the other hand, I have changed the "* " to stop in the evidence. @sibyl229 and I are going to talk to @Paul-Davis later in the week. I will make sure to ask him if it would make more sense to have it be STOP in the database instead of "*".

**Comment by chris-grove** [comment]
@sibyl229 @a8wright 
It's OK, I'm not holding out for the "Opal stop to C"; what you've added now "STOP to C" is sufficient. My main point was to add back the "Effect on protein: Readthrough" and if possible "STOP to C" or equivalent. So, I think it looks good now and you can close the ticket.

**Comment by sibyl229** [comment]
Thanks a lot @chris-grove ! Closing
