### ISSUE TITLE
How to BLAST proteins against the Hawaiian/CB4856 proteome?

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6857]
*Help Desk chat transcript. Issue can be closed if question was resolved in chat.*

visitor_name (visitor_email): So, here is my problem:I am working with C. elegans strains N2 and CB4856. After some reading and trying, I came to understand that all the genes listed on WormBase were based on the N2 strain. Therefore, when I was first blasting, I was blasting N2 genes against the N2 genome, so my results were telling me that I had perfect matches all the time. I was finally able to blast against the CB4856 genome using the University of Washington C. elegans genome project (PRJNA275000), which is the genome for CB4856. However, WormBase will not return anything at all when I tried to do a protein query. However, it does return some results when I do the nucleotides query. But because it will take virtually forever to translate the nucleotide sequence to the protein sequence, it is impractical to do so.
Therefore, I need help doing a protein query. Thank you!</br>Chris: Hello Jean-Pierra</br>visitor_name (visitor_email): Hi</br>Chris: So, you have a large list of proteins that you want to BLAST against the CB4856 genome/proteome specifically?</br>Chris: visitor_name, sorry</br>visitor_name (visitor_email): Im doing an in silico analysis of the two strains and I look for specific genes of interests. Once I find these genes, I try to blast them against the CB4856 genome since the genes on WormBase are based on N2</br>Chris: OK</br>Chris: We don't currently (as far as I'm aware) have a way to BLAST protein sequences against the CB4856 proteome</br>Chris: Is that what you're trying to do?</br>visitor_name (visitor_email): Yes</br>visitor_name (visitor_email): Do you have any ideas on how I can do this?</br>Chris: OK, I don't have a solution to that off hand. Let's end the chat, and we will both get a transcript of the conversation. Then I will send around to the general WormBase consortium to ask for advice on how to accomplish this</br>Chris: You will be CC'ed</br>visitor_name (visitor_email): Okay thanks. Here's my email</br>visitor_name (visitor_email): visitor_email</br>Chris: OK thanks. I'll be in touch</br>visitor_name (visitor_email): Thanks!</br>Chris: You're welcome! Talk soon

**Reported by:** Jean******* (jamo**************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/tools/support?url=/">https://www.wormbase.org/tools/support?url=/</a>
**Browser:** Chrome 71.0.3578.98

**Comment by epaule** [comment]
as far as I know, there is no gene set for the Hawaiian strain of C.elegans. 
Which is why the protein data you can find on WormBase is based on a mapping of N2 genes using GenBlastG.
The mapping in no way guarantees complete or unique gene models (some even have in-frame stops and frameshifts) and is moistly used to orient yourself on the Hawaiian genome.

So I think options are:
a.) you download the protein fasta file from the Hawaiian strain at WormBase (ftp://ftp.wormbase.org/pub/wormbase/releases/current-production-release/species/c_elegans/PRJEB28388/) and blast/align it locally on your computer
or
b.) you map your proteins onto the N2 genome and check the pairwise alignments on UCSC for the respective place on the Hawaiian genome (which you can find in the WormBase public hub attached to the C.elegans N2 assembly).
or
c.) you grab the Hawaiian genome from the same WormBase link above and use TBLASTN or GenBlastG or GeMoMa or something like that to align your proteins directly. Generally I would actually recommend nucleotide sequences rather than proteins for that, as it would make the alignments more accurate and faster, but YMMV.
