### ISSUE TITLE
Variation Overview Addition.

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/website#6878]
Hi Webteam,

Currently there is no way of telling if an allele was generated with the use of CRISPR technology from it's summary page.

There is a production method attribute attached to the variation if it's an Engineered_allele.

https://staging.wormbase.org/species/c_elegans/variation/WBVar02148651?redirect=1#9--10

Production_method -> CRISPR_Cas9

Could I get this added to the Overview widget in the box on the RH side.

![overview_addition_var_crispr](https://user-images.githubusercontent.com/717707/51851716-5befa800-231c-11e9-889d-be16072ca253.png)

Thanks

**Comment by sibyl229** [comment]
Hi @Paul-Davis I added the production method (ie, CRISPR-Cas9, etc) to variation overview. 

I made some adjustment. It's in the main content rather in the box, because things on the right side of the screen are more easily ignored than the left side. 

Please let me know the wording and placement is okay. Thanks!

**Comment by sibyl229** [comment]
Fix was deployed to production in WS270. Closing. Please feel free to repo if there is a problem.
