### ISSUE TITLE
  I found an entry error on the strain ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6886]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I found an entry error on the strain VC2552 page, where the corresponding allele is listed as: F090F7.7(ok3133) III.<br/>However the correct gene name is F09F7.7 (nmad-1).<br/>Best<br/>Attila</p>

**Reported by:** Atti********* (a.st**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Safari/604.1.38

**Comment by Paul-Davis** [comment]
Dear Attila,

Thank you for letting us know about this bug. We get our strain data 
from the CGC as part of our strain list update. I will correct it in 
WormBase and feed this back to them so that we don't get the same error 
next time we take the data.

Thanks again.

Paul


On 30/01/2019 20:30, no-reply@wormbase.org wrote:
> Content Correction
>
>   I found an entry error on the strain VC2552 page, where the 
> corresponding allele is listed as: F090F7.7(ok3133) III.
> However the correct gene name is F09F7.7 (nmad-1).
> Best
> Attila
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #6886. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6886>.
>
> Reported by: Attila Stetak (a.stetak@unibas.ch)
> 30 Jan 19 20:30
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/604.1.38 
> (KHTML, like Gecko) Version/11.0 Safari/604.1.38
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
Corrected in WB for WS271 reported to CGC so we don't get it next time we update.
