### ISSUE TITLE
sorry, I've asked this before, and I promise to wr...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6899]
*Help Desk query collected when no chat operators were online. Follow up required.*

sorry, I've asked this before, and I promise to write it down this time- how do I get all of the genes that have been shown to be expressed in a particular cell, say 'M3' neuron for example?

**Reported by:** Pete***** (pete*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/#012-34-5">https://www.wormbase.org/#012-34-5</a>
**Browser:** Safari 12.0.2

**Comment by raymond91125** [comment]
Hi Peter,

You can use the ontology browser on the M3 neuron anatomy page <https://wormbase.org/species/all/anatomy_term/WBbt:0003754#4--10><https://wormbase.org/species/all/anatomy_term/WBbt:0003754#4--10>.

Click on the link to the right of "M3 neuron (WBbt:0003754)", you'd get a page with gene lists.

Cheers,

Raymond

On 05/02/2019 1:00 PM, no-reply@wormbase.org<mailto:no-reply@wormbase.org> wrote:
offline chat sorry, I've asked this before, and I promise to write it down this time- how do I get all of the genes that have been shown to be expressed in a particular cell, say 'M3' neuron for example?

Submitted From:
  https://www.wormbase.org/#012-34-5 https://www.wormbase.org/#012-34-5<http://www.wormbase.org/https://www.wormbase.org/#012-34-5>

This issue has been assigned ticket number: #6899. Follow progress on our issue tracker<https://github.com/WormBase/website/issues/6899>.

Reported by: Peter Roy (peter.roy@utoronto.ca<mailto:peter.roy@utoronto.ca>)
05 Feb 19 21:00


This question was reported via the web interface at wormbase.org. You can also email us<mailto:help@wormbase.org> directly.

--
--
You received this message because you are subscribed to the "WormBase: help" group.
To post to this group, send email to help@wormbase.org<mailto:help@wormbase.org>
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en

---
You received this message because you are subscribed to the Google Groups "WormBase: help" group.
To unsubscribe from this group and stop receiving emails from it, send an email to help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>.


--
__
Raymond Lee
raymond@caltech.edu<mailto:raymond@caltech.edu>
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
