### ISSUE TITLE
I'm trying to download a FASTA file of a sequence ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6912]
*Help Desk query collected when no chat operators were online. Follow up required.*

I'm trying to download a FASTA file of a sequence defined by genomic position.  There used to be a button for doing this but I don't see it anymore.  Thanks for your help.

**Reported by:** Kevi********** (kevi**********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/tools/genome/jbrowse-simple/?tracks=Curated_Genes,Classical_alleles,YACs_Fosmids_Cosmids&amp;loc=IV:387759..388927&amp;data=data/c_elegans_PRJNA13758">https://www.wormbase.org/tools/genome/jbrowse-simple/?tracks=Curated_Genes,Classical_alleles,YACs_Fosmids_Cosmids&amp;loc=IV:387759..388927&amp;data=data/c_elegans_PRJNA13758</a>
**Browser:** Chrome 71.0.3578.98

**Comment by scottcain** [comment]
Replied to the user:
Hi Kevin,

In the new genome browser (JBrowse) there isn't currently a button for downloading fasta; I plan on adding one soon.

In the meantime, it's not hard, just involves a few steps, depending on what you want to do.  If you want the sequence around a particular gene or transcript, you can turn on the "Curated Genes" track and right or control click on gene.  From the resulting popup menu, select "View Sequence".  You will get a dialog asking you to pick a transcript and after picking one, the resulting window will let you do a variety of useful operations like highlighting, upper/lower casing, and hiding features, as well as letting you display up to a few kb of up or downstream sequence.  You can copy from this dialog box and frequently preserve highlighting (in my experience it varies by browser--last I tried, Firefox worked, Chrome didn't and I don't remember for Safari or Edge).

Alternatively, if you want the sequence of a "random" region, you can turn on the "reference sequence" track, zoom the view to the region you want fasta for, then mouse over the label for that track, which makes it more "solid" and displays a down triangle indicating a menu.  Clicking on that gives a menu with the option "Save track data".  Selecting that will give you a dialog box that will give you the option to view or save the visible region's data as fasta.  I don't think it gives you an option for where to save it, so it will end up in your Downloads folder or where ever your default location is.

**Comment by Paul-Davis** [comment]
@scottcain I see you answer this question quite a lot......is there a way to include a Help or FAQ button on the jbrowse page as users might find this helpful?

**Comment by Paul-Davis** [comment]
![scott](https://user-images.githubusercontent.com/717707/52626844-fa970f80-2eab-11e9-9e22-f99d68aba86f.png)

Maybe something over in this section above the tracks like you did with the modencode data??

**Comment by scottcain** [comment]
@Paul-Davis That's a good idea; I've been somewhat distracted by obtaining a technological solution that will take me some time to do (which is still worthwhile), while a simple thing like this would be really useful too.  There are a few approaches that I could take: 1. a link under the modencode link that points at a blog post I could write, or 2. modifying the help text in the "general" dialog box under the Help menu.  The first option is easier to find but introduces more "clutter" for everybody, including people who don't care.  The latter option is harder to find (though one would hope that a person trying to answer a question of "how do I..." would look there) but is cleaner and presumably briefer, since the the space is limited in that dialog box, though it could still point to a blog point for more information.  I'll work on a blog post and decide how to link to it later.

**Comment by tharris** [comment]
Resolved.
