### ISSUE TITLE
  There is a correction on the mutation...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6929]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;There is a correction on the mutation for unc-13(n2813) communicated to me by Jim Rand.<br/>The correct change is S(1572)R   <br/>NOT S(1574)R as we reported in our paper, i figured we should put it on wormbase to clarify the issue:<br/>S(1572)R        <br/>TGATTGTGCACTTGACGCCATTAAAGACAG / T>A / TTCCATGCATCCGGAAAAGGACTTAAGAAA</p>

**Reported by:** Erik********** (jorg**********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36

**Comment by Paul-Davis** [comment]
Dear Erik,

Thank you for forwarding this correction, if everyone is in agreement 
then we can make this update for release WS271 of WormBase.

Just checking it's still pending curation so I can curate the variation 
so that it gets mapped to the genome for the 1st time.

Paul




On 20/02/2019 20:55, no-reply@wormbase.org wrote:
> Content Correction
>
>   There is a correction on the mutation for unc-13(n2813) communicated 
> to me by Jim Rand.
> The correct change is S(1572)R
> NOT S(1574)R as we reported in our paper, i figured we should put it 
> on wormbase to clarify the issue:
> S(1572)R
> TGATTGTGCACTTGACGCCATTAAAGACAG / T>A / TTCCATGCATCCGGAAAAGGACTTAAGAAA
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #6929. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6929>.
>
> Reported by: Erik Jorgensen (jorgensen@biology.utah.edu)
> 20 Feb 19 20:55
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 
> (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
No response but the location and the data checks out.....cited bot users for the change and curated the sequence details.
