### ISSUE TITLE
WS271 gene descriptions-loss of elegans orthologs for C. remanei and C. japonica

### ISSUE THREAD

**Issue by rankishore** [WormBase/website#6953]
@gw3 and Hinxton: From generating WS271 descriptions, we noticed that--
1.  C. remanei lost orthology sentences to elegans for over 20,000 genes
2. C. japonica also lost orthology to elegans sentences for over a 1000 genes
3. The remanei PRJNA53967.WS270.orthologs.txt file which we use for generating orthology sentences has over 27,000 gene ids in the form of PRJEB28388_chrIII_pilon.g8020	chrIII_pilon.g8020;  This is most likely why we lost all those orthology to elegans sentences, as we cannot use gene IDs of this nature.

Will these IDs be removed and replaced with WBGene IDs?

**Comment by gw3** [comment]
It looks like there were a few corrections to the script 'dump_species_orthologs.pl' in January '19 to correct problems that had appeared in WS269.

The release WS269 had the genome of the strain C. elegans VC2010 added - this is the genome that has genome sequences and genes named like: 'PRJEB28388_chrX_pilon.g21065    chrX_pilon.g21065'

WS269 dumped out orthologies for C. elegans VC2010 genes as well as C. elegans N2 genes, so the file 'elegans.orthologs.txt' was twice as large in WS269 as in other releases.

The corrections to the script mean that only genes with a WBGeneID and which are mapped to the genome are now output, so the extra VC2010 genes (and their orthologs) are not in 'elegans.orthologs.txt' in WS270. Consequently this file is half the size it was in WS269 and is comparable to the size of the file in WS268.

The WS270 file still has the orthologs between C. elegans N2 genes and C. elegans VC2010 genes, which is why you see lines like:
'Caenorhabditis elegans  PRJEB28388_chrI_pilon.g841      chrI_pilon.g841 WormBase-Compara'.
These lines are correct as they capture orthologies between N2 and VC2010.
