### ISSUE TITLE
  How can I compare ChIP Seq results fr...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6969]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How can I compare ChIP Seq results from two different datasets? Valerie Reinke's two SMA-3 ChIP Seq datasets are on ModEncode but not in WormBase- is it possible to get them in WormBase? I'd like to compare these data sets with two other ChIP Seq datasets that are on WormBase to determine what target genes are unique to the individual datasets and which target genes are shared between datasets.<br/>Thank you!</p>

**Reported by:** Tina************ (tgum*************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36

**Comment by scottcain** [comment]
Emailed the user:

Hi Tina,

I'm responsible for the genome browsers for WormBase and interact with the modENCODE data sometimes.  Can you send me a link or some identifier for the data sets you're looking for?  I poked around the modENCODE site and didn't find anything that fits your description, but I find the modENCODE site somewhat opaque.

**Comment by scottcain** [comment]
Email thread, from Tina:
Hi! Thanks for getting back to me so quickly.

Let me correct and refine our question for you. We want to compare the Reinke SMA-3 ChIP dataset “eGFP-sma-3 ChIP-seq of whole organism”, which isn’t on modENCODE, but is available on the UCSC Genome Browser, at least we’ve figured out how to look at individual potential genomic target regions and see if there’s an eGFP-sma-3 ChIP-seq hit at that specific site. 

ModENCODE (http://data.modencode.org/?Organism=C.%20elegans ) has three datasets we’d like to compare to this SMA-3 dataset.

    2612: BLMP-1;OP109;Fed L1 stage larvae;20 degree celsius;ChIP-seq (C. elegans)
    4036: BLMP-1;OP109;Embryos;20 degree celsius;ChIP-seq (C. elegans)
    3228: SMA-9;OP130;Larvae L2 stage;20 degree celsius;ChIP-seq (C. elegans)

Does that help you help us?

**Then from me:**

Ah, Ok.  This track is from the modERN project, which I've thought about every so often for the past few years and whether I should try to pull all of that data into WormBase like we did with modENCODE. It's a big undertaking, so I think about it and then set it aside to work on "more pressing" issues :-/

I think it is possible for you to do it in an ad hoc way but I want to sort out exactly how and I'll let you know.

**And another follow up from me:**

I nearly have a solution, but a complicating factor is that a new release of WormBase is going to come out in the next day or so, and as a result, I don't want to muck around with the pre-release version of JBrowse right now.  To get these data to display in JBrowse, I have to write some custom code to deal with the fact that they name their chromosomes "chrI", "chrII", etc, but we use I, II, etc, and JBrowse doesn't understand yet that those are the same thing.  After I sort that out, you just need the URL of the bigbed file at the encode project and you can add a track yourself (I'll give you directions after I get it working here).

**Comment by scottcain** [comment]
And another follow up from me:
Hi Tina and Mohammed,

I changed my mind; why not live life on the edge.  I realized the change I had to make in the JBrowse code was quite small so I did it, next release be damned! :-)

To try this out, you'll have to use the WormBase staging server, your thoughts on which will be of particular interest to me, since I've been working on the modENCODE data presentation a lot recently.  I changed the display so that the minimum value on the y axis is the mean + 1.65 times the standard deviation to clear out much of the noise.  I'll be interested if you find that more useful in your analysis.  A sample location in the browser is here, with the genes track and the modENCODE tracks you wanted:

https://staging.wormbase.org/tools/genome/jbrowse-simple/full.html?data=data%2Fc_elegans_PRJNA13758&loc=II%3A6528792..6626814&tracks=Curated%20Genes%20(protein%20coding)%2CBLMP-1%20Combined%20(GFP%20ChIP)_%20BLMP-1_Emb%2CBLMP-1%20Combined%20(GFP%20ChIP)_%20BLMP1_GFP_L1%2CSMA-9%20Combined%20(GFP%20ChIP)

To add the modERN track, you need the URL of the track data.  To get that, you click on the link in the UCSC track listing labeled "eGFP-sma-3 ChIP-seq of whole organism ENCSR992FVB" and then, in the line of the table that says "Optimal IDR thresholded peaks" under views, click on the "schema" link (you might have to side scroll to see that link--it's a pretty wide table).  In the resulting page, there is a url next to the words "Big Bed File", which is https://www.encodeproject.org/files/ENCFF055GQP/@@download/ENCFF055GQP.bigBed?proxy=true (you can just copy it from here, but I wanted to let you know how I got it.)

Now that you have that url, in JBrowse next to the species name and bioproject id, there is a File menu.  Click on that and select "Open track file or URL".  In the resulting dialog box, paste the above url in the "Remote URLs" box.  Normally, JBrowse will just automatically identify what sort of data is being loaded, but the trailing "proxy=true" on the URL will confuse it, so in the blue box labeled "Files and URLs", you'll have to use the drop down menu to select "BigBed".  Then click on the open button and you should get a track with some unattractive orange-yellow boxes representing the data you wanted.

One small-ish caveat is that JBrowse won't remember you did this when you reload the page, which can be a bit of a hassle.  That's one reason I'd like to pull all of these tracks inside the WormBase JBrowse instance.

Please let me know how it goes and if you have any more questions,
Scott
