### ISSUE TITLE
  Hi,  I remember there used to be a to...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6972]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi, <br/>I remember there used to be a tool, in which I can input a list of gene from my expression study, and query what other experiments produce a similar list of genes. We used that a few years ago, and found that our data set was highly similar to a data set associated with a AMPK mutant study. <br/>Is that tool still available, and how / where can I find it?  <br/>Thank you!</p>

**Reported by:** Sylv** (sylv******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:65.0) Gecko/20100101 Firefox/65.0

**Comment by raymond91125** [comment]
SPELL?

under Tools->BY SEQUENCE.

https://spell.wormbase.org/

Raymond

On 07/03/2019 10:25 AM, no-reply@wormbase.org<mailto:no-reply@wormbase.org> wrote:
How Do I ...?

  Hi,
I remember there used to be a tool, in which I can input a list of gene from my expression study, and query what other experiments produce a similar list of genes. We used that a few years ago, and found that our data set was highly similar to a data set associated with a AMPK mutant study.
Is that tool still available, and how / where can I find it?
Thank you!

Submitted From:
  support /tools/support<http://www.wormbase.org//tools/support>

This issue has been assigned ticket number: #6972. Follow progress on our issue tracker<https://github.com/WormBase/website/issues/6972>.

Reported by: Sylvia (sylvia.lee@cornell.edu<mailto:sylvia.lee@cornell.edu>)
07 Mar 19 18:25

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:65.0) Gecko/20100101 Firefox/65.0

This question was reported via the web interface at wormbase.org. You can also email us<mailto:help@wormbase.org> directly.

--
--
You received this message because you are subscribed to the "WormBase: help" group.
To post to this group, send email to help@wormbase.org<mailto:help@wormbase.org>
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en

---
You received this message because you are subscribed to the Google Groups "WormBase: help" group.
To unsubscribe from this group and stop receiving emails from it, send an email to help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>.


--
__
Raymond Lee
raymond@caltech.edu<mailto:raymond@caltech.edu>
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by rankishore** [comment]
Closing, as User was replied to and we did not hear back with further questions/clarifications.
