### ISSUE TITLE
Hi,
I was looking for RNAi-caused phenotypes, Y10G...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6973]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi,
I was looking for RNAi-caused phenotypes, Y10G11A.1
for example, and found that one phenotype was embryonic lethal. The supporting evidence showed the reference number (78425) and paper (Galy 2003). However, when I clicked 78425, it showed three RNAi targets (Y95B8A.4, Y77E11A.13, and Y10G11A.1). I further checked the paper and it showed Y77E11A.13 RNAi caused embryonic lethality. My question is that if the information that Y10G11A.1 RNAi causes embryonic lethality is wrong or it is correct just because of some reasons (for example, Y10G11A.1 and Y77E11A.13 share similarity in sequence)?
Thank you very much : )

**Reported by:** Andr** (gemi**********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/species/c_elegans/gene/WBGene00012423#048ea-9gc-3">https://wormbase.org/species/c_elegans/gene/WBGene00012423#048ea-9gc-3</a>
**Browser:** Chrome 72.0.3626.121

**Comment by chris-grove** [comment]
My email to user:
"""
Thanks for writing in. In general, if there are multiple genes listed in the "Gene targets" table on an RNAi object page it would indicate that our mapping pipeline detected sufficient sequence similarity to the dsRNA sequence used in the experiment so as to warrant applying the phenotypes for that experiment to all of those genes. As it turns out, the mapping of Y10G11A.1 to WBRNAi00078425 is likely due to an error in our mapping pipeline that has just recently been fixed. This correction will be visible in our WS269 release due out any day now. You can see this change on our staging site now (note that our staging site is unstable and is not intended for regular use):

https://staging.wormbase.org/species/c_elegans/rnai/WBRNAi00078425#041--10

As you can see, this RNAi experiment is now predicted to only knockdown npp-20 (Y77E11A.13). There are currently no annotated observed phenotypes for Y10G11A.1.

Apologies for any confusion.

Let us know if you have any additional questions.
"""
