### ISSUE TITLE
  I think if would be beneficial to hav...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6974]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I think if would be beneficial to have some kind of redirection when coming to a dead end. I know at times we could be looking for information that could not possibly exist in the database just yet; but it can be frustrating at times when you get a "Zero results."</p><p>What were you doing? <br />&nbsp;&nbsp;I was trying to find information about gene EVL-14 with GFP tag. I did a species search with C. elegans and did a general search as well; however still got zero results. </p>

**Reported by:** Alic*** (asal*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36

**Comment by Paul-Davis** [comment]
Dear Alicia,

Apologies you are having difficulties with our search,

Searching "All" for EVL-14 you should get 127 results returned the 1st 
being the evl-14 gene in C. elegans.
https://www.wormbase.org/search/all/EVL-14

This can be refined initially by selecting "Gene" and searching the same 
term
https://www.wormbase.org/species/c_elegans/gene/WBGene00001352#0g619--10

Once on the gene summary page you can access all of the information we 
have collected about the evl-14 gene.

I cannot reproduce the "Dead end" you describe unless you re using a 
complicated free text search string. In this case it would be difficult 
to come up with a redirect as the site cannot determine what you asking. 
If you have a suggestion about a redirect/landing page we could use 
instead of just stating "Sorry, 0 results found for the search X" I'm 
sure the web team would appreciate your input.

Paul





On 11/03/2019 04:05, no-reply@wormbase.org wrote:
> Feature Request
>
>   I think if would be beneficial to have some kind of redirection when 
> coming to a dead end. I know at times we could be looking for 
> information that could not possibly exist in the database just yet; 
> but it can be frustrating at times when you get a "Zero results."
>
> What were you doing?
>   I was trying to find information about gene EVL-14 with GFP tag. I 
> did a species search with C. elegans and did a general search as well; 
> however still got zero results.
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #6974. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/6974>.
>
> Reported by: Alicia (asalaman@vols.utk.edu)
> 11 Mar 19 04:05
>
> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, 
> like Gecko) Chrome/72.0.3626.121 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
