### ISSUE TITLE
  Hi, In the entry for the gene set-33 ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6976]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi,<br/>In the entry for the gene set-33 (Y108F1.3) there is a lot of RNAi data. Some of these publication used the Ahringer RNAi library (Including one from Ahringer herself). When I looked this gene in the library I could not find it. <br/>I thought that there may be a previous name (in fact even the term Y108F doesn't appear there).<br/>Am I missing the previous name, or was it not not included in the library?<br/>Thanks</p>

**Reported by:** Yona******** (yona**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:65.0) Gecko/20100101 Firefox/65.0

**Comment by chris-grove** [comment]
My email response to user:
"""
The link to set-33 is coming from these RNAi experiments because the clone sjj_Y110A7A.a (clone from the let-630 locus) from the Ahringer library was used, as can be seen in the RNAi page "Details" widget, for example:

https://www.wormbase.org/species/c_elegans/rnai/WBRNAi00095767#01--10

Our mapping pipeline appears to have identified set-33 as having sufficient sequence similarity to this clone, although I'm struggling to find the similarity myself by BLAST or sequence alignment. This may be an indication of a bug in our pipeline, so I'll contact the developers who maintain this code and investigate what might be going on.

Thanks for the heads up, and I'll get back to you with whatever I find out.
"""

**Comment by chris-grove** [comment]
@khowe 
Could you look into the source of this RNAi-to-gene mapping? It doesn't seem to me like the clone:

sjj_Y110A7A.a (Source BioScience: I-2C12)

has sufficient (or any) sequence similarity to set-33 and yet it is coming up as a primary RNAi target in these cases:

https://www.wormbase.org/species/c_elegans/rnai/WBRNAi00095767#01--10
https://www.wormbase.org/species/c_elegans/rnai/WBRNAi00004519#01--10
https://www.wormbase.org/species/c_elegans/rnai/WBRNAi00026574#01--10

(among others). I thought this might be due to the bug that was just fixed, but the issue is on staging as well:

https://staging.wormbase.org/species/c_elegans/rnai/WBRNAi00095767#01--10

Any ideas?

Thanks!

**Comment by chris-grove** [comment]
@khowe 
Nevermind, it looks like there's 150+ bp almost exact match. Clustal Omega was not finding it among longer sequences.

User responded and is satisfied.
