### ISSUE TITLE
  Hi Wormbase, I'm curious about the cr...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6988]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi Wormbase,<br/>I'm curious about the criteria by which genes are eliminated from analysis when using the Enrichment Analylsis tool. I recently tried to analyze a list of ~800 genes and more than half were not included in the GO enrichment analysis even though they are valid Wormbase genes. Some of them do not seem to have GO terms associated with them, but others (e.g. dhs-8) did. Are there any parameters that I could adjust to get more genes included as part of the analysis?</p>

**Reported by:** Matt********* (matt**************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36

**Comment by raymond91125** [comment]
Hi Matt,

Apologies for the late response. In the case of dhs-8, it presently has a singleton association with GO:0055114 which is 'excluded' from the ontology terms in the dictionary that we use for the enrichment analysis.

The full set of GO terms were trimmed based on several criteria as described in the reference below. In particular, GO:0055114 was trimmed due to the "ceiling filter" which basically removes a term if all of its child terms are included (Figure 1C in the paper).

Cheers,

Raymond

David Angeles-Albores, Raymond Y. N. Lee, Juancarlos Chan and Paul W. Sternberg (2016), "Tissue enrichment analysis for C. elegans genomics", BMC Bioinformatics 17:366

On 13/03/2019 2:35 PM, no-reply@wormbase.org<mailto:no-reply@wormbase.org> wrote:
How Do I ...?

  Hi Wormbase,
I'm curious about the criteria by which genes are eliminated from analysis when using the Enrichment Analylsis tool. I recently tried to analyze a list of ~800 genes and more than half were not included in the GO enrichment analysis even though they are valid Wormbase genes. Some of them do not seem to have GO terms associated with them, but others (e.g. dhs-8) did. Are there any parameters that I could adjust to get more genes included as part of the analysis?

Submitted From:
  support /tools/support<http://www.wormbase.org//tools/support>

This issue has been assigned ticket number: #6988. Follow progress on our issue tracker<https://github.com/WormBase/website/issues/6988>.

Reported by: Matt Youngman (matthew.youngman@villanova.edu<mailto:matthew.youngman@villanova.edu>)
13 Mar 19 21:35

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36

This question was reported via the web interface at wormbase.org. You can also email us<mailto:help@wormbase.org> directly.

--
--
You received this message because you are subscribed to the "WormBase: help" group.
To post to this group, send email to help@wormbase.org<mailto:help@wormbase.org>
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en

---
You received this message because you are subscribed to the Google Groups "WormBase: help" group.
To unsubscribe from this group and stop receiving emails from it, send an email to help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>.


--
__
Raymond Lee
raymond@caltech.edu<mailto:raymond@caltech.edu>
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by vanaukenk** [comment]
@raymond91125 - is it okay to close this ticket?

**Comment by raymond91125** [comment]
Not heard back from user.
