### ISSUE TITLE
  I am having difficulty getting inform...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#6991]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I am having difficulty getting information about sequence breakpoints of deletions. This used to be available from clicking on allele (say, tm, gk or ok) under the Genetics tab. Now I go to alleles where we have obtained the sequence before, and it is no longer there. Help?<br/>Thanks!</p>

**Reported by:** Dave******* (worm*****************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:65.0) Gecko/20100101 Firefox/65.0

**Comment by raymond91125** [comment]
Hi Dave,

Try the widget "Molecurlar Details", e.g. <https://wormbase.org/species/c_elegans/variation/WBVar00145615#-6-3><https://wormbase.org/species/c_elegans/variation/WBVar00145615#-6-3>.

Cheers,

Raymond

On 15/03/2019 9:31 AM, no-reply@wormbase.org<mailto:no-reply@wormbase.org> wrote:
How Do I ...?

  I am having difficulty getting information about sequence breakpoints of deletions. This used to be available from clicking on allele (say, tm, gk or ok) under the Genetics tab. Now I go to alleles where we have obtained the sequence before, and it is no longer there. Help?
Thanks!

Submitted From:
  support /tools/support<http://wormbase.org//tools/support>

This issue has been assigned ticket number: #6991. Follow progress on our issue tracker<https://github.com/WormBase/website/issues/6991>.

Reported by: Dave Reiner (wormboy2000@gmail.com<mailto:wormboy2000@gmail.com>)
15 Mar 19 16:31

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:65.0) Gecko/20100101 Firefox/65.0

This question was reported via the web interface at wormbase.org. You can also email us<mailto:help@wormbase.org> directly.

--
--
You received this message because you are subscribed to the "WormBase: help" group.
To post to this group, send email to help@wormbase.org<mailto:help@wormbase.org>
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en

---
You received this message because you are subscribed to the Google Groups "WormBase: help" group.
To unsubscribe from this group and stop receiving emails from it, send an email to help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>.


--
__
Raymond Lee
raymond@caltech.edu<mailto:raymond@caltech.edu>
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
