### ISSUE TITLE
How to find the starting and ending locations of CDS in new version Wormbase?

### ISSUE THREAD

**Issue by epaule** [WormBase/website#7000]
To Whom It May Concern:

I am writing to ask how to find the starting and ending locations of CDS in new version Wormbase. I have been using the WS268 version Wormbase JBrowse to find CDS starting and ending locations in C.elegansgenome for many genes (right click on a feature then choose the button “View details/Show Subfeatures”). I noticed that the Wormbase has been updated into WS269 version. But, in this new version, I can’t find the starting and ending locations of each CDS anymore in JBrowse (see attached figure). So, could you help me with that how can I find the starting and ending locations of CDS in C.elegansgenome in the new version, with or without JBrowse?

**Comment by scottcain** [comment]
My reply to the user:

Hi Bowen,

Do you want the "View Details" window for these features (like the attached image for a SNP)?  My apologies for taking it away.  Since I'd never publicized that one could even get that display, it didn't occur to me that someone might be using it.  I can restore it shortly (I'll have to do a some testing on our development site first, but then I can move it on to the WS269 browser).

**Comment by scottcain** [comment]
More follow up to the user:

HI Bowen,

The View Details window is now available on the Curated Genes tracks on the main website's JBrowse for all species EXCEPT C. elegans.  If the way it's set up now works for you, let me know and I'll do the same for C. elegans (elegans is a little extra work and I want to make sure it's good before I touch it, especially on a live web site).

**Comment by scottcain** [comment]
More communications, from Bowen:
Thank you so much for the very kind reply.  I think the way of JBrowse set up works for me now except C. elegans. Could you, with respect, please do the same for C. elegans. This will be a great help to my work.

From me:
Hi Bowen,

I've implemented the dropdown menu the same way for C. elegans on the main WormBase site now too.  To see it, you might have to clear your cache in your browser for WormBase since web browsers tend to be very aggressive about cache JBrowse related files.  Please let me know if this works for you.
