### ISSUE TITLE
Hello, I am trying to find information on C.Elegan...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7002]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello, I am trying to find information on C.Elegans. specifically Uncoordinated mutation (n494),(e55) and (e53). Can you help me

**Reported by:** Tawa************ (twil************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/#012-346-5">https://wormbase.org/#012-346-5</a>
**Browser:** Chrome 72.0.3626.121

**Comment by raymond91125** [comment]
On WormBase pages, in the top right text search box, If you search "for a variation" with an allele name, you can reach the Variation report page, e.g. searching "n494", you get <https://wormbase.org/species/c_elegans/variation/WBVar00089548#012345678--10><https://wormbase.org/species/c_elegans/variation/WBVar00089548#012345678--10>.

Cheers,

Raymond

On 21/03/2019 1:42 PM, no-reply@wormbase.org<mailto:no-reply@wormbase.org> wrote:
offline chat Hello, I am trying to find information on C.Elegans. specifically Uncoordinated mutation (n494),(e55) and (e53). Can you help me

Submitted From:
  https://wormbase.org/#012-346-5 https://wormbase.org/#012-346-5<http://www.wormbase.org/https://wormbase.org/#012-346-5>

This issue has been assigned ticket number: #7002. Follow progress on our issue tracker<https://github.com/WormBase/website/issues/7002>.

Reported by: Tawana Willliams (twilli16@ggc.edu<mailto:twilli16@ggc.edu>)
21 Mar 19 20:42


This question was reported via the web interface at wormbase.org. You can also email us<mailto:help@wormbase.org> directly.

--
--
You received this message because you are subscribed to the "WormBase: help" group.
To post to this group, send email to help@wormbase.org<mailto:help@wormbase.org>
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en

---
You received this message because you are subscribed to the Google Groups "WormBase: help" group.
To unsubscribe from this group and stop receiving emails from it, send an email to help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>.


--
__
Raymond Lee
raymond@caltech.edu<mailto:raymond@caltech.edu>
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687


--
--
You received this message because you are subscribed to the "WormBase: help" group.
To post to this group, send email to help@wormbase.org<mailto:help@wormbase.org>
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en

---
You received this message because you are subscribed to the Google Groups "WormBase: help" group.
To unsubscribe from this group and stop receiving emails from it, send an email to help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>.
