### ISSUE TITLE
  For getting expected acd-5 promoter r...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7003]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;For getting expected acd-5 promoter region, we used D1037 cosmid and N2 lysis template with 2 different primers.<br/>However, we can get 3.2kb even that we expected 5kb length promoter.<br/>5kb sequence came from wormbase data base, but when we check the sequence it was little bit different. <br/>So please check the sequence of acd-5 in your database again for other researchers.<br/>I attach my primer information that i used for sequencing of acd-5 promoter region.<br/>This is expected acd-5 promoter site that we used, <br/>I:3662000..3666999<br/>This is primers that we used for confirming sequence.<br/>1st forward primer :  gtcgcatcctggaacaactc<br/>2nd forward primer : ttgaaagaggaaacgaggcgac<br/>3rd reverse primer :  ggcatcttcatcatctcgttcg<br/>Thank you</p>

**Reported by:** Kyeo*********** (kmmo****************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36

**Comment by chris-grove** [comment]
My email to user:
"""
Thank you for reporting the potential discrepancy.

It seems there are a few possible issues here:

1) Checking your primers on wild type (N2) genomic sequence, I predict a 5,158 nt amplicon using primers 1 (FW) and 3 (RV) (see attached sequence) and a 3,672 nt amplicon using primers 2 (FW) and 3 (RV) (see attached sequence). Could you clarify the size of the amplicon you acquired using each pair of primers? Also, if you have sequenced each amplicon, could you provide the sequence of each?

2) It seems that there is about 2kb of repeats within this region with a common 26 nt repeat like this:

tttttaggtgaatggttagagtcata

or similar. The reason I mention it is that it is possible that amplification, sequencing, or both could be affected by such a repeat region and, as such, it could be that our standard genome reference sequence is slightly off (due to repeat complications) and/or that your PCR and/or sequencing is slightly off.

If you could send your sequencing results, we can discuss further with our sequence curators to see what might be at issue here.
"""

**Comment by chris-grove** [comment]
From user:
"""
Thanks for your respond

I send you some of my sequence files that i used,

I marked primers, each sequencing results and missing part that i mentioned (The repeat one).

So, please check this files and tell me the results.

Best regard
"""

**Comment by chris-grove** [comment]
My response:
"""
 Hi Kyeong,

Thanks for the sequences. BLASTing your "Repeat confirm results" sequence against the genome confirms that your sequence matches the region except that it doesn't include most of the repeat region (except for two repeats at ~52bp at one end):

<img width="1188" alt="Screenshot 2019-03-31 13 20 26" src="https://user-images.githubusercontent.com/611382/55292421-d7231800-53b8-11e9-8c73-5a63b5158a44.png">


Our sequence curators will have a look and get back to you.

Thanks
"""

**Comment by gw3** [comment]
Hi Kyeong,

The region between acd-5 and the next gene smp-2 is larger in the VC2010 
strain assembly than in the N2 assembly.
It is about 4.7 Kb in N2 and about 9.2 Kb in VC2010.
So either this region is incorrectly assembled in N2, or possibly the 
repeat region has different lengths in N2 clones with different ancestry.

I think that it would be sensible to concentrate on the region after the 
repeat, that is the region that starts with the sequence:

taataactcataataatgatcaacatatcagtcaaaccttagaggtttccct

This appears to have the trancription start sites.

Gary

**Comment by gw3** [comment]
Hi Kyeong,

The region between acd-5 and the next gene smp-2 is larger in the VC2010 strain assembly than in the N2 assembly.
It is about 4.7 Kb in N2 and about 9.2 Kb in VC2010.
So either this region is incorrectly assembled in N2, or possibly the repeat region has different lengths in N2 clones with different ancestry.

I think that it would be sensible to concentrate on the region after the repeat, that is the region that starts with the sequence:

taataactcataataatgatcaacatatcagtcaaaccttagaggtttccct

This appears to have the trancription start sites.

Gary
