### ISSUE TITLE
Using the new Genome Browser, how can I select a f...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7040]
*Help Desk query collected when no chat operators were online. Follow up required.*

Using the new Genome Browser, how can I select a fragment and dump selection as FASTA?

**Reported by:** Alva** (rank**********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/tools/genome/jbrowse/?data=data/c_elegans_PRJNA13758&amp;loc=X:15491181..15510160&amp;tracks=Curated_Genes,Classical_alleles,YACs_Fosmids_Cosmids&amp;highlight=X:15499757..15502894">https://wormbase.org/tools/genome/jbrowse/?data=data/c_elegans_PRJNA13758&amp;loc=X:15491181..15510160&amp;tracks=Curated_Genes,Classical_alleles,YACs_Fosmids_Cosmids&amp;highlight=X:15499757..15502894</a>
**Browser:** Chrome 73.0.3683.86

**Comment by raymond91125** [comment]
Hi Alvaro,

Let us know if this does not address your question. <http://blog.wormbase.org/2019/03/18/getting-dna-sequence-from-jbrowse/><http://blog.wormbase.org/2019/03/18/getting-dna-sequence-from-jbrowse/>.

Cheers,

Raymond

On 10/04/2019 3:35 PM, no-reply@wormbase.org<mailto:no-reply@wormbase.org> wrote:
offline chat Using the new Genome Browser, how can I select a fragment and dump selection as FASTA?

Submitted From:
  https://wormbase.org/tools/genome/jbrowse/?data=data/c_elegans_PRJNA13758&loc=X:15491181..15510160&tracks=Curated_Genes,Classical_alleles,YACs_Fosmids_Cosmids&highlight=X:15499757..15502894 https://wormbase.org/tools/genome/jbrowse/?data=data/c_elegans_PRJNA13758&loc=X:15491181..15510160&tracks=Curated_Genes,Classical_alleles,YACs_Fosmids_Cosmids&highlight=X:15499757..15502894<http://www.wormbase.org/https://wormbase.org/tools/genome/jbrowse/?data=data%2Fc_elegans_PRJNA13758&loc=X%3A15491181..15510160&tracks=Curated_Genes%2CClassical_alleles%2CYACs_Fosmids_Cosmids&highlight=X%3A15499757..15502894>

This issue has been assigned ticket number: #7040. Follow progress on our issue tracker<https://github.com/WormBase/website/issues/7040>.

Reported by: Alvaro (rankinlabtech@psych.ubc.ca<mailto:rankinlabtech@psych.ubc.ca>)
10 Apr 19 22:35


This question was reported via the web interface at wormbase.org. You can also email us<mailto:help@wormbase.org> directly.

--
--
You received this message because you are subscribed to the "WormBase: help" group.
To post to this group, send email to help@wormbase.org<mailto:help@wormbase.org>
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en

---
You received this message because you are subscribed to the Google Groups "WormBase: help" group.
To unsubscribe from this group and stop receiving emails from it, send an email to help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>.


--
__
Raymond Lee
raymond@caltech.edu<mailto:raymond@caltech.edu>
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
