### ISSUE TITLE
  I'm trying to search for all genes in...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7041]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I'm trying to search for all genes in C. elegans whose "Type" is "snRNA" (as listed in the Overview for the gene once I click on the gene). I can't find these by just searching "snRNA" since the search doesn't seem to include look through the text in the "Type". <br/>Is there a way to search for genes with a specific "Type"? <br/>Thank you for your help!</p>

**Reported by:** Elis*********** (eame****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0

**Comment by chris-grove** [comment]
My email to user:
"""
There are two ways of querying out this list of C. elegans snRNA genes:

1) WormMine: From the WormMine home page:

http://intermine.wormbase.org/tools/wormmine/begin.do

there are a series of template queries grouped into tabs in the middle of the page. Select the "GENOMICS" tab (visible by default" and click on the template query called "Transcript Type, Species --> Genes". On the subsequent page, select your species as "Caenorhabditis elegans" and your transcript type ("Method") as "snRNA" and click on "Show Results". That should return a list of 124 genes. Note that there are also "snlRNA" genes (small nuclear-like RNA) which could be considered a subclass of snRNA; choosing "snlRNA" instead of "snRNA" returns an additional 5 genes (129 genes total). You can import the following XML query (using the "Import query from XML" option on the "QueryBuilder" tab of WormMine):

`<query name="" model="genomic" view="Gene.primaryIdentifier Gene.symbol Gene.secondaryIdentifier Gene.transcripts.symbol Gene.transcripts.method Gene.organism.name" longDescription="Return all genes of a particular transcript type from a given species" sortOrder="Gene.primaryIdentifier asc" constraintLogic="A and (B or C)">
  <constraint path="Gene.organism.name" code="A" op="=" value="Caenorhabditis elegans"/>
  <constraint path="Gene.transcripts.method" code="B" op="=" value="snRNA"/>
  <constraint path="Gene.transcripts.method" code="C" op="=" value="snlRNA"/>
</query>`

Note that there is also an "snRNA" WormMine class that you can query for all C. elegans snRNA genes:

`<query name="" model="genomic" view="SnRNA.gene.primaryIdentifier SnRNA.gene.secondaryIdentifier SnRNA.gene.symbol SnRNA.gene.transcripts.method SnRNA.gene.biotype" longDescription="" sortOrder="SnRNA.gene.primaryIdentifier asc">
  <constraint path="SnRNA.organism.name" op="=" value="Caenorhabditis elegans"/>
</query>`

2) WormBase ParaSite BioMart:

https://parasite.wormbase.org/biomart/martview

Here is a URL for a query that gets you the same 129 genes:

`http://parasite.wormbase.org/biomart/martview?VIRTUALSCHEMANAME=parasite_mart&ATTRIBUTES=wbps_gene.default.feature_page.wbps_gene_id|wbps_gene.default.feature_page.external_gene_id|wbps_gene.default.feature_page.gene_biotype&FILTERS=wbps_gene.default.naive_filters.species_id_1010."elegaprjna13758"|wbps_gene.default.naive_filters.biotype."snRNA"&VISIBLEPANEL=resultspanel`

Let us know if you have any further questions.
"""

**Comment by chris-grove** [comment]
User is happy

**Comment by chris-grove** [comment]
Response from user:
"""
sorry to bother you again, but I have another question. I was able to find and download a list of snRNAs and snlRNAs based on your instructions, but I noticed that none of the genes are annotated as "U1", "U2-1", etc. Do you know if any of the worm gene databases annotate the snRNAs with what U snRNA they are (e.g. annotated as "U4 snRNA" instead of just "snRNA")?

I was able to confirm that the snRNAs list I downloaded does include U snRNAs by comparing the sequences to those listed in the Thomas et al 1990 paper, but I'm hoping there's a smarter way to assign which is which U snRNA!

Thank you again for your help!
"""

My response:
"""
 I think our annotations of each snRNA as U1, U2, etc. are a bit sparse, but the ones I can find appear to have that type of name in the "Other names" field of the gene, for example:

https://wormbase.org/species/c_elegans/gene/WBGene00006315#0gd96e--10

You can take the list of 129 gene IDs and paste it into our SimpleMine tool:

https://wormbase.org/tools/mine/simplemine.cgi

and select the following output attributes:

WormBase Gene ID
Public Name
WormBase Status
Sequence Name
Other Name
Transcript
Concise Description
Automated Description

and you will get a table with as much information like this as we have available (see attached Excel spreadsheet). You can find info in concise description (at least for the gene sup-6) and in the Other Name column.

You may also want to see this section of the WormBook chapter on non-coding RNAs:

http://www.wormbook.org/chapters/www_noncodingRNA/noncodingRNA.html#d0e391

and review the referenced publications.

I hope that helps.
"""
