### ISSUE TITLE
  I was hoping to find snip-SNPs from t...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7043]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I was hoping to find snip-SNPs from this paper but the link provided in the paper is broken. I really like this format of the browsing the genome for snip-SNPs. https://www.nature.com/articles/ng0601_160 <br/>Found the data in an old filemaker format on this site. I was wondering if this information is on the wormbase website?<br/>http://jorgensen.biology.utah.edu/SNPs/</p><p>What were you doing? <br />&nbsp;&nbsp;RFLP mapping</p>

**Reported by:** sneh******** (sneh*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36

**Comment by chris-grove** [comment]
My email to user:
"""
I'm not sure exactly which browsing format you are referring to. I don't have Filemaker installed so I'm also not sure the content of that file. You can find the page for this publication at WormBase here:

https://wormbase.org/resources/paper/WBPaper00004703#03--10

There are 6,339 variations associated with the paper which can be imported into WormMine:

http://intermine.wormbase.org/tools/wormmine/begin.do

I imported them all into WormMine to generate a table of pertinent information that is available in WormMine for each variation (see attached Excel spreadsheet). Let us know if you're still in need of something else, and if so what exactly is the information that you are looking for.
"""

**Comment by chris-grove** [comment]
Response from user:
"""
Thanks for your prompt response and the SNPs table. I am trying to narrow down QTLs in the lab, and I need reliable SNPs with location information along the chromosome. The data was I was referring to had this type of information. It has primers for amplifying the allele and also the restriction enzyme to use. I don't have to go about designing primers etc., therefore, saves a lot of time especially because Wicks et al. did that already. I downloaded the database (in an ancient version of FileMaker format) and tried a couple of ways to get into an excel file or at least a modern FileMaker format, but it didn't work. It loads only 10 SNPs on filemaker6. I have attached it here for you to see. I am hoping some version of this is on wormbase, and I need to query the information. If it is not too much trouble, could you at least send me back the table with chromosomal location information? I will use that information to design primers myself. 
"""

**Comment by chris-grove** [comment]
My response to user:
"""
OK, I see. Unfortunately, WormMine doesn't store variation locations right now (other than chromosome location by proxy to its association to a gene). This information can be gleaned from individual WormBase variation pages, like:

https://wormbase.org/species/c_elegans/variation/WBVar00000970#0569--10

but if you're looking for a faster option, the best other option I can think of is to download the C. elegans GFF3 file:

ftp://ftp.wormbase.org/pub/wormbase/releases/current-production-release/species/c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS269.annotations.gff3.gz

unzip the file, and then perform a grep operation on the file using your list of 6,339 variation IDs to pull out all GFF3 location information for each variation. This can be done by creating a file of a simple list of the WB Variation IDs, let's call it "Wicks_WB_Var_IDs.txt" (note grep is sensitive to newline character types, so copying and pasting the list into a text document from Excel might cause problems; I've attached my version of the file which I've confirmed works) and then running the command:

grep -f Wicks_WB_Var_IDs.txt c_elegans.PRJNA13758.WS269.annotations.gff3 > Wicks_SNPs_locations.gff3

You could also call the output file "Wicks_SNPs_locations.txt" instead of "Wicks_SNPs_locations.gff3", it's up to you. This will take a while to run (checking for each of 6,339 IDs in the 28,828,875 lines of the GFF3 file), but then you should be able to open the file in Excel or another spreadsheet editor to see the chromosomal coordinates for each variation; or you can use a script to parse the GFF3.

I'm running the command on my computer now, but as I said it is taking a while and so I probably won't be able to send you the results before the end of the day; I'll send the results on Monday. If you need the results sooner you can run it on your machine.

Let me know if you need something else.
"""
