### ISSUE TITLE
  Dear Mr/Ms, We have recently publishe...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7048]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Dear Mr/Ms,<br/>We have recently published a paper:<br/>PLoS Genet. 2019 Feb 26;15(2):e1007981. doi: 10.1371/journal.pgen.1007981.<br/>There, we describe the C.elegans Integrator complex and name some genes (and in some cases re-name others):<br/>INTS-1 (C06A5.1),<br/>INTS-2 (ZC376.6),<br/>INTS-3 (Y92H12A.4),<br/>INTS-4 (W04A4.5),<br/>INTS-5 (Y51A2D.7),<br/>INTS-6 (F08B4.1),<br/>INTS-7 (D1043.1),<br/>INTS-8 (Y48G10A.4),<br/>INTS-9 (F19F10.12),<br/>INTS-11 (F10B5.8)<br/>and<br/>INTS-13 (R02D3.4)<br/>Please, could you let me know how to proceed to include those names and the information in wormbase?<br/>Many thanks!<br/>Juan</p>

**Reported by:** Juan******** (juan**********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0

**Comment by Paul-Davis** [comment]
Dear Juan,

Thank you for getting in contact, I am ccing the gene nomenclature list 
so that we can get this into WormBase.

Currently we have 1,2,4,5,7,8 in the database that will be visible in 
WS271 release of WormBase.

The additional names:

ints-3 (Y92H12A.4),
ints-6 (F08B4.1), - currently named dic-1
ints-9 (F19F10.12),
ints-11 (F10B5.8),
ints-13 (R02D3.4),

Will be reviewed and someone will get back to you if there are any issues.

Paul

PS. It is usual to email the genenames@wormbase.org list prior to 
publication in case there are any names held confidentially with the 
gene names committee to avoid any conflict/confusion.


On 12/04/2019 11:45, no-reply@wormbase.org wrote:
> Content Correction
>
>   Dear Mr/Ms,
> We have recently published a paper:
> PLoS Genet. 2019 Feb 26;15(2):e1007981. doi: 10.1371/journal.pgen.1007981.
> There, we describe the C.elegans Integrator complex and name some 
> genes (and in some cases re-name others):
> INTS-1 (C06A5.1),
> INTS-2 (ZC376.6),
> INTS-3 (Y92H12A.4),
> INTS-4 (W04A4.5),
> INTS-5 (Y51A2D.7),
> INTS-6 (F08B4.1),
> INTS-7 (D1043.1),
> INTS-8 (Y48G10A.4),
> INTS-9 (F19F10.12),
> INTS-11 (F10B5.8)
> and
> INTS-13 (R02D3.4)
> Please, could you let me know how to proceed to include those names 
> and the information in wormbase?
> Many thanks!
> Juan
>
> Submitted From:
>   support /tools/support <http://www.wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #7048. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/7048>.
>
> Reported by: Juan Cabello (juan.cabello@riojasalud.es)
> 12 Apr 19 10:45
>
> Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by gw3** [comment]
Hi Mike,

The structure of all genes requesting a gene name is checked by a gene 
sequence curator.
This message has no other effect on the process of assigning a gene name.

The structure of Y92H12A.4 looks OK.
The structure of F08B4.1 looks OK.
The structure of F19F10.12 looks OK.
The structure of F10B5.8 looks OK.
The structure of R02D3.4 looks OK.

(The other loci have already been checked in an earlier email.)

Gary Williams
WormBase

**Comment by vanaukenk** [comment]
I've added all of the appropriate gene-paper connections in the paper editor.

**Comment by draciti** [comment]
is this good to close?

**Comment by Paul-Davis** [comment]
yes good to close @draciti
