### ISSUE TITLE
I couldn't figure out how to download genomic sequ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7071]
*Help Desk query collected when no chat operators were online. Follow up required.*

I couldn't figure out how to download genomic sequence, so I went back to WS150 and did it the old way. Is there an updated protocol for the current genome browser?

**Reported by:** Erin***** (e.cr**********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/#012-34-5">https://wormbase.org/#012-34-5</a>
**Browser:** Safari 12.1

**Comment by scottcain** [comment]
Replied to the user:

Since we've been getting this question a lot, I wrote a blog post about it:

http://blog.wormbase.org/2019/03/18/getting-dna-sequence-from-jbrowse/

I would just add a few comments directly about your question though: first, GBrowse (the old genome browser) is still available on the website if you'd rather use it and you don't have to go all the way back to WS150(!) as that is a pretty old data set and an old assembly.  But the good news is, I think JBrowse gives you more ways to download sequence that you might find more useful that GBrowse anyway.

Please let me know if you have any questions,
Scott
