### ISSUE TITLE
How to retrieve the promoter of a gene from wormba...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7083]
*Help Desk query collected when no chat operators were online. Follow up required.*

How to retrieve the promoter of a gene from wormbase and how to decide to what length the sequence should be taken starting from Exon 1 of the gene to get the full promoter. One more query is what is the meaning of Reference sequence (DNA).

**Reported by:** Bika** (bika*****************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/species/c_elegans/gene/WBGene00006654#01f-9g4deac-10">https://www.wormbase.org/species/c_elegans/gene/WBGene00006654#01f-9g4deac-10</a>
**Browser:** Firefox 66.0

**Comment by chris-grove** [comment]
My email to user:
"""
Here's a screen capture video that demonstrates a few ways to get the promoter sequence for a gene:

https://www.dropbox.com/s/nv46vmc01lqm99j/Finding_the_vha-6_promoter_sequence_May_15_2018.mov?dl=0

There are some minor differences in user interface since this video was made, but it should be straightforward to follow. You may also be interested in our intergenic seqeuences file on our FTP site:

ftp://ftp.wormbase.org/pub/wormbase/releases/current-production-release/species/c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS269.intergenic_sequences.fa.gz

This file lists all sequences between two adjacent genes. Note that this file name will change with the next release of WormBase (WS270) but the same file type can always be found in this directory:

ftp://ftp.wormbase.org/pub/wormbase/releases/current-production-release/species/c_elegans/PRJNA13758/

As for how to decide what length of sequence should be taken, that isn't quite so straightforward as many factors can be taken into account. You can look at transcription start site (TSS) tracks in JBrowse or limits of EST sequence evidence for example:

https://www.wormbase.org/tools/genome/jbrowse-simple/?data=data%2Fc_elegans_PRJNA13758&loc=X%3A11762401..11782500&tracks=Curated_Genes%2CTSS%20(Chen)%20Reverse%2CTSS%20(Saito)%20Reverse%2CTSS%20(Kruesi)%20Reverse%2CESTs%20(best)&highlight=

You can also look at possible locations of RNA Polymerase II (several tracks available in JBrowse, but I couldn't see anything informative for ttx-3).

Let us know if you have additional questions.
"""
