### ISSUE TITLE
  Download the sequence for specific ge...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7089]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Download the sequence for specific genomic coordinates</p>

**Reported by:** Tzit********** (tzit*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

**Comment by raymond91125** [comment]
This blog post may be of help <http://blog.wormbase.org/2019/03/18/getting-dna-sequence-from-jbrowse/><http://blog.wormbase.org/2019/03/18/getting-dna-sequence-from-jbrowse/>.

Raymond

On 03/05/2019 11:02 AM, no-reply@wormbase.org<mailto:no-reply@wormbase.org> wrote:
How Do I ...?

  Download the sequence for specific genomic coordinates

Submitted From:
  support /tools/support<http://www.wormbase.org//tools/support>

This issue has been assigned ticket number: #7089. Follow progress on our issue tracker<https://github.com/WormBase/website/issues/7089>.

Reported by: Tzitziki Lemus (tzitzikilemus@gmail.com<mailto:tzitzikilemus@gmail.com>)
03 May 19 18:02

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

This question was reported via the web interface at wormbase.org. You can also email us<mailto:help@wormbase.org> directly.

--
--
You received this message because you are subscribed to the "WormBase: help" group.
To post to this group, send email to help@wormbase.org<mailto:help@wormbase.org>
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en

---
You received this message because you are subscribed to the Google Groups "WormBase: help" group.
To unsubscribe from this group and stop receiving emails from it, send an email to help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>.


--
__
Raymond Lee
raymond@caltech.edu<mailto:raymond@caltech.edu>
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
