### ISSUE TITLE
  I need snp names for variations that ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7090]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I need snp names for variations that I originally found on the Waterston site at University of Washington (no longer available). I know the specific location of the snp's, but when I scan in the genome browser, they don't seem to be there.I'm assuming that one is snp_F41D9[3], since I know that it is an F41D9 snp at LGX: 8391286, and it maps between F41D9[2] and F41D9[4]. The other is a K07E3 snp at 8088135. </p><p>What were you doing? <br />&nbsp;&nbsp;Searching for snp's using the genome browser</p>

**Reported by:** Mind******************* (mose************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36

**Comment by scottcain** [comment]
My response to the user:

Just to make sure I understand: you're looking for two C. elegans SNPs. One is at about X:8391286 and the other is at about X:8088135.

I believe the first match for the first one is gk287340 at X:8391292:

https://staging.wormbase.org/species/c_elegans/variation/WBVar00510583

For the second one, there are two that are about the same distance from the initial coordinate:
1.  WBVar00081078 at X:8088185:
https://staging.wormbase.org/species/c_elegans/variation/WBVar00081078

2. WBVar01884644 at X:8088083:
https://staging.wormbase.org/species/c_elegans/variation/WBVar01884644

I would guess that the first one is more likely to be what you're looking for, particularly because the coordinate could be a typo off of the exact coordinate you were looking for.

If this isn't what you were looking for, please let us know,
Scott

**Comment by scottcain** [comment]
Response from the user:

Hi Scott,
Thanks for your help. The upstream snp checks out. Restriction site matches, alternative name matches, and it was a Hawaiian snp--not sure how the numbering got messed up. 

Downstream still not correct. Restriction site change not the same and it does not appear to be a Hawaiian snp. Now knowing that the numbering I have could be a bit off, I'll keep looking.

**Comment by scottcain** [comment]
Next response:

I went back to the source GFF for the N2 strain looked for Hawaiian variations within a few hundred bases of your initial coordinate, and found these:

```X    Variation_project_Polymorphism    deletion    8088071    8088100    .    +.    variation=WBVar01981044;public_name=WBVar01981044;other_name=cewivar00707127;strain=CB4856;polymorphism=1;consequence=Intron
X    Variation_project_Polymorphism    SNP    8088185    8088185    .    +    .variation=WBVar00081078;public_name=WBVar00081078;other_name=snp_K07E3[1],haw105438,cewivar00274858;strain=CB4856,JU263,JU300,JU322,JU397,JU533,JU642;polymorphism=1;substitution=G/A;consequence=Silent
X    Variation_project_Polymorphism    SNP    808963    808963    .    +    .variation=WBVar00074555;public_name=WBVar00074555;other_name=haw98915,cewivar00268285;strain=CB4856,ED3017,ED3021,ED3052,JU258,JU322,JU533,JU775,JU1171,MY2,MY14,MY16;polymorphism=1;substitution=G/A;consequence=Intron
X    Variation_project_Polymorphism    SNP    808974    808974    .    +    .variation=WBVar00074556;public_name=WBVar00074556;other_name=haw98916,cewivar00268286;strain=CB4856,ED3021,ED3052,MY16;polymorphism=1;substitution=T/C;consequence=Intron
X    Variation_project_Polymorphism    insertion_site    8089048    8089048    .    +.    variation=WBVar01927523;public_name=WBVar01927523;other_name=cewivar00646191;strain=AB1,AB3,CB4853,CB4854,CB4856,ED3017,ED3021,ED3040,ED3042,ED3049,ED3052,ED3057,ED3072,GXW1,JU258,JU263,JU300,JU322,JU360,JU397,JU533,JU642,JU775,JU1088,JU1171,JU1400,JU1401,JU1652,KR314,LKC34,MY1,MY2,MY14,PX174;polymorphism=1;insertion=AG```

Do any of these help?

**Comment by scottcain** [comment]
User figured it out.
