### ISSUE TITLE
how do i get the sequence for a highlighted part o...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7094]
*Help Desk query collected when no chat operators were online. Follow up required.*

how do i get the sequence for a highlighted part of the genome

**Reported by:** Mich**** (mich************************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/tools/genome/jbrowse-simple/?tracks=Curated_Genes,Classical_alleles,YACs_Fosmids_Cosmids&amp;loc=IV:10457172..10462423&amp;data=data/c_elegans_PRJNA13758&amp;highlight=IV:10457926..10462010">https://www.wormbase.org/tools/genome/jbrowse-simple/?tracks=Curated_Genes,Classical_alleles,YACs_Fosmids_Cosmids&amp;loc=IV:10457172..10462423&amp;data=data/c_elegans_PRJNA13758&amp;highlight=IV:10457926..10462010</a>
**Browser:** Chrome 74.0.3729.131

**Comment by scottcain** [comment]
I wrote this blog post about obtaining sequence from JBrowse:

http://blog.wormbase.org/2019/03/18/getting-dna-sequence-from-jbrowse/

What this document doesn't explicitly address is obtaining sequence from highlighted regions (because I didn't really think people used that functionality).  If you read the section in the blog post about "Getting sequence from a specific range" and do what it says, the resulting download dialog will have "Highlighted region" as an option under the "Region to save" selector.

Please let me know if this doesn't happen or you need more help,
Scott
