### ISSUE TITLE
  Hi, How do I find a list of all the n...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7108]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi,<br/>How do I find a list of all the nematodes? I found this list (link below) but, some of the species are not nematodes in this. Do you have any data which gives me species names of all the nematodes in wormbase?<br/>https://www.wormbase.org/species/all#135--10</p><p>What were you doing? <br />&nbsp;&nbsp;Trying to get the names of all the nematodes (only nematodes) genome in wormbase. </p>

**Reported by:** Swad** (ssin******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36

**Comment by raymond91125** [comment]
https://parasite.wormbase.org/species.html

Raymond

On 08/05/2019 11:36 AM, no-reply@wormbase.org<mailto:no-reply@wormbase.org> wrote:
How Do I ...?

  Hi,
How do I find a list of all the nematodes? I found this list (link below) but, some of the species are not nematodes in this. Do you have any data which gives me species names of all the nematodes in wormbase?
https://www.wormbase.org/species/all#135--10

What were you doing?
  Trying to get the names of all the nematodes (only nematodes) genome in wormbase.

Submitted From:
  support /tools/support<http://www.wormbase.org//tools/support>

This issue has been assigned ticket number: #7108. Follow progress on our issue tracker<https://github.com/WormBase/website/issues/7108>.

Reported by: Swadha (ssingh235@ucmerced.edu<mailto:ssingh235@ucmerced.edu>)
08 May 19 18:36

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36

This question was reported via the web interface at wormbase.org. You can also email us<mailto:help@wormbase.org> directly.

--
--
You received this message because you are subscribed to the "WormBase: help" group.
To post to this group, send email to help@wormbase.org<mailto:help@wormbase.org>
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en

---
You received this message because you are subscribed to the Google Groups "WormBase: help" group.
To unsubscribe from this group and stop receiving emails from it, send an email to help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>.


--
__
Raymond Lee
raymond@caltech.edu<mailto:raymond@caltech.edu>
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
