### ISSUE TITLE
On Chrome, JBrowse images in gene page Location widget not always displaying gene model

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#7109]
On the Chrome browser, on several gene pages the Location widget is not showing the gene model for the respective gene:

https://wormbase.org/species/c_elegans/gene/WBGene00013215#09--10
https://wormbase.org/species/c_elegans/gene/WBGene00000830#09--10
https://wormbase.org/species/c_elegans/gene/WBGene00000831#09--10
https://wormbase.org/species/c_elegans/gene/WBGene00013220#09--10

<img width="1105" alt="Screenshot 2019-05-08 15 19 07" src="https://user-images.githubusercontent.com/611382/57402158-acd92d00-71a4-11e9-84e1-0e12c9cb3829.png">

This doesn't appear to be an issue on Firefox or Safari.

**Comment by scottcain** [comment]
@chris-grove Thanks for reporting this.  For me the behavior is somewhat different and consistent across browsers: it draws the image but makes the Curated Genes track ridicoulously tall, but does put the gene model at the top of the image.  It only does this for some gene models though, which is very strange.  Ordinarily, if I saw that I would guess that just of screen , there is a gene with many transcripts and JBrowse is drawing it like that in anticipation that you'd be scrolling and need the extra real estate, but in each example you posted, that's not the case (that is, there is not multi-transcript gene nearby).

I'll look into it.

**Comment by scottcain** [comment]
This problem is almost certainly related to this bug:

https://github.com/gmod/jbrowse/issues/1190

which has been fixed in more recent versions of JBrowse, and explains why it only happens some of the time.  I was planning on upgrading for the WS271 release anyway as there are several other things that I'd like to address, so this just adds to the list of reasons to do it.

I'll leave this bug open until I do the upgrade.

**Comment by chris-grove** [comment]
@scottcain 
OK, thanks for looking into it!

**Comment by scottcain** [comment]
I've installed the newest version of jbrowse (1.16.4) on staging which has fixed this issue for the examples you provided and hopefully generally.  It's difficult to test in any robust way since it happens in an unpredictable way, but I'm hopeful that this is a complete fix based on what the JBrowse devs said.

Closing...

**Comment by chris-grove** [comment]
Thanks @scottcain !
