### ISSUE TITLE
  I'm looking for poly(A) RNAs (includi...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7111]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;I'm looking for poly(A) RNAs (including all non-coding RNAs like miRNAs) sequences in wormbase in the current version. If such type of information available in the database then how should I retrieve? Thanks.</p><p>What were you doing? <br />&nbsp;&nbsp;Looking for miRNA transcripts having Poly(A). </p>

**Reported by:** Gane********** (gane*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.108 Safari/537.36

**Comment by chris-grove** [comment]
@gw3 's email to user:
"""
We don't have Poly(A) sites associated with non-coding RNA genes in our database, so I wrote a little program to find non-coding RNA genes which overlapped (or were within 100 bases on the 3' end) with a known Poly(A) site.

An overlap between a gene and a known poly(A) site does not, of course, necessarily mean that the gene's transcript does have a poly(A) tail.
The results files are attached.

There are no scRNA gene which overlap a known poly(A) site.
I did not attempt to find any piRNA genes overlapping poly(A) sites because they are very small and there are tens of thousands of them.

I hope this is useful.
"""
