### ISSUE TITLE
Hello, I was searching for different genes and end...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7118]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello, I was searching for different genes and ended up with this message (and no results): http://wormbase-search-ws270.us-east-1.elasticbeanstalk.com/integration/search?type=gene&amp;page=1&amp;query=daf-9 failed with 502. Hope it helps to fix bugs

**Reported by:** Mart** (dmjo***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/search/gene/daf-9">https://wormbase.org/search/gene/daf-9</a>
**Browser:** Chrome 72.0.3626.121

**Comment by sibyl229** [comment]
I replied to the user:

> Sorry about the problem, and thanks for writing to us about it. I think it’s a temporary problem that happened when we were deploying a fix to the server. It should have recovered now. If not, please let me know.


The problem was probably due to me turning of the old instance too early in a [blue/gene deployment](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features.CNAMESwap.html), before the DNS record expires. So for a short while, the domain name continued to resolve to the IP address of the old instance that was turned off.
