### ISSUE TITLE
  Hi, I would like to download the sequ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7128]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi,<br/>I would like to download the sequences, in FASTA format and “spliced” for different lists of genes (almost 1000 per list). Is there a way to download all of them? Thank you very much, best<br/>Piergiuseppe</p>

**Reported by:** Pier**************** (pier***************************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (iPhone; CPU iPhone OS 12_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Mobile/15E148 Safari/604.1

**Comment by raymond91125** [comment]
You might want to try using ParaSite BioMart <https://parasite.wormbase.org/biomart/martview><https://parasite.wormbase.org/biomart/martview>.

A sample query can be found here <https://bit.ly/2WSXqyd><https://bit.ly/2WSXqyd>.

Cheers,

Raymond

On 20/05/2019 4:12 AM, no-reply@wormbase.org<mailto:no-reply@wormbase.org> wrote:
How Do I ...?

  Hi,
I would like to download the sequences, in FASTA format and â€œsplicedâ€ for different lists of genes (almost 1000 per list). Is there a way to download all of them? Thank you very much, best
Piergiuseppe

Submitted From:
  support /tools/support<http://wormbase.org//tools/support>

This issue has been assigned ticket number: #7128. Follow progress on our issue tracker<https://github.com/WormBase/website/issues/7128>.

Reported by: Piergiuseppe Quarato (piergiuseppe.quarato@pasteur.fr<mailto:piergiuseppe.quarato@pasteur.fr>)
20 May 19 11:12

Mozilla/5.0 (iPhone; CPU iPhone OS 12_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Mobile/15E148 Safari/604.1

This question was reported via the web interface at wormbase.org. You can also email us<mailto:help@wormbase.org> directly.

--
--
You received this message because you are subscribed to the "WormBase: help" group.
To post to this group, send email to help@wormbase.org<mailto:help@wormbase.org>
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en

---
To unsubscribe from this group and stop receiving emails from it, send an email to help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>.


--
__
Raymond Lee
raymond@caltech.edu<mailto:raymond@caltech.edu>
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
