### ISSUE TITLE
Improve visibility of gene names in JBrowse image on PCR product pages

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#7151]
I often need to check PCR product object pages to make sure that it cleanly overlaps a particular gene. However, when I open the Location widget on these pages, more often than not, the name of the gene is very difficult, if not impossible, to read clearly from the static JBrowse image. For example:

https://wormbase.org/species/all/pcr_oligo/sjj_T04D1.4#1--10

<img width="910" alt="Screenshot 2019-05-31 15 05 08" src="https://user-images.githubusercontent.com/611382/58728726-87130280-83b5-11e9-9b24-7b02525d471c.png">

https://wormbase.org/species/all/pcr_oligo/sjj_C29H12.5#1--10

<img width="928" alt="Screenshot 2019-05-31 15 06 09" src="https://user-images.githubusercontent.com/611382/58728781-a447d100-83b5-11e9-8cad-db6742e1d99b.png">

https://wormbase.org/species/all/pcr_oligo/sjj_F02A9.4#1--10

<img width="919" alt="Screenshot 2019-05-31 15 07 13" src="https://user-images.githubusercontent.com/611382/58728844-cc373480-83b5-11e9-8322-48334c1dde75.png">

Could we make the gene names more visible? This appears to particularly affect genes with only one transcript isoform.

**Comment by scottcain** [comment]
That's an interesting problem: the gene names are technically on the screen, just hiding under the "Curated Genes" track label.  As far as I know, it's not possible to turn of the track labels by URL (which is what we'd need to do in this case), but I'll poke around and see if I can.  Of course, in that instance, the track labels wouldn't be visible, but I think that would be OK, since it's fairly obvious what each of the tracks is.

**Comment by chris-grove** [comment]
OK, thanks @scottcain

**Comment by scottcain** [comment]
Another option that is perhaps slightly less attractive is to add more buffer on the left side; we can play with that too.

**Comment by scottcain** [comment]
Oh, no, that wouldn’t work, at least as implemented now: the buffer is on the pcr product’s boundaries, not the enclosing gene. For an approach like this to work, we’d have to check if there is an overlapping gene and then change the boundaries based on that. Not impossible but more work than just changing a constant.

**Comment by scottcain** [comment]
A few things: 
1. Hiding tracklabels via the url is supported in the current version of jbrowse on staging.  The result would look something like this: https://staging.wormbase.org//tools/genome/jbrowse-simple/full.html?overview=0&tracks=Curated_Genes%2CMicroarray%20oligo%20probes%2CPCR%20Assays%2CORFeome%20PCR%20Products%2CYACs_Fosmids_Cosmids&loc=I%3A4686674..4688780&data=data%2Fc_elegans_simple&nav=0&tracklist=0&tracklabels=0

2. We'll have to ask @sibyl229 about adding that as an option specifically in pcr  product location widgets; I'm sure it can be done, just need to do it.

3. I realized while researching this that JBrowse is omitting some tracks because of spaces in their names; I'll have to fix that either in the catalyst side or JBrowse side.

**Comment by scottcain** [comment]
@sibyl229 ,

The jbrowse_view macro is what does the heavy lifting for the location widget, right? And it doesn't know what context that method is being called in (is it for a gene page, a pcr product page, etc), right?  I'm wondering if we can detect that is being drawn for a pcr product page and append to the url "&tracklabels=0".  I don't really want to do that all the time but I think in the context of the pcr product page it's ok.  I think a hacky way to do this would be to test the JBrowse url for a string like "ORFeome" which is only used in the pcr product context.  Would this be an OK thing to do?

**Comment by sibyl229** [comment]
Hi @chris-grove @scottcain I turned of the track labels in the jbrowse preview on the pcr oligo pages. The behaviour of other data pages (such as transcript page) should remain unchanged. And the linkouts to jbrowse page should also remain unchanged. 

Could you take a look? Thanks!

For testing:
https://staging.wormbase.org/species/all/pcr_oligo/sjj_C29H12.5#1--10
https://staging.wormbase.org/species/c_elegans/transcript/B0336.6.1#063--10

**Comment by chris-grove** [comment]
@sibyl229 
That's better thanks! I'll close this ticket.
@scottcain 
Longer term, it would be nice to still see the track labels, but just not have them conceal any important information. This gets at my general issue with JBrowse tending to overcrowd visual space in an effort to maximize efficiency of space usage.
