### ISSUE TITLE
  what is F3delta? What is hTau (V33TM)...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7157]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;what is F3delta?<br/>What is hTau (V33TM)<br/>What is the significance of mutations in BR6427 strain?</p>

**Reported by:** Rebe********** (rebe*******************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134

**Comment by raymond91125** [comment]
Hi,

Your questions appear rather specific to a particular context. Can you clarify? Are they related to some homework or exam set?

Raymond

On 04/06/2019 8:46 AM, no-reply@wormbase.org<mailto:no-reply@wormbase.org> wrote:
Question:

  what is F3delta?
What is hTau (V33TM)
What is the significance of mutations in BR6427 strain?

Submitted From:
  support /tools/support<http://wormbase.org//tools/support>

This issue has been assigned ticket number: #7157. Follow progress on our issue tracker<https://github.com/WormBase/website/issues/7157>.

Reported by: Rebecca Ibekwe (rebeccaibekwe@gmail.com<mailto:rebeccaibekwe@gmail.com>)
04 Jun 19 15:46

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134

This question was reported via the web interface at wormbase.org. You can also email us<mailto:help@wormbase.org> directly.

--
--
You received this message because you are subscribed to the "WormBase: help" group.
To post to this group, send email to help@wormbase.org<mailto:help@wormbase.org>
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en

---
To unsubscribe from this group and stop receiving emails from it, send an email to help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>.


--
__
Raymond Lee
raymond@caltech.edu<mailto:raymond@caltech.edu>
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by chris-grove** [comment]
Email response from @WBjae 
"""
Just for the reference, please see the comment below.

In genotype, delta (uppercase Greek character) usually means a deletion. So, F3 delta means F3 has a deletion of something. 
BR6427 strain has F3 fragment of human Tau protein  with K280 deleted. K280 means a lysine residue at 280.
F3 is one of pro aggregation fragment of the human Tau protein.

You maybe mean hTau (V337M), which means human Tau protein mutated from V (valine) to M (methionine) at 337.

I believe you can figure out the significance of these mutations in the strain from the paper here (Fatuouros C, et al. Hum Mol Genet. 2012 Aug 15;21(16):3587-603).
"""
