### ISSUE TITLE
I would like to annotate pks-1 and nrps-1 with inf...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7159]
*Help Desk query collected when no chat operators were online. Follow up required.*

I would like to annotate pks-1 and nrps-1 with info in our paperdoi:10.1038/nchembio.2144

How do I do this?  I think we got a request a long time ago but forgot

**Reported by:** Rebe*********** (butc****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/resources/paper/WBPaper00049938#0--10">https://wormbase.org/resources/paper/WBPaper00049938#0--10</a>
**Browser:** Chrome 74.0.3729.169

**Comment by Paul-Davis** [comment]
Dear Rebecca,

Thank you for contacting WormBase about submitting data, there are a 
number of submission forms here: 
https://wormbase.org/about/userguide/submit_data#012--10
If there isn't a form for the type of data you would like to submit, 
pease email the help@wormbase.org email address and we can put you in 
contact with a curator who can help you.

Paul

On 05/06/2019 14:50, no-reply@wormbase.org wrote:
> offline chat I would like to annotate pks-1 and nrps-1 with info in 
> our paperdoi:10.1038/nchembio.2144 How do I do this? I think we got a 
> request a long time ago but forgot
>
> Submitted From:
>   https://wormbase.org/resources/paper/WBPaper00049938#0--10 
> https://wormbase.org/resources/paper/WBPaper00049938#0--10 
> <http://www.wormbase.org/https://wormbase.org/resources/paper/WBPaper00049938#0--10> 
>
>
> This issue has been assigned ticket number: #7159. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/7159>.
>
> Reported by: Rebecca Butcher (butcher@chem.ufl.edu)
> 05 Jun 19 13:50
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by chris-grove** [comment]
My response to user:
"""
 We would greatly appreciate any phenotype data that you would like to contribute. Here's a personalized link to our phenotype submission form (with the publication ID and your name and email address pre-entered):

https://wormbase.org/submissions/phenotype.cgi?input_1_pmid=27501395&input_1_person=Rebecca+A+Butcher&termid_1_person= WBPerson6498&input_1_email=butcher@chem.ufl.edu

A quick look at the paper suggest that the following phenotype terms may be appropriate for you:

metabolite content decreased (WBPhenotype:0002270)
https://wormbase.org/species/all/phenotype/WBPhenotype:0002270#03--10

mRNA levels reduced (WBPhenotype:0000137)
https://wormbase.org/species/all/phenotype/WBPhenotype:0000137#03--10

slow development (WBPhenotype:0000674)
https://wormbase.org/species/all/phenotype/WBPhenotype:0000674#03--10

organism starvation hypersensitive (WBPhenotype:0000457)
https://wormbase.org/species/all/phenotype/WBPhenotype:0000457#03--10

Feel free to suggest additional phenotype terms that we may not already have (e.g. "recovery from starvation induced L1 arrest variant", etc.)
"""

She has since responded with her submissions.
