### ISSUE TITLE
 Server Error: 500 at  rest/widget/transcript/MTCE...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7174]
*Submitted from the feedback form on the WormBase website.*

<p>Server Error: 500 at <a href="http://wormbase.org/rest/widget/transcript/MTCE.3.1/sequences">rest/widget/transcript/MTCE.3.1/sequences</a></p><p></p><p>Error Message:<br> Caught exception in WormBase::Web::Controller::REST->widget "http://wormbase-rest-ws270.us-east-1.elasticbeanstalk.com/rest/widget/transcript/MTCE.3.1/sequences failed with 500 at /usr/local/wormbase/website/lib/WormBase/Web/Controller/REST.pm line 970." </p>

**Reported by:** Anon***** (andy************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36

**Comment by raymond91125** [comment]
https://wormbase.org/species/c_elegans/transcript/MTCE.3.1#6--10

**Comment by a8wright** [comment]
This has been resolved and pushed to production

**Comment by raymond91125** [comment]
Thanks for reporting the problem. It appears to have been resolved.

Raymond

On 18/06/2019 1:51 PM, no-reply@wormbase.org<mailto:no-reply@wormbase.org> wrote:
Bug Report

Server Error: 500 at rest/widget/transcript/MTCE.3.1/sequences<http://wormbase.org/rest/widget/transcript/MTCE.3.1/sequences>

Error Message:
Caught exception in WormBase::Web::Controller::REST->widget "http://wormbase-rest-ws270.us-east-1.elasticbeanstalk.com/rest/widget/transcript/MTCE.3.1/sequences failed with 500 at /usr/local/wormbase/website/lib/WormBase/Web/Controller/REST.pm line 970."<http://wormbase-rest-ws270.us-east-1.elasticbeanstalk.com/rest/widget/transcript/MTCE.3.1/sequencesfailedwith500at/usr/local/wormbase/website/lib/WormBase/Web/Controller/REST.pmline970.>

Submitted From:
  support /tools/support<http://wormbase.org//tools/support>

This issue has been assigned ticket number: #7174. Follow progress on our issue tracker<https://github.com/WormBase/website/issues/7174>.

Reported by: andylam@udel.edu<mailto:andylam@udel.edu>
18 Jun 19 20:51

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36

This question was reported via the web interface at wormbase.org. You can also email us<mailto:help@wormbase.org> directly.

--
--
You received this message because you are subscribed to the "WormBase: help" group.
To post to this group, send email to help@wormbase.org<mailto:help@wormbase.org>
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en

---
To unsubscribe from this group and stop receiving emails from it, send an email to help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>.


--
__
Raymond Lee
raymond@caltech.edu<mailto:raymond@caltech.edu>
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
