### ISSUE TITLE
Find all transgenes for a list of genes

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7180]
*Submitted from the feedback form on the WormBase website.*

<p>Server Error: 500 at <a href="http://www.wormbase.org/rest/widget/transgene/all/mapped_transgenes">rest/widget/transgene/all/mapped_transgenes</a></p><p></p><p>Error Message:<br> Caught exception in WormBase::Web::Controller::REST->widget "Invalid object tag "Reporter_product" at /usr/local/wormbase/website/lib/WormBase/API/Object/Transgene.pm line 75." </p><p>What were you doing? <br />&nbsp;&nbsp;I am trying somehow extract from wormbase a list of all the transgenes associated with my transcriptome hits. I have been trying to use WormMine, and using the html source code to try to figure out what terms to search for. That led me here and I was attempting to download a list of all transgenes for excel, because at least then I can search quickly instead of having to go to each gene page individually</p>

**Reported by:** Elys************* (elys*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36

**Comment by raymond91125** [comment]
Hi Elyse,

Sorry that we don't yet have a web tool for a class (e.g. transgene)-wide dump to EXCEL and transgenes have not yet been included in WormMine.

Instead of a table for all transgenes, you may use the REST API to fetch specific information only for the genes you're interested in.
You can get instructions here <https://wormbase.org/about/userguide/for_developers/api-rest#10--10>

One example <http://rest.wormbase.org/rest/widget/gene/WBGene00001135/reagents> (partial result below)

Thus, you can programmatically get all the transgenes that your genes are annotated to.

Cheers,

Raymond

{
  "class": "gene",
  "name": "WBGene00001135",
  "uri": "rest/widget/gene/WBGene00001135/reagents",
  "fields": {
    "antibodies": {
      "data": null,
      "description": "antibodies generated against protein products or gene fusions"
    },
    "transgenes": {
      "data": [
        {
          "construct": {
            "id": "WBCnstr00003206",
            "label": "WBCnstr00003206",
            "class": "construct",
            "taxonomy": "all"
          },
          "used_in": {
            "id": "WBTransgene00003224",
            "label": "sEx13603",
            "class": "transgene",
            "taxonomy": "all"
          },
          "use_summary": "[rCesZK512.6::GFP + pCeh361]",
          "used_in_type": "Transgene construct",
          "use_lab": []
        },

**Comment by chris-grove** [comment]
My email response to user:
"""
Just to add to Raymond's response: Here (attached) is a table of all transgenes, their respective construct objects, and those constructs' respective genes. The "Driven by gene" columns represent genes whose, for example, promoters are cloned into the construct to drive expression of the "Gene expressed" genes. These are from our most recent build of the database WS272.

I hope that helps.

Let us know if you have questions.
"""
