### ISSUE TITLE
 Server Error: 500 at  rest/widget/transgene/all/m...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7181]
*Submitted from the feedback form on the WormBase website.*

<p>Server Error: 500 at <a href="http://wormbase.org/rest/widget/transgene/all/mapped_transgenes">rest/widget/transgene/all/mapped_transgenes</a></p><p>
</p><p>Error Message:<br> Caught exception in WormBase::Web::Controller::REST-&gt;widget "Invalid object tag "Reporter_product" at /usr/local/wormbase/website/lib/WormBase/API/Object/Transgene.pm line 75." </p>

**Reported by:** Elys* (echr**************************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//rest/widget/transgene/all/mapped_transgenes">/rest/widget/transgene/all/mapped_transgenes</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36

**Comment by raymond91125** [comment]
related to issue #7180.

**Comment by raymond91125** [comment]
Hi Elyse,

Sorry that we don't yet have a web tool for a class (e.g. transgene)-wide dump to EXCEL and transgenes have not yet been included in WormMine.

Instead of a table for all transgenes, you may use the REST API to fetch specific information only for the genes you're interested in.

You can get instructions here <https://wormbase.org/about/userguide/for_developers/api-rest#10--10><https://wormbase.org/about/userguide/for_developers/api-rest#10--10>

One example <http://rest.wormbase.org/rest/widget/gene/WBGene00001135/reagents><http://rest.wormbase.org/rest/widget/gene/WBGene00001135/reagents> (partial result below)

Thus, you can programmatically get all the transgenes that your genes are annotated to.

Cheers,

Raymond


{
  "class": "gene",
  "name": "WBGene00001135",
  "uri": "rest/widget/gene/WBGene00001135/reagents",
  "fields": {
    "antibodies": {
      "data": null,
      "description": "antibodies generated against protein products or gene fusions"
    },
    "transgenes": {
      "data": [
        {
          "construct": {
            "id": "WBCnstr00003206",
            "label": "WBCnstr00003206",
            "class": "construct",
            "taxonomy": "all"
          },
          "used_in": {
            "id": "WBTransgene00003224",
            "label": "sEx13603",
            "class": "transgene",
            "taxonomy": "all"
          },
          "use_summary": "[rCesZK512.6::GFP + pCeh361]",
          "used_in_type": "Transgene construct",
          "use_lab": []
        },

...


On 20/06/2019 10:01 AM, no-reply@wormbase.org<mailto:no-reply@wormbase.org> wrote:
Bug Report

Server Error: 500 at rest/widget/transgene/all/mapped_transgenes<http://www.wormbase.org/rest/widget/transgene/all/mapped_transgenes>

Error Message:
Caught exception in WormBase::Web::Controller::REST->widget "Invalid object tag "Reporter_product" at /usr/local/wormbase/website/lib/WormBase/API/Object/Transgene.pm line 75."

What were you doing?
  I am trying somehow extract from wormbase a list of all the transgenes associated with my transcriptome hits. I have been trying to use WormMine, and using the html source code to try to figure out what terms to search for. That led me here and I was attempting to download a list of all transgenes for excel, because at least then I can search quickly instead of having to go to each gene page individually

Submitted From:
  support /tools/support<http://www.wormbase.org//tools/support>

This issue has been assigned ticket number: #7180. Follow progress on our issue tracker<https://github.com/WormBase/website/issues/7180>.

Reported by: Elyse Christensen (elyselaurette@gmail.com<mailto:elyselaurette@gmail.com>)
20 Jun 19 17:01

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36

This question was reported via the web interface at wormbase.org. You can also email us<mailto:help@wormbase.org> directly.

--
--
You received this message because you are subscribed to the "WormBase: help" group.
To post to this group, send email to help@wormbase.org<mailto:help@wormbase.org>
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en

---
To unsubscribe from this group and stop receiving emails from it, send an email to help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>.


--
__
Raymond Lee
raymond@caltech.edu<mailto:raymond@caltech.edu>
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by raymond91125** [comment]
@a8wright pointed out a class summary page that may be useful.
https://wormbase.org/species/c_elegans/transgene#0123--10
