### ISSUE TITLE
Where can I find all the genes for the olfactory r...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7182]
*Help Desk query collected when no chat operators were online. Follow up required.*

Where can I find all the genes for the olfactory receptors in the AWC neuron?

**Reported by:** Pris***** (phka**********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/about/userguide#0123456--10">https://www.wormbase.org/about/userguide#0123456--10</a>
**Browser:** Chrome 75.0.3770.80

**Comment by raymond91125** [comment]
I would get the overlap of genes annotated for:

1. G protein-coupled receptor activity <https://wormbase.org/species/all/go_term/GO:0004930#2--10><https://wormbase.org/species/all/go_term/GO:0004930#2--10>

2. AWC <https://wormbase.org/species/all/anatomy_term/WBbt:0005672#4--10><https://wormbase.org/species/all/anatomy_term/WBbt:0005672#4--10>

To the right of the focus term, there are hyperlinks to gene lists.

cheeers,

Raymond


On 6/20/19 2:43 PM, no-reply@wormbase.org<mailto:no-reply@wormbase.org> wrote:
offline chat Where can I find all the genes for the olfactory receptors in the AWC neuron?

Submitted From:
  https://www.wormbase.org/about/userguide#0123456--10 https://www.wormbase.org/about/userguide#0123456--10<http://www.wormbase.org/https://www.wormbase.org/about/userguide#0123456--10>

This issue has been assigned ticket number: #7182. Follow progress on our issue tracker<https://github.com/WormBase/website/issues/7182>.

Reported by: Priscilla (phka2017@mymail.pomona.edu<mailto:phka2017@mymail.pomona.edu>)
20 Jun 19 21:43


This question was reported via the web interface at wormbase.org. You can also email us<mailto:help@wormbase.org> directly.

--
--
You received this message because you are subscribed to the "WormBase: help" group.
To post to this group, send email to help@wormbase.org<mailto:help@wormbase.org>
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en

---
To unsubscribe from this group and stop receiving emails from it, send an email to help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>.

**Comment by raymond91125** [comment]
http://barc.wi.mit.edu/tools/compare/

I can't think of an easier way right now.

Raymond

On 6/20/19 5:15 PM, Priscilla Ki wrote:
Hello,
Is there a way of finding the overlap other than manually?
Best,
Priscilla Ki

From: "Lee, Raymond" <raymond@caltech.edu><mailto:raymond@caltech.edu>
Date: Thursday, June 20, 2019 at 4:36 PM
To: Priscilla Ki <phka2017@mymail.pomona.edu><mailto:phka2017@mymail.pomona.edu>
Cc: "reply@reply.github.com"<mailto:reply@reply.github.com> <reply@reply.github.com><mailto:reply@reply.github.com>, "help@wormbase.org"<mailto:help@wormbase.org> <help@wormbase.org><mailto:help@wormbase.org>
Subject: Re: [wormbase-help] offline chat transcript: Where can I find all the genes for the olfactory r... (Priscilla)


I would get the overlap of genes annotated for:

1. G protein-coupled receptor activity <https://wormbase.org/species/all/go_term/GO:0004930#2--10><https://wormbase.org/species/all/go_term/GO:0004930#2--10>

2. AWC <https://wormbase.org/species/all/anatomy_term/WBbt:0005672#4--10><https://wormbase.org/species/all/anatomy_term/WBbt:0005672#4--10>

To the right of the focus term, there are hyperlinks to gene lists.

cheeers,

Raymond


On 6/20/19 2:43 PM, no-reply@wormbase.org<mailto:no-reply@wormbase.org> wrote:
offline chat Where can I find all the genes for the olfactory receptors in the AWC neuron?

Submitted From:
  https://www.wormbase.org/about/userguide#0123456--10 https://www.wormbase.org/about/userguide#0123456--10<http://www.wormbase.org/https:/www.wormbase.org/about/userguide#0123456--10>

This issue has been assigned ticket number: #7182. Follow progress on our issue tracker<https://github.com/WormBase/website/issues/7182>.

Reported by: Priscilla (phka2017@mymail.pomona.edu<mailto:phka2017@mymail.pomona.edu>)
20 Jun 19 21:43

This question was reported via the web interface at wormbase.org. You can also email us<mailto:help@wormbase.org> directly.
--
--
You received this message because you are subscribed to the "WormBase: help" group.
To post to this group, send email to help@wormbase.org<mailto:help@wormbase.org>
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en

---
To unsubscribe from this group and stop receiving emails from it, send an email to help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>.
