### ISSUE TITLE
  What organization(s) or to whom could...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7184]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;What organization(s) or to whom could I send a worm for DNA evaluation?</p><p>What were you doing? <br />&nbsp;&nbsp;I found a rather large worm at the bottom of a can of stout beer & would like to know what type of worm it is.</p>

**Reported by:** MJ (Misc******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (iPhone; CPU iPhone OS 11_2_5 like Mac OS X) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0 Mobile/15D60 Safari/604.1

**Comment by raymond91125** [comment]
Hi MJ,

We do not offer such services and I couldn't tell you if there is anyone that would.

Raymond


On 6/23/19 10:51 PM, no-reply@wormbase.org<mailto:no-reply@wormbase.org> wrote:
Question:

  What organization(s) or to whom could I send a worm for DNA evaluation?

What were you doing?
  I found a rather large worm at the bottom of a can of stout beer & would like to know what type of worm it is.

Submitted From:
  support /tools/support<http://www.wormbase.org//tools/support>

This issue has been assigned ticket number: #7184. Follow progress on our issue tracker<https://github.com/WormBase/website/issues/7184>.

Reported by: MJ (Miscjohnsons@gmail.com<mailto:Miscjohnsons@gmail.com>)
24 Jun 19 05:51

Mozilla/5.0 (iPhone; CPU iPhone OS 11_2_5 like Mac OS X) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0 Mobile/15D60 Safari/604.1

This question was reported via the web interface at wormbase.org. You can also email us<mailto:help@wormbase.org> directly.

--
--
You received this message because you are subscribed to the "WormBase: help" group.
To post to this group, send email to help@wormbase.org<mailto:help@wormbase.org>
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en

---
To unsubscribe from this group and stop receiving emails from it, send an email to help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>.
