### ISSUE TITLE
Hello. I can't find in the user guide of the API-R...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7186]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello. I can't find in the user guide of the API-REST how to specify the output format. I wanted to obtain a json from the widget example: "https://wormbase.org/rest/widget/gene/WBGene00006763/human_diseases" but I can't get information of how to do so. Can you give me some information about that? Thank you

**Reported by:** Ana ******* (ana.**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/about/userguide/for_developers/API-REST/Gene#human_diseases">https://wormbase.org/about/userguide/for_developers/API-REST/Gene#human_diseases</a>
**Browser:** Chrome 75.0.3770.100

**Comment by raymond91125** [comment]
https://wormbase.org/rest/widget/gene/WBGene00006763/human_diseases?content-type=application/json

is the format to retrieve JSON.

And a brief description <https://wormbase.org/about/userguide/for_developers/API-REST#01--10><https://wormbase.org/about/userguide/for_developers/API-REST#01--10>.

Please let us know if you have more questions.

Cheers,

Raymond

On 6/24/19 11:53 AM, no-reply@wormbase.org<mailto:no-reply@wormbase.org> wrote:
offline chat Hello. I can't find in the user guide of the API-REST how to specify the output format. I wanted to obtain a json from the widget example: "https://wormbase.org/rest/widget/gene/WBGene00006763/human_diseases"<https://wormbase.org/rest/widget/gene/WBGene00006763/human_diseases> but I can't get information of how to do so. Can you give me some information about that? Thank you

Submitted From:
  https://wormbase.org/about/userguide/for_developers/API-REST/Gene#human_diseases https://wormbase.org/about/userguide/for_developers/API-REST/Gene#human_diseases<http://www.wormbase.org/https://wormbase.org/about/userguide/for_developers/API-REST/Gene#human_diseases>

This issue has been assigned ticket number: #7186. Follow progress on our issue tracker<https://github.com/WormBase/website/issues/7186>.

Reported by: Ana Sabater (ana.sabatera@um.es<mailto:ana.sabatera@um.es>)
24 Jun 19 18:53


This question was reported via the web interface at wormbase.org. You can also email us<mailto:help@wormbase.org> directly.

--
--
You received this message because you are subscribed to the "WormBase: help" group.
To post to this group, send email to help@wormbase.org<mailto:help@wormbase.org>
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en

---
To unsubscribe from this group and stop receiving emails from it, send an email to help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>.

**Comment by raymond91125** [comment]
Hi Anne,

We have also converted most of the REST endpoints to newer
architecture. You can access about 95% of the rest endpoints through
the following interface: http://rest.wormbase.org/index.html

These rest endpoints provide all output as JSON.

Adam

On Mon, Jun 24, 2019 at 8:19 PM Lee, Raymond <raymond@caltech.edu> wrote:
>
> https://wormbase.org/rest/widget/gene/WBGene00006763/human_diseases?content-type=application/json
>
> is the format to retrieve JSON.
>
> And a brief description <https://wormbase.org/about/userguide/for_developers/API-REST#01--10>.
>
> Please let us know if you have more questions.
>
> Cheers,
>
> Raymond
>
> On 6/24/19 11:53 AM, no-reply@wormbase.org wrote:
>
> offline chat Hello. I can't find in the user guide of the API-REST how to specify the output format. I wanted to obtain a json from the widget example: "https://wormbase.org/rest/widget/gene/WBGene00006763/human_diseases" but I can't get information of how to do so. Can you give me some information about that? Thank you
>
> Submitted From:
>   https://wormbase.org/about/userguide/for_developers/API-REST/Gene#human_diseases https://wormbase.org/about/userguide/for_developers/API-REST/Gene#human_diseases
>
> This issue has been assigned ticket number: #7186. Follow progress on our issue tracker.
>
> Reported by: Ana Sabater (ana.sabatera@um.es)
> 24 Jun 19 18:53
>
> This question was reported via the web interface at wormbase.org. You can also email us directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
> ---
> To unsubscribe from this group and stop receiving emails from it, send an email to help+unsubscribe@wormbase.org.
>
> --
> --
> You received this message because you are subscribed to the "WormBase: help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>


-- 
Adam Wright Lead Software Developer
416-673-8571
Ontario Institute for Cancer Research
