### ISSUE TITLE
  We registrated WormBase previously an...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7187]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;We registrated WormBase previously and used your library.<br/>I've forgotten my password, and tried to submit new password.<br/>However, my email address doesn't work showing the following message;<br/>"no WormBase account is associated with this email"<br/>What should I do, now?</p>

**Reported by:** Kazu************* (saka***********************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15

**Comment by scottcain** [comment]
@sibyl229 Did you see this from a few weeks ago?

**Comment by tharris** [comment]
@sibyl229 I don't have a record of this query or its resolution. Any insight?

**Comment by sibyl229** [comment]
@tharris I replied in August 16, 2019, but forgot to mark the ticket.

> Sorry to hear about the problem with your WormBase account. Unfortunately, I didn't find any account in our database with your name or email address. Is there another email address or name you might have provided? I can try to look them up in the database.

Alternatively, you can use the "Sign in with Google” login option to create a new account. Or if you prefer, I can create a new account for you with this email address. But since this will be a new account, it won’t have the content that you previously saved. 

Please let me know if you want a new account created with your institutional email address, or have other questions.
