### ISSUE TITLE
Hi, I'm trying to find out whether you have siRNAs...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7188]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi, I'm trying to find out whether you have siRNAs for RabGTPases.

**Reported by:** Domi***************** (d.mc***********************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/about/userguide/for_users#1--10">https://wormbase.org/about/userguide/for_users#1--10</a>
**Browser:** Chrome 70.0.3538.110

**Comment by raymond91125** [comment]
I don't believe we have siRNAs per se but we do have information about sequences used in RNAi experiments.

You can use the ontology page to find Rab family of proteins <https://wormbase.org/species/all/go_term/GO:0032482#02--10><https://wormbase.org/species/all/go_term/GO:0032482#02--10>. Click on "33 gene products (32 direct)" to get at the gene list.

And on each gene page, you can find the primer pairs in the Reagents widget. For example, <https://wormbase.org/species/c_elegans/gene/WBGene00004266#0d--3><https://wormbase.org/species/c_elegans/gene/WBGene00004266#0d--3>.

Hope this is of help to you.

Raymond

On 6/24/19 8:56 PM, Dominique McConnachie wrote:
Hi Raymond,

Sorry for the lack of detail. I’m trying to find if you have the Rab siRNAs on your data base? I’m looking to perform siRNA knock down of Rab GTPases in planarian schmidtea Mediterranea and I’m trying to see if this would be possible.

BW,
Dominique

On 25 Jun 2019, at 1:45 pm, Lee, Raymond <raymond@caltech.edu<mailto:raymond@caltech.edu>> wrote:


Please elaborate what you meant by "Whether you have...". What type of information do you need?

Raymond

On 6/24/19 8:16 PM, no-reply@wormbase.org<mailto:no-reply@wormbase.org> wrote:
offline chat Hi, I'm trying to find out whether you have siRNAs for RabGTPases.

Submitted From:
  https://wormbase.org/about/userguide/for_users#1--10 https://wormbase.org/about/userguide/for_users#1--10<http://www.wormbase.org/https://wormbase.org/about/userguide/for_users#1--10>

This issue has been assigned ticket number: #7188. Follow progress on our issue tracker<https://github.com/WormBase/website/issues/7188>.


Reported by: Dominique McConnachie (d.mcconnachie@imb.uq.edu.au<mailto:d.mcconnachie@imb.uq.edu.au>)
25 Jun 19 03:16


This question was reported via the web interface at wormbase.org<http://wormbase.org>. You can also email us<mailto:help@wormbase.org> directly.

--
--
You received this message because you are subscribed to the "WormBase: help" group.
To post to this group, send email to help@wormbase.org<mailto:help@wormbase.org>
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en

---
To unsubscribe from this group and stop receiving emails from it, send an email to help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>.
