### ISSUE TITLE
Hello, I found that another name of rab-18 is pra-...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7189]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello, I found that another name of rab-18 is pra-1. Could you please share the reason for that such as references ect. Thanks

**Reported by:** Zhao***** (zhao**************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/species/c_elegans/gene/WBGene00004277#eg42356-9017f-3">https://wormbase.org/species/c_elegans/gene/WBGene00004277#eg42356-9017f-3</a>
**Browser:** Safari 12.1.1

**Comment by raymond91125** [comment]
It appears to be coming from this EMBL entry <https://www.ebi.ac.uk/ena/data/view/U23938><https://www.ebi.ac.uk/ena/data/view/U23938>.

Raymond

FYI, I found this information by opening up the widget (Tools) Tree Display, looking to the right of tag Other_name pra-1.

On 25/06/2019 1:11 PM, no-reply@wormbase.org<mailto:no-reply@wormbase.org> wrote:
offline chat Hello, I found that another name of rab-18 is pra-1. Could you please share the reason for that such as references ect. Thanks

Submitted From:
  https://wormbase.org/species/c_elegans/gene/WBGene00004277#eg42356-9017f-3 https://wormbase.org/species/c_elegans/gene/WBGene00004277#eg42356-9017f-3<http://www.wormbase.org/https://wormbase.org/species/c_elegans/gene/WBGene00004277#eg42356-9017f-3>

This issue has been assigned ticket number: #7189. Follow progress on our issue tracker<https://github.com/WormBase/website/issues/7189>.

Reported by: Zhao Xuan (zhao.xuan@yale.edu<mailto:zhao.xuan@yale.edu>)
25 Jun 19 20:11


This question was reported via the web interface at wormbase.org. You can also email us<mailto:help@wormbase.org> directly.

--
--
You received this message because you are subscribed to the "WormBase: help" group.
To post to this group, send email to help@wormbase.org<mailto:help@wormbase.org>
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en

---
To unsubscribe from this group and stop receiving emails from it, send an email to help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>.


--
__
Raymond Lee
raymond@caltech.edu<mailto:raymond@caltech.edu>
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687
