### ISSUE TITLE
Hi, I have a list of genes and I would like to ret...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7191]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi, I have a list of genes and I would like to retrieve all of their protein sequences in one big file.  I thought maybe I could use WormMine.  I made and saved a list in WormMine.  But then I didn't know what to do afterwards.

Thanks,
visitor_name

**Reported by:** Rebe*** (butc****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/#012-34-5">https://www.wormbase.org/#012-34-5</a>
**Browser:** Chrome 75.0.3770.100

**Comment by raymond91125** [comment]
You can start the template query (Home->PROTEINS->Gene=>Proteins).

Edit the query:
a. tick "constrain to be IN saved Gene list" and pick your list.
b. hit "Edit Query"
c. tick Protein->Sequence->Residues ClobAccess SHOW

An example in XML is pasted below that you can play with by entering it here <http://intermine.wormbase.org/tools/wormmine/importQueries.do?query_builder=yes><http://intermine.wormbase.org/tools/wormmine/importQueries.do?query_builder=yes>

Raymond


<query model="genomic" view="Gene.symbol Gene.transcripts.symbol Gene.transcripts.CDSs.symbol Gene.transcripts.CDSs.protein.primaryIdentifier Gene.transcripts.CDSs.protein.symbol Gene.transcripts.CDSs.protein.sequence.residues" sortOrder="Gene.symbol ASC" >
  <constraint path="Gene" op="IN" value="Gene list for all organisms 26 Jun 2019 15.5" code="A" />
</query>

On 26/06/2019 2:47 PM, no-reply@wormbase.org<mailto:no-reply@wormbase.org> wrote:
offline chat Hi, I have a list of genes and I would like to retrieve all of their protein sequences in one big file. I thought maybe I could use WormMine. I made and saved a list in WormMine. But then I didn't know what to do afterwards. Thanks, Rebecca

Submitted From:
  https://www.wormbase.org/#012-34-5 https://www.wormbase.org/#012-34-5<http://www.wormbase.org/https://www.wormbase.org/#012-34-5>

This issue has been assigned ticket number: #7191. Follow progress on our issue tracker<https://github.com/WormBase/website/issues/7191>.

Reported by: Rebecca (butcher@chem.ufl.edu<mailto:butcher@chem.ufl.edu>)
26 Jun 19 21:47


This question was reported via the web interface at wormbase.org. You can also email us<mailto:help@wormbase.org> directly.

--
--
You received this message because you are subscribed to the "WormBase: help" group.
To post to this group, send email to help@wormbase.org<mailto:help@wormbase.org>
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en

---
To unsubscribe from this group and stop receiving emails from it, send an email to help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>.


--
__
Raymond Lee
raymond@caltech.edu<mailto:raymond@caltech.edu>
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by raymond91125** [comment]
From User:
"Thanks, this worked great and I would have never figured it out myself."
