### ISSUE TITLE
Hi, when I look up the 'molt defective' phenotype ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7192]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi, when I look up the 'molt defective' phenotype on the wormbase website, and then click on 'RNAi' in the list on the left, I get a list of genes with this RNAi phenotype. I want to download this, but the button 'Save table' doesn't seem to be working for me on Firefox.

**Reported by:** Avri********* (alc@************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/species/all/phenotype/WBPhenotype:0000638#04--10">https://wormbase.org/species/all/phenotype/WBPhenotype:0000638#04--10</a>
**Browser:** Firefox 65.0

**Comment by chris-grove** [comment]
My email to user:
"""
The "Save table" functionality relies on Flash to function, and as often times Flash is disabled by default on many browsers for security reasons, you have to enable Flash to run on the page to get the "Save table" button to work properly. Here's a screen recording of how you can enable Flash on the page:

https://www.dropbox.com/s/ptfp0l136ywdhk5/Enabling_Flash_on_WormBase_June_27_2019.mov?dl=0

Let us know if you have any other questions, or if that doesn't work for you.
"""

**Comment by raymond91125** [comment]
Hi Avril,

I would add that the table you wanted to download actually doesn't directly have the target gene information. To get at those, you could use the ontology browser <https://wormbase.org/species/all/phenotype/WBPhenotype:0000638#3--10><https://wormbase.org/species/all/phenotype/WBPhenotype:0000638#3--10>. Click on the hypertext of gene product counts to the right of the focus term will lead you to gene lists (note: does not include the NOT affected).

Cheers,

Raymond

On 27/06/2019 7:03 AM, Grove, Christian A. (Chris) wrote:
Hi Avril,

The "Save table" functionality relies on Flash to function, and as often times Flash is disabled by default on many browsers for security reasons, you have to enable Flash to run on the page to get the "Save table" button to work properly. Here's a screen recording of how you can enable Flash on the page:

https://www.dropbox.com/s/ptfp0l136ywdhk5/Enabling_Flash_on_WormBase_June_27_2019.mov?dl=0

Let us know if you have any other questions, or if that doesn't work for you.

Best,

Chris Grove
WormBase


________________________________
From: no-reply@wormbase.org<mailto:no-reply@wormbase.org> <no-reply@wormbase.org><mailto:no-reply@wormbase.org>
Sent: Thursday, June 27, 2019 4:31 AM
To: help@wormbase.org<mailto:help@wormbase.org>
Cc: alc@sanger.ac.uk<mailto:alc@sanger.ac.uk>
Subject: [wormbase-help] offline chat transcript: Hi, when I look up the molt defective phenotype ... (Avril Coghlan)

offline chat Hi, when I look up the 'molt defective' phenotype on the wormbase website, and then click on 'RNAi' in the list on the left, I get a list of genes with this RNAi phenotype. I want to download this, but the button 'Save table' doesn't seem to be working for me on Firefox.

Submitted From:
  https://wormbase.org/species/all/phenotype/WBPhenotype:0000638#04--10 https://wormbase.org/species/all/phenotype/WBPhenotype:0000638#04--10<http://www.wormbase.org/https://wormbase.org/species/all/phenotype/WBPhenotype:0000638#04--10>

This issue has been assigned ticket number: #7192. Follow progress on our issue tracker<https://github.com/WormBase/website/issues/7192>.

Reported by: Avril Coghlan (alc@sanger.ac.uk<mailto:alc@sanger.ac.uk>)
27 Jun 19 11:31


This question was reported via the web interface at wormbase.org. You can also email us<mailto:help@wormbase.org> directly.

--
--
You received this message because you are subscribed to the "WormBase: help" group.
To post to this group, send email to help@wormbase.org<mailto:help@wormbase.org>
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en

---
To unsubscribe from this group and stop receiving emails from it, send an email to help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>.
--
--
You received this message because you are subscribed to the "WormBase: help" group.
To post to this group, send email to help@wormbase.org<mailto:help@wormbase.org>
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en

---
To unsubscribe from this group and stop receiving emails from it, send an email to help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>.


--
__
Raymond Lee
raymond@caltech.edu<mailto:raymond@caltech.edu>
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by raymond91125** [comment]
Dear Raymond, Chris, 

Thanks so much for your helpful replies. 

I realised yesterday after emailing you that I should be able to get the
information on phenotypes using the WormBase REST API, and I would like
to learn to use this, so have set myself the challenge of writing a
script to use the REST API to get this information! I will let you know
if I get stuck. 

thanks again, 

Avril 

On 2019-06-27 18:27, Lee, Raymond wrote:

> Hi Avril, 
> 
> I would add that the table you wanted to download actually doesn't directly have the target gene information. To get at those, you could use the ontology browser <https://wormbase.org/species/all/phenotype/WBPhenotype:0000638#3--10> [3]. Click on the hypertext of gene product counts to the right of the focus term will lead you to gene lists (note: does not include the NOT affected). 
> 
> Cheers, 
> 
> Raymond 
> 
> On 27/06/2019 7:03 AM, Grove, Christian A. (Chris) wrote: 
> 
>> Hi Avril, 
>> 
>> The "Save table" functionality relies on Flash to function, and as often times Flash is disabled by default on many browsers for security reasons, you have to enable Flash to run on the page to get the "Save table" button to work properly. Here's a screen recording of how you can enable Flash on the page: 
>> 
>> https://www.dropbox.com/s/ptfp0l136ywdhk5/Enabling_Flash_on_WormBase_June_27_2019.mov?dl=0 
>> 
>> Let us know if you have any other questions, or if that doesn't work for you. 
>> 
>> Best, 
>> 
>> Chris Grove 
>> WormBase 
>> 
>> -------------------------
>> 
>> FROM: no-reply@wormbase.org <no-reply@wormbase.org>
>> SENT: Thursday, June 27, 2019 4:31 AM
>> TO: help@wormbase.org
>> CC: alc@sanger.ac.uk
>> SUBJECT: [wormbase-help] offline chat transcript: Hi, when I look up the molt defective phenotype ... (Avril Coghlan) 
>> 
>> offline chat Hi, when I look up the 'molt defective' phenotype on the wormbase website, and then click on 'RNAi' in the list on the left, I get a list of genes with this RNAi phenotype. I want to download this, but the button 'Save table' doesn't seem to be working for me on Firefox. 
>> 
>> Submitted From: 
>> https://wormbase.org/species/all/phenotype/WBPhenotype:0000638#04--10 https://wormbase.org/species/all/phenotype/WBPhenotype:0000638#04--10 [1] 
>> 
>> This issue has been assigned ticket number: #7192. Follow progress on our issue tracker [2]. 
>> 
>> Reported by: Avril Coghlan (alc@sanger.ac.uk) 
>> 27 Jun 19 11:31 
>> 
>> This question was reported via the web interface at wormbase.org. You can also email us directly. -- 
>> -- 
>> You received this message because you are subscribed to the "WormBase: help" group.
>> To post to this group, send email to help@wormbase.org
>> To unsubscribe from this group, send email to
>> help+unsubscribe@wormbase.org
>> For more options, visit this group at
>> http://groups.google.com/a/wormbase.org/group/help?hl=en
>> 
>> --- 
>> To unsubscribe from this group and stop receiving emails from it, send an email to help+unsubscribe@wormbase.org. -- 
>> -- 
>> You received this message because you are subscribed to the "WormBase: help" group.
>> To post to this group, send email to help@wormbase.org
>> To unsubscribe from this group, send email to
>> help+unsubscribe@wormbase.org
>> For more options, visit this group at
>> http://groups.google.com/a/wormbase.org/group/help?hl=en
>> 
>> --- 
>> To unsubscribe from this group and stop receiving emails from it, send an email to help+unsubscribe@wormbase.org.
> 
> -- 
> __
> Raymond Lee
> raymond@caltech.edu
> http://www.WormBase.org/
> California Institute of Technology
> Division of Biology and Biological Engineering
> Mail Code 156-29
> Pasadena, CA 91125
> USA
> tel: 626.395.2687

 

Links:
------
[1]
http://www.wormbase.org/https://wormbase.org/species/all/phenotype/WBPhenotype:0000638#04--10
[2] https://github.com/WormBase/website/issues/7192
[3] https://wormbase.org/species/all/phenotype/WBPhenotype:0000638#3--10


-- 
 The Wellcome Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.
