### ISSUE TITLE
  How do I get the sequences of a highl...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7220]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How do I get the sequences of a highlighted region upstream of a gene using the JBrowse?</p>

**Reported by:** Hong******* (hyha*************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36

**Comment by scottcain** [comment]
Responded to user:

Hello,

There are several ways to get sequence from JBrowse, depending on what you want.  Since this question comes up a lot, I wrote a blog post about it:

http://blog.wormbase.org/2019/03/18/getting-dna-sequence-from-jbrowse/

Please let me know if you have any questions,
Scott
