### ISSUE TITLE
Dear WormBase, I noticed that the blurb about almo...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7238]
*Help Desk query collected when no chat operators were online. Follow up required.*

Dear WormBase, I noticed that the blurb about almost every gene without a gene-name I look up tells me that it interacts with one or more of these: daf-2, daf-12, daf-16 or skn-1 (always three interactors listed plus a bunch of chemicals). The interactions tab shows nothing of this kind. I have the feeling that this automatically generated blurb has a bug. Best regards, Karin

**Reported by:** Kari********* (kk52********)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://www.wormbase.org/species/c_elegans/gene/WBGene00018946#0c-d9e1643fbg8-10-13">https://www.wormbase.org/species/c_elegans/gene/WBGene00018946#0c-d9e1643fbg8-10-13</a>
**Browser:** Chrome 75.0.3770.142

**Comment by WenChenWormBase** [comment]
Dear Karin,

You were probably referring to the summary of interactions derived from
genomic studies like RNA-Seq and microarray. The interaction widget does
not list results from these genomic studies.

Here is the complete summary for F56C3.9. The automated description only
listed three interacting genes and chemicals. It is possible that those
genes you saw were always ranked at the front  because of their gene ids or
names.

Your Input Automated Description Expression Cluster Summary
F56C3.9 Is affected by several genes including daf-16, skn-1, and daf-12
based on microarray, RNA-seq, and tiling array studies\; is affected by
twelve chemicals including hydrogen sulfide, Mercuric Chloride, and
Tunicamycin based on microarray and RNA-seq studies\; is predicted to
encode a protein with the following domains: BTB\/POZ domain and
SKP1\/BTB\/POZ domain superfamily. Affected by cyc-1, lin-35, wdr-23,
rsr-2, emr-1, lem-2, blmp-1, csr-1, ubc-9, clk-1, ham-3, npr-1, dop-1,
skn-1, mir-34, daf-12, daf-16, dpy-21, glh-4, glh-1, pgl-1, pgl-3, lin-22,
elt-2, elt-7, nuo-6, eat-2, dcr-1, rde-4, osm-7, osm-11, mir-243, ash-2,
crh-1, tax-6, mir-35, tbx-2, isp-1 and pmk-1 according to microarray,
RNA-seq and tiling array. Affected by hydrogen sulfide, Mercuric Chloride,
Tunicamycin, D-glucose, juglone, TPEN, Psoralens, allantoin, Sirolimus,
metformin, Rifampin, Cry5B, resveratrol, Chlorpyrifos, Humic Substances,
paraquat and adsorbable organic bromine compound according to microarray
and RNA-seq.
You can access the complete expression cluster summaries from the
SimpleMine tool listed under "Tools" menu. They are only included in
automated description when the genes have no other experimental
information.


Wen Chen
Curator, WormBase


On Tue, Jul 30, 2019 at 3:10 PM <no-reply@wormbase.org> wrote:

> offline chat Dear WormBase, I noticed that the blurb about almost every
> gene without a gene-name I look up tells me that it interacts with one or
> more of these: daf-2, daf-12, daf-16 or skn-1 (always three interactors
> listed plus a bunch of chemicals). The interactions tab shows nothing of
> this kind. I have the feeling that this automatically generated blurb has a
> bug. Best regards, Karin
>
> Submitted From:
>
> https://www.wormbase.org/species/c_elegans/gene/WBGene00018946#0c-d9e1643fbg8-10-13
> https://www.wormbase.org/species/c_elegans/gene/WBGene00018946#0c-d9e1643fbg8-10-13
> <http://www.wormbase.org/https://www.wormbase.org/species/c_elegans/gene/WBGene00018946#0c-d9e1643fbg8-10-13>
>
> This issue has been assigned ticket number: #7238. Follow progress on our issue
> tracker <https://github.com/WormBase/website/issues/7238>.
>
> Reported by: Karin Kiontke (kk52@nyu.edu)
> 30 Jul 19 22:10
>
> This question was reported via the web interface at wormbase.org. You can
> also email us <help@wormbase.org> directly.
>
> --
> --
> You received this message because you are subscribed to the "WormBase:
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>
>

-- 
Wen Chen
Curator, WormBase
