### ISSUE TITLE
  how do I search for all genes that ha...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7244]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;how do I search for all genes that have a given phenotype</p>

**Reported by:** Kevi*********** (kevi***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Safari/605.1.15

**Comment by raymond91125** [comment]
You can use the Phenotype ontology browser.

1. From the front page, search "for a phenotype" at top right, say "sterile".

2. On the sterile phenotype page, open the Ontology Browser widget <https://wormbase.org/species/all/phenotype/WBPhenotype:0000688#3--10><https://wormbase.org/species/all/phenotype/WBPhenotype:0000688#3--10>.

3. click on the numbers (e.g. 3475 gene products (2836 direct)) to the right of the focus term in green.

4. there are lists of gene perturbations that generate the sterile phenotype.

Cheers,

Raymond

On 05/08/2019 10:51 AM, no-reply@wormbase.org<mailto:no-reply@wormbase.org> wrote:
How Do I ...?

  how do I search for all genes that have a given phenotype

Submitted From:
  support /tools/support<http://www.wormbase.org//tools/support>

This issue has been assigned ticket number: #7244. Follow progress on our issue tracker<https://github.com/WormBase/website/issues/7244>.

Reported by: Kevin O'Connell (kevino@mail.nih.gov<mailto:kevino@mail.nih.gov>)
05 Aug 19 17:51

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Safari/605.1.15

This question was reported via the web interface at wormbase.org. You can also email us<mailto:help@wormbase.org> directly.

--
--
You received this message because you are subscribed to the "WormBase: help" group.
To post to this group, send email to help@wormbase.org<mailto:help@wormbase.org>
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en

---
To unsubscribe from this group and stop receiving emails from it, send an email to help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>.


--
__
Raymond Lee
raymond@caltech.edu<mailto:raymond@caltech.edu>
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by raymond91125** [comment]
From User: 
Thanks Raymond!
