### ISSUE TITLE
Some experimental disease genes not making into FTP disease associations file (and therefore SimpleMine as well)

### ISSUE THREAD

**Issue by chris-grove** [WormBase/website#7252]
I found that the following five genes:

WBGene00000934
WBGene00006597
WBGene00010988
WBGene00011305
WBGene00019241

have experimental disease information in WS271 ACEDB and on the live website (Human Diseases widget on respective gene pages), but are missing experimental disease info in the SimpleMine results, likely because they are also missing from the WS271 disease associations file on the FTP site here:

ftp://ftp.wormbase.org/pub/wormbase/releases/WS271/ONTOLOGY/disease_association.WS271.wb

Not sure what the issue is.

**Comment by WenChenWormBase** [comment]
SimpleMine disease association came from the file on FTP.

**Comment by epaule** [comment]
I can find all but WBGene00019241 and WBGene00011305 in disease_association.WS271.wb

**Comment by chris-grove** [comment]
@epaule 
The three genes:

WBGene00000934
WBGene00006597
WBGene00010988

Are in the disease associations file via IEA evidence code annotations, which are predictions based on orthology to human disease genes. The experiment-based annotations would have an IMP evidence code, but those annotations for these genes are missing from the disease associations file.

**Comment by epaule** [comment]
as far as I can see from https://github.com/WormBase/wormbase-pipeline/blob/bd30ea2a161b024f72950925d312f9035d39898f/scripts/ONTOLOGY/make_disease_GAF.pl

the Experimental_model tag needs to have either a Paper_evidence or an Accession_evidence to appear in the file.
WBGene00000934, as example, only has a Curator_confirmed and a Date_last_updated evidence

**Comment by chris-grove** [comment]
@epaule 
OK, thanks, that probably explains it. It seems we should probably not dump these associations into ACEDB if they don't also meet the same criteria.
I think @rankishore can take a look when she's back from vacation at the end of the month.

**Comment by khowe** [comment]
@chris-grove @epaule I think there may be a deeper issue with this. The make_disease_GAF script was last touched over 4 years ago, pre-AGR. Since AGR, we have created the Disease_model_annotation class, and @rankishore has been curating newer associations into that class. She has said that migrating older annotations into the new model would be too much work, so we currently have: old model populated with old data, new model populated with new data. 

The script we use for our AGR disease upload looks in both places for data:

https://github.com/WormBase/wormbase-pipeline/blob/master/scripts/AGR/make_agr_disease_json.pl

The script also has an option to report DAF. @WenChenWormBase can your SimpleMine import process deal with DAF (as well as the old GAF-style assoc files)? If so, we should (a) start producing a DAF as part of the build, and put it in the ONTOLOGY folder, and (b) switch off the running of the make_disease_GAF script. 

I'm surprised that this has not come up before, so it could be I'm missing something...

**Comment by chris-grove** [comment]
@khowe 
OK thanks for that perspective. We'll see what @WenChenWormBase says.

Maybe we can discuss in more detail once @rankishore is back from vacation.

**Comment by WenChenWormBase** [comment]
@khowe, I would rather take the data directly from ACeDB. Where are the scripts that you used to generate the FTP files? It may help me to alternate the SimpleMine building pipeline if I can read your scripts.

**Comment by raymond91125** [comment]
https://github.com/WormBase/wormbase-pipeline/blob/master/scripts/AGR/make_agr_disease_json.pl

**Comment by WenChenWormBase** [comment]
Thank you, @raymond91125 !

**Comment by raymond91125** [comment]
Each release, I produce a disease GAF that includes the non-IEA annotations (from DAF), e.g. <http://caltech.wormbase.org/ontology/disease_association.WS271.wb.clean>. The three genes @chris-grove specified, their IMP annotations are not in because they are not in either input files.

**Comment by WenChenWormBase** [comment]
SimpleMine is now updated. Thank you, Chris, for bringing up this issue.

Your Input | Public Name | Disease Info
-- | -- | --
WBGene00000934 | dat-1 | dopamine  beta-hydroxylase deficiency \| DOID:0090145 \| By Experiment,postural  orthostatic tachycardia syndrome \| DOID:0111154 \| By Orthology
WBGene00006597 | tor-1 | Parkinson's disease \| DOID:14330 \| By Experiment,torsion dystonia 1 \| DOID:0060730 \| By Orthology
WBGene00010988 | metr-1 | type 2 diabetes mellitus \| DOID:9352 \| By Experiment,neural tube defect \| DOID:0080074 \| By Orthology
WBGene00011305 | R186.1 | chromosome 22q11.2 deletion syndrome, distal \| DOID:0060413 \| By Experiment
WBGene00019241 | trm-2A | chromosome 22q11.2 deletion syndrome, distal \| DOID:0060413 \| By Experiment
