### ISSUE TITLE
  CEOP5527 This operon has been placed ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7253]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;CEOP5527<br/>This operon has been placed on 2 genes B028.11 and natc-2, but the intergenic region between these two genes is over 5kb. What is the experimental evidence for this operon? Could this operon be placed in the wrong place?<br/>Thanks,<br/>Rose</p><p>What were you doing? <br />&nbsp;&nbsp;Using JBrowse to look at natc-2</p>

**Reported by:** Rose******* (rama*************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36

**Comment by Paul-Davis** [comment]
Dear Rose,

Thanks for contacting WormBase.

You are right, CEOP5527 is a little outside the expected organisation of 
a standard 2 gene operon. The operons that you see placed on the genome 
browser are based on the component gene spans that are manually curated 
so it is in the intended location. I believe that the intergenic space 
is a little strange as it is quite  repetitive (see the blast repeat 
motifs). That said there is also a lot of stranded and unstranded RNASeq 
data suggesting that this intergenic sequence is transcribed and likely 
part of some pre-mRNA molecule. This also could be a hybrid operon as 
there is more than enough space for an independent promoter although the 
expression levels of the respective sets of introns seems to be pretty 
level so that scenario looks less likely.

The operon was created primarily based on the SL2 site WBsf022111. This 
is defined by many RNASeq experiments, Traditional EST and Tec-Red 
sequence data meaning that it really does look like a gene which is 
downstream in an operon. This operon also falls into the last round of 
operon edits made by Tom Blumenthal where all downstream genes have a 
minimum of 5% SL2 reads from the total SL reads for the given site.

The only way to be 100% sure that this is an operon is to confirm it 
experimentally in the lab.

Hope this helps, all the best

Paul

On 08/08/2019 23:33, no-reply@wormbase.org wrote:
> Feature Request
>
>   CEOP5527
> This operon has been placed on 2 genes B028.11 and natc-2, but the 
> intergenic region between these two genes is over 5kb. What is the 
> experimental evidence for this operon? Could this operon be placed in 
> the wrong place?
> Thanks,
> Rose
>
> What were you doing?
>   Using JBrowse to look at natc-2
>
> Submitted From:
>   support /tools/support <http://wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #7253. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/7253>.
>
> Reported by: Rose Malino (ramalino@ucsd.edu)
> 08 Aug 19 22:33
>
> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, 
> like Gecko) Chrome/75.0.3770.142 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
