### ISSUE TITLE
Hi! I'm wondering if there's a way to search acros...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7261]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hi! I'm wondering if there's a way to search across gene descriptions for a specific term? The general search isn't bringing up desired results. Thanks!

**Reported by:** Joce*** (jhav***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/species/c_elegans/gene/WBGene00019362#046-9g-3">https://wormbase.org/species/c_elegans/gene/WBGene00019362#046-9g-3</a>
**Browser:** Chrome 74.0.3729.169

**Comment by raymond91125** [comment]
what kind of term?

raymond

On 16/08/2019 2:08 PM, no-reply@wormbase.org<mailto:no-reply@wormbase.org> wrote:
offline chat Hi! I'm wondering if there's a way to search across gene descriptions for a specific term? The general search isn't bringing up desired results. Thanks!

Submitted From:
  https://wormbase.org/species/c_elegans/gene/WBGene00019362#046-9g-3 https://wormbase.org/species/c_elegans/gene/WBGene00019362#046-9g-3<http://www.wormbase.org/https://wormbase.org/species/c_elegans/gene/WBGene00019362#046-9g-3>

This issue has been assigned ticket number: #7261. Follow progress on our issue tracker<https://github.com/WormBase/website/issues/7261>.

Reported by: Jocelyn (jhaversat@gmail.com<mailto:jhaversat@gmail.com>)
16 Aug 19 21:08


This question was reported via the web interface at wormbase.org. You can also email us<mailto:help@wormbase.org> directly.

--
--
You received this message because you are subscribed to the "WormBase: help" group.
To post to this group, send email to help@wormbase.org<mailto:help@wormbase.org>
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en

---
To unsubscribe from this group and stop receiving emails from it, send an email to help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>.


--
__
Raymond Lee
raymond@caltech.edu<mailto:raymond@caltech.edu>
http://www.WormBase.org/
California Institute of Technology
Division of Biology and Biological Engineering
Mail Code 156-29
Pasadena, CA 91125
USA
tel: 626.395.2687

**Comment by chris-grove** [comment]
My email to user:
"""
The gene search on WormBase is already indexing content from gene descriptions, so if there's a gene description that contains your keyword of interest, it should come back with your search results. For example, if you search "for a gene" with the keyword "kinase", you will get a list of genes in the search results that have descriptions that refer to the word "kinase":

https://wormbase.org/search/gene/kinase

Let us know what word or category of word you are looking for and we'll see if we can find relevant genes that way or by some other method.
"""

**Comment by chris-grove** [comment]
user response:
"""
"CDK" which stands for "Cylin-dependent Kinase" 
"""

**Comment by chris-grove** [comment]
My email to user:
"""
 It looks like you were searching for the acronym "CDK". When I search WormBase "for a gene" with the keyword "CDK", I get the following results:

https://wormbase.org/search/gene/CDK

Are there other results you were expecting instead?

Let us know if we can assist further.
"""

**Comment by raymond91125** [comment]
Just to add, anther way you can get at CDKs is through the GO term search <https://wormbase.org/species/all/go_term/GO:0004693#02--10><https://wormbase.org/species/all/go_term/GO:0004693#02--10>. In the Ontology Browser widget, click on the text to the right of the focus term, there are 14 genes directly annotated.
"
Yet another way (strictly as you wanted) is to use the Simplemine <https://wormbase.org/tools/mine/simplemine.cgi><https://wormbase.org/tools/mine/simplemine.cgi>. Tick only "Concise Description" and click "Query all C. elegans". Then you can do a word search for "CDK". You will have to screen for those actually code for CDK.

Cheers,

Raymond

On 19/08/2019 6:29 AM, Grove, Christian A. (Chris) wrote:
Hi again Jocelyn,

It looks like you were searching for the acronym "CDK". When I search WormBase "for a gene" with the keyword "CDK", I get the following results:

https://wormbase.org/search/gene/CDK

Are there other results you were expecting instead?

Let us know if we can assist further.

Chris
________________________________
