### ISSUE TITLE
If you want to select a region on the genome and g...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7281]
*Help Desk query collected when no chat operators were online. Follow up required.*

If you want to select a region on the genome and get FASTA sequence for your selection as you were able to do in the legacy browser, what do you have to do. It seems like you can only click on annotations and get the sequences for these rather than get the sequence of any selection.

**Reported by:** Rach************* (rach*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/species/c_elegans/gene/WBGene00002220#0ef-9g1-3">https://wormbase.org/species/c_elegans/gene/WBGene00002220#0ef-9g1-3</a>
**Browser:** Chrome 75.0.3770.100

**Comment by scottcain** [comment]
My reply:


Since this isn't quite the same as the old genome browser, we get a fair number of questions about this topic.  Please take a look at a blog post I did about this to help explain how to do it:

  http://blog.wormbase.org/2019/03/18/getting-dna-sequence-from-jbrowse/

Please let me know if you have any more questions,
Scott
