### ISSUE TITLE
  Dear wormbase, I am looking for a way...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7282]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Dear wormbase,<br/>I am looking for a way to extract all the mutant C elegans alleles and genes that have a dominant phenotype. How can I do this?</p><p>What were you doing? <br />&nbsp;&nbsp;I tried using wormmine and simplemine but i couldnt find a way to extract this info</p>

**Reported by:** Itam****** (itam***************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36

**Comment by WenChenWormBase** [comment]
@chris-grove SimpleMine does not have information on dominant phenotype. Can you do this via  WormMine or AQL?

**Comment by chris-grove** [comment]
@WenChenWormBase 
Yes, I can do this via AQL, but cannot access ACEDB via the "ws" command on Spica currently. Have sent you an email with error messages.

**Comment by chris-grove** [comment]
Emailed user:
"""
The only way I know to query this currently is to perform an AQL query of the ACEDB database. I've attached a text file containing the AQL queries I performed and two Excel spreadsheets with the results. One Excel sheet has the dominant alleles, their phenotypes and the evidence source (paper or person). The other has the dominant alleles mapped to their respective genes. Note that some variations/alleles map to multiple genes and some don't map to any genes likely either because they haven't been mapped yet or they haven't yet been curated.

Let me know if you have any questions.
"""
