### ISSUE TITLE
  We want to map the expression of two ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7306]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;We want to map the expression of two alternatively spliced exons (whose expression are mutually exclusive) of a C. elegans gene (coq-2, exons 6a and 6e) during the worm lifecycle. Can this information be retrieved from the wormbase? In other words, is RNAseq data (at the exon level) mapped to the genome at the different stages.    </p>

**Reported by:** Gust*********** (gsal*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36

**Comment by Paul-Davis** [comment]
You were nominated on the call last night @gw3 think you are the best to advise on this.

**Comment by fayerodgers** [comment]
@gw3 this is the same user that wrote to me separately. I replied, but cc'd hinxton instead of help. Pasted my response below:

Good to meet you too! I’m afraid we don’t quantify at the exon level, only the gene level. You could look on JBrowse to see the aligned tracks which might give you a sense of what you’re looking for, eg:
https://parasite.wormbase.org/jbrowse/index.html?data=%2Fjbrowse-data%2Fcaenorhabditis_elegans_prjna13758%2Fdata&loc=III%3A6935271..6940137&tracks=DNA%2CGene_Models%2CRNASeq%2FSRR400287%2CRNASeq%2FSRR522881%2CRNASeq%2FSRR405093%2CRNASeq%2FSRR405094&highlight=
 
For the gene level quantifications, we retrieve the data from the RNASeq-er API (https://www.ebi.ac.uk/fg/rnaseq/api/). We don’t use it, but they do also quantify by exon (using DEXSeq). You can find the FTP locations for the C elegans studies here:
 
https://www.ebi.ac.uk/fg/rnaseq/api/tsv/getStudiesByOrganism/caenorhabditis_elegans
 
So if you can identify a study looking at different life stages, you could get the exon counts directly from there.
 
We (WormBase ParaSite) don’t curate the C elegans RNASeq data very well, because WormBase does a better job! So I’m cc’ing my C elegans colleagues who might be able to suggest a better way to find what you’re after. One final suggestion would be to check the modENCODE datasets (http://www.modencode.org/), which have transcriptional data from lots of life stages. Again, I can’t see any exon-level quantifications, but maybe my C elegans friends know more.

**Comment by gw3** [comment]
Gustavo,

We use the program 'cufflinks' to calculate the FPKM values from the 
RNASeq alignment data.
Cufflinks produces the FPKM values for individual isoforms as well as a 
combined value for the complete Gene.
I can therefore output the data you require.

Bear in mind that I am not confident that the expression value can be 
accurately calculated by proportionately assigning the aligned RNASeq 
reads to one isoform or another. These values should be taken with a 
pinch of salt.

I've put the median values of the life stages of coq-2 in the file:

ftp://ftp.ebi.ac.uk/pub/databases/wormbase/STAFF/gw3/WS273_coq-2.csv

Let me know if anything is not clear.

Gary Williams
