### ISSUE TITLE
  Hi, I'm working with deletion mutants...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7313]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi,<br/>I'm working with deletion mutants of a gene, which weren't characterized. We sequenced them and I was wondering if there's any tool on wormbase to predict protein sequence upon deletion.<br/>Also, is there any way to download a gene structure in .svg or other format?<br/>Thanks in advance,<br/>Dani</p><p>What were you doing? <br />&nbsp;&nbsp;I tried online exon-intron predictors with the full sequence, but doesn't match what is annotated in wormbase.</p>

**Reported by:** Dani*********** (hoch************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36

**Comment by Paul-Davis** [comment]
Dear Dani,

I don't believe we have a way of generating the predicted protein 
structure for large deletions, but if we have all of the necessary 
sequence data you can see the WT and Deleted sequence in the Molecular 
details widget on the Variation Summary page, but this is genomic 
consequence rather than protein.

Example:
https://wormbase.org/species/c_elegans/variation/WBVar00092661#02-45673189-10

If you have sequence data that you would be willing to share with the 
community you can either submit it through our Allele form:
https://wormbase.org/submissions/allele_sequence.cgi

or send it via this thread or directly to myself.

There is a tutorial on how to get high resolution images from jbrowse

http://blog.wormbase.org/2016/02/10/creating-hi-res-screenshots-in-jbrowse/

Hope this helps

Paul




On 23/09/2019 17:25, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   Hi,
> I'm working with deletion mutants of a gene, which weren't 
> characterized. We sequenced them and I was wondering if there's any 
> tool on wormbase to predict protein sequence upon deletion.
> Also, is there any way to download a gene structure in .svg or other 
> format?
> Thanks in advance,
> Dani
>
> What were you doing?
>   I tried online exon-intron predictors with the full sequence, but 
> doesn't match what is annotated in wormbase.
>
> Submitted From:
>   support /tools/support <http://wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #7313. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/7313>.
>
> Reported by: Daniel Hochbaum (hoch30@gmail.com)
> 23 Sep 19 16:25
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 
> (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================
