### ISSUE TITLE
  for gene ced-1. mutant allele e1375: ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7314]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;for gene ced-1. mutant allele e1375:  in the nucleotide sequence the + and - strands are switched.</p><p>What were you doing? <br />&nbsp;&nbsp;going to perform PCR on wildtype vs ced-1(e1375) and was looking at where the pre-mature stop was. If you can confirm this that would be awesome</p>

**Reported by:** Marc************** (marc************************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36

**Comment by Paul-Davis** [comment]
Dear Marc,

Thanks for contacting WormBase.

This Variation was originally curated on the negative strand and appears 
to be displayed correctly when looking at the Molecular details widget 
of (+) STRAND (-) STRAND however, it does appear that the flanking 
sequences we use to place the mutation on the genome incorrectly contain 
the deleted sequence, this causes the web display to highlight the 
incorrect 2 bp in the WT and insert the insert sequence 1bp shifted to 
the right with the incorrect 2bp deleted in the mutant sequence.

Hopefully the below formatting will transfer correctly over email.

----------------------------------------------------------------------------------------------
-ve strand web display - confirmed curated on the -ve strand

WT(-) cacggaggcttcaagcgttgactcaAAtgaatccaaaatggcgacctgaacc
LFlank   tcgacacggaggcttcaagcgttgactcaa
RFlank atgaatccaaaatggcgacctgaaccgtgt
Curated Deletion                       AT

* Issue flanks contain the deleted sequence which needs to be fixed

Mut(-) 
cacggaggcttcaagcgttgactcaTGCGTTGACTCAATGCGTTGACTCGTTGACtgaatccaaaatggcgacctgaacc
Deleted bp A                            A
LFlank   tcgacacggaggcttcaagcgttgactcaa
RFlank atgaatccaaaatggcgacctgaaccgtgt
Insilico mut 
cacggaggcttcaagcgttgactcaTGCGTTGACTCAATGCGTTGACTCGTTGACtgaatccaaaatggcgacctgaacc
True mut 
cacggaggcttcaagcgttgactcaaTGCGTTGACTCAATGCGTTGACTCGTTGACgaatccaaaatggcgacctgaaccgtgt
True Del                               A                            T

Issue inserted sequence is 1bp shifted because of the flanking data 
issue and out of context.

I will fix the primary data so that in WS274 this should be displayed in 
the correct context.

If I have misunderstood your original issue please feel free to contact 
me directly to resolve any further issues.

Paul

**Comment by Paul-Davis** [comment]
It looks like email messed with the formatting attached is a screenshot 
of what I was trying to send.

Paul

On 25/09/2019 10:39, Paul Davis wrote:
>
> Dear Marc,
>
> Thanks for contacting WormBase.
>
> This Variation was originally curated on the negative strand and 
> appears to be displayed correctly when looking at the Molecular 
> details widget of (+) STRAND (-) STRAND however, it does appear that 
> the flanking sequences we use to place the mutation on the genome 
> incorrectly contain the deleted sequence, this causes the web display 
> to highlight the incorrect 2 bp in the WT and insert the insert 
> sequence 1bp shifted to the right with the incorrect 2bp deleted in 
> the mutant sequence.
>
> Hopefully the below formatting will transfer correctly over email.
>
> ---------------------------------------------------------------------------------------------- 
>
> -ve strand web display - confirmed curated on the -ve strand
>
> WT(-) cacggaggcttcaagcgttgactcaAAtgaatccaaaatggcgacctgaacc
> LFlank   tcgacacggaggcttcaagcgttgactcaa
> RFlank atgaatccaaaatggcgacctgaaccgtgt
> Curated Deletion                       AT
>
> * Issue flanks contain the deleted sequence which needs to be fixed
>
> Mut(-) 
> cacggaggcttcaagcgttgactcaTGCGTTGACTCAATGCGTTGACTCGTTGACtgaatccaaaatggcgacctgaacc
> Deleted bp A                            A
> LFlank   tcgacacggaggcttcaagcgttgactcaa
> RFlank atgaatccaaaatggcgacctgaaccgtgt
> Insilico mut 
> cacggaggcttcaagcgttgactcaTGCGTTGACTCAATGCGTTGACTCGTTGACtgaatccaaaatggcgacctgaacc
> True mut 
> cacggaggcttcaagcgttgactcaaTGCGTTGACTCAATGCGTTGACTCGTTGACgaatccaaaatggcgacctgaaccgtgt
> True Del                               A   T
>
> Issue inserted sequence is 1bp shifted because of the flanking data 
> issue and out of context.
>
> I will fix the primary data so that in WS274 this should be displayed 
> in the correct context.
>
> If I have misunderstood your original issue please feel free to 
> contact me directly to resolve any further issues.
>
> Paul
>
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
![e1375](https://user-images.githubusercontent.com/717707/65590158-3afe5600-df82-11e9-94fa-bc5b50e49bdc.png)

**Comment by chris-grove** [comment]
@Paul-Davis 
Just to clarify: I believe the allele in question is actually ced-1(e1735); e1375 is an allele of daf-18

**Comment by Paul-Davis** [comment]
@chris-grove gah, no wonder the guy was so confused......looks like there was an error in e1375 anyway :(
