### ISSUE TITLE
C. briggsae population variant data

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7350]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi,<br/>I was recently reading this paper (https://www.ncbi.nlm.nih.gov/pubmed/25783854), in which they state that they deposited all of their C. briggsae population variant data in Wormbase.  Can you point me to where I may be able to find and download these data from Wormbase?  Additionally, I know there has been population sequencing of C. elegans and I wonder if the data on C. elegans variants (or any other Wormbase genome) is present also in Wormbase.  It would be great if these data were all in one place, and it seems like they may be here but I just can't find them.<br/>Thank you very much,<br/>visitor_name</p>

**Reported by:** Matt********** (mdda****************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36

**Comment by Paul-Davis** [comment]
Dear Matt,

Thanks for contacting WormBase. Going back to 2015 we were in 
correspondence with the Author to incorporate this SNP data into 
WormBase. At the time it was felt that some additional work was needed 
to clean up the existing C. briggsae variation data in order for this 
data to be merged correctly. It seems that this work stalled so it was 
never processed and incorporated.

We do have the data, so I have requested that we add the vcf file as a 
viewable track on jbrowse as an interim and we will look at reviving 
this task following your email.

I will also talk with colleagues when I'm back in the office tomorrow 
regarding your questions about population sequencing studies and how 
best we could make this data available to you.

Paul


On 15/10/2019 20:50, no-reply@wormbase.org wrote:
> How Do I ...?
>
>   Hi,
> I was recently reading this paper 
> (https://www.ncbi.nlm.nih.gov/pubmed/25783854), in which they state 
> that they deposited all of their C. briggsae population variant data 
> in Wormbase. Can you point me to where I may be able to find and 
> download these data from Wormbase? Additionally, I know there has been 
> population sequencing of C. elegans and I wonder if the data on C. 
> elegans variants (or any other Wormbase genome) is present also in 
> Wormbase. It would be great if these data were all in one place, and 
> it seems like they may be here but I just can't find them.
> Thank you very much,
> Matt Daugherty
>
> Submitted From:
>   support /tools/support <http://wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #7350. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/7350>.
>
> Reported by: Matt Daugherty (mddaugherty@ucsd.edu)
> 15 Oct 19 19:50
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 
> (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
Hi Paul,

Thank you for your quick and detailed response.  Anything you can do to help would be greatly appreciated!

Thanks,

Matt

Matt Daugherty
Assistant Professor
University of California, San Diego
Section of Molecular Biology, Division of Biological Sciences
5326 Natural Sciences Building
9500 Gilman Drive 0377
La Jolla CA, 92093-0377
MDDaugherty@UCSD.edu<mailto:MDDaugherty@UCSD.edu>
http://www.daughertylab.org/



On Oct 16, 2019, at 1:53 PM, Paul Davis <paul.davis@wormbase.org<mailto:paul.davis@wormbase.org>> wrote:


Dear Matt,

Thanks for contacting WormBase. Going back to 2015 we were in correspondence with the Author to incorporate this SNP data into WormBase. At the time it was felt that some additional work was needed to clean up the existing C. briggsae variation data in order for this data to be merged correctly. It seems that this work stalled so it was never processed and incorporated.

We do have the data, so I have requested that we add the vcf file as a viewable track on jbrowse as an interim and we will look at reviving this task following your email.

I will also talk with colleagues when I'm back in the office tomorrow regarding your questions about population sequencing studies and how best we could make this data available to you.

Paul


On 15/10/2019 20:50, no-reply@wormbase.org<mailto:no-reply@wormbase.org> wrote:
How Do I ...?

  Hi,
I was recently reading this paper (https://www.ncbi.nlm.nih.gov/pubmed/25783854), in which they state that they deposited all of their C. briggsae population variant data in Wormbase. Can you point me to where I may be able to find and download these data from Wormbase? Additionally, I know there has been population sequencing of C. elegans and I wonder if the data on C. elegans variants (or any other Wormbase genome) is present also in Wormbase. It would be great if these data were all in one place, and it seems like they may be here but I just can't find them.
Thank you very much,
Matt Daugherty

Submitted From:
  support /tools/support<http://wormbase.org//tools/support>

This issue has been assigned ticket number: #7350. Follow progress on our issue tracker<https://github.com/WormBase/website/issues/7350>.


Reported by: Matt Daugherty (mddaugherty@ucsd.edu<mailto:mddaugherty@ucsd.edu>)
15 Oct 19 19:50

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36

This question was reported via the web interface at wormbase.org<http://wormbase.org>. You can also email us<mailto:help@wormbase.org> directly.

--
--
You received this message because you are subscribed to the "WormBase: help" group.
To post to this group, send email to help@wormbase.org<mailto:help@wormbase.org>
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en



--
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
Hi Paul,

I was wondering if there was any update on this?  Did the vcf data ever get 'cleaned up'?

Thank you very much,

Matt

Matt Daugherty
Assistant Professor
University of California, San Diego
Section of Molecular Biology, Division of Biological Sciences
5326 Natural Sciences Building
9500 Gilman Drive 0377
La Jolla CA, 92093-0377
MDDaugherty@UCSD.edu<mailto:MDDaugherty@UCSD.edu>
http://www.daughertylab.org/

On Oct 16, 2019, at 1:53 PM, Paul Davis <paul.davis@wormbase.org<mailto:paul.davis@wormbase.org>> wrote:


Dear Matt,

Thanks for contacting WormBase. Going back to 2015 we were in correspondence with the Author to incorporate this SNP data into WormBase. At the time it was felt that some additional work was needed to clean up the existing C. briggsae variation data in order for this data to be merged correctly. It seems that this work stalled so it was never processed and incorporated.

We do have the data, so I have requested that we add the vcf file as a viewable track on jbrowse as an interim and we will look at reviving this task following your email.

I will also talk with colleagues when I'm back in the office tomorrow regarding your questions about population sequencing studies and how best we could make this data available to you.

Paul


On 15/10/2019 20:50, no-reply@wormbase.org<mailto:no-reply@wormbase.org> wrote:
How Do I ...?

  Hi,
I was recently reading this paper (https://www.ncbi.nlm.nih.gov/pubmed/25783854), in which they state that they deposited all of their C. briggsae population variant data in Wormbase. Can you point me to where I may be able to find and download these data from Wormbase? Additionally, I know there has been population sequencing of C. elegans and I wonder if the data on C. elegans variants (or any other Wormbase genome) is present also in Wormbase. It would be great if these data were all in one place, and it seems like they may be here but I just can't find them.
Thank you very much,
Matt Daugherty

Submitted From:
  support /tools/support<http://wormbase.org//tools/support>

This issue has been assigned ticket number: #7350. Follow progress on our issue tracker<https://github.com/WormBase/website/issues/7350>.


Reported by: Matt Daugherty (mddaugherty@ucsd.edu<mailto:mddaugherty@ucsd.edu>)
15 Oct 19 19:50

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36

This question was reported via the web interface at wormbase.org<http://wormbase.org>. You can also email us<mailto:help@wormbase.org> directly.

--
--
You received this message because you are subscribed to the "WormBase: help" group.
To post to this group, send email to help@wormbase.org<mailto:help@wormbase.org>
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en



--
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
Hi Matt,

Sorry I missed your reply.

We have the data available on our staging site:

https://staging.wormbase.org/tools/genome/jbrowse-simple/?data=data%2Fc_briggsae_PRJNA10731&loc=III%3A6896180..6905477&tracks=Curated_Genes%2Cbriggsae%20variation&highlight=

and we are going to make these live for WS274. We will continue to look 
into how we can provision additional data to users.

Paul


On 30/10/2019 21:27, Daugherty, Matt wrote:
> Hi Paul,
>
> I was wondering if there was any update on this?  Did the vcf data 
> ever get 'cleaned up'?
>
> Thank you very much,
>
> Matt
>
> Matt Daugherty
> Assistant Professor
> University of California, San Diego
> Section of Molecular Biology, Division of Biological Sciences
> 5326 Natural Sciences Building
> 9500 Gilman Drive 0377
> La Jolla CA, 92093-0377
> MDDaugherty@UCSD.edu <mailto:MDDaugherty@UCSD.edu>
> http://www.daughertylab.org/
>
>> On Oct 16, 2019, at 1:53 PM, Paul Davis <paul.davis@wormbase.org 
>> <mailto:paul.davis@wormbase.org>> wrote:
>>
>>
>> Dear Matt,
>>
>> Thanks for contacting WormBase. Going back to 2015 we were in 
>> correspondence with the Author to incorporate this SNP data into 
>> WormBase. At the time it was felt that some additional work was 
>> needed to clean up the existing C. briggsae variation data in order 
>> for this data to be merged correctly. It seems that this work stalled 
>> so it was never processed and incorporated.
>>
>> We do have the data, so I have requested that we add the vcf file as 
>> a viewable track on jbrowse as an interim and we will look at 
>> reviving this task following your email.
>>
>> I will also talk with colleagues when I'm back in the office tomorrow 
>> regarding your questions about population sequencing studies and how 
>> best we could make this data available to you.
>>
>> Paul
>>
>>
>> On 15/10/2019 20:50,no-reply@wormbase.orgwrote:
>>> How Do I ...?
>>>
>>>   Hi,
>>> I was recently reading this paper 
>>> (https://www.ncbi.nlm.nih.gov/pubmed/25783854), in which they state 
>>> that they deposited all of their C. briggsae population variant data 
>>> in Wormbase. Can you point me to where I may be able to find and 
>>> download these data from Wormbase? Additionally, I know there has 
>>> been population sequencing of C. elegans and I wonder if the data on 
>>> C. elegans variants (or any other Wormbase genome) is present also 
>>> in Wormbase. It would be great if these data were all in one place, 
>>> and it seems like they may be here but I just can't find them.
>>> Thank you very much,
>>> Matt Daugherty
>>>
>>> Submitted From:
>>>   support/tools/support <http://wormbase.org//tools/support>
>>>
>>> This issue has been assigned ticket number: #7350. Follow progress 
>>> on ourissue tracker <https://github.com/WormBase/website/issues/7350>.
>>>
>>>
>>> Reported by: Matt Daugherty (mddaugherty@ucsd.edu)
>>> 15 Oct 19 19:50
>>>
>>> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 
>>> (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
>>>
>>> This question was reported via the web interface at wormbase.org 
>>> <http://wormbase.org>. You can alsoemail us 
>>> <mailto:help@wormbase.org>directly.
>>>
>>> --
>>> --
>>> You received this message because you are subscribed to the 
>>> "WormBase: help" group.
>>> To post to this group, send email tohelp@wormbase.org
>>> To unsubscribe from this group, send email to
>>> help+unsubscribe@wormbase.org
>>> For more options, visit this group at
>>> http://groups.google.com/a/wormbase.org/group/help?hl=en
>>>
>>
>> -- 
>> ===========================================
>> WormBase
>> European Bioinformatics Institute (EMBL-EBI)
>> European Molecular Biology Laboratory
>> Wellcome Trust Genome Campus
>> Hinxton
>> Cambridge CB10 1SD
>> United Kingdom
>> ===========================================
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by tharris** [comment]
Closed. Now available in production.
