### ISSUE TITLE
Hello!I would like to know how to pick worms and k...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7356]
*Help Desk query collected when no chat operators were online. Follow up required.*

Hello!I would like to know how to pick worms and keep the worms in one place for test the virulence of bacteria?I'm looking forward to your reply.

**Reported by:** Winn** (hele*******************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org/https://wormbase.org/#01-23-6">https://wormbase.org/#01-23-6</a>
**Browser:** Chrome 73.0.3683.75

**Comment by Paul-Davis** [comment]
Dear Winnie,

Your best bet would be to try the worm community forum as there are lots 
of protocols and threads about lab techniques on there. The community 
will also be able to help you design your experiments if you write a 
post on there.

https://forums.wormbase.org

Good luck

Paul



On 18/10/2019 08:21, no-reply@wormbase.org wrote:
> offline chat Hello!I would like to know how to pick worms and keep the 
> worms in one place for test the virulence of bacteria?I'm looking 
> forward to your reply.
>
> Submitted From:
>   https://wormbase.org/#01-23-6 https://wormbase.org/#01-23-6 
> <http://www.wormbase.org/https://wormbase.org/#01-23-6>
>
> This issue has been assigned ticket number: #7356. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/7356>.
>
> Reported by: Winnie (helen1281985640@163.com)
> 18 Oct 19 07:21
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
Thank you very much!!!

At 2019-10-18 17:51:35, "Paul Davis" <paul.davis@wormbase.org> wrote:



Dear Winnie,


Your best bet would be to try the worm community forum as there are lots of protocols and threads about lab techniques on there. The community will also be able to help you design your experiments if you write a post on there.


https://forums.wormbase.org



Good luck


Paul







On 18/10/2019 08:21, no-reply@wormbase.org wrote:

offline chat Hello!I would like to know how to pick worms and keep the worms in one place for test the virulence of bacteria?I'm looking forward to your reply.

Submitted From:
  https://wormbase.org/#01-23-6https://wormbase.org/#01-23-6

This issue has been assigned ticket number: #7356. Follow progress on our issue tracker.

Reported by: Winnie (helen1281985640@163.com)
18 Oct 19 07:21



This question was reported via the web interface at wormbase.org. You can also email us directly.

--
--
You received this message because you are subscribed to the "WormBase: help" group.
To post to this group, send email to help@wormbase.org
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en






-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom 
===========================================

**Comment by Paul-Davis** [comment]
Dear Paul,
Thank you so much! I found so many great ideas on the forum! It's brilliant! Wish you have a happy life!

Yours,
Winnie.

At 2019-10-18 17:51:35, "Paul Davis" <paul.davis@wormbase.org> wrote:



Dear Winnie,


Your best bet would be to try the worm community forum as there are lots of protocols and threads about lab techniques on there. The community will also be able to help you design your experiments if you write a post on there.


https://forums.wormbase.org



Good luck


Paul







On 18/10/2019 08:21, no-reply@wormbase.org wrote:

offline chat Hello!I would like to know how to pick worms and keep the worms in one place for test the virulence of bacteria?I'm looking forward to your reply.

Submitted From:
  https://wormbase.org/#01-23-6https://wormbase.org/#01-23-6

This issue has been assigned ticket number: #7356. Follow progress on our issue tracker.

Reported by: Winnie (helen1281985640@163.com)
18 Oct 19 07:21



This question was reported via the web interface at wormbase.org. You can also email us directly.

--
--
You received this message because you are subscribed to the "WormBase: help" group.
To post to this group, send email to help@wormbase.org
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en






-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom 
===========================================
