### ISSUE TITLE
ok3707 sequence details

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7366]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi there, <br/>I have a question about the ok3707 annotation. The VC3015 strain listing says that ok3707 is a 645 bp deletion, but the ok3707 variation listing says it is a 1307 bp deletion. We did some PCRs and it looks like 645 bp is more likely to be correct. I think ok3707 was misannotated as the region inside the internal primer pair rather than the deletion. Is it possible to update this with the correct deletion sequence? Is this data available somewhere else to verify? We've also sent our PCRs for sequencing to verify. Thanks for your help.<br/>Best wishes,<br/>Ann</p>

**Reported by:** Ann ****** (ann.***********************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.2 Safari/605.1.15

**Comment by Paul-Davis** [comment]
Dear Ann,

Thank you for getting in touch. The majority of the ok alleles were not 
sequenced so as you have identified the annotation uses the Internal 
right and left primer sequences to identify the target region of the 
deletion. This is because the actual break points of the deletion are 
not known but from the work the consortia did we know the likely size of 
the deletion which is displayed in the primary data in the Strain object.

When you get your sequence data back we would be interested in this so 
that we can update the annotation to show the exact deletion rather than 
the wider region currently displayed.

Paul



On 24/10/2019 08:41, no-reply@wormbase.org wrote:
> Content Correction
>
>   Hi there,
> I have a question about the ok3707 annotation. The VC3015 strain 
> listing says that ok3707 is a 645 bp deletion, but the ok3707 
> variation listing says it is a 1307 bp deletion. We did some PCRs and 
> it looks like 645 bp is more likely to be correct. I think ok3707 was 
> misannotated as the region inside the internal primer pair rather than 
> the deletion. Is it possible to update this with the correct deletion 
> sequence? Is this data available somewhere else to verify? We've also 
> sent our PCRs for sequencing to verify. Thanks for your help.
> Best wishes,
> Ann
>
> Submitted From:
>   support /tools/support <http://wormbase.org//tools/support>
>
> This issue has been assigned ticket number: #7366. Follow progress on 
> our issue tracker <https://github.com/WormBase/website/issues/7366>.
>
> Reported by: Ann Wehman (ann.wehman@uni-wuerzburg.de)
> 24 Oct 19 07:41
>
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 
> (KHTML, like Gecko) Version/13.0.2 Safari/605.1.15
>
> This question was reported via the web interface at wormbase.org. You 
> can also email us <mailto:help@wormbase.org> directly.
>
> -- 
> -- 
> You received this message because you are subscribed to the "WormBase: 
> help" group.
> To post to this group, send email to help@wormbase.org
> To unsubscribe from this group, send email to
> help+unsubscribe@wormbase.org
> For more options, visit this group at
> http://groups.google.com/a/wormbase.org/group/help?hl=en
>

-- 
===========================================
WormBase
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Trust Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
===========================================

**Comment by Paul-Davis** [comment]
Waiting for user to submit the seq data before closing.

**Comment by Paul-Davis** [comment]
Curated
