### ISSUE TITLE
  How do I get information from our wor...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7405]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;How do I get information from our work on CREB (crh-1) into Wormbase? We showed in 2010 that loss of crh-1 abolishes long-term associative olfactory memory (Kauffman, et al. PLoS Biology), and that rescue and overexpression increase long-term memory, but I see that this information is not included in the description of crh-1. (We have been wondering why no one cites our work for memory and CREB! This may help. <br/>Thank you,<br/>visitor_name<br/>Princeton</p>

**Reported by:** Cole********* (ctmu******************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Safari/605.1.15

**Comment by chris-grove** [comment]
My email response to user:
"""
Thanks for writing in. Apologies, we haven't yet curated your 2010 paper for phenotypes. If you could submit the phenotypes via our phenotype form we would greatly appreciate it. The form can always be found by clicking on "Submit Data" under the main search box on any WormBase page to get to our "Submit data" page:

https://wormbase.org/about/userguide/submit_data#01--10

In the "Community Curation" widget, click on the link "Fill out online form" to the right of "Phenotype Data Submission", which will take you to our phenotype submission page:

https://wormbase.org/submissions/phenotype.cgi

Enter your name into the "Your Name" field and your name and WBPerson ID (WBPerson3142) should show up in the autocomplete drop down menu. Selecting your name will automatically populate the email field. Then enter the PubMed ID for the paper in question:

20502519

If knockdown was achieved using RNAi please enter the gene name into the "RNAi target gene" field. Otherwise enter alleles into the "Allele" field and overexpression transgenes into the "Overexpression Transgene" field. Then enter the relevant phenotype into the "Observed Phenotype" field. Probably the most relevant phenotype currently in our phenotype ontology is "memory retention defective". To let me know if you'd like a more specific phenotype term, click on the checkbox next to "Can't find your Phenotype?" and enter in a phenotype suggestion like "long-term associate olfactory memory defective" and I will add it to our phenotype ontology.

If you notice missing phenotypes in the future, and you have a minute to submit them, we would greatly appreciate you submitting them through the form above.
"""
