### ISSUE TITLE
  Hello! I am in the process of analyzi...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7438]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hello!<br/>I am in the process of analyzing sequencing data and am looking for genes associated with a particular phenotype X that is a category in Wormbase. There are 2 things that I have noticed: 1) it does not seem possible to download a bulk gene list of genes that are known to be associated with phenotype X, 2) genes that have been pulled out in screens or other studies that have probed phenotype X do not have the phenotype X tag associated with them, in short: the gene list for phenotype X is not up to date/is incomplete.  Are there ways to address the issues I am encountering already in place in Wormbase? Or is this something that can be done in the future.  Thank you for your help and all the work you do!<br/>visitor_name</p>

**Reported by:** Jadi*** (jadi********************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36

**Comment by nuin** [comment]
My answer to the user

Hi Jadiel


Thanks for your message.

WormBase’s bulk search tool is WormMine, which is our own iteration of the data warehousing tool InterMine. You can access through the Tools menu from the main site at this link

http://intermine.wormbase.org

We have pre-set templates that query gene/phenotype relationships, such as 

Gene --> Allele Phenotypes

but at the same time you can setup you own queries with your own list of genes and other structures of interest. We have a small guide on how to setup your queries that can be accessed from WormMine. The query system quite powerful but at the same time it lacks some more user friendliness. If you have problems, please contact us again and we will be happy to help you.

Regarding your second question, I am not the best person to answer, I am sure one of the curators will get in touch with you to address your concerns.

Thanks for contacting WormBase.

Cheers

Paulo

**Comment by chris-grove** [comment]
Email reply to user:
"""
In addition to Paulo's comments, WormBase provides a phenotype association file on our FTP site that provides all gene-to-phenotype associations from allele-based and RNAi-based phenotype observations. The current file can always be found in this FTP directory:

ftp://ftp.wormbase.org/pub/wormbase/releases/current-production-release/ONTOLOGY/

The general form for the file name is "phenotype_association.WSXXX.wb" where "WSXXX" is the WormBase release version, currently WS273. So the current file is:

ftp://ftp.wormbase.org/pub/wormbase/releases/current-production-release/ONTOLOGY/phenotype_association.WS273.wb

This provides observed and not observed gene-to-phenotype associations along with the reference identifier (as a WBPaper ID, if available; associations without a paper are generally personal communications) as well as variation/allele identifiers or RNAi (experiment) identifiers. The file format generally conforms to the gene annotation file (GAF) format:

http://geneontology.org/docs/go-annotation-file-gaf-format-2.1/

Another place to get genes associated with a particular phenotype is the WormBase phenotype page. For example:

https://wormbase.org/species/all/phenotype/WBPhenotype:0000062#03--10

The "Ontology Browser" widget provides the number of genes directly annotated to this term (2,250 genes for the 'lethal' phenotype) as well as the number of genes directly annotated or inferred to be annotated to this term (5,138 genes), where inference is derived from annotations made to more specific phenotype terms like "embryonic lethal" or "larval lethal". Clicking on those numbers will direct you to a page where you can download the list of genes for either list. Note that the FTP phenotype association file only provides direct annotations, not annotations to more specific terms as the Ontology Browser provides. Also note that the Ontology Browser only provides genes with an observed phenotype, not "not observed" annotations.

You can use WormMine as suggested by Paulo, but in order to get all allele-based and RNAi-based as well as all observed and NOT observed associations you will need to run four queries and compile the results. You can use the WormMine "Import query from XML" option on the WormMine QueryBuilder tab:

http://intermine.wormbase.org/tools/wormmine/customQuery.do

Click on the "Import query from XML" link and copy and paste the following XML queries (see below), click submit and then click on "Show results". You can export the resulting tables in TSV format. The following queries will pull out direct annotations only for the "lethal" phenotype. You will need to change the query constraint to your phenotype of interest. You can do this after you submit the XML query and before you click on "Show results" by clicking on the blue edit icon next to the phenotype constraint "= lethal" in the "Query Overview" section and in the pop-up dialog box entering your own phenotype name.

1) All genes with an allele-based "lethal" phenotype observation:

`<query name="" model="genomic" view="Gene.primaryIdentifier Gene.secondaryIdentifier Gene.symbol Gene.allele.primaryIdentifier Gene.allele.symbol" longDescription="" sortOrder="Gene.primaryIdentifier asc">
  <constraint path="Gene.allele.phenotype.name" op="=" value="lethal"/>
</query>`


2) All genes with an allele-based "lethal" phenotype NOT observed observation:

`<query name="" model="genomic" view="Gene.primaryIdentifier Gene.secondaryIdentifier Gene.symbol Gene.allele.primaryIdentifier Gene.allele.symbol" longDescription="" sortOrder="Gene.primaryIdentifier asc">
  <constraint path="Gene.allele.phenotypeNotObserved.name" op="=" value="lethal"/>
</query>`

3) All genes with an RNAi-based "lethal" phenotype observation:

`<query name="" model="genomic" view="Gene.primaryIdentifier Gene.secondaryIdentifier Gene.symbol Gene.RNAiResult.primaryIdentifier" longDescription="" sortOrder="Gene.primaryIdentifier asc">
  <constraint path="Gene.RNAiResult.phenotype.name" op="=" value="lethal"/>
</query>`


4) All genes with an RNAi-based "lethal" phenotype NOT observed observation:

`<query name="" model="genomic" view="Gene.primaryIdentifier Gene.secondaryIdentifier Gene.symbol Gene.RNAiResult.primaryIdentifier" longDescription="" sortOrder="Gene.primaryIdentifier asc">
  <constraint path="Gene.RNAiResult.phenotype_not_observed.name" op="=" value="lethal"/>
</query>`


Final note: genes may be annotated to the same phenotype as observed and not observed simultaneously for various reasons (maybe a null allele is lethal but a weak loss of function allele is not (or an RNAi knockdown is not)) and sometimes the phenotype is observed in the context of an additional mutation in the background, so it is always worth following up what you find by looking at individual annotations for proper interpretation.

Let us know if you have additional questions.
"""
