### ISSUE TITLE
  Hi  How do I efficiently convert peak...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7455]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi <br/>How do I efficiently convert peak calls from Chip-seq data based on sequence positions into gene names?<br/>best,<br/>adam antebi</p>

**Reported by:** Anon***** (aant**************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15

**Comment by Gschindelman** [comment]
Adam,
Sorry you have yet to receive a reply to your WormBase help question, but many of our staff are currently at a meeting.  Hopefully someone will have an answer soon.
Apologies
Gary Schindelman
Helpdesk


On Dec 9, 2019, at 2:23 PM, no-reply@wormbase.org<mailto:no-reply@wormbase.org> wrote:

Question:

  Hi
How do I efficiently convert peak calls from Chip-seq data based on sequence positions into gene names?
best,
adam antebi

Submitted From:
  support /tools/support<http://wormbase.org//tools/support>

This issue has been assigned ticket number: #7455. Follow progress on our issue tracker<https://github.com/WormBase/website/issues/7455>.


Reported by: aantebi@age.mpg.de<mailto:aantebi@age.mpg.de>
09 Dec 19 22:23

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15

This question was reported via the web interface at wormbase.org<http://wormbase.org/>. You can also email us<mailto:help@wormbase.org> directly.

--
--
You received this message because you are subscribed to the "WormBase: help" group.
To post to this group, send email to help@wormbase.org<mailto:help@wormbase.org>
To unsubscribe from this group, send email to
help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>
For more options, visit this group at
http://groups.google.com/a/wormbase.org/group/help?hl=en

---
To unsubscribe from this group and stop receiving emails from it, send an email to help+unsubscribe@wormbase.org<mailto:help+unsubscribe@wormbase.org>.

**Comment by gw3** [comment]
Adam,

You are going to have to do a bit of programming to do this.
The TF peak calls and the genes are in the WormBase C. elegans GFF file.

 ftp://ftp.wormbase.org/pub/wormbase/releases/WS274/species/c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS274.annotations.gff3.gz 

The TF peak regions have lines like this with a Source column of 'TF_binding_site_region':

I       TF_binding_site_region  TF_binding_site 3403    4072    .       +       .       Name=WBsf331847;tf_id=WBTranscriptionFactor000703;tf_name=DPL-1

This file also contains the lines for the genes with a Source column of 'WormBase' and a 'Type' column of 'gene', e.g.:

I       WormBase        gene    4115    10606   .       -       .       ID=Gene:WBGene00022277;Name=WBGene00022277;locus=homt-1;sequence_name=Y74C9A.3;biotype=protein_coding;so_term_name=protein_coding_gene;curie=WB:WBGene00022277;Alias=homt-1,Y74C9A.3

You will need to write a program that takes the position of any TF peak positions you are interested in and writes out the names of genes within a distance that you specify.

Hope this helps,
Gary
