### ISSUE TITLE
is there a way to identify all of the annotated tr...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7474]
*Help Desk query collected when no chat operators were online. Follow up required.*

is there a way to identify all of the annotated transcription factors in the genome?

**Reported by:** Pete***** (pete*****************)
**Submitted from:** <a target="_blank" href="http://wormbase.org/https://wormbase.org/tools#0--10">https://wormbase.org/tools#0--10</a>
**Browser:** Safari 13.0.3

**Comment by chris-grove** [comment]
My email response:

"""
 WormBase has an under-utilized class called ?Transcription_factor which contains all of the manually annotated transcription factors. I'm attaching the list (Excel file) of Transcription_factor objects from the database for the WS274 release of WormBase. Note that I've filtered the list to only those that have an annotated "Product_of" gene listed. You can turn the filter off in Excel. Let me know if you would prefer a flat/text file.

I'm also attaching a list of 934 C. elegans genes whose products were predicted to be DNA-binding transcription factors from this paper I co-authored in 2005:

https://www.ncbi.nlm.nih.gov/pubmed/?term=16420670

Since this list was published, 9 of the genes have been marked as dead and merged into a different gene (merge recipient noted), 19 have been now classified as pseudogenes, and 2 are now classified as 'transposon in origin', resulting in a total of 904 remaining genes.

After accounting for dead genes, pseudogenes and transposons, the 904 genes in the latter list is entirely included in the WormBase list (1099 total genes). The discrepancy (195 extra genes in the WB list) can be explained by the fact that the WB list includes transcription co-activators, general transcription factors like TBP (TATA-Box Binding Protein) and the general transcription factors like the TAFs (TBP-Associated Factors), and other proteins that happen to be part of transcription factor complexes, whereas the 2005 list only includes those genes whose products are thought to bind directly to DNA in a sequence-specific manner.

Note that there may be multiple genes for a single WBTranscriptionFactor ID, indicating that the gene products are likely members of a larger complex which only has a single ID.

If you really want to cover all your bases, you can also look at the Gene Ontology term page for "DNA-binding transcription factor activity" (GO:0003700):

https://wormbase.org/species/all/go_term/GO:0003700#02--10

In the "Ontology Browser" widget, I would click on the respective "# gene products (# direct)" links next to each term and download the list of genes with direct annotations (for C. elegans or non-elegans species). This approach will be more inclusive of genes from other species.

If I use WormMine to find C. elegans genes annotated directly to this term or its subtype terms, I find 21 additional genes that may be considered DNA-binding transcription factors (list attached).

Let me/us know if you have any questions.
"""
