### ISSUE TITLE
GO_annotation No Gene

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/website#7485]
Hi,

WS275 sees 4 GO_annotation not connected to a WBGene...this seems to cause an issue in producing the GAF file.

GO_annotation : "00101558"
GO_annotation : "00101578"
GO_annotation : "00101591"
GO_annotation : "00101629"

Added code to ignore GO_annotations not connected to a WBGene object,  this "might" have come about during WS275 production as all non-WBGenes genes were deleted?

Would be good to have a check at CalTech pre-upload for GO_annotations not connected to a valid WBGene just in case.

P

**Comment by vanaukenk** [comment]
@Paul-Davis 
I'll take a look and see what's happening here.

**Comment by vanaukenk** [comment]
These annotations had been fixed at the source (Noctua) but because the GO release pipeline was delayed they didn't get incorporated into the WS275 WB .ace file.
We now have a check for annotation objects coming from Noctua that don't correspond to WBGenes, so I'll double-check that the GO_annotations objects are okay for the WS276 upload.
Thanks for letting us know about this @Paul-Davis

**Comment by Paul-Davis** [comment]
TY @vanaukenk
