### ISSUE TITLE
  Hi there, I have a question relating ...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#7486]
*Submitted from the feedback form on the WormBase website.*

<p>&nbsp;&nbsp;Hi there,<br/>I have a question relating to the lifespan phenotype of mlt-3 RNAi (https://wormbase.org/species/c_elegans/rnai/WBRNAi00070420#014--10):<br/>I looked up the original paper, and found no words about<br/>Y39C12A.1/mlt-3 in both the main body and the supplementary tables.<br/>On the other hand, the authors reported the phenotype for the Y39C12A.2 RNAi.<br/>Would you please check the record and see if it needs to be corrected?<br/>Thank you!</p><p>What were you doing? <br />&nbsp;&nbsp;postdoc</p>

**Reported by:** Anon***** (liwe***************)
**Submitted from:** <a target="_blank" href="http://wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.18362

**Comment by chris-grove** [comment]
Hello,

Thanks for pointing out the issue. It looks as though the original annotation was made using the Ahringer RNAi clone "sjj_Y39C12A.b" that, likely at the time, was the only clone from that library that was expected to target the gene Y39C12A.2, which as you point out is mentioned in the paper. It seems like the authors used the Ahringer library for their screen, so clone sjj_Y39C12A.b would have been the obvious choice. Since then, the gene models have changed such that mlt-3 now encompasses the entire genomic locus including Y39C12A.2 (and covered by the sjj_Y39C12A.b clone) and the gene Y39C12A.2 is now considered a pseudogene (the suspicion for which is alluded to in the paper). This history of gene models can be seen in this JBrowse screen shot:

<img width="981" alt="Screenshot 2020-01-02 13 35 50" src="https://user-images.githubusercontent.com/611382/71686525-65259800-2d69-11ea-8166-7bd2048cbbb0.png">

So, if the authors did indeed use the sjj_Y39C12A.b Ahringer clone for their knockdown, then the annotation is correct and should remain as is. Considering that Y39C12A.2 is now considered a pseudogene and yet the authors observed a phenotype suggests that mlt-3 may in fact be the actual target of the reported knockdown. The other explanation is that the second possible target, F40C5.2:

https://wormbase.org/species/c_elegans/rnai/WBRNAi00070420#0145--10

Is the gene knocked down that is causing the phenotype.

Given all of this, I will leave the annotation as is unless we can confirm that the authors used a different RNAi clone for their experiments.
